### ISSUE TITLE
Get() from an sstable

### ISSUE THREAD

**Issue by tzahij** [cockroachdb/pebble#1001]
The [documentation on sstable](https://godoc.org/github.com/cockroachdb/pebble/sstable) has the following example at the beginning:

`r := table.NewReader(file, options)`
`defer r.Close()`
`return r.Get(key)`

I found no Get() method on sstable Reader.
Is there an efficient why to Get() directly from an SStable?
And thanks for this amazing piece of code.
Tzahi

**Comment by petermattis** [comment]
@tzahij The doc and code are out of sync apparently!

There is a `Reader.get()` method, but it is unexported. I can't recall the reason for not exporting it. Note that internally `Reader.get()` creates an iterator. Adding a non-iterator lookup path would involve significant code duplication, and most users of `Reader` want to read multiple keys. For example, `DB.Get()` needs to be able to read multiple keys from an sstable in the case of merge records. `sstable.Iterator.SeekGE` should be nearly as fast as a dedicated `Reader.Get` operation. I'm open to seeing this changed, but I don't care strongly enough about it to do so myself (nor do we have a need). Pull requests are welcome, though it should be a bit more than simply exporting the existing `Reader.get`.

**Comment by tzahij** [comment]
Thanks again. This is a fine solution for us
