### ISSUE TITLE
compaction: incorporate point tombstones into compaction heuristics

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1016]
In https://github.com/cockroachlabs/support/issues/638 and https://github.com/cockroachlabs/support/issues/710 we saw jobs tables with large counts of uncompacted point tombstones, bloating the on-disk size by orders of magnitude and crippling queries against the table.

One potential solution to this problem is #972, age-triggered compactions, ensuring that we eventually compact tables with really old point tombstones. Alternatively, it's worth explore incorporating point tombstones into our compaction heuristics. Here is a rough, unprincipled sketch of what this might look like: 150f09852df345d0c5610d0539b2df78658108a7

Point tombstones in large-value tables are particularly problematic with the min-overlapping ratio heuristic, because point tombstones are always small-sized. Since they're so compact, point tombstones overlapping many lower-levelled sstables may fit into a single higher level sstable. The high overlapping ratio de-prioritizes compacting the tables.

**Comment by petermattis** [comment]
> One potential solution to this problem is #972, age-triggered compactions, ensuring that we eventually compact tables with really old point tombstones.

I think we should do age-triggered compactions as well as account for point tombstones in our compaction heuristics. The age-triggered compactions are a fail safe against some workload where the compaction heuristics do not work well. 

> Alternatively, it's worth explore incorporating point tombstones into our compaction heuristics. Here is a rough, unprincipled sketch of what this might look like: 150f098

I think we should do something like this. I think we can quibble about the specific heuristics on the PR itself, but adjusting the compensated size in this manner makes sense to me.

> Point tombstones in large-value tables are particularly problematic with the min-overlapping ratio heuristic, because point tombstones are always small-sized. Since they're so compact, point tombstones overlapping many lower-levelled sstables may fit into a single higher level sstable. The high overlapping ratio de-prioritizes compacting the tables.

This is a good observation.
