### ISSUE TITLE
datadriven: add convenience facilities

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#102]
The datadriven tests are powerful, yet there is a bunch of manual and error prone parsing in the customization needed for a particular test. For example, `runDBDefineCmd` contains:

```
	for _, arg := range td.CmdArgs {
		switch arg.Key {
		case "target-file-sizes":
			opts.Levels = make([]db.LevelOptions, len(arg.Vals))
			for i := range arg.Vals {
				size, err := strconv.ParseInt(arg.Vals[i], 10, 64)
				if err != nil {
					return nil, err
				}
				opts.Levels[i].TargetFileSize = size
			}
		case "snapshots":
			snapshots = make([]uint64, len(arg.Vals))
			for i := range arg.Vals {
				seqNum, err := strconv.ParseUint(arg.Vals[i], 10, 64)
				if err != nil {
					return nil, err
				}
				snapshots[i] = seqNum
				if i > 0 && snapshots[i] < snapshots[i-1] {
					return nil, fmt.Errorf("Snapshots must be in ascending order")
				}
			}
		default:
			return nil, fmt.Errorf("%s: unknown arg: %s", td.Cmd, arg.Key)
		}
	}
```

I think `datadriven` can provide a number of convenience facilities for parsing commands and arguments. There can be a utility for parsing args into a struct using struct tags, similar to how [`github.com/jmoiron/sqlx`](https://github.com/jmoiron/sqlx) allows struct/slice unmarshalling for SQL results. And there can be a facility for parsing a string using a regexp and parsing the matched fields. Something like:

```
  var level int
  var lower, upper db.InternalKey
  ScanRegexp(`L([0-9]+):([^-]+)-(.+)`, &level, &lower, &upper)
```

**Comment by tbg** [comment]
Note that datadriven is more powerful in the main repo and that I just forked that into cockroachdb/datadriven for use in etcd/raft.

**Comment by petermattis** [comment]
> Note that datadriven is more powerful in the main repo and that I just forked that into cockroachdb/datadriven for use in etcd/raft.

I just took a quick look, and didn't notice any differences. Is there something in particular you're thinking of?

**Comment by tbg** [comment]
I'm not sure when the pebble code was copied, but I added .Scan at some point in the main repo. If they're identical, might still be worth not diverging, i.e. updating upstream and vendoring here.

**Comment by petermattis** [comment]
`ScanArgs`? Yep, I missed that. Thanks for the pointer. That looks useful.
