### ISSUE TITLE
vfs: WAL preallocation broken in two ways

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/pebble#1047]
_NOTE: I might be wrong about this as I don't quite understand everything that's going on here._

Currently, it doesn't look like WAL preallocation, added in https://github.com/cockroachdb/pebble/commit/1a60443264903b8f64eb97b04ecde983ab7b7506, is properly working. It seems to be broken for two reasons.

The first reason is that, as of https://github.com/cockroachdb/pebble/commit/341164583f87cb754452e7c085d22e0119f25c24, `diskHealthCheckingFile` now sits between `syncingFile` and `*os.File`. `diskHealthCheckingFile` does not have an `Fd() uintptr` method, so it does not support the file descriptor check [here](https://github.com/cockroachdb/pebble/blob/48f55301c5c4197021b030979007fe2fecf17380/vfs/syncing_file.go#L60), which means that it turns WAL preallocation into a no-op [here](https://github.com/cockroachdb/pebble/blob/48f55301c5c4197021b030979007fe2fecf17380/vfs/syncing_file.go#L99).

The second is more trivial. We call preallocate with a size of the file's existing offset, without actually taking into account the size of the data we're about to write to the file:
https://github.com/cockroachdb/pebble/blob/48f55301c5c4197021b030979007fe2fecf17380/vfs/syncing_file.go#L82-L83
I believe this should be:
```
_ = f.preallocate(atomic.LoadInt64(&f.atomic.offset) + int64(len(p)))
```
Notice that `n` doesn't get set until _after_ we already write to the file.

**Comment by petermattis** [comment]
> The first reason is that, as of 3411645, diskHealthCheckingFile now sits between syncingFile and *os.File. diskHealthCheckingFile does not have an Fd() uintptr method, so it does not support the file descriptor check here, which means that it turns WAL preallocation into a no-op here.

`diskHealthCheckingFile` embeds a `File`. I thought that means that it would inherit the `Fd()` method. I could have sworn this came up in code review when `diskHealthCheckingFile` was introduced. Cc @itsbilal. 

> The second is more trivial. We call preallocate with a size of the file's existing offset, without actually taking into account the size of the data we're about to write to the file.

Yeah, this does seem wrong. I'm guessing something was refactored at some point and a bug was introduced.

> Currently, it doesn't look like WAL preallocation, added in 1a60443, is properly working. It seems to be broken for two reasons.

It is possible we should just remove WAL preallocation as WAL recycling provides the real benefit.

**Comment by nvanbenschoten** [comment]
> diskHealthCheckingFile embeds a File. I thought that means that it would inherit the Fd() method.

`File` itself doesn't have an `Fd()` method, only specific instances of it do. So embedding the interface doesn't lead to the `Fd()` method being inherited by `diskHealthCheckingFile`.

> Yeah, this does seem wrong. I'm guessing something was refactored at some point and a bug was introduced.

This part may not actually be broken. Even from the [very beginning](https://github.com/cockroachdb/pebble/commit/1a60443264903b8f64eb97b04ecde983ab7b7506#diff-60a4c92570b5eba90c1482cbe4000ffc9a0f701f9b1b569464d2439aa72f32f4R57), we included the `+ int64(n)` part, which is always `0`. But `preallocate` expects an offset and not a length. So I think `+ int64(n)` was just harmless noise.

**Comment by petermattis** [comment]
> File itself doesn't have an Fd() method, only specific instances of it do. So embedding the interface doesn't lead to the Fd() method being inherited by diskHealthCheckingFile.

 Yep. This is definitely broken.

**Comment by itsbilal** [comment]
Played with file wrappers and Fd() in the Go playground yesterday, and yes, we'd need to fix that. `encryptedFile` has the same problem too.

> I could have sworn this came up in code review when diskHealthCheckingFile was introduced.

I remember it coming up around `Prefetch()`, but don't recall if it came up with `diskHealthCheckingFile`.
