### ISSUE TITLE
recent writes lost use pebble.NoSync

### ISSUE THREAD

**Issue by zydovech** [cockroachdb/pebble#1052]
when use pebble.NoSync write data, when process crashes recent writes will be lost 。 
 Setting Sync can result in slower writes.
setting pebble.NoSync , sometimes only write memtable,not write wal。 [queueBlock](https://github.com/cockroachdb/pebble/blob/a53f229c8c9c123df22c56b60b82d4bb59dad430/internal/record/log_writer.go#L667)   [ready.Signal()](https://github.com/cockroachdb/pebble/blob/a53f229c8c9c123df22c56b60b82d4bb59dad430/internal/record/log_writer.go#L525)

Are there other options to just write without fsync ？

The reproduction procedure is as follows, the first read always return ```pebble: not found```， when crashes without  ```db.Close()```
```go 
package main

import (
	"fmt"
	"log"

	"github.com/cockroachdb/pebble"
)

func main() {
	db, err := pebble.Open("demo", &pebble.Options{})
	if err != nil {
		log.Fatal(err)   //always return pebble: not found
	}
	key := []byte("hello")
	value, closer, err := db.Get(key)
	if err != nil {
		log.Println(err)
	}
	if err := db.Set(key, []byte("world"), pebble.NoSync); err != nil {
		log.Fatal(err)
	}
	value, closer, err = db.Get(key)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s %s\n", key, value)
       //crashes
	panic("fail") 
	if err := closer.Close(); err != nil {
		log.Fatal(err)
	}
	if err := db.Close(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by jbowens** [comment]
With `pebble.NoSync`, there are no durability guarantees until the next write with `pebble.Sync` completes. Some storage engines may have an option to flush writes to the OS page cache without fsyncing, but Pebble doesn't have such an option because we don't have a need for it in CockroachDB.

If you want to ensure previously written data is on disk, you'll need to write something `pebble.Sync`.

**Comment by petermattis** [comment]
The Pebble philosophy is that if you want durability you need to specify `pebble.Sync`. Without an `fsync` you only get the illusion of durability: written data may survive a process crash but not an OS crash / machine restart. Pebble's behavior means that bugs in this area will be surfaced sooner. We're unlikely to change this behavior as Pebble's primary user is CockroachDB which absolutely needs the strict durability guarantee.

**Comment by zydovech** [comment]
Thank you for your reply.  first,  I saw the comment of  [WriteOptions.Sync](https://github.com/cockroachdb/pebble/blob/a53f229c8c9c123df22c56b60b82d4bb59dad430/options.go#L111) , which shows if OS not crash , then ```pebble.NoSync```  no writes will be lost  .  but actually writes lost, this part confuses  me.

**Comment by petermattis** [comment]
The comments on `WriteOptions.Sync` appear to be inaccurate.
