### ISSUE TITLE
Possible to have a "complete" archive version e.g. version 1.0.N that will never be updated?

### ISSUE THREAD

**Issue by hiqsociety** [cockroachdb/pebble#1064]
Possible to have a "complete" archive version e.g. version 1.0.N that will never be updated like boltdb? This is so that we dont have to have oops, gotchas etc that need to be upgraded all the time. just a basic version of which the db is solid and complete.

there are too many DBs out there facing this problem of which is why the adoption is "fragmented". i think boltdb is great as it is for its purpose but since pebble is "new", would hope that there's a complete version with the basic features needed so we can work on the "basic" version to build a solid foundation on... like boltdb

**Comment by petermattis** [comment]
@hiqsociety Are you looking for official releases ala https://github.com/boltdb/bolt/releases? Those aren't currently provided. As it says on the packaging, Pebble is targeted mainly at CockroachDB. If you want to target a stable version of Pebble, then you can use the `crl-release-X` branches that correspond to the CockroachDB versions. The latest release branch is [`crl-release-20.2`](https://github.com/cockroachdb/pebble/tree/crl-release-20.2). I suppose we could add tags for each CRDB release and make a corresponding Pebble release at that time. Would that be satisfactory?

**Comment by oakad** [comment]
What about providing a go.mod?

The vendor dir is quite large but the packages in there are commonly used by projects which may be interested in pebble.

go.mod can pave the path to both versioned releases and to reduction in size.

**Comment by hiqsociety** [comment]
yes. that'll be satisfactory.

**Comment by nicktrav** [comment]
> yes. that'll be satisfactory.

Reading between the lines here and calling this one done.

**Comment by nicktrav** [comment]
Err maybe not - looks like you're looking for _tags_, rather than just branches. Curious to know whether a branch is sufficient here, @hiqsociety?

For tags, we'd likely have to come up with a versioning scheme independent of CRDB, or attempt to keep our tagging in line with CRDB's tagging. That warrants some more thought.

If branches are sufficient, we can close.

**Comment by imsodin** [comment]
To use pebble as a go module, having tags with semantic versioning would be nice - then it's clear what version is in use/required by the downstream project. With branches you'll just get the date and git commit sha as a reference. Not sure that's a requirement for OP, but in the context of branches vs tags likely relevant.

**Comment by nicktrav** [comment]
@jbowens - I wonder if we could do something as simple as working with the dev-inf folks to ensure that when a Cockroach release is tagged, we tag the associated `crl-release-*` branch with the same Cockroach release version. We could possibly "backfill" some tags for existing versions.

**Comment by RaduBerinde** [comment]
I just tagged a `v1.0.0` release with the version that is part of CockroachDB 23.1.12.

I plan to tag a `v1.1.0` release within the next months or so with the version that is part of CockroachDB 23.2.0 or .1.

Next version will be `v2.0.0` and will correspond to CockroachDB 24.1. This version will no longer support older formats (including RocksDB and LevelDB).
