### ISSUE TITLE
Update README with information about production ready / stability

### ISSUE THREAD

**Issue by robert-zaremba** [cockroachdb/pebble#1065]
Could you please provide information for:

* How stable pabble is?
* Is it production ready?

At [Cosmos](cosmos.network/) (blockchain) we are designing a new storage and currently benchmarking RocksDB and BadgerDB and thinking about Pabble as well. Our main requirement for the underlying KV store is a snapshot functionality and batch  updates.

**Comment by robert-zaremba** [comment]
thanks.

**Comment by robert-zaremba** [comment]
BTW: is Pabble using same mechanism for snapshots as RocksDB?

**Comment by petermattis** [comment]
If you're referring to [DB.NewSnapshot](https://pkg.go.dev/github.com/cockroachdb/pebble#DB.NewSnapshot) the answer is yes.
