### ISSUE TITLE
What kind of options can you set with pebbledb?

### ISSUE THREAD

**Issue by hiqsociety** [cockroachdb/pebble#1113]
1. I'm asking regarding size of sstables / logs. possible to set these?

2. any limitations / caveats using pebble? e.g. maximum database sizes? will large db strangle resources during compaction?

**Comment by petermattis** [comment]
> I'm asking regarding size of sstables / logs. possible to set these?

You can set [LevelOptions.TargetFileSize](https://github.com/cockroachdb/pebble/blob/master/options.go#L188) on a per-level basis, which is what controls the size of sstables. You can set [Options.MemTableSize](https://github.com/cockroachdb/pebble/blob/master/options.go#L411) which roughly controls the size of the log (it actually controls the size of the memtable, whenever the memtable is flushed, the log is rotated). Choosing good values for these settings is a bit of a dark art and I can't really help you with doing so. There is roughly similar control to what RocksDB gives you, so if any reading you do on similar RocksDB configuration should be applicable here.

> any limitations / caveats using pebble? e.g. maximum database sizes? will large db strangle resources during compaction?

No specific caveats come to mind. Yes there are limitations, but they are quite high and unfortunately not well documented. (Send a PR for improvement as you track any down). An example limitation is that a batch cannot be larger than 4GB. Very large keys and values are likely to be problematic as they need to be kept in memory, sometimes as part of persistent metadata. We've tested a single Pebble DB of 9 TB in size. A large DB does not strangle resources during compaction, but the write amplification is often higher in a large DB than a small one (depends on your workload).

**Comment by hiqsociety** [comment]
since a large db's write amplification will be higher than a small one, is there a posibility that sharding / splitting up DB into more DB folders will alleviate this issue?

What's the "max" size of DB possible with pebble? 1 petabyte?

**Comment by petermattis** [comment]
> since a large db's write amplification will be higher than a small one, is there a posibility that sharding / splitting up DB into more DB folders will alleviate this issue?

That is not something we've tested, but my intuition is that splitting up a DB on a single disk will only hurt, not help. Yes, each DB will be smaller, but you need some indexing structure on top to figure out which DB a key resides in and that indexing structure is materially the same as what Pebble has internally. Using separate DBs mean that the individual Pebble instances will be sharing the disk resource, likely in a way that they interfere with each other. 

> What's the "max" size of DB possible with pebble? 1 petabyte?

We've tested up to 9TB on CockroachDB. Certain pieces of Pebble metadata need to be stored in memory and that metadata scales with the size of the on-disk data. An effort was made to ensure that we use efficient data structures for this metadata (O(logn) algorithms, not O(n)). I imagine Pebble can scale to large disk sizes, but doing so has not been a priority for our use cases.

PS Can you put a petabyte of storage in a single machine nowadays?

**Comment by petermattis** [comment]
> yes you can put a petabyte of storage in a single virtual machine nowadays. (cloud services)

Out of curiosity, which cloud service are you referring to? The max AWS EBS volume size is 16 TB. The max GCP persistent disk size is 64 TB. You can attach multiple volumes to a machine, but you'd want to put a single Pebble instance on each.

> so how does 9TB of data "react" / respond? 9TB is not a lot nowadays as well. probable 100TB is something to test with. hope to have some info / benchmark / analysis on this.

9TB worked ok. I doubt 100TB will as there hasn't been any effort to make Pebble work at that scale. To be fair to Pebble, in my experience RocksDB doesn't even scale to 9TB as it hits internal O(num-sstable) bottlenecks well before that. I'd be interested in hearing any reports of success or failure passed 9TB, though this isn't an area we're worried about and are unlikely to invest any effort in investigation or fixing any problems you find. That said, PRs are welcome.

**Comment by damienhollis** [comment]
Hi @petermattis, just watching this thread and was interested in your comment that you aren't concerned with Pebble supporting more than 9TB. I assume the reasoning for this is that with CRDB the intention would be just to scale out to more nodes and therefore never need such big Pebble instances?

**Comment by petermattis** [comment]
> Hi @petermattis, just watching this thread and was interested in your comment that you aren't concerned with Pebble supporting more than 9TB. I assume the reasoning for this is that with CRDB the intention would be just to scale out to more nodes and therefore never need such big Pebble instances?

Correct. Or run multiple Pebble instances on a single node where each Pebble instance is running on a separate disk/volume. I expect we'll increase the size we've tested Pebble at over time, but it isn't any sort of pressing concern right now.

**Comment by damienhollis** [comment]
Thanks for confirming.

**Comment by nicktrav** [comment]
Treating the original question on OPTIONS as answered. Closing.
