### ISSUE TITLE
background error: pebble: keys must be added in order: #0,DEL, #1838,SET

### ISSUE THREAD

**Issue by savsgio** [cockroachdb/pebble#1131]
I can see another issue about this error (#1089 #577), but without solution.

This is my configuration:
```go
opts := &pebble.Options{}
wo := &pebble.WriteOptions{
    Sync: false,
}

db, err := pebble.Open(path, opts)
```

I only use the default API of Pebble, not `SSTable` directly.

**Comment by savsgio** [comment]
Version: `github.com/cockroachdb/pebble v0.0.0-20210503173641-1387689d3d7c`

**Comment by petermattis** [comment]
Duplicated of #1133.
