### ISSUE TITLE
Documentation on batch usage?

### ISSUE THREAD

**Issue by hiqsociety** [cockroachdb/pebble#1132]
How do I use batch? What's the difference between batch and nosync and batch deferred?

**Comment by petermattis** [comment]
The docs on batch are [here](https://pkg.go.dev/github.com/cockroachdb/pebble#Batch). They may not answer all your questions, but there are words about regular vs deferred ops. The sync vs nosync behavior is described on the docs for [WriterOptions.Sync](https://pkg.go.dev/github.com/cockroachdb/pebble#WriteOptions). There are no examples of using a Batch in the docs at this time. Feel free to send a PR following the pattern in `iterator_example_test.go`.

**Comment by nicktrav** [comment]
Closing as a question that was answered.
