### ISSUE TITLE
Add time-series metrics measuring symptoms users of pebble are experiencing

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/pebble#1141]
API boundaries are great places to add time-series metrics measuring symptoms experienced by users of that API. For example:

```
package main

import (
	"fmt"
	"log"

	"github.com/cockroachdb/pebble"
)

func main() {
	db, err := pebble.Open("demo", &pebble.Options{})
	if err != nil {
		log.Fatal(err)
	}
	key := []byte("hello")
	if err := db.Set(key, []byte("world"), pebble.Sync); err != nil {
		log.Fatal(err)
	}
	value, closer, err := db.Get(key)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s %s\n", key, value)
	if err := closer.Close(); err != nil {
		log.Fatal(err)
	}
	if err := db.Close(); err != nil {
		log.Fatal(err)
	}
}
```

We should have time-series metrics tracking the error rate & latency profiles of calls to `db.Get`. Not just calls to `db.Get`. Calls to pebble in general.

This will compliment https://github.com/cockroachdb/pebble/issues/1140.

**Comment by petermattis** [comment]
Similar to #11140, I'd argue this should be done in CRDB, not in Pebble itself. I think the CRDB level operations have a better correspondence to what we'd want to measure.

**Comment by joshimhoff** [comment]
Makes sense; closing.
