### ISSUE TITLE
Build is failing for current master (edcfca5432fbae98b6191ca282551a1c4b5cbd6b)

### ISSUE THREAD

**Issue by dioptre** [cockroachdb/pebble#1155]
```sh
go build
# github.com/cockroachdb/pebble/vendor/github.com/cockroachdb/errors/errbase
vendor/github.com/cockroachdb/errors/errbase/adapters_errno.go:36:18: e.Is undefined (type syscall.Errno has no field or method Is)
vendor/github.com/cockroachdb/errors/errbase/adapters_errno.go:37:18: e.Is undefined (type syscall.Errno has no field or method Is)
vendor/github.com/cockroachdb/errors/errbase/adapters_errno.go:38:18: e.Is undefined (type syscall.Errno has no field or method Is)
```

```go build``` works for commit b64dcf2173d7fa03f54db3df14b89876fa807e42

Using go version 1.12.7:
https://www.digitalocean.com/community/tutorials/how-to-install-go-on-debian-10

**Comment by petermattis** [comment]
go1.12 is quite old and is no longer supported by Pebble. The oldest version of Go that is supported (known to compile and tested as part of CI) is go1.14, though we should probably bump that to go1.15 soon.

**Comment by dioptre** [comment]
You really think it's worth introducing syntactical/regression errors, putting thousands of production machines at risk for these 3 lines? And you want to introduce more in 1.15?

I would have to agree to disagree on this.

**Comment by jbowens** [comment]
What? I don’t understand the production risk here. If anything using unsupported Go versions that no longer receive security patches puts machines at risk.

**Comment by dioptre** [comment]
The only risk to my internal processes were the addition of these few lines of code. If it were an unbelievable feature I would totally support it, but this doesn't make sense to me.

**Comment by petermattis** [comment]
> You really think it's worth introducing syntactical/regression errors, putting thousands of production machines at risk for these 3 lines? And you want to introduce more in 1.15?

We're not introducing incompatibilities with older versions of Go on purpose, but Go marches forward and we're marching with it. Maintaining compatibility with older version of Go takes effort and to date there has been zero reason to do so. You're the first person to notice this and the first person to raise it as a problem. I'm curious to hear why upgrading to a newer version of Go is a burden. We're unlikely to start supporting go1.12 again at this point, but the beautiful thing about open source is the source is all there for you to modify.

> I would have to respectfully agree to disagree on this.

Ok.

**Comment by dioptre** [comment]
Fair enough. Just my 2c! :)
