### ISSUE TITLE
Lost writes when process crashes

### ISSUE THREAD

**Issue by cfsghost** [cockroachdb/pebble#1165]
Thanks for your good works. Pebble is good KV engine written in Golang we have never seen before. :-)

There is a big problem we encounter that lost writes when process crashes, and it seems no way to recover memtable from WAL (We found WAL never sync to storage when we try to write data (small data) for testing. That's why WAL has nothing after crashing).

We know Pebble has no guarantee for durability on `NoSync` mode, but `Sync` mode is `too slow` for us.  I wonder that is it possible to provide an option to allow `fsync` or other way writing to OS cache for WAL?

We really need this function, especially for container platform that terminates our application anytime, it will cause data lost with useless WAL. We supposes to recover memtable from WAL as long as WAL can be stored as much as possible.

Anyway, we still want to fix it for our application, even if Pebble do not provide a way to solve this WAL problem. Currently, we attempt to implement own WAL outside of Pebble in order to recover memtable after process crashes.

However, there is an integration issue how to locate the exact position of the last write before crashing. Any ideas?

**Comment by cfsghost** [comment]
Well, I found a way to force write to WAL file with `db.LogData()`. Inspired by Checkpoint's withFlushedWAL.

**Comment by jbowens** [comment]
> Well, I found a way to force write to WAL file with db.LogData(). Inspired by Checkpoint's withFlushedWAL.

Calling `DB.LogData` with `pebble.Sync` is the right way to ensure prior writes are flushed and synced. 👍
