### ISSUE TITLE
tool: improve `lsm` usability

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1177]
In a large MANIFEST with high read-amplification, the LSM visualizer hangs generating the html. With one such MANIFEST I was able to generate the visualizer using the pebble tool at 82fe782f03717b9f474ade933abd119fbb660224 (pre-sublevel support). We could add a flag to omit sublevel granularity, or maybe there are low-hanging optimizations that can make it feasible to generate with sublevels.

Another option is to add flags to generate the visualization over short spans of the `MANIFEST`, eg edit _x_ to _y_.

**Comment by jbowens** [comment]
Realizing it would also be nice if the visualizer displayed the edit's offset, so that it's easier to correlate with the text dump of the MANIFEST.

**Comment by mufeez-amjad** [comment]
> Another option is to add flags to generate the visualization over short spans of the MANIFEST, eg edit x to y.

> Realizing it would also be nice if the visualizer displayed the edit's offset, so that it's easier to correlate with the text dump of the MANIFEST.

These were both introduced in https://github.com/cockroachdb/pebble/pull/1449

**Comment by jbowens** [comment]
Thanks @mufeez-amjad, I'll close this out
