### ISSUE TITLE
db: sstable metadata consistency checks

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/pebble#1202]
(creating issue from internal storage stability doc)

The encryption-at-rest / range tombstone bug caused the end key for in-memory sstable metadata to be corrupted in such a way that the key was very likely not a valid MVCC encoded key (the key was essentially replaced with random bytes). We could add an `Options.ValidateKey` method that could be called on the keys in sstable metadata before committing a new version. Doing so would have caught the corruption earlier and very likely prevented it from spreading.
Taking this further, we could periodically validate the keys stored in sstable metadata as a background operation.

**Comment by nicktrav** [comment]
@sumeerbhola - do we have any links to the original issue that generated this issue? Specifically looking for some real-world data that I can use to construct some tests to cover the planned additions.

**Comment by sumeerbhola** [comment]
The fix for the original issue is here
https://github.com/cockroachdb/pebble/pull/994 and some testing in https://github.com/cockroachdb/pebble/pull/995
The `vfs.FS` implementation provided in CockroachDB's `engineccl.encryptedFS` mutates the slice passed into `Write` since it encrypts in-place. Which is what corrupted the metadata.
 
Since this checking will be on the in-memory `versionEdit` generated by a compaction, it may be tricky to inject "in-memory" corruption into the compaction path. Instead we could just test a standalone `versionEditValidation` func.
