### ISSUE TITLE
reduce allocations coming via MergeOlder

### ISSUE THREAD

**Issue by BrannonKing** [cockroachdb/pebble#1206]
For my application, the allocation profiler shows a lot of memory pressure originating in base.AppendValueMerger.MergeOlder. Can we add some mechanism here to preallocate sufficient memory in the buffer? Should it at least check the capacity of the existing buffer before making a new one? Can we reuse buffers there?

**Comment by petermattis** [comment]
@BrannonKing You can use `sync.Pool` allocation for the `ValueMerger` object returned by `pebble.Merger.Merge`, and return the merger to the pool when `ValueMerger.Finish` is called. Inside the `ValueMerger` you can allocate reusable buffers. Should `AppendValueMerger` being doing this? I'd argue no. That is really a demonstration of how a merger can work. If you want high performance I'd recommend creating a custom merger.

**Comment by BrannonKing** [comment]
I understand now. Thank you.
