### ISSUE TITLE
db: option to disable the cache when using Get

### ISSUE THREAD

**Issue by damnever** [cockroachdb/pebble#1208]
`Get` frequently at some time point may result in high memory usage caused by the `internal.Cache`, the cache may be useless under some circumstances and user can disable it on demand.

**Comment by petermattis** [comment]
This also applies to iteration via `NewIterator`. Allowing the cache to be disabled would require plumbing this configuration down to `sstable.Reader.readBlock`. On the iterator side, the obvious place to add this configuration would be `IterOptions`. `DB.Get` doesn't have anything similar. I'm supportive of seeing this added, yet we don't have any need for it ourselves so you'll have to implement it if you want it any time soon.

**Comment by damnever** [comment]
I have done some [experiments](https://github.com/damnever/pebble/commit/7a4fdf501f29fd6bce131b96ccb812e98fa89039), the root cause of my problem is probably because of the random reads, which lead to a lot of [`Cache.Alloc`](https://github.com/cockroachdb/pebble/blob/master/internal/cache/clockpro.go#L695).

**Comment by damnever** [comment]
This feature is still important.
