### ISSUE TITLE
how to set the options of pebble appropriately

### ISSUE THREAD

**Issue by zengmenglu** [cockroachdb/pebble#1215]
When we use pebble, we do like this:

`db, err := pebble.Open(file, &pebble.Options{})`

How to set the `&pebble.Options{}` appropriately？And can someone or any docs explain the configuration items in `pebble.Options`, and the corresponding relations between pebble and goleveldb options? Thanks!

**Comment by jbowens** [comment]
Hi, the best resource on each of the configuration options is the inlined documentation. See https://pkg.go.dev/github.com/cockroachdb/pebble#Options

**Comment by nicktrav** [comment]
I believe this question was answered. Closing.
