### ISSUE TITLE
Is there a way to delete a key in ValueMerger？

### ISSUE THREAD

**Issue by damnever** [cockroachdb/pebble#1219]
When the ValueMerger produces an empty value, I want to delete the key safely.

**Comment by petermattis** [comment]
@damnever An empty value is different than a non-existent key. There isn't currently a facility for having a `ValueMerger` delete a key. One could be added. We'd need to be careful to only perform the deletion when the `ValueMerger` is used during iteration or during bottom level compactions. That shouldn't be difficult though, as there is already logic to detect that in passing the `includesBase` flag to `ValueMerger.Finish`.

We (CRL) have no need for this facility at this time, so if you want it on any deterministic time frame you'll have to add it yourself. Such is open source.

**Comment by damnever** [comment]
I'd love to contribute, but the code base is relatively large for me. I did some code glance and search, and I don't know if that's ok to add an option for ValueMerger and try to set the KeyKind to  InternalKeyKindDelete [here](https://github.com/cockroachdb/pebble/blob/61318a019370e3666d66ef96880b0af9b9b65285/compaction_iter.go#L328).

**Comment by petermattis** [comment]
Changing the `ValueMerger.Finish()` interface could be done. This does break API compatibility, but it is easy for users to adapt to. Alternately, you could add an optional `ValueMerger2` interface that is used when implemented. If you're familiar with Go, this pattern is used in the stdlib and elsewhere. If you're not familiar with Go, this all might be a bit of a heavy lift.
