### ISSUE TITLE
db: more deterministic SingleDelete semantics for Set

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/pebble#1255]
Currently SingleDelete is only guaranteed to behave correctly if the key has been Set at most once.
- We say something about Merge in the code, but CockroachDB does not currently use Merge with SingleDelete, and this issue is not trying to make it behave better for Merge.
- The RockDB doc for SingleDelete says it can be used if the user key has only been Set once since the last SingleDelete https://github.com/facebook/rocksdb/wiki/Single-Delete. I haven't verified whether that doc is correct, but this is definitely not true for Pebble (see example below).

We need to accommodate cases where the key has been Set at most once since the last Delete/SingleDelete. That is, sequences like `Set => SingleDelete/Delete => Set => SingleDelete` where `=>` is happens-before. This will eliminate current bugs in CockroachDB related to early intent removal (https://github.com/cockroachdb/cockroach/issues/69891) which cause us to forget whether the user key has been used before, and will eliminate future concerns related to range movement using Delete to delete a range (instead of DeleteRange). The above sequences do not work correctly since it can be transformed into `Set => Set => SingleDelete` if the later `Set` and `SingleDelete/Delete` meet in a compaction. This can then be transformed into `Set` if the later `Set` and `SingleDelete` meet in a compaction.

The following informally sketches the solution.

Semantics: SingleDelete declares a desire by the caller to Delete that user key, where the caller expects that a Get at a sequence number after the SingleDelete should return nothing. In return, the caller is promising that there is at most one Set since the last Delete/SingleDelete.

Solution:
- Introduce a SET-WITH-DEL key-kind that represents a SET that has potentially consumed a DEL or SINGLEDEL key-kind in a compaction.
- The current SET key-kind will be interpreted as a SET that makes a promise that it has not consumed a DEL or SINGLEDEL. This is what will be written when a caller uses `pebble.Writer.Set`.
- A `SET => SINGLEDEL` in a compaction causes both to be consumed. A `SET-WITH-DEL => SINGLEDEL` in a compaction results in a `DEL`.
- Compatibility:
  - An alternative would be to interpret the current SET as a SET that makes no promise and introduce a SET-WITHOUT-DEL. This seems more natural since older versions of Pebble are not tracking these states. However such older versions are not correct with this broader use of SINGLEDEL either, so the broader use must be introduced *after* we are running the newer Pebble.
  - CockroachDB 21.1 to 21.2 transition: Nodes running 21.1 cannot read a Pebble store that was used by a 21.2 node and now contains SET-WITH-DEL. Similarly, 21.1 nodes cannot interpret snapshot sstables that contain SET-WITH-DEL.
    - 21.2 nodes will generate snapshot sstables that contain SET. This follows naturally from the fact that SET is what is written by `pebble.Writer.Set`.
    - We will introduce the new behavior of `compaction_iter.go` producing `SET-WITH-DEL` using the "format major version" being developed in https://github.com/cockroachdb/pebble/pull/1227
    - This format upgrade needs to happen when the cluster version is finalized to 21.2. We do not want to have 21.2 clusters that are not tracking `SET-WITH-DEL` since this can be a source of subtle correctness bugs due to future code changes.

TODO: proof sketch. Intuitively, the above works because `SET-WITHOUT-DEL => SINGLEDEL` in a compaction can precisely count according to the original promise made by the caller. When we can't count precisely, we fall back to interpreting SINGLEDEL as DEL, which is consistent with the original desire by the caller that the user key be deleted.

**Comment by petermattis** [comment]
When I read https://github.com/cockroachdb/cockroach/issues/69891 my initial thought was that we'd have to somehow record that a DEL occurred underneath a SET. I was imagining we'd to steal a bit from the key kind to indicate that a DEL occurred underneath another record and has been compacted away. Your idea of adding a single new SET-WITH-DEL key kind wastes fewer kinds. For completeness, we could later add a MERGE-WITH-DEL as that is the only other record we'd potentially need to remember a compacted away DEL for. With either approach, we'll have to update everywhere that switches on the key kind. There is also the concern about forwards compatibility. Old versions of Pebble won't be able to handle these new records. I'll continue to noodle on this, but I don't currently see another option for extending the SINGLEDEL semantics.

**Comment by jbowens** [comment]
This comment in RocksDB seems to describe that RocksDB implements the desired semantics by refusing to drop `SINGLEDEL`s until either they successfully drop a key _or_ there's a guarantee the user key doesn't appear in a lower level.
 
https://github.com/facebook/rocksdb/blob/2e09a54c4fb82e88bcaa3e7cfa8ccbbbbf3635d5/db/compaction/compaction_iterator.cc#L515-L545

**Comment by sumeerbhola** [comment]
@jbowens I was unable to interpret rule 2 in that RocksDB comment since it talks about "allow Transactions to do write-conflict checking" and "If there is no earlier snapshot, then we know ...". If there are no snapshots in the system at all, do you think it will elide the SingleDelete? I guess other than curiosity it doesn't matter too much what RocksDB did since they say later that "Deletes ... are not supported on the same key that has a SingleDelete" and we explicitly want to support Deletes on the same key.

**Comment by sumeerbhola** [comment]
> I was imagining we'd to steal a bit from the key kind to indicate that a DEL occurred underneath another record and has been compacted away. Your idea of adding a single new SET-WITH-DEL key kind wastes fewer kinds.

Do you think stealing a bit simplifies some code? I guess an `InternalIterator` implementation could hide the difference from `Iterator` by applying a bit mask. But there are other cases where `InternalIterator` needs to expose the difference, so I am not sure whether this is a real code simplification. We do have 4 unused bits of the 8 bits reserved for the `InternalKeyKind` so if we use up 1 bit here we still have ample room to grow.

**Comment by petermattis** [comment]
> Do you think stealing a bit simplifies some code?

I don't know. I think you'd have to inspect the places we switch on key kind to make that determination.

**Comment by sumeerbhola** [comment]
@jbowens @tbg  I'm trying to reason about whether this Pebble change is a CockroachDB release blocker or a GA blocker for 21.2.
If the beta for 21.2 has a workaround in CockroachDB and does not have this Pebble change, can we subsequently introduce a cluster version `roachpb.Version{Major: 21, Minor: 1, Internal: <something bigger>}` for the GA release and bump up Pebble's "format major version" and CockroachDB's "minimum storage version" and start writing `SET-WITH-DEL`? This would make 21.2 GA more robust and allow us to introduce wider usage of `SingleDelete` for 22.1.

**Comment by jbowens** [comment]
@sumeerbhola I believe that we can introduce a new cluster version in GA. I think the only requirement is that GA needs to include the final 21.1 cluster version.

**Comment by petermattis** [comment]
Per @andy-kimball's recent internal CRL message, the 21.2 betas need to be compatible with the eventual 21.2 release. I don't know if that constrains against introducing a new cluster version after the first beta.

**Comment by tbg** [comment]
It should be possible to introduce the new pebble behavior in 21.2 GA even if the first beta(s) don't have it yet, however this will need close coordination with the release-eng team. Essentially we need to coordinate minting the 21.2 cluster version on the release-21.2 branch so that this happens only when you have put in the version gate to use the SET-WITH-DEL.
Serverless should be OK with this. They need a build that doesn't explode on them an upgrade path, that's about it. Concretely, we could have the Serverless use (say) `21.2-beta.1` which is really `roachpb.Version{Major: 21, Minor: 1, Internal: 12345 (or whatever the pebble version gate ends up being)}` and the final version `{21, 2, 0}` is only present in `beta.2`. Serverless would then upgrade to 21.2 GA when it is available.

The meta question is whether it is risky to make these pebble changes. I do think the pebble change is absolutely necessary in the mean time and makes SingleDel "usable". But are we going to mess something up putting this in in a hurry? On the face of it these changes seem "not too complicated" but I'm too far removed from this code to really tell. As a general rule of thumb, I think we should be conservative at this point - we have a single user of SingleDel in CRDB and (hopefully) have good confidence that we have made it safe.

**Comment by sumeerbhola** [comment]
> The meta question is whether it is risky to make these pebble changes. I do think the pebble change is absolutely necessary in the medium term and makes SingleDel "usable". But are we going to mess something up putting this in in a hurry? On the face of it these changes seem "not too complicated" but I'm too far removed from this code to really tell. As a general rule of thumb, I think we should be conservative at this point - we have a single user of SingleDel in CRDB and (hopefully) have good confidence that we have made it safe.

I would lean heavily towards fixing this in Pebble for GA. Otherwise we have to keep hacks like `mustUseClearRange=true` for the duration of 21.2, and hope that there are no other undiscovered cases. That is, I think fixing Pebble is the lesser risk.

It is very unfortunate that we are discovering this problem now, even though separated intents were enabled for almost the whole of the 21.2 development cycle -- we should also see whether we could have better KV package unit tests that would uncover such problems (and needless to say, storage package unit tests).

**Comment by tbg** [comment]
Ok, I trust your judgment there. It would be nice to be on solid ground wrt SingleDel semantics in 22.1.
