### ISSUE TITLE
internal/metamorphic: same seed may generate different operations

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1289]
Discovered when debugging #1285.

When setting `-seed` locally to that of a failed remote test run, a different sequence of operations may be generated. This defeats the purpose of having a seed, which should produce a stable output, even across platforms.

Investigate why this is happening, and what we can do to mitigate.

**Comment by jbowens** [comment]
Was the difference in generated operations definitely run with the same commit SHA? New uses of the randomness can cause the operations generated from a seed to diverge between SHAs.

Reiterating the suggestion during standup: Incorporating a checksum value into the seed would allow us to fail immediately if we generate an unexpected set of operations.

There exists the [TestGeneratorRandom](https://github.com/cockroachdb/pebble/blob/031921b4a1c647e889a8875c43b75532fb5f61f3/internal/metamorphic/generator_test.go#L127) unit test that tests reproducibly generating operations. If there's a bug, it's probably higher up than `generate`, and maybe we should add a unit test higher up as well.

**Comment by nicktrav** [comment]
Yeah, same original SHA:

```console
$ git rev-parse HEAD
634eb34a29e146116a53e77e1fea8f67bce8a686
$ rm -rf internal/metamorphic/_meta/
$ go test -mod=vendor -tags 'invariants' -run TestMeta$ ./internal/metamorphic -seed 1632284396633596427 -keep
ok      github.com/cockroachdb/pebble/internal/metamorphic      70.106s
$ diff -u internal/metamorphic/_meta/*/ops ~/Downloads/Nightlies_Nightly_Pebble_Metamorphic_27546_artifacts/meta/210922-001956.633/ops | head
--- internal/metamorphic/_meta/210927-112034.733/ops    2021-09-27 11:20:34.000000000 -0700
+++ /Users/nickt/Downloads/Nightlies_Nightly_Pebble_Metamorphic_27546_artifacts/meta/210922-001956.633/ops      2021-09-22 04:20:48.000000000 -0700
@@ -1,4 +1,4 @@
-Init(65 /* batches */, 85 /* iters */, 64 /* snapshots */)
+Init(149 /* batches */, 204 /* iters */, 149 /* snapshots */)
 db.Set("khlisfnqwv", "kfnyjfqdrkg")
 db.Get("khlisfnqwv")
 db.Set("khlisfnqwv", "eesrcjruzhixtjsjh")
@@ -8097,8 +8097,12341 @@
 db.SingleDelete("nyqrc", false /* maybeReplaceDelete */)
```

> Reiterating the suggestion during standup: Incorporating a checksum value into the seed would allow us to fail immediately if we generate an unexpected set of operations.

+1 - this sounds like a good idea.

**Comment by nicktrav** [comment]
> There exists the TestGeneratorRandom unit test that tests reproducibly generating operations. If there's a bug, it's probably higher up than generate, and maybe we should add a unit test higher up as well.

Wondering if there's something platform-specific that's leaking into the RNG. The test suite runs on Linux, and I'm testing on a Mac.
