### ISSUE TITLE
perf: rate-limit file deletions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#129]
RocksDB has support for rate-limit how fast sstables and WAL files are deleted. This is controlled by [`SstFileManager`](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/sst_file_manager.h#L84-L118) which CockroachDB currently doesn't use (perhaps it should). There are two parameters which control the rate of file deletions:

```
// @param rate_bytes_per_sec: How many bytes should be deleted per second, If
//    this value is set to 1024 (1 Kb / sec) and we deleted a file of size 4 Kb
//    in 1 second, we will wait for another 3 seconds before we delete other
//    files, Set to 0 to disable deletion rate limiting.
//    This option also affect the delete rate of WAL files in the DB.
...
// @param bytes_max_delete_chunk: if a file to delete is larger than delete
//    chunk, ftruncate the file by this size each time, rather than dropping the
//    whole file. 0 means to always delete the whole file. If the file has more
//    than one linked names, the file will be deleted as a whole. Either way,
//    `rate_bytes_per_sec` will be appreciated. NOTE that with this option,
//    files already renamed as a trash may be partial, so users should not
//    directly recover them without checking.
```

Why rate-limit file deletions? https://github.com/facebook/rocksdb/pull/5116 says "high delete rate on SSDs that may affect other operations".

@ajkr Can you shed more light on the benefits of rate-limiting file deletions?

**Comment by ajkr** [comment]
I think there was some firmware-dependent thing where the deleted data might be garbage collected immediately, causing a latency spike for foreground I/Os. Spacing out deletion in the application prevents that undesirable outcome, regardless of how large compactions are and regardless of the firmware.

**Comment by ajkr** [comment]
There is a pretty timely article mentioning its usage in FB (their Cassandra uses RocksDB as its storage engine so I imagine the "internal delete scheduler that slowly deletes files" refers to Rocks's delete scheduler): https://lwn.net/SubscriberLink/787272/2ffe477b25b4940b/

**Comment by petermattis** [comment]
Interesting. How do we detect if badness is happening with discard?

**Comment by ajkr** [comment]
I think the disk stall detector is a good bet. Maybe have a way to log warnings when disk stall is 1+ second, then we can see if it correlates with file deletions in the log.
