### ISSUE TITLE
 leaked iterators occurred when I ran a simple test

### ISSUE THREAD

**Issue by duwu** [cockroachdb/pebble#1294]
The output is as follows:
shelock@shelockdeMacBook-Pro bigcache-bench % go test -bench=BenchmarkPebbleGet -benchmem -benchtime=4s ./... -timeout 30m
goos: darwin
goarch: amd64
pkg: github.com/allegro/bigcache-bench
cpu: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
BenchmarkPebbleGet-8             1000000              6801 ns/op              40 B/op          3 allocs/op
2021/09/29 16:48:19 leaked iterators: current
0.0:
  000285:[key-0000000000-key-0000000000]
  000169:[key-0000492994-key-0000520289]
  000171:[key-0000520290-key-0000547577]
  000173:[key-0000547578-key-0000574872]
  000175:[key-0000574873-key-0000602157]
  000177:[key-0000602158-key-0000629453]
                        .
                        .
                        .
  000195:[key-0000847791-key-0000875069]

 
6:
  000284:[key-0000000000-key-0000513868]
  000108:[key-0000513869-key-0000999999]
exit status 1
FAIL    pebble_bench       8.696s
FAIL

The code is as follows,Is there  anything wrong?
```golang
func BenchmarkPebbleGet(b *testing.B) {
	b.StopTimer()
	cache := pebble.NewCache(int64(b.N))
	db, err := pebble.Open("demo", &pebble.Options{Cache: cache})
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	for i := 0; i < b.N; i++ {
		if err := db.Set([]byte(key(i)), value(), pebble.NoSync); err != nil {
			log.Fatal(err)
		}
	}
        b.StartTimer()

	for i := 0; i < b.N; i++ {

		_, closer, err := db.Get([]byte(key(i)))
		if err != nil {
			if err != pebble.ErrNotFound {
				log.Fatal(err)
			}

		} else {
			closer.Close()
		}

	}
	
}
```

**Comment by bananabrick** [comment]
This comment from the `NewCache` function might be relevant.
```
// NewCache creates a new cache of the specified size. Memory for the cache is
// allocated on demand, not during initialization. The cache is created with a
// reference count of 1. Each DB it is associated with adds a reference, so the
// creator of the cache should usually release their reference after the DB is
// created.
//
//   c := pebble.NewCache(...)
//   defer c.Unref()
//   d, err := pebble.Open(pebble.Options{Cache: c})
```
You probably want a `cache.Unref()` after the db has opened successfully.

**Comment by duwu** [comment]
@bananabrick thank u very much ,however the problem is not solved

**Comment by petermattis** [comment]
@duwu I don't see anything obviously wrong with your code. There is no report of a leaked iterator when I run your benchmark. Does this problem reliably occur for you?

**Comment by jbowens** [comment]
Closing for now, assuming this issue is resolved. Please re-open if the issue persists.
