### ISSUE TITLE
Run ycsb benchmarks for longer than 10 minutes

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/pebble#1343]
We currently run the pebble ycsb benchmarks for 10 minutes per workload, and we run each workload 5 times. This has served us well when detecting performance regressions which become apparent within the first 10 minutes of running pebble and this also gives us a baseline for pebble performance.

1. One motivating reason to bump the duration of these workloads is the pebble ycsb/E related investigation which I looked into recently. Turns out that prior to commit [f2339cc7857325dc55c9f3460001dc8518d9fc3a](https://github.com/cockroachdb/pebble/commit/f2339cc7857325dc55c9f3460001dc8518d9fc3a), ycsb/E w-amp would increase with time due to read compactions. I observed w-amps in the range of 45-70, after 2 hours of running ycsb/E. Running our benchmarks for longer would've allowed us to detect the read compaction issues much earlier than we initially did. There could be other features in the future which reduce the performance of the system with respect to time.

2. Right now, the cache hit rates in our nightly benchmarks are close to 100%. This is because there isn't enough data in the lsm to cause cache evictions. By only running the benchmarks for 10 minutes, we get a false sense of pebble's performance because we're not testing scenarios with cache misses.

3. By running benchmarks for longer, we get lsms with more data in them, which more accurately simulates real workloads.

Proposal: Run the workloads for both 10 minutes, and 1-2 hours. The longer workloads might not need 5 runs per workload.

**Comment by nicktrav** [comment]
@bananabrick  - we're good on this one now, yeah? Done in cockroachdb/cockroach#71943.

**Comment by bananabrick** [comment]
@nicktrav I missed your comment before. Yea, I can close this. There are some changes I have in mind for each individual test, but those changes are separate from this issue.
