### ISSUE TITLE
manifest: optimize NewL0Sublevels for the flush case

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/pebble#1406]
The general case of making NewL0Sublevels incremental (by reusing the previous L0Sublevels) is hard since there can be files being added and removed due to L0=>Lbase or intra-L0 compactions.

The flush case is somewhat simpler: there are a handful of files being added as the latest files to L0, so they will slide in on top of existing intervals, and cause some intervals to be split.
Looking at a profile of `BenchmarkL0SublevelsInit` which has ~33,000 files, and runs in 44.16s on my macbook, the major components that can be saved are:
```
    244            .     10.65s           	keys = sortAndDedup(keys, cmp) 
    259         50ms      5.33s           		f.minIntervalIndex = sort.Search(len(keys), func(index int) bool { 
    260            .          .           			return intervalKeyCompare(cmp, intervalKey{key: f.Smallest.UserKey}, keys[index]) <= 0 
    261            .          .           		}) 
    267         50ms      4.81s           			sort.Search(len(keys)-f.minIntervalIndex, func(index int) bool { 
    301        780ms     11.65s           			interval.files = append(interval.files, f) 
```
and some smaller ones.
The incremental version would need to:
- split intervals corresponding to the start and end of flushed files and adjust the `minIntervalIndex` and `maxIntervalIndex` of existing files.
- add the new files on top of these split and overlapping intervals.
- some more details TBD

One question is whether this complexity is worth it: a slow NewL0Sublevels means slower flushes, but if Pebble is already behind by having too many files in L0, is there any point in making flushes faster and avoiding write stalls due to too many memtables?

**Comment by jbowens** [comment]
> One question is whether this complexity is worth it: a slow NewL0Sublevels means slower flushes, but if Pebble is already behind by having too many files in L0, is there any point in making flushes faster and avoiding write stalls due to too many memtables?

Since applying version edits is sequential and requires holding `DB.mu`, a slow `NewL0Sublevels` blocks everyone else, including compactions trying to install their version edits. That reduces the _effective_ compaction concurrency. I wonder how much `NewL0Sublevels` slowness reduces the effective compaction concurrency as read-amplification is building, but before hitting hard memtable stalls.

**Comment by itsbilal** [comment]
I think this would be a good win; there's definitely a case to be made about incrementally building L0Sublevels, and flushes are the most straightforward place. Happy to take this on as well. The only "expensive thing" in a flush incremental build would be having to shift all the `{min,max}IntervalIndexes` ahead . 

I wonder if we can also do an incremental update for an LBase compaction. A rectangle (or union of rectangles, increasing in breadth as we descend sublevels) will disappear, but determining all the interval changes for each sublevel and also determining the downward sublevel shifts could be expensive enough to make that a de-optimization.
