### ISSUE TITLE
perf: add range key benchmarks and address performance

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1444]
Once we're farther along with the range keys implementation, we should add benchmarks and evaluate the performance impact of range keys on combined iteration.

In the meantime, I'll catalog potential performance improvement ideas here:

* ~~The `rangekey.Iter` has unnecessary, redundant per-fragment key comparisons. See these TODOs: [1](https://github.com/cockroachdb/pebble/blob/90d9c97f8c623f1d5d447995429c5c35564fd347/internal/rangekey/iter.go#L70-L72), [2](https://github.com/cockroachdb/pebble/blob/90d9c97f8c623f1d5d447995429c5c35564fd347/internal/rangekey/iter.go#L94-L96)~~
* Avoid unnecessary duplicate copying of range-key state in Iterator. See this TODO in `Iterator.saveRangeKey`: [iterator.go:1341-1343](https://github.com/cockroachdb/pebble/blob/c75a2e96a7e8e7418f53ff563ec620097dd8d495/iterator.go#L1341-L1343)
* #1605 
* #1742

**Comment by mwang1026** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/83049
