### ISSUE TITLE
db: push down time-bound iterator filtering

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1446]
CockroachDB's time-bound iterators now use block-property filtering to skip over sstables and blocks that wholly consist of data outside the time-bound iterator's timestamp range (#1190). When a block does contain relevant data, the CockroachDB-level iterator must still visit every key contained within the block, discarding those outside of the time bounds. Each one of these keys needs to bubble up through the Pebble iterator, which involves at least one key comparison within the merging iterator, plus one key comparison within the `pebble.Iterator` to determine if it's a new user key. Pushing down the timestamp comparison into the block would allow us to discard irrelevant keys using the comparatively cheap timestamp comparison, avoiding extra full key comparisons of potentially long keys.

https://github.com/cockroachdb/pebble/issues/1190#issuecomment-1007484821

**Comment by jbowens** [comment]
#111338 pushed down filtering into `pebble.Iterator`. It doesn't avoid the merging iterator comparisons, but it does replace unnecessary `nextUserKey` comparisons with timestamp comparisons. I'm not sure there's much more to be gained by pushing down the filtering even further. Maybe a bit, but then `WithLimit` calls would not be bounded when time-bound iteration is active. Thoughts on closing this out?

**Comment by sumeerbhola** [comment]
Closing this sounds good.
