### ISSUE TITLE
Compact end cannot be nil, difficult to compact the whole database

### ISSUE THREAD

**Issue by hkalina** [cockroachdb/pebble#1474]
In Pebble it is difficult to **compact the whole database** - for leveldb I can just call:
```
db.CompactRange(nil, nil)
```
However if I pass "nil" into the end of Pebble compact, I will get an error:
```
db.Compact(..., nil)
"Compact start \\xf0 is not less than end "
```
I can do something similar:
```
db.Compact([]byte{}, []byte{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff})
```
However it seems there is no obvious value, which could be passed to compact the end of the database - keys like `{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01}` will still be ignored.

**Comment by nicktrav** [comment]
One approach that we take [internally](https://github.com/cockroachdb/pebble/blob/060753c8d4c7a043189274a689560cdb3c9a2ce5/cmd/pebble/compact.go#L354-L389) is to first compute the range of the keyspace that should be compacted, then using those keys to pass to `Compact()`:

```go
var d *pebble.DB
// ... open DB, etc.

iter := d.NewIter(nil)
var first, last []byte
if iter.First() {
  first = append(first, iter.Key()...)
}
if iter.Last() {
  last = append(last, iter.Key()...)
}
if err := iter.Close(); err != nil {
  return err
}
if err := d.Compact(first, last); err != nil {
  return err
}
```

As for adding the `Compact(nil, nil)` shorthand for compacting the entire DB, I'd have to let someone else weigh in that. It sounds like a reasonable idea, though I'm not sure if there's a particular reason for that not having been added in the past.

**Comment by bananabrick** [comment]
This is what we do in Cockroach:
```
// Compact implements the Engine interface.
func (p *Pebble) Compact() error {
	return p.db.Compact(nil, EncodeKey(MVCCKeyMax))
}
```

So, if your application has a key which sorts after every other key, that can be used. I think using `nil, nil` is fine. Feel free to make a pull request which does that.

This is where the function is: https://github.com/cockroachdb/pebble/blob/master/db.go#L1197

**Comment by petermattis** [comment]
It is somewhat subtle to have an API which treats `nil` and `[]byte{}` differently. I say this even though we have APIs like `Iterator.Key()` that return `nil` when done, so I'm not perfectly consistent. I have a mild preference for introducing a `CompactAll()` method if you want to compact everything and can't easily generate an "infinity" key.

**Comment by hkalina** [comment]
@petermattis please notice it is not only about compacting ALL - we compact part-by-part like this:
```
for b := 0x00; b <= 0xf0; b += 0x10 {
	start := []byte{byte(b)}
	end   := []byte{byte(b + 0x10)}
	if b == 0xf0 {
		end = []byte{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff} // not sufficient if there is a greater key in db
	}
	updateProgressBar(...)
	err := db.Compact(start, end)
}
```

**Comment by petermattis** [comment]
Ack. I'm sympathetic to this usage, though still adverse to using `nil` to indicating a max key. Is there anything preventing you from doing as @nicktrav suggests and creating an iterator and calling `Last()` to find the largest key? The overhead of creating the iterator and seeking to the last key will be trivial in comparison to the compaction. You can wrap this all up in some sort of `LargestKey` helper function.

**Comment by hkalina** [comment]
Solution by @nicktrav should be sufficient, thanks!
