### ISSUE TITLE
debug tools should handle partially written/corrupted manifests

### ISSUE THREAD

**Issue by tbg** [cockroachdb/pebble#1475]
Got this on a node that had crashed after running out of disk:

```
 ~/cockroach debug pebble db properties .
pebble: reading manifest "MANIFEST-000001": pebble/record: invalid chunk
```

I assume that if I freed up some space, CRDB would start again. So the debug tools too should be able to investigate the DB.

**Comment by jbowens** [comment]
Do you happen to have a copy of the MANIFEST?

> I assume that if I freed up some space, CRDB would start again.

I think this error is actually a low-level corruption error that would trigger during store start too.

**Comment by tbg** [comment]
I don't unfortunately. This was on one of the clearrange runs, but I did lots of them and didn't save their data.

**Comment by jbowens** [comment]
Going to close out this as unactionable.
