### ISSUE TITLE
db: add external sstable iterator interface

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1526]
Clients, including CockroachDB, sometimes have a need to iterate over the merged keys of several external sstables. In CockroachDB, backups are written in an sstable format. Incremental backups record a diff of changed state. During restore, CockroachDB must iterate over the backup sstables to reconstruct the current state, merging across sstables. Today, this is performed by [pkg/storage.multiIterator](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/multi_iterator.go).

We should provide a facility for external users like CockroachDB to use Pebble's own internal iterators, especially now that iteration has become more complicated with interleaving range keys.

----

One implementation idea is to allow constructing `*pebble.Iterator` that reads these external sstables through constructing an artificial `readState` representing the input set of sstables. We could require that the sstables have all-zero sequence numbers, and assign each of sstable within the input set an artificial global sequence number, so that invariant checks and zero-seqnum optimizations aren't run afoul.

**Comment by jbowens** [comment]
@erikgrinaker — I'm giving this a stab today. It looks pretty feasible, but famous last words.

@sumeerbhola — Do you have any thoughts on the above implementation strategy?

**Comment by sumeerbhola** [comment]
> Do you have any thoughts on the above implementation strategy?

How will we deal with the fact that these are not leveled ssts, and can't be treated as being in the same level since they can overlap?
