### ISSUE TITLE
db: split L0 compactions for concurrent manual compactions

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/pebble#1533]
While benchmarking https://github.com/cockroachdb/pebble/pull/1487, we noticed that the key ranges in L0, are difficult to split into non overlapping key ranges.

If we consider each file interval in L0, as a node, and edges between these nodes if the file intervals overlap, then the graph of these file intervals, has exactly one connected component. For this reason, we can't split the files in L0, into non overlapping key ranges. It's worthwhile to investigate why the key ranges have high overlap. But, we could also try to work around the problem.

It might be possible to split the L0 sublevels by their sequence numbers. For example, if we have a 1000 sublevels, and files in these sublevels have sequence number from 1-1000+, then we can split the sequence numbers into 1-200, 201-400, etc, and find non overlapping key ranges for each sequence number range. By splitting files based on these sequence numbers ranges, we reduce the probability of file overlap, and it might be possible to get more concurrency out of L0 manual compactions.

**Comment by sumeerbhola** [comment]
> If we consider each file interval in L0, as a node, and edges between these nodes if the file intervals overlap, then the graph of these file intervals, has exactly one connected component.
> ...
> It's worthwhile to investigate why the key ranges have high overlap. But, we could also try to work around the problem.

+1 to understanding why the key ranges have high overlap. I would urge not trying to work around the problem without a proper understanding.

**Comment by mufeez-amjad** [comment]
I started looking into the keyrange overlap issue for L0, specifically why `L0Sublevels.InUseKeyRanges(start, end)` returns 1 keyrange, but haven't determined the cause. Commenting my progress here for anyone else to take a look.

When running `./pebble bench ycsb /mnt/data1 --workload=F --duration=10m --concurrency=1000`, it looks like after roughly 8 minutes, 

```go
start := []byte("a")
end := []byte("z")
v.L0Sublevels.InUseKeyRanges(start, end)
```
continues to return 1 single keyrange. I noticed that there are also some periods (~3 minutes in) where this happens but it seems to recover. 

I also ran the workload with concurrency=256 and `InUseKeyRanges` was always much greater than 1 for L0. Maybe concurrency=1000 is an extreme case that produces this issue?

Also, here is the state of L0Sublevels when `InUseKeyRanges=1` (@ ts ~= 8m15s in the debug output),
```
inUseKeyRanges b/w [a, z]: 1
Number of L0 sublevels: 9
Number of ordered intervals: 508
L0.0 has 44 files
L0.1 has 39 files
L0.2 has 36 files
L0.3 has 33 files
L0.4 has 26 files
L0.5 has 23 files
L0.6 has 26 files
L0.7 has 13 files
L0.8 has 14 files
```

Here is the full debug output ([with keyranges](https://github.com/cockroachdb/pebble/files/8158210/out.txt), [without](https://github.com/cockroachdb/pebble/files/8158213/out-clean.txt)), and the [manifest](https://github.com/cockroachdb/pebble/files/8158217/MANIFEST-000001.zip).

**Comment by bananabrick** [comment]
Thanks for the investigation @mufeez-amjad . I think with the lower concurrency, the L0 read amp probably wasn't high enough for the high overlap to occur. I think the result would've been the same as the 1000 concurrency case, if we let it run for longer.

I think the next steps here should be to:
1. Investigate some more to determine if we have some logic/heuristic which leads to high overlap in L0.
2. Fix the problem, if it is unavoidable.
3. If the problem is unavoidable, then we can work around it by only considering a few sublevels at a time for manual compactions.

**Comment by bananabrick** [comment]
I looked into the high overlap. First, I determined what was going on in a Pebble level workload, and then ran a Cockroach level workload, to see if the behaviour was reproducible.

**Starting with pebble ycsb/F**

Running the workload with a concurrency of 256 for 30 seconds creates enough overlap in L0 that the L0Sublevels.InUseKeyRanges function returns only 1 key range. Running the compaction log tool on this, we get:

```
node: 0, store: 0
from: 010101 00:00
  to: 010101 00:10
______from________to___default______move_____elide____delete_____flush_____total_____bytes______time
        L0        L4        14         0         0         0         0        14     1.6 G        0s
        L0        L5        38         0         0         0         0        38     602 M        0s
        L0        L6         1         0         0         0         0         1      58 M        0s
        L4        L5       157        62         0         0         0       219     1.9 G        0s
        L5        L6       149         0         0         0         0       149     2.2 G        0s
     total                 359        62         0         0         0       421     6.4 G        0s
```

The lsm looked like the following before the first time L0Sublevels.InUseKeyRanges returned a single key range:
```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         2    73 M       -   944 M       -       -       -       -   954 M       -       -       -     1.0
      0       109   168 M    1.91   882 M     0 B       0     0 B       0   865 M     529     0 B       5     1.0
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      4        45   176 M    2.95   240 M     0 B       0     0 B       0   240 M      62   240 M       1     1.0
      5        47   190 M    0.89   414 M     0 B       0    48 M      13   624 M     170   624 M       1     1.5
      6        50   330 M       -   330 M     0 B       0     0 B       0   825 M     133   826 M       1     2.5
  total       251   864 M       -   954 M     0 B       0    48 M      13   3.4 G     894   1.7 G       8     3.7
  flush        14
compact       126   1.2 G    28 M       2          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype       113       0       0      13       0  (default, delete, elision, move, read)
 memtbl         2   128 M
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache       267   8.0 M    0.4%  (score == hit-rate)
 tcache         2   1.3 K   26.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers         0
 filter         -       -    0.0%  (score == utility)
 ```

The read amp was 5 with a ~100 files in L0. Note that there were 218 orderedIntervals in L0(2 * num files), and each file was spanning around 16 ordered intervals. This means that each file in L0 had an overlap with at least 8 other files. With only a ~100 total files in L0, it's not surprising that L0Sublevels.InUseKeyRanges only returns one key range. Note that after this point, we continued to return only one key range.

The problem seems to be each file being a little wide, instead of a few files overlapping every other file.

To confirm that the problem wasn't related to the key distribution generated by the workload, I ran the workload with a random distribution, and saw the same result.

Don't have a conclusion yet, will flush more results tomorrow.

**Comment by bananabrick** [comment]
Flushing some more data from the Pebble ycsb/F workload which was generating high overlap.

I added instrumentation to the code to:
### Check if flush splitting is occurring.
This works as expected.

### Check whether L0->Lbase compactions were successfully reducing the height of L0.
Seemed to work.

### Check whether the flush splitting logic was working as intended

Looking at another L0Sublevels construction which occurred within the first 10 seconds of starting the ycsb/F benchmark, the number of sublevels was 8, there were ~400 ordered intervals, on average each file was spanning ~8 ordered intervals, and the widest file was spanning ~18 ordered intervals. For this example, here's a map from the the height of an orderedInterval to the number of orderedIntervals with the given height:
```
1 -> 27
4 -> 82
5 -> 105
6 -> 62
7 -> 16
0 -> 1
2 -> 45
3 -> 51
8 -> 9
```
Here's a distribution of the file widths(# of ordered intervals a file spans) of *some* of the files to the number of files with that width(this doesn't include all of the files in L0).
```
10 -> 28
7 -> 24
8 -> 26
15 -> 10
13 -> 22
5 -> 24
11 -> 18
16 -> 14
18 -> 4
1 -> 20
2 -> 20
9 -> 30
3 -> 28
0 -> 32
14 -> 16
6 -> 20
12 -> 18
17 -> 8
4 -> 36
```

cc @itsbilal, nothing stands out to me as pathological. Maybe the fact that the flushSplitMaxBytes gets multiplied by the number of sublevels, which is used to prevent excessive flush splitting, but might be causing too little flush splitting. I'd appreciate some help with what else I should look at.

Attaching the manifest generated during the first 10 seconds of running ycsb/F:
[mani.zip](https://github.com/cockroachdb/pebble/files/8320115/mani.zip)

**Comment by sumeerbhola** [comment]
> L0Sublevels.InUseKeyRanges function returns only 1 key range

I didn't understand this. Does this mean that InUseKeyRanges(x, x) where x is a random key contained in some L0 file returns a span that covers all of L0?

> The read amp was 5 with a ~100 files in L0. Note that there were 218 orderedIntervals in L0(2 * num files), and each file was spanning around 16 ordered intervals. This means that each file in L0 had an overlap with at least 8 other files.

Some of those "8 other files" would not have overlapped with each other since the read amp was 5, yes?

**Comment by bananabrick** [comment]
> I didn't understand this. Does this mean that InUseKeyRanges(x, x) where x is a random key contained in some L0 file returns a span that covers all of L0?

To split L0 for manual compactions, we call  `L0Sublevels.InUseKeyRanges` over the entire key space. The `InUseKeyRanges` is expected to return the non-overlapping key ranges from all of L0. But it only returns a single key range because of the high overlap in L0.

> Some of those "8 other files" would not have overlapped with each other since the read amp was 5, yes?

I was using averages in that example, but I posted the file width distributions in [this](https://github.com/cockroachdb/pebble/issues/1533#issuecomment-1074583951) comment from a different run.

In the end, what I'm seeing is that if a file at level `i` is likely to overlap with > 1 file in level `i+1`, then we're likely to be unable to split the key ranges in L0 for use in concurrent manual compactions.

**Comment by sumeerbhola** [comment]
I think it is a mistake to use `L0Sublevels.InUseKeyRanges` to split the manual compactions out of L0.
Consider the following simple example with 3 sub-levels and the x-axis representing the key space and [---] representing file width:

```
[------][------][------][------][------]
      [------][------][------][------]
[------][------][------][------][------]
```
InUseKeyRanges will combine everything into one.
But there is compaction concurrency, though not all files will get picked if we union all the concurrent compactions. The following shows 2 concurrent compactions. But the ones that remain can be picked after some compactions complete.

```
[--1---][------][------][--2---][------]
      [--1---][------][--2---][--2---]
[--1---][--1---][--2---][--2---][--2---]
```

https://github.com/sumeerbhola/pebble/blob/9e120aba7e13e62e73fb3d30351a50e3614ee14e/tool/manifest.go#L359-L380 has some hacky code to show this, which I ran over the second manifest you shared over slack. It often has 6+ compaction concurrency and at the end of the manifest after 10 minutes there is concurrency for 14 compactions (though this might overcount a bit because it isn't considering the constraint from Lbase).

**Comment by bananabrick** [comment]
Thanks @sumeerbhola. I was seeing behaviour similar to your example, but I wrongly assumed that this would effect compaction concurrency out of L0. Files in some sublevel `i` were bridging two or more  files in sublevel `i+1`, and this was true for files in all sublevels which would cause `L0Sublevels.InUseKeyranges` to return only `1` key range.

The manual compaction code is structured to require non-overlapping key ranges to compact, which is what `calculateInUseKeyRanges` and `L0Sublevels.InUseKeyranges` was being used for.

Would the method I wrote up when I created this issue be the right path forward? cc @itsbilal 
```
It might be possible to split the L0 sublevels by their sequence numbers. For example, if we have a 1000 sublevels, and files in these sublevels have sequence number from 1-1000+, then we can split the sequence numbers into 1-200, 201-400, etc, and find non overlapping key ranges for each sequence number range. By splitting files based on these sequence numbers ranges, we reduce the probability of file overlap, and it might be possible to get more concurrency out of L0 manual compactions.
```

Even compacting a single sublevel at a time, starting from the lowest sublevel, and thus avoiding overlap with higher sublevels, would probably be much faster than the DAYS it takes to compact a large L0. It might also be faster to just schedule `MaxConcurrentCompactions` number of L0->LBase compactions, using the existing L0 compaction mechanisms.

**Comment by sumeerbhola** [comment]
> "It might be possible to split the L0 sublevels by their sequence numbers. ...

This idea may work, though there are questions about how we would adapt the granularity of splitting and what happens if the granularity we choose does not have any concurrency etc.
But I am also not keen on creating yet another complicated way to find concurrency in L0 for compactions. We have L0Sublevels, which is complex, but principled from a modeling perspective, and we should seriously consider adding improvements to it for the manual compaction case if we need them, rather than considering another way to organize L0 for compactions.

> Even compacting a single sublevel at a time, starting from the lowest sublevel ...

There are cases with 100s of sublevels. I think we should aim to do better than this.

It is easy to change `L0Sublevels.PickBaseCompaction` to take an optional `[start,end)`, since all it requires is narrowing the iteration in the initial ordered intervals loop https://github.com/cockroachdb/pebble/blob/7ad3551b20501b64dd2f89c0ed29bf61e8b66e67/internal/manifest/l0_sublevels.go#L1350-L1363. And compactions are allowed to exceed `[start,end)` since it is just a best-effort guideline. So we can keep calling this and starting compactions until there are no more compactions to start, then whenever a compaction completes and L0 is not yet empty, repeat this.

**Comment by itsbilal** [comment]
Thanks for mentioning that example Sumeer - my bad on not highlighting that earlier. I was wrongly assuming inUseKeyRanges was a better proxy for `PickBaseCompaction` when it isn't. It is possible to have better compaction concurrency here and flush splits aren't necessarily too bad here.

I would also caution against overthinking a solution beyond manual compactions. The bottom-up approach to picking L0 compactions that Arjun devised when doing manual compactions is a huge improvement for manual compactions, but for automatic ones we already have heuristics where we stop adding more files "on top" of the seed files for the compaction if it significantly grows that compaction. Maybe we could take another look at that logic to see if some of the numbers (eg. `maxExpandedBytes`) could be optimized, but broadly it is sound logic and I think we can leave it alone and focus on optimizing manual compactions alone.

And on that, it seems like the crux of the issue with manual compactions is we need to decide up-front what key ranges to schedule for compaction. `pickManualHelper` calls Overlaps which expands the key range all the way up to L0, while `PickBaseCompaction` does the far more concurrency-friendly optional expansion in the upward direction of the sublevel tree. For that reason I really like Sumeer's idea to reuse `PickBaseCompaction` (and maybe all of `pickL0` but with intra-L0 compactions disabled) for manual compactions.

**Comment by bananabrick** [comment]
Taking a closer look at the manual compaction code, it might be possible to make a different kind of optimization which is orthogonal to the current concurrency based optimizations we're considering. cc @itsbilal 

I believe that if we're doing a compaction out of L0 to Lbase, then we create iterators over each file in L0 which is involved in the compaction, and then we create a merging iter out of those. When we perform a manual compaction, we create an iter over every single file in L0(and there can be tens of thousands of these files), and then create a merging iter out of those. That's expensive.

It might be possible to instead create level iters over every sublevel in L0, and then create a merging iter over those. I don't have proof that this will be faster, but I think it's likely.

**Comment by itsbilal** [comment]
@bananabrick That's a good catch - we really should create levelIters there. We already do that in `finishInitializingIter` for actual user-facing iterators, but we do the inefficient shove-file-iterators-into-mergingIter thing for compactions. It may not speed up the compaction much, but it'd probably optimize our memory/cache usage instead of having all SSTs open throughout the compaction. And yes, that can be a separate issue.

**Comment by sumeerbhola** [comment]
As mentioned earlier, with concurrent compactions out of L0 (and other levels), we can switch to more often using crdb_internal.compact_engine_span (online manual compaction) instead of offline manual compaction, since it is hard to predict when a manual compaction will finish (or at least flatten L0), and users are wary of taking a CockroachDB node offline for an indeterminate interval of time.
One thing we need to address in using L0Sublevels.PickBaseCompaction is that the current approach to deciding when manual compactions are done for a level does not work. We currently queue the manual compactions for a level with all the non-overlapping key spans. For L0 sub-levels ,where a compaction may not completely slice out a key span out of all sub-levels, we need a better way to scope what is left to do, and inform L0Sublevels to construct compactions primarily using what it is left to do.

**Comment by sumeerbhola** [comment]
Thinking some more about the termination condition for saying compactions out-of-L0 are done when using L0Sublevels.PickBaseCompaction: given the shape of how we slice files out of L0 (roughly triangular shapes from the sub-levels), this is a complex problem and to do it perfectly (compacting the files that were in L0 at the start of the manual compaction) will require more tracking of files and algorithmic changes to L0Sublevels. I am wary of compicating L0Sublevels for this case.
A simpler alternative would be to rely on the fact that L0Sublevels is already trying to pick intervals that have maximum depth. So we could simply make a note of the byte size of L0 (B) when the manual compaction is requested, and when the subsequent sequence of manual L0=>Lbase compactions have moved > B out of L0, declare that L0 is done and then start on Lbase. This would be true to the spirit of what the manual compaction was requesting.

**Comment by nicktrav** [comment]
Moving this back into the backlog, as we decided to go with adding the machinery to be able to run a blocking SQL command to bump the compaction concurrency for 22.2.

**Comment by bananabrick** [comment]
I don't foresee the need for this, and will close this out, given that we have the tool to increase compaction concurrency.
