### ISSUE TITLE
TestOpenWALReplayReadOnlySeqNums failing intermittently

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1549]
Reproducer on master (at 69a82fe4):

```
$ go test -mod=vendor -tags 'invariants' -run TestOpenWALReplayReadOnlySeqNums -count 100 .
--- FAIL: TestOpenWALReplayReadOnlySeqNums (0.00s)
    open_test.go:820:
                Error Trace:    open_test.go:820
                                                        open_test.go:854
                Error:          Received unexpected error:
                                open original/000007.sst: file does not exist
                Test:           TestOpenWALReplayReadOnlySeqNums
--- FAIL: TestOpenWALReplayReadOnlySeqNums (0.00s)
    open_test.go:820:
                Error Trace:    open_test.go:820
                                                        open_test.go:854
                Error:          Received unexpected error:
                                open original/000005.sst: file does not exist
                Test:           TestOpenWALReplayReadOnlySeqNums
0x7fd6e800f690: memTable buffer was not freed
FAIL    github.com/cockroachdb/pebble   0.014s
FAIL
```

I bisected this down #1487.

**Comment by nicktrav** [comment]
cc: @mufeez-amjad @bananabrick

**Comment by bananabrick** [comment]
@mufeez-amjad 

I thought about how the behaviour before and after your pr were different and it looks like removing the following lines gets rid of this error: https://github.com/cockroachdb/pebble/blob/master/db.go#L1292-L1297

I don't know what to make of that yet.

**Comment by bananabrick** [comment]
Modified the `copyFiles` function in `TestOpenWALReplayReadOnlySeqNums` to 

```
	copyFiles := func(srcDir, dstDir string) {
		files, err := mem.List(srcDir)
		// time.Sleep(1)
		files1, err := mem.List(srcDir)
		require.Equal(t, files, files1)
		require.NoError(t, err)
		for _, f := range files {
			require.NoError(t, vfs.Copy(mem, mem.PathJoin(srcDir, f), mem.PathJoin(dstDir, f)))
		}
	}
```

Here's the diff:
```
                Error:          Not equal: 
                                expected: []string{"marker.manifest.000001.MANIFEST-000001", "marker.format-version.000005.006", "OPTIONS-000003", "000010.sst", "LOCK", "CURRENT", "000008.log", "000009.log", "MANIFEST-000001", "000006.log"}
                                actual  : []string{"000008.log", "000009.log", "MANIFEST-000001", "000006.log", "marker.manifest.000001.MANIFEST-000001", "marker.format-version.000005.006", "OPTIONS-000003", "000010.sst", "LOCK", "CURRENT"}
```

Looks like a logical race where files are getting deleted due to background compactions.

**Comment by mufeez-amjad** [comment]
I looked into the test failure and it looks like an automatic compaction is scheduled from L0 to L6, and, in some cases, when `db.manualCompact` is called on L0, the `LevelSlice` is already empty and so we exit early. In other cases, the manual compaction gets (retried and) dropped later on which allows the automatic compaction more time to finish.

In the first case, the compaction is still running after the call to `db.Compact` and changes between listing contents in the directory to copying them.

I can think of two ways to fix this:
1. Wait for all compactions to finish either at the end of `db.Compact` or in the test itself.
2. Remove that level empty check.

For 2, I think the downside would be that even if the start level was empty, we would split compactions and queue them all to be possibly scheduled. Sometimes there can be many key ranges (50+) and it would be better to avoid the extra computation. It would also pose a problem for when we don't have automatic compactions disabled and it's possible that we continuously retry a split compaction and hold up the rest of the queue.

1 would look something like this:
```go
d.mu.Lock()
for d.mu.compact.compactingCount > 0 {
	d.mu.compact.cond.Wait()
}
d.mu.Unlock()
```

**Comment by bananabrick** [comment]
Yea, waiting for the compactions to finish sgtm.
