### ISSUE TITLE
Periodically clearing keys

### ISSUE THREAD

**Issue by theflyingcodr** [cockroachdb/pebble#1566]
Hi, just a quick question regarding periodically clearing down records.

I will have a pebble store that every 10 seconds or so will read all records from Pebble, aggregate some values then send them somewhere. After this, the keys that have been aggregated are no longer required and can be removed.

What's the best way of achieving this, at moment I'm doing this:

```go
        // Code that iterates and does aggregates
	_ = iter.Close()
	b := db.NewBatch()
	if err := b.DeleteRange(earliestKey, latestKey, &pebble.WriteOptions{}); err != nil {
		log.Fatal().Err(err).Msg("failed to delete range")
	}
	if err := db.Apply(b, &pebble.WriteOptions{}); err != nil {
		log.Fatal().Err(err).Msg("failed to apply batch")
	}
	if err := db.Compact(earliestKey, latestKey, true); err != nil {
		log.Fatal().Err(err).Msg("failed to compact range")
	}
```

Do I need the batch here and will compact do the same thing as DeleteRange or do I need both?

**Comment by bananabrick** [comment]
Hi, thanks for trying out Pebble.

You can use `db.DeleteRange`, which should handle the batch creation and application for you. You need the `db.DeleteRange` call, but you don't necessarily need the `Compact` call. The `Compact` call blocks until the database is completely compacted, and shouldn't be called once every 10 seconds. As the database grows larger, compactions will be performed in the background, automatically.

**Comment by theflyingcodr** [comment]
@bananabrick ok great, thanks for that, so my general principle here is ok, I can ditch the batch and compact in that case. Thanks!

**Comment by jbowens** [comment]
@theflyingcodr You may also want to consider setting `Options.Experimental.DeleteRangeFlushDelay` to a multiple of your 10-second interval (for example, maybe `2*time.Minute`). If you're deleting data that is still in the memtable, the data won't actually be dropped until the memtable is flushed. The `Options.Experimental.DeleteRangeFlushDelay` option will trigger a flush of the memtable within the configured duration if one hasn't already happened.

**Comment by theflyingcodr** [comment]
Thanks for the info, didn't know about that! Shall get that added too 👌👍

**Comment by nicktrav** [comment]
@theflyingcodr - hopefully you got the answer you were looking for here. I'm going to close this out, but feel free to re-open if there's anything unanswered.
