### ISSUE TITLE
Compiling issue on ARM platform

### ISSUE THREAD

**Issue by dodiadodia** [cockroachdb/pebble#1575]
When compling on ARM platform (using GOARCH=arm), we encounter the following problem:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/4024470/157823974-899794a7-a47c-4adb-a512-4b52ce9429e1.png">
There is a discussion on StackOverFlow:
https://stackoverflow.com/questions/36231049/why-does-printing-out-max-int-cause-compile-error-in-golang

**Comment by jbowens** [comment]
Looks like you're compiling on a 32-bit ARM? Pebble currently doesn't support 32-bit architectures. See #884.

**Comment by imsodin** [comment]
I had the same issue and took a stab at fixing it in https://github.com/cockroachdb/pebble/pull/1619

**Comment by jbowens** [comment]
We only support 64-bit for now, so I'm going to close this out.
