### ISSUE TITLE
db: add custom profile for open iterators

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1597]
Open iterators pin memtables and sstables. Iterators must not be kept open for a long duration to avoid bloating memory or disk space usage. Go supports [custom pprof profiles](https://rakyll.org/custom-profiles/), which we could leverage here. We would [`pprof.Profile.Add`](https://pkg.go.dev/runtime/pprof#Profile) when an iterator is opened, and [`pprof.Profile.Remove`](https://pkg.go.dev/runtime/pprof#Profile) when an iterator is closed, using the iterator pointer itself as the `value` argument.

Tangentially related to #723, another custom profile issue.

**Comment by nicktrav** [comment]
Building on top of this profiling mechanism, we could also keep track of when iters were created (and where), and provide a means of introspecting "long lived iters".

If we wire that up into Cockroach, I can imagine something like a debug page that prints out all the open iters sorted in descending order of age, along with where they were allocated, and possibly all the other iter stats (bytes scanned, skipped, etc.).

**Comment by nicktrav** [comment]
Linking #1609, cockroachdb/cockroach#68303 and cockroachlabs/support#1403 (internal), as they all would have benefited from the additional observability proposed here.

**Comment by jbowens** [comment]
Linking cockroachdb/cockroach#71481.

**Comment by nicktrav** [comment]
Linking cockroachdb/cockroach#79879.
