### ISSUE TITLE
perf: fractional cascading on seeks

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#16]
RocksDB performs [fractional cascading](https://github.com/facebook/rocksdb/wiki/Indexing-SST-Files-for-Better-Lookup-Performance) on lookups in some restricted circumstances. The reason behind not supporting it everywhere is complexity. We should investigate whether this optimization can be applied to `mergingIter` to reduce the seek time within a level.

**Comment by ajwerner** [comment]
This still seems legit.

**Comment by jbowens** [comment]
I wonder how RocksDB maintains the index for fractional cascading? Each compaction shifts all the relative positions within the level. We've seen anything O(# files in a level) show up as a bottleneck. Updating the relative positions of all files within the touched levels seems prohibitively expensive.

**Comment by petermattis** [comment]
My recollection is that RocksDB rebuilds the affected levels and updates the index for fractional cascading on each compaction. One of the big optimizations for large data sizes you made in Pebble was to avoid such full rebuilds (i.e. the per-level btree). 

It strikes me that a b-epsilon tree gets something like fractional cascading because the metadata is in a single b-tree. I don't see how we could achieve that in Pebble, but thought I'd mention it.

**Comment by sumeerbhola** [comment]
Once we have the very large LSMs for compaction benchmarking, we could do some iteration benchmarks on them to see how much time is actually spent in this binary search.
