### ISSUE TITLE
vfs: WithDiskHealthChecks doesn't time filesystem ops

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1643]
The [`vfs.WithDiskHealthChecks`](https://github.com/cockroachdb/pebble/blob/31def7d7bdf69d56fe373ebc57d68f7838adaaaa/vfs/disk_health.go#L137) function wraps a vfs.FS and watches for disk stalls by timing all write operations. Individual `vfs.File`s are wrapped with a [`diskHealthCheckingFile`](https://github.com/cockroachdb/pebble/blob/31def7d7bdf69d56fe373ebc57d68f7838adaaaa/vfs/disk_health.go#L25). A close reading didn't reveal any gaps in coverage there.

However, the `vfs.FS`'s implementation does not time calls to [`Create`](https://github.com/cockroachdb/pebble/blob/31def7d7bdf69d56fe373ebc57d68f7838adaaaa/vfs/disk_health.go#L149), [`ReuseForWrite`](https://github.com/cockroachdb/pebble/blob/31def7d7bdf69d56fe373ebc57d68f7838adaaaa/vfs/disk_health.go#L165), or wholly unimplemented methods like `Link`, `Remove`, `RemoveAll`, `MkdirAll` or `Lock`. Since all of these filesystem operations may need to write data to disk, they should all be wrapped with timing.

Related to cockroachlabs/support#1520.

**Comment by nicktrav** [comment]
Is this something we should be backporting?

**Comment by jbowens** [comment]
Let's see how clean the vendor bump is. There will be some work to hook up the `io.Closer`.
