### ISSUE TITLE
db: sstable output size during compactions should consider range tombstones

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#167]
See https://github.com/facebook/rocksdb/issues/3977 for the similar issue in RocksDB. The TLDR is the the sstable output size does not truncate range tombstones. This can result in an sstable covering an excessively large number of sstables in the level below, resulting in an excessively large compaction. There is a [comment](https://github.com/petermattis/pebble/blob/master/compaction.go#L994-L995) in the code about this:

		// TODO(peter,rangedel): Need to incorporate the range tombstones in the
		// shouldStopBefore decision.

I'm not clear on exactly how I'd want to incorporate range tombstones in the `shouldStopBefore` decision. See the RocksDB issues for a problematic scenario. It is possible that we need to truncate and split range tombstones to avoid creating sstables which overlap too much in the grandparent level.

**Comment by petermattis** [comment]
See also https://github.com/petermattis/pebble/pull/244#pullrequestreview-278624898.

**Comment by ajkr** [comment]
I was thinking the iterator underlying compaction iterator could present the range tombstone start keys inline with the point keys. When compaction iterator encounters such a key, it would pass the corresponding end key to `shouldStopBefore`. If `shouldStopBefore` returns true, then it stops and cuts the file immediately (i.e., before the start key of the range tombstone whose end key we want to exclude).

Will take a look at what's been done already and whether this is feasible given the current code structure.

**Comment by ajkr** [comment]
`shouldStopBefore` might be due for a remodeling. It recomputes every time we encounter a key how many bytes of grandparent files are now overlapped. But it's not really necessary. We could just compute once at the start of each file where that file's limit should be according to grandparent overlap. The exclusive limit would be the start of the first grandparent file that would cause us to exceed the size limit if we included it. Then, when we pass this limit to `finishOutput()`, it looks like it gets passed along to `Tombstones()`, which automatically truncates our tombstones to that point. Will try this out.

**Comment by ajkr** [comment]
I tried out @petermattis's original suggestion today: `What I think we may want to change is the shouldStopBefore return value. Rather than truncating before the supplied key, I think we want to allow truncation between the previous key that was output for an sstable, and the current key. And that determination will be made using the grandparents level.`

It is pretty close to correct but this edge case is troubling me:

- input level file has point key a, rangedel a-z
- grandparent level indicates cut should happen somewhere between a and z, let's say at m
- the compaction iterator only sees key a twice (one is the sentinel key for the rangedel). Neither one meets `shouldStopBefore`'s criteria so there's no file cutting. Then the full rangedel is output leading to a larger-than-desired future compaction.

**Comment by petermattis** [comment]
> the compaction iterator only sees key a twice (one is the sentinel key for the rangedel). Neither one meets shouldStopBefore's criteria so there's no file cutting. Then the full rangedel is output leading to a larger-than-desired future compaction.

Is the concern that there is no other key being output in the compaction? I think there needs to be a final call into `shouldStopBefore` when we reach the end of the compaction input so that we can place range tombstones into sstables aligned with the grandparent boundary. This actually probably needs to happen in a loop. In your scenario, you could imagine grandparent boundaries at `m`, `q`, `s`, `u`, `x`, etc. I think this actually applies to any separation between sstables.

**Comment by ajkr** [comment]
Yes there is no other key to pass to `shouldStopBefore`. Hm, yeah, we can just make it take the empty key or nil key and in that case simply return the next file limit. Yes, I agree it needs to happen in a loop (not just the `shouldStopBefore` at the end - also there could be multiple file limits between two point keys earlier in the compaction). OK, this is sounding cleaner than I was thinking yesterday.
