### ISSUE TITLE
db: enable dynamic adjustment of block-property filters for range-key masking

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1713]
Currently, range-key masking is implemented exclusively through the `keyspan.InterleavingIter`'s `SkipPoint` hook. Every point key masked by a range-key must be read and surfaced all the way up to the `InterleavingIter` before it's discarded.

In order for MVCC Delete Range to be reasonably performant for wide deletions, we'll need to make use of block-property filters to avoid loading blocks that only contain deleted data. We can do this by adjusting the `RangeKeyMasking` iterator options to allow the caller to specify closures that create/mutate the iterator's point block property filter when provided with a range key that must masks.

**Comment by jbowens** [comment]
This is going to be a little tricky. Today, block property filters are static, and they're unaware of user key bounds. They apply equally across the entirety of the keyspace.

With range-key masking, the block-property filter needs to be applied only for the bounds of the range key. I'm considering two options:

**1. Seeking the point iterator after masking**

The low-level block-property filter (eg, in the `sstable` package) used for range-key masking remains agnostic of bounds. When a Pebble iterator steps onto a range key that must behave as a mask, it adjusts the block property filter to begin answering `Intersects` calls determining that a property intersects only if all the keys' suffixes are ≥ the mask suffix `M`. When the Pebble iterator steps off of the range key `b-d`, the point iterator lands on some key, say `y`. The key `y` may be too far. There may exist key a key `k` with a suffix `<M`, st `d ≤ k < y`. The key `k` was hidden because the block-property filter was active when considering a point key block that extended to or beyond `d`.

When stepping off a masking range-key deletion, the `InterleavingIter` could re-seek the point iterator (`SeekGE(<end>)` when iterating forward or `SeekLT(<start>)` when iterating backward). There are few smaller optimizations we can make:
a. If we surface knowledge of whether the block-property filter excluded any keys, we can avoid the seek if nothing was excluded.
b. We could first try to Prev the point iterator. If we land on a key `<d`, then we can Next and proceed. Otherwise, seek.

**2. Consider user key bounds during filtering**

The block-property filter used for range-key masking and supplied to the sstable package by the pebble package could implement a slightly larger interface, including two new methods:
```
type DynamicBlockPropertyFilter interface {
	BlockPropertyFilter
	IsActive() bool
	IntersectsBounded(lower, upper []byte, props []byte)
}
```
If a dynamic block property filter indicates it `IsActive`, the sstable reader may call `IntersectsBounded`, supplying the lower and upper bounds of the sstable/index block/data block. There might be some awkwardness to support exclusive sstable end-boundaries. I'm unclear on how the opposite bound would be saved, and how we avoid needing to save the bound all the time. Limiting this copy to cases with a masking range key is the intention of the `IsActive` method.

The above seems like it has the potential to get extremely complicated and brittle, so I'm leaning towards the seek option. cc @sumeerbhola

**Comment by nicktrav** [comment]
Side note: knowledge of skipped blocks during iteration seems like something that would be inherently useful for gauging the effectiveness of the block properties - i.e. exposing something like `BlockBytesSkipped` / `BlocksSkipped` in the iter stats?

Sounds like such metric could build on top of / reuse the machinery required for the optimizations mentioned for option 1.

**Comment by jbowens** [comment]
Another option:

**3. Use only one bound**
Only apply the block-property filter once the point iterator is already stepped into the first bound. Then the block-property filter only needs to check the other bound. This does mean that we can never avoid the first block load on a Seek that falls into the masked keyspace.

**Comment by sumeerbhola** [comment]
I think option 3 is very acceptable from a performance perspective -- it is very unlikely that the point block was aligned with the start of the range-key, so there were likely other keys outside the range-key span in that block.

**Comment by jbowens** [comment]
> I think option 3 is very acceptable from a performance perspective -- it is very unlikely that the point block was aligned with the start of the range-key, so there were likely other keys outside the range-key span in that block.

That's a good point. In #1824 I took this approach. However in that implementation, a SeekGE into the middle of a range key still requires that the point iterator first be positioned, requiring an unnecessary block load.

I'm planning on trying to eliminate that block load, but I'm not sure how yet.

**Comment by jbowens** [comment]
^ maybe that's not worthwhile, since lazy-combined iteration means that the first seek into a range key will always load the point-key block first. we'd only benefit on subsequent seeks once the iterator is already configured to use combined iteration.

**Comment by sumeerbhola** [comment]
> However in that implementation, a SeekGE into the middle of a range key still requires that the point iterator first be positioned, requiring an unnecessary block load.

This seems acceptable to me. We can try to optimize this later if it actually turns out to be significant.

**Comment by jbowens** [comment]
I'm wondering if it might become significant because of the way we frequently re-seek the iterator to skip over old versions of a key during a scan...

It would be great if we could keep the existing bpf active if `TrySeekUsingNext=true`, but it seems tricky.

**Comment by sumeerbhola** [comment]
> I'm wondering if it might become significant because of the way we frequently re-seek the iterator to skip over old versions of a key during a scan...

Trying to make sure I understand. So the first time we land on a masked key, we have already loaded the block. It its older versions cross into the next block which is fully masked, and we happen to get to it by stepping, we're good, since then the block property filtering will activate and skip all the subsequent blocks that are masked (regardless of what key it is). It seems the problem is that if we seek before stepping into the next block, and the next `roachpb.Key` is in that next block, we will load it. And this can repeat.
When we do a seek, and we are already at a range key that covers the seek position, we don't really need to clear the mask. We could keep that current mask and then the seek will utilize it correctly (though not SeekLT, since it does a SeekGE on the index, and the upper bound is not externally guaranteed).

**Comment by jbowens** [comment]
> we happen to get to it by stepping, we're good, since then the block property filtering will activate and skip all the subsequent blocks that are masked (regardless of what key it is)

That's true, but (with the current code) a subsequent seek will still seek the iterator back to the block we previously skipped through stepping.

> When we do a seek, and we are already at a range key that covers the seek position, we don't really need to clear the mask. We could keep that current mask and then the seek will utilize it correctly 

Yeah, I think the seek key also needs to be ≥ the existing point key (or `TrySeekUsingNext=true`), because otherwise a seek may reposition the iterator to a block that includes keys beneath the range key's lower bound.

Created #1841 to track.
