### ISSUE TITLE
perf: possible regression in YCSB{D,E,F} benchmarks (05/22)

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1724]
There is a visible step change in read-amp and write-amp in the D, E, and F benchmarks around May 12 / 13.

Read amp:

<img width="568" alt="Screen Shot 2022-05-24 at 11 41 48 AM" src="https://user-images.githubusercontent.com/804457/170109424-d36d937e-ea06-42a1-b6c4-88ef41ba600c.png">

Write amp:

<img width="568" alt="Screen Shot 2022-05-24 at 11 42 10 AM" src="https://user-images.githubusercontent.com/804457/170109462-b559edb7-fe0f-40a2-a64c-2f7a20867995.png">

**Comment by nicktrav** [comment]
There were two changes around that time:
- https://github.com/cockroachdb/pebble/commit/b8c9a560bed578ca2eeb742e0ebda7d5f16c6b47
- https://github.com/cockroachdb/pebble/commit/7c5f0cbb260a9d0238fe3a63359ccbb58d9950b9

The first is a change to `internal/metamorphic`, which leaves the second as the more likely commit producing the difference.

@jbowens - I couldn't see an obvious link between the second commit the reduction in write-amp and a corresponding increase in read-amp.

**Comment by jbowens** [comment]
I'd be surprised if 7c5f0cbb260a9d0238fe3a63359ccbb58d9950b9 is related. I believe the ycsb tests don't configure bounds. Reduced write-amp and increased read-amp suggests compactions are slower or fewer are being scheduled. I took a brief look through the cockroach repo commits in that time period and didn't see any infra-related commits. It's also possible we're seeing the effect of some change to the underlying AWS infra.

It'd be good to try re-run a SHA from before from before the change in w-amp and r-amp to see whether the old w-amp and r-amp are reproducible on current infra and cockroach-repo configuration.

**Comment by nicktrav** [comment]
> It'd be good to try re-run a SHA from before from before the change in w-amp and r-amp to see whether the old w-amp and r-amp are reproducible on current infra and cockroach-repo configuration.

👍 - will give this a whirl and report back.

**Comment by nicktrav** [comment]
Dropping in some notes ...

Here's my method - create roachprod workers with the same configuration as the nightly benchmark:

```bash
$ ./bin/roachprod create travers-test -n 2 --clouds aws --aws-machine-type-ssd c5d.4xlarge
```

Do some minimal setup on each worker to enable building Pebble, then running the benchmark

```bash
# System deps.
sudo apt-get update && sudo apt-get install -y make gcc

# Install Go.
cd /tmp
curl -LO https://go.dev/dl/go1.18.2.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.18.2.linux-amd64.tar.gz
sudo ln -s /usr/local/go/bin/go /usr/local/bin/go

# Install and build Pebble.
cd
git clone https://github.com/cockroachdb/pebble
cd pebble
go build -mod=vendor -o pebble ./cmd/pebble

# Generate test data.
./pebble bench ycsb /mnt/data1/bench \
    --wipe  --workload=read=100 --concurrency=1 --values=1024 \
    --initial-keys=10000000 --cache=4294967296 --num-ops=1 && \
  rm -f /mnt/data1/data.tar && \
  tar cvPf /mnt/data1/data.tar /mnt/data1/bench > init.log 2>&1

# Run Benchmark.
rm -fr /mnt/data1/bench && \
  tar xPf /mnt/data1/data.tar && \
  ./pebble bench ycsb /mnt/data1/bench \
    --workload=D --concurrency=256 --values=1024 --keys=uniform \
    --initial-keys=0 --prepopulated-keys=10000000 --cache=4294967296 \
    --duration=1h30m0s 2>&1 | tee ycsb.log
```

I'm currently comparing two SHAs:

- bb2c1501 - the tip of `master` as of the time of writing
- f8897076 - a SHA from ~May 5, prior to the step change in behavior

I'm only about 30m into the 1h30m run, but I'm already noticing a material difference in the ops/sec values:

```console
# Current master
____optype__elapsed__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
 insert__5    30m0s         2708.3         6231.2     37.7     50.3     54.5     60.8
   read_95    30m0s        51761.2       118397.9      0.7     10.0     13.6     26.2

# f8897076
____optype__elapsed__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
 insert__5   30m20s         2017.1         5752.9     44.0     65.0     71.3     71.3
   read_95   30m20s        38587.5       109285.5      4.7     12.6     16.3     29.4
```

I then went back and compared some previous runs from the TeamCity logs (at around the same time in the benchmark) - note there are 5 workers per nightly run:

```console
# Master - bb2c1501ac23
 insert__5    30m0s         2785.2         5854.0     28.3     39.8     44.0     46.1
   read_95    30m0s        51943.5       111192.4      0.7     11.0     14.7     24.1

 insert__5    30m0s         2572.8         6420.4     35.7     50.3     54.5     56.6
   read_95    30m0s        48489.4       122025.8      3.4     11.0     15.2     33.6

 insert__5    30m0s         2029.8         5979.3     44.0     58.7     60.8     60.8
   read_95    30m0s        38238.9       113615.0      5.0     12.6     16.3     27.3

 insert__5    30m0s         2417.2         5957.3     32.5     44.0     46.1     50.3
   read_95    30m0s        46459.8       113220.5      4.5     12.1     15.2     24.1

 insert__5    30m0s         2781.5         6348.9     32.5     46.1     52.4     54.5
   read_95    30m0s        51210.9       120551.2      0.8     10.5     14.2     22.0

# A run from May 11th - f8897076324b
 insert__5    30m0s         2000.7         5332.5     13.6     17.8     17.8     18.9
   read_95    30m0s        37554.8       101319.4      8.9     17.8     18.9     28.3

 insert__5    30m0s         2221.1         5934.5     21.0     35.7     41.9     46.1
   read_95    30m0s        42136.3       112766.7      6.3     13.6     17.8     31.5

 insert__5    30m0s         1931.3         5248.7     16.8     30.4     33.6     35.7
   read_95    30m0s        34796.0        99756.6      8.4     17.8     18.9     28.3

 insert__5    30m0s         2032.7         5265.7     18.9     30.4     33.6     37.7
   read_95    30m0s        38670.7       100007.8      7.3     15.7     17.8     31.5

 insert__5    30m0s         1873.4         5028.4     13.6     17.8     18.9     21.0
   read_95    30m0s        37392.1        95566.3      8.9     17.8     18.9     27.3
```

While there is some variance, the ops/sec value is ~10k higher on the more recent SHA, but seems to taper off faster, finishing lower than the older SHA.

I'll post again when the current benchmark run is complete, which will contain the read- and write-amp values.

**Comment by nicktrav** [comment]
Benchmarks finished:

```console
# bb2c1501ac23 - current master
____optype__elapsed_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
 insert__5  5400.0s       18247766         3379.2     21.2     22.0     56.6     67.1    302.0
   read_95  5400.0s      346661866        64196.5      2.9      1.0     10.5     15.7    419.4

Benchmarkycsb/D/values=1024 364909632  67575.7 ops/sec  278496905320 read  317610333838 write  10.18 r-amp  16.05 w-amp

__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1    20 M       -    18 G       -       -       -       -    18 G       -       -       -     1.0
      0       282   418 M    1.23    18 G     0 B       0     0 B       0    18 G    12 K     0 B      11     1.0
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3        59   227 M    1.93    21 G     0 B       0     0 B       0    37 G    10 K    37 G       1     1.7
      4       208   1.4 G    1.95    20 G     0 B       0   2.2 G     686    68 G    10 K    68 G       1     3.4
      5       397   5.1 G    1.82    21 G     0 B       0   1.0 G     256    80 G   6.3 K    80 G       1     3.8
      6       770    21 G       -    18 G     0 B       0     0 B       0    75 G   2.9 K    75 G       1     4.1
  total      1716    28 G       -    18 G     0 B       0   3.2 G     942   296 G    42 K   259 G      15    16.0
  flush       298
compact     11102    21 G   471 M       3          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype     10160       0       0     942       0       0  (default, delete, elision, move, read, rewrite)
 memtbl         1    64 M
zmemtbl         0     0 B
   ztbl         2   4.1 M
 bcache     267 K   3.9 G   92.6%  (score == hit-rate)
 tcache     1.7 K   1.1 M  100.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers      1994
 filter         -       -    0.0%  (score == utility)

# f8897076324b
____optype__elapsed_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
 insert__5  5400.0s       15830162         2931.5     21.9     15.7     65.0     79.7   2415.9
   read_95  5400.0s      300678844        55681.0      3.4      1.3     13.1     18.9   2415.9

Benchmarkycsb/D/values=1024 316509006  58612.5 ops/sec  258558172987 read  292451333223 write  9.25 r-amp  17.03 w-amp

__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1    50 M       -    16 G       -       -       -       -    16 G       -       -       -     1.0
      0       105   178 M    1.24    16 G     0 B       0     0 B       0    16 G    10 K     0 B       5     1.0
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3        53   204 M    1.92    19 G     0 B       0   4.0 M       2    34 G   9.4 K    34 G       1     1.8
      4       141   959 M    1.56    18 G     0 B       0   1.8 G     566    61 G   9.5 K    61 G       1     3.4
      5       331   4.3 G    1.56    19 G     0 B       0   1.2 G     275    73 G   5.8 K    73 G       1     3.9
      6       750    20 G       -    17 G     0 B       0     0 B       0    72 G   2.8 K    72 G       1     4.1
  total      1380    26 G       -    16 G     0 B       0   3.0 G     843   272 G    38 K   241 G       9    17.0
  flush       258
compact     10326    14 G   271 M       3          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype      9483       0       0     843       0       0  (default, delete, elision, move, read, rewrite)
 memtbl         1    64 M
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache     266 K   3.9 G   92.2%  (score == hit-rate)
 tcache     1.4 K   916 K  100.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers      1554
 filter         -       -    0.0%  (score == utility)
```

The trend is there - i.e. higher read amp and lower write amp on the more recent SHA - though it's hard to say if that's just within the margin of error.

I did look back through the nightly runs and the behavior change was clear on the night of 5/14, which was the first night we ran with 7c5f0cbb260a9d0238fe3a63359ccbb58d9950b9, after a streak of 7+ days running f8897076324b. That still _could_ be coincidental, but I'm going to re-run either side of those commits with a larger number of workers and see what comes back. Hoping that a larger sample size can give us some more confidence.

**Comment by nicktrav** [comment]
Still no discernible difference between the two runs - both had results similar to the more recent runs.

I put the results for the two different runs here:
- f8897076324b4880f14305000506972434d1fe73 - https://gist.github.com/nicktrav/578b07e0acebec478e0f17febd7d53ef
- 7c5f0cbb260a9d0238fe3a63359ccbb58d9950b9 - https://gist.github.com/nicktrav/dcd6ec0015a0556f7de00d3da90fb3d5

You'll notice the r-amp and w-amp values around around 9.5 and 16.5, respectively (from a _very_ crude eyeball average), for both sets of results.

This would indeed seem to implicate something external to Pebble. Finding out what this is will be tough.

I also took a closer look at some of the profiling data on either side of the behavior change, and I noticed that we are allocating a _lot_ more memory now, from 5/14 onwards

Here are some sets of profiles. I'm looking at "allocated space". You'll notice before 5/14, the allocated space from the benchmark itself (from the iterator instantiation) was around 300-350GB. After 5/14, we're sometimes allocating nearly double that, in the 700GB+ range, with a lot more variance.

5/12 (before)
- https://share.polarsignals.com/1804cf8/
- https://share.polarsignals.com/1cf6722/
- https://share.polarsignals.com/81fcfdf/
- https://share.polarsignals.com/9600e3b/
- https://share.polarsignals.com/2078385/

5/13 (before)
- https://share.polarsignals.com/c1c12f2/
- https://share.polarsignals.com/3b22274/
- https://share.polarsignals.com/bdbd1d6/
- https://share.polarsignals.com/cc1ae8d/
- https://share.polarsignals.com/ec46e6f/

5/14 (after)
- https://share.polarsignals.com/c54d036/
- https://share.polarsignals.com/3ce4004/
- https://share.polarsignals.com/d370c67/
- https://share.polarsignals.com/732b1d9/
- https://share.polarsignals.com/b72bb35/

5/25 (after)
- https://share.polarsignals.com/2690729/
- https://share.polarsignals.com/8578889/
- https://share.polarsignals.com/275e701/
- https://share.polarsignals.com/27dd781/
- https://share.polarsignals.com/3c184ac/

And for the two runs I did today - which show similar behavior to the post-5/14 behavior:

f8897076324b4880f14305000506972434d1fe73
- https://share.polarsignals.com/a3798ef/
- https://share.polarsignals.com/50f6fc1/
- https://share.polarsignals.com/23c727e/
- https://share.polarsignals.com/1c2d643/
- https://share.polarsignals.com/dc176ea/

7c5f0cbb260a9d0238fe3a63359ccbb58d9950b9
- https://share.polarsignals.com/e0f75a0/
- https://share.polarsignals.com/a6987c3/
- https://share.polarsignals.com/fbb7f79/
- https://share.polarsignals.com/78902f0/
- https://share.polarsignals.com/5b7703d/

**Comment by nicktrav** [comment]
I ran the benchmark again once more, but this time I used both AWS and GCP.

On the same cloud platform, there isn't much variance between the the results - when aggregating all pprof profiles from all of the 5 machines in each run. This backs up the hypothesis that this is caused by something external to Pebble.

CPU - AWS - before

![Screenshot from 2022-06-01 15-20-57](https://user-images.githubusercontent.com/804457/171511593-9304bcdf-3e44-4327-88e4-93980651318d.png)

CPU - AWS - after

![Screenshot from 2022-06-01 15-21-02](https://user-images.githubusercontent.com/804457/171511612-ddb7eb32-7c35-484d-aa5b-ea0d6d3cee3b.png)

CPU - GCP - before

![Screenshot from 2022-06-01 15-21-07](https://user-images.githubusercontent.com/804457/171511626-24713bdf-6fa9-4f61-879f-e399c5de2e36.png)

CPU - GCP - after

![Screenshot from 2022-06-01 15-21-12](https://user-images.githubusercontent.com/804457/171511653-c0904dcf-2320-4abf-9503-1caf5451dbf5.png)

RAM:

```console
# AWS - before
Flat	Flat%	Sum%	Cum	Cum%	Name	Inlined?
2954.60GB	91.28%	91.28%	2982.80GB	92.15%	github.com/cockroachdb/pebble.constructPointIter	

# AWS - after
Flat	Flat%	Sum%	Cum	Cum%	Name	Inlined?
3862701.95MB	92.71%	92.71%	3892822.48MB	93.44%	github.com/cockroachdb/pebble.constructPointIter	

# GCP - before
Flat	Flat%	Sum%	Cum	Cum%	Name	Inlined?
1363.25GB	73.58%	73.58%	1425.35GB	76.93%	github.com/cockroachdb/pebble.constructPointIter	

# GCP - after
Flat	Flat%	Sum%	Cum	Cum%	Name	Inlined?
1319141.21MB	72.93%	72.93%	1381110.19MB	76.36%	github.com/cockroachdb/pebble.constructPointIter	
```

Curiously, the results on GCP are _far_ better than the results on AWS (over a 2x improvement). I created clusters with the following:

```shell
# AWS
$ ./bin/roachprod create travers-before -n 5 --clouds aws --aws-machine-type-ssd c5d.4xlarge 

# GCP
$ ./bin/roachprod create travers-before-gcp -n 5 --clouds gce --gce-machine-type n1-standard-16 --gce-local-ssd-count 1
```

Here are the overall results comparing the two clouds:

```console
# AWS - before
Benchmarkycsb/D/values=1024 313112070  57983.7 ops/sec  251431627065 read  284938100845 write  9.15 r-amp  16.78 w-amp
Benchmarkycsb/D/values=1024 382818942  70892.3 ops/sec  307793466901 read  348784797458 write  9.16 r-amp  16.80 w-amp
Benchmarkycsb/D/values=1024 310703907  57537.7 ops/sec  256954140942 read  290196399867 write  8.89 r-amp  17.23 w-amp
Benchmarkycsb/D/values=1024 325894477  60350.8 ops/sec  273946084567 read  308859711371 write  8.61 r-amp  17.47 w-amp
Benchmarkycsb/D/values=1024 356703956  66056.2 ops/sec  272114011052 read  310324381077 write  10.27 r-amp  16.04 w-amp

# AWS - after
Benchmarkycsb/D/values=1024 380754032  70509.8 ops/sec  298353345497 read  339094717016 write  9.61 r-amp  16.42 w-amp
Benchmarkycsb/D/values=1024 309896153  57388.1 ops/sec  253380109151 read  286514513095 write  9.29 r-amp  17.05 w-amp
Benchmarkycsb/D/values=1024 316729834  58653.6 ops/sec  262672793771 read  296578035490 write  8.75 r-amp  17.26 w-amp
Benchmarkycsb/D/values=1024 364329534  67468.4 ops/sec  282935389689 read  321943684694 write  9.70 r-amp  16.30 w-amp
Benchmarkycsb/D/values=1024 375309108  69501.5 ops/sec  290688848279 read  330885802157 write  9.88 r-amp  16.25 w-amp

# GCP - before
Benchmarkycsb/D/values=1024 812548595  150471.7 ops/sec  748960017299 read  836072738290 write  6.58 r-amp  18.97 w-amp
Benchmarkycsb/D/values=1024 832450729  154157.0 ops/sec  771638602772 read  860865148944 write  6.68 r-amp  19.07 w-amp
Benchmarkycsb/D/values=1024 842717218  156058.6 ops/sec  781434162261 read  871747896500 write  6.66 r-amp  19.07 w-amp
Benchmarkycsb/D/values=1024 830800625  153851.4 ops/sec  769694443640 read  858778650096 write  6.65 r-amp  19.06 w-amp
Benchmarkycsb/D/values=1024 847324666  156911.8 ops/sec  786098897119 read  876907370148 write  6.69 r-amp  19.08 w-amp

# GCP - after
Benchmarkycsb/D/values=1024 821306114  152093.3 ops/sec  757855058203 read  845905380547 write  6.66 r-amp  18.99 w-amp
Benchmarkycsb/D/values=1024 799233802  148005.9 ops/sec  736017922336 read  821697032563 write  6.67 r-amp  18.96 w-amp
Benchmarkycsb/D/values=1024 830452293  153787.3 ops/sec  767550682974 read  856533118002 write  6.63 r-amp  19.02 w-amp
Benchmarkycsb/D/values=1024 829084490  153534.1 ops/sec  766607012642 read  855460646380 write  6.69 r-amp  19.02 w-amp
Benchmarkycsb/D/values=1024 804688175  149016.1 ops/sec  739466245775 read  825690001854 write  6.62 r-amp  18.92 w-amp
```

And to the previous comment, it is interesting to see that on GCP we spend about 85% less time in `runtime.makeslice` when doing a `(*DB).NewIter`:

AWS - 731s in `runtime.makeslice`

![Screenshot from 2022-06-01 15-57-37](https://user-images.githubusercontent.com/804457/171515112-9445c524-d604-4344-9688-33338113b19b.png)

GCP - 114.57s in `runtime.makeslice`

![Screenshot from 2022-06-01 15-57-41](https://user-images.githubusercontent.com/804457/171515135-fc6f6c23-5227-4473-9854-ace383f5388e.png)

I put all the profiles and logs [here](https://drive.google.com/drive/folders/1eEY_O7sDc7ILqCtwQE_QWboK-oXhD7QN?usp=sharing).

**Comment by nicktrav** [comment]
In keeping with the aforementioned timeboxing of this, I'm going to close this out.
