### ISSUE TITLE
db: hold commit pipeline mutex when closing DB

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1728]
*This was the result of some conversation on on #1719.*

The commit pipeline mutex is used as an external synchronization mechanism for log writes. If an operation (set, delete, etc.) is performed on the DB after the DB has been closed, the operation can cause a data race in the log writer. This was observed in cockroachdb/cockroach#81511, following a change that allowed concurrent operations post-close (see the original change in cockroachdb/cockroach#81133).

The data race is most likely caused by the omission of a commit-pipeline lock in `DB.Close`. Closing the WAL writer is required to hold the commit pipeline mutex normally (eg, `makeRoomForWrite` always holds `d.commit.mu`).

We could also consider adjusting `DB.Close` to make concurrent operations a little easier to catch. For example, changing the first line of `Close()` to swap `d.closed`'s value to `ErrClosed`, increasing the chances a concurrent operation observes the `ErrClosed`.

While the data race has since been fixed above Pebble (see cockroachdb/cockroach#81813), and despite the fact that calling a method on the DB post-close is undefined, we should fix the issue in Pebble.

**Comment by nicktrav** [comment]
The following is a reliable reproducer:

```go
package pebble

import (
	"sync"
	"testing"

	"github.com/cockroachdb/pebble/vfs"
	"github.com/stretchr/testify/require"
)

func Test(t *testing.T) {
	db, err := Open("", &Options{
		FS: vfs.NewMem(),
	})
	require.NoError(t, err)

	// Two goroutines racing each other. One attempts to Set a record into the
	// DB, the other attempts to close the DB.
	var wg sync.WaitGroup

	wg.Add(1)
	go func() {
		defer func() {
			if r := recover(); r != nil {
				t.Logf("WARN: saw panic on record write: %s", r)
			}
			wg.Done()
		}()

		t.Logf("writing record ...")
		err := db.Set([]byte("foo"), nil, nil)
		if err != nil {
			t.Logf("WARN: saw error on record write: %s", err)
		}
	}()

	wg.Add(1)
	go func() {
		defer wg.Done()
		t.Logf("closing db ...")
		err := db.Close()
		require.NoError(t, err)
	}()

	wg.Wait()
	t.Logf("done")
}
```

```bash
$ go test -run '^Test$' -race -count 1 .
```

<details>
<summary>Output</summary>

```console
==================
WARNING: DATA RACE
Read at 0x00c0002ae000 by goroutine 27:
  github.com/cockroachdb/pebble/record.(*LogWriter).emitEOFTrailer()
      /Users/nickt/Development/pebble/record/log_writer.go:678 +0x4b
  github.com/cockroachdb/pebble/record.(*LogWriter).Close()
      /Users/nickt/Development/pebble/record/log_writer.go:589 +0x32
  github.com/cockroachdb/pebble.(*DB).Close()
      /Users/nickt/Development/pebble/db.go:1203 +0x64e
  github.com/cockroachdb/pebble.Test.func2()
      /Users/nickt/Development/pebble/test_test.go:41 +0xc8

Previous write at 0x00c0002ae000 by goroutine 26:
  sync/atomic.StoreInt32()
      /nix/store/0bh8m4vqb7c7n4sn73ka53yn45yj3zd0-go-1.18.2/share/go/src/runtime/race_amd64.s:229 +0xb
  sync/atomic.StoreInt32()
      <autogenerated>:1 +0x1a
  github.com/cockroachdb/pebble/record.(*LogWriter).SyncRecord()
      /Users/nickt/Development/pebble/record/log_writer.go:646 +0xe4
  github.com/cockroachdb/pebble.(*DB).commitWrite()
      /Users/nickt/Development/pebble/db.go:851 +0x51a
  github.com/cockroachdb/pebble.(*DB).commitWrite-fm()
      <autogenerated>:1 +0x64
  github.com/cockroachdb/pebble.(*commitPipeline).prepare()
      /Users/nickt/Development/pebble/commit.go:379 +0x2db
  github.com/cockroachdb/pebble.(*commitPipeline).Commit()
      /Users/nickt/Development/pebble/commit.go:253 +0xb7
  github.com/cockroachdb/pebble.(*DB).Apply()
      /Users/nickt/Development/pebble/db.go:757 +0x465
  github.com/cockroachdb/pebble.(*DB).Set()
      /Users/nickt/Development/pebble/db.go:575 +0x108
  github.com/cockroachdb/pebble.Test.func1()
      /Users/nickt/Development/pebble/test_test.go:31 +0x10c

Goroutine 27 (running) created at:
  github.com/cockroachdb/pebble.Test()
      /Users/nickt/Development/pebble/test_test.go:38 +0x4ee
  testing.tRunner()
      /nix/store/0bh8m4vqb7c7n4sn73ka53yn45yj3zd0-go-1.18.2/share/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /nix/store/0bh8m4vqb7c7n4sn73ka53yn45yj3zd0-go-1.18.2/share/go/src/testing/testing.go:1486 +0x47

Goroutine 26 (finished) created at:
  github.com/cockroachdb/pebble.Test()
      /Users/nickt/Development/pebble/test_test.go:22 +0x3f2
  testing.tRunner()
      /nix/store/0bh8m4vqb7c7n4sn73ka53yn45yj3zd0-go-1.18.2/share/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /nix/store/0bh8m4vqb7c7n4sn73ka53yn45yj3zd0-go-1.18.2/share/go/src/testing/testing.go:1486 +0x47
==================
--- FAIL: Test (0.00s)
    test_test.go:30: writing record ...
    test_test.go:40: closing db ...
    test_test.go:46: done
    testing.go:1312: race detected during execution of test
FAIL
FAIL    github.com/cockroachdb/pebble   0.867s
FAIL
```
</details>

**Comment by petermattis** [comment]
> The data race is most likely caused by the omission of a commit-pipeline lock in DB.Close. Closing the WAL writer is required to hold the commit pipeline mutex normally (eg, makeRoomForWrite always holds d.commit.mu).

It is fundamentally racy to perform a `Set` on a DB that is concurrently being `Closed`. The `DB.closed` atomic var is intended to help detect this. What we're seeing here is a gap in that detection. `DB.Close` acquires `DB.mu`, but `DB.Set` does not need to do so unless the memtable is being flushed. Acquiring `DB.commit.mu` in before closing the WAL in `DB.Close` should significantly grow the detection window.

Be aware that grabbing `DB.commit.mu` before closing the WAL in `DB.Close` is slightly tricky because `DB.commit.mu` must be acquired before `DB.mu`. Heck, it is probably fine to just grab `DB.commit.mu` at the start of `DB.Close` because nothing else should be running concurrently.
