### ISSUE TITLE
metamorphic: hook up multi-level compactions to the metamoprhic tests

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1745]
Multi-level compactions are being considered for addition in #1603 🎉. We'll likely split out the scheduling of these compactions into a separate patch, as it will require some tuning, experimenting and benchmarking to get right.

In the interim, to give us confidence that it's working as expected, we should update the metamorphic test suite to ensure these compactions can be scheduled, most likely in a dedicated variant of the test suite (i.e. `standard-xyz` runs with a bit flipped that can schedule the compactions).

**Comment by itsbilal** [comment]
Cc @msbutler - this should be pretty easy to hook up once enough heuristics are merged to allow triggering multi level compactions via the option flag.
