### ISSUE TITLE
High newMemTable memory usage when CGO_ENABLED=0

### ISSUE THREAD

**Issue by JustinAzoff** [cockroachdb/pebble#1754]
Hi!

I'm seeing some weirdness around heap usage when CGO_ENABLED is 0.  I noticed it when writing multiple databases concurrently, which I think exacerbates the issue.  Ultimately I can use CGO, so it's possibly not a huge problem.  My use case is writing time partitioned databases across multiple disks in a JBOD, so one process ends up with a lot of open databases.

Using the program inlined at the end, I observe the following:

```
CGO_ENABLED=1 go build && ./pebble-memory-test 

# Have the server batch load 200,000 items into 20 DB's
for x in $(seq 20);do
    curl -s "localhost:6060/?q="{01..20} > /dev/null
    echo top20|go tool pprof http://localhost:6060/debug/pprof/heap 2>/dev/null |grep total$
done
```

Outputs:

```
(pprof) Showing nodes accounting for 136.81MB, 99.64% of 137.31MB total
(pprof) Showing nodes accounting for 347.02MB, 98.95% of 350.71MB total
(pprof) Showing nodes accounting for 429.90MB, 98.69% of 435.62MB total
(pprof) Showing nodes accounting for 622.64MB, 99.01% of 628.88MB total
(pprof) Showing nodes accounting for 516.83MB, 98.81% of 523.08MB total
(pprof) Showing nodes accounting for 612.38MB, 98.72% of 620.32MB total
(pprof) Showing nodes accounting for 445.04MB, 98.61% of 451.30MB total
(pprof) Showing nodes accounting for 577.16MB, 98.93% of 583.38MB total
(pprof) Showing nodes accounting for 239.32MB, 99.10% of 241.50MB total
(pprof) Showing nodes accounting for 226.45MB, 98.83% of 229.13MB total
(pprof) Showing nodes accounting for 229.53MB, 99.33% of 231.07MB total
(pprof) Showing nodes accounting for 227.97MB, 99.33% of 229.51MB total
(pprof) Showing nodes accounting for 230.31MB, 98.85% of 232.99MB total
(pprof) Showing nodes accounting for 229.28MB, 98.84% of 231.96MB total
(pprof) Showing nodes accounting for 230.32MB, 98.85% of 233MB total
(pprof) Showing nodes accounting for 228.77MB, 99.06% of 230.95MB total
(pprof) Showing nodes accounting for 228.77MB, 99.33% of 230.31MB total
(pprof) Showing nodes accounting for 229.29MB, 99.06% of 231.47MB total
(pprof) Showing nodes accounting for 229.51MB, 99.11% of 231.59MB total
(pprof) Showing nodes accounting for 231.85MB, 99.34% of 233.39MB total
```

However, if it's ran with CGO_ENABLED=0, the output is this:
```
(pprof) Showing nodes accounting for 142.89MB, 98.96% of 144.40MB total
(pprof) Showing nodes accounting for 346.93MB, 98.82% of 351.08MB total
(pprof) Showing nodes accounting for 439.20MB, 98.51% of 445.86MB total
(pprof) Showing nodes accounting for 592.02MB, 98.99% of 598.05MB total
(pprof) Showing nodes accounting for 595.04MB, 98.82% of 602.13MB total
(pprof) Showing nodes accounting for 803.56MB, 99.06% of 811.16MB total
(pprof) Showing nodes accounting for 1218.29MB, 99.62% of 1222.94MB total
(pprof) Showing nodes accounting for 1218.29MB, 99.62% of 1222.94MB total
(pprof) Showing nodes accounting for 1513.73MB, 99.53% of 1520.92MB total
(pprof) Showing nodes accounting for 1513.73MB, 99.53% of 1520.92MB total
(pprof) Showing nodes accounting for 1503.16MB, 99.67% of 1508.19MB total
(pprof) Showing nodes accounting for 1505.73MB, 99.56% of 1512.44MB total
(pprof) Showing nodes accounting for 1505.73MB, 99.56% of 1512.44MB total
(pprof) Showing nodes accounting for 1541.73MB, 99.67% of 1546.77MB total
(pprof) Showing nodes accounting for 1544.79MB, 99.64% of 1550.31MB total
(pprof) Showing nodes accounting for 1504.92MB, 99.57% of 1511.50MB total
(pprof) Showing nodes accounting for 1544.79MB, 99.64% of 1550.36MB total
(pprof) Showing nodes accounting for 1544.79MB, 99.64% of 1550.33MB total
(pprof) Showing nodes accounting for 1544.79MB, 99.68% of 1549.81MB total
(pprof) Showing nodes accounting for 1504.68MB, 99.63% of 1510.24MB total
```

The full profile in cumulative mode is:

```
Dropped 25 nodes (cum <= 7.55MB)
      flat  flat%   sum%        cum   cum%
       1MB 0.066% 0.066%  1506.74MB 99.77%  main.(*Server).Load
         0     0% 0.066%  1506.74MB 99.77%  net/http.(*ServeMux).ServeHTTP
         0     0% 0.066%  1506.74MB 99.77%  net/http.(*conn).serve
         0     0% 0.066%  1506.74MB 99.77%  net/http.HandlerFunc.ServeHTTP
         0     0% 0.066%  1506.74MB 99.77%  net/http.serverHandler.ServeHTTP
         0     0% 0.066%  1342.79MB 88.91%  github.com/cockroachdb/pebble.(*Batch).Commit (inline)
         0     0% 0.066%  1342.79MB 88.91%  github.com/cockroachdb/pebble.(*DB).Apply
         0     0% 0.066%  1281.56MB 84.86%  github.com/cockroachdb/pebble.(*DB).commitWrite
         0     0% 0.066%  1281.56MB 84.86%  github.com/cockroachdb/pebble.(*DB).makeRoomForWrite
         0     0% 0.066%  1281.56MB 84.86%  github.com/cockroachdb/pebble.(*commitPipeline).Commit
         0     0% 0.066%  1281.56MB 84.86%  github.com/cockroachdb/pebble.(*commitPipeline).prepare
 1280.50MB 84.79% 84.85%  1280.50MB 84.79%  github.com/cockroachdb/pebble/internal/manual.New (inline)
         0     0% 84.85%     1280MB 84.75%  github.com/cockroachdb/pebble.(*DB).newMemTable
         0     0% 84.85%   161.95MB 10.72%  github.com/cockroachdb/pebble.(*Batch).Merge
         0     0% 84.85%   161.95MB 10.72%  github.com/cockroachdb/pebble.(*Batch).MergeDeferred (inline)
  161.95MB 10.72% 95.58%   161.95MB 10.72%  github.com/cockroachdb/pebble.(*Batch).grow
         0     0% 95.58%   161.95MB 10.72%  github.com/cockroachdb/pebble.(*Batch).prepareDeferredKeyValueRecord
   61.23MB  4.05% 99.63%    61.23MB  4.05%  github.com/cockroachdb/pebble.newFlushableBatch
```

```
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	_ "net/http/pprof"
	"strings"
	"time"

	"github.com/cockroachdb/pebble"
)

type Server struct {
	dbs map[string]*pebble.DB
}

func (s *Server) Open(fn string) (*pebble.DB, error) {
	db, ok := s.dbs[fn]
	if ok {
		return db, nil
	}

	log.Printf("Opening new db %s", fn)
	db, err := pebble.Open(fn, &pebble.Options{
		BytesPerSync: 64 * 1024 * 1024,
		MemTableSize: 32 * 1024 * 1024,
	})
	if err != nil {
		return nil, err
	}
	s.dbs[fn] = db
	return db, nil
}

func (s *Server) OpenAll() error {
	files, err := ioutil.ReadDir(".")
	if err != nil {
		return err
	}

	for _, f := range files {
		if strings.HasSuffix(f.Name(), ".db") {
			_, err := s.Open(f.Name())
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (s *Server) Load(w http.ResponseWriter, r *http.Request) {
	q := r.FormValue("q")
	if q == "" {
		q = "01"
	}
	fn := fmt.Sprintf("%s.db", q)
	db, err := s.Open(fn)
	if err != nil {
		log.Fatal(err)
	}

	count := 200_000

	batch := db.NewBatch()

	ts := time.Now().Unix()

	for i := 0; i < count; i++ {
		k := []byte(fmt.Sprintf("%v-%d", ts, i))
		v := []byte(fmt.Sprintf("%d ", i))
		//log.Printf("Setting %s to %s", k, v)
		err := batch.Merge(k, v, nil)
		if err != nil {
			log.Fatal(err)
		}
	}

	err = batch.Commit(nil)
	if err != nil {
		log.Fatal(err)
	}
	if err := db.Set([]byte(fmt.Sprintf("%v.indexed", ts)), []byte("1"), nil); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Loaded %d records into %s\n", count, fn)
	fmt.Fprintf(w, "Loaded %d records into %s\n", count, fn)
}

func main() {
	s := &Server{
		dbs: make(map[string]*pebble.DB),
	}

	err := s.OpenAll()
	if err != nil {
		log.Fatal(err)
	}

	http.HandleFunc("/", s.Load)
	log.Printf("Listening...")
	log.Println(http.ListenAndServe("localhost:6060", nil))
}
```

**Comment by protosam** [comment]
This might be a major factor in what's going on. When I lower this, Go doesn't try to obliterate my available RAM. 
```
	db, err := pebble.Open(fn, &pebble.Options{
		BytesPerSync: 64 * 1024 * 1024,
		MemTableSize: 32 * 1024 * 1024,
	})
```

Have you tried calling `db.Flush()` or `db.AsyncFlush()` after the batch commit is actually done?

**Comment by protosam** [comment]
When I tried this with CGO_ENABLED=0, I'm pretty sure the work completed a lot faster.

For some perspective on why it's so high, you're concurrently making opening 20 databases with a MemTableSize of 32MB. The math is 32MB * 20 = roughly 640MB, I would be more concerned if it were much higher than that.

With CGO enabled I suspect something to do with the runtime hack is being handled more conveniently. There's a lot of archaic things from Go's past and CGO.

**Comment by JustinAzoff** [comment]
> The math is 32MB * 20 = roughly 640MB, I would be more concerned if it were much higher than that.

Yeah, that's where I was confused, since it ends up using 2147.89MB

Could something be holding onto a reference to the arenaBuf?

DB.newMemTable does

```
    mem := newMemTable(memTableOptions{
        Options:   d.opts,
        arenaBuf:  manual.New(int(size)),
        logSeqNum: logSeqNum,
    })
```

and in there this happens

```
    arena := arenaskl.NewArena(m.arenaBuf)
    m.skl.Reset(arena, m.cmp)
    m.rangeDelSkl.Reset(arena, m.cmp)
    m.rangeKeySkl.Reset(arena, m.cmp)
```

where NewArena does

```
// NewArena allocates a new arena using the specified buffer as the backing
// store.
func NewArena(buf []byte) *Arena {
    // Don't store data at position 0 in order to reserve offset=0 as a kind
    // of nil pointer.
    return &Arena{
        n:   1,
        buf: buf,
    }
}
```

This attempts to un reference the arenabuf on the mem table:

```
entry.releaseMemAccounting = func() {
        manual.Free(mem.arenaBuf)
        mem.arenaBuf = nil
        ...
```

which works for sure for the cgo version, since Free calls `C.free` first, but the nocgo version relies on the reference count.. but if something in the skl stuff still has a reference somewhere it will never get freed.

**Comment by protosam** [comment]
Something else also comes to mind. Pebble had to do something that's a bit hacky because how the GC works: https://github.com/cockroachdb/pebble/blob/master/docs/memory.md

It's not pretty, but I think it's fine. When I was tinkering with this I couldn't get it to become a runaway process. The memory usage held a trend every time and I observed that the upper extremes freed. 

If one was so inclined, some testing could be done to see if Go would give back the memory to paging on Linux or something; but I don't have the cycles for that myself.

**Comment by JustinAzoff** [comment]
I've done some more testing, and yeah, I think some of this just might be GC stuff.  I'm not 100% sure but the way the memtables double up to the final size may also contribute to heap size being a bit higher than just len(databases) * MemTableSize.

One thing I didn't realize before that caused a lot of confusion on my part is that memory allocated via the cgo allocation is completely invisible to pprof.  The heap usage for cgo isn't massively better than without, it's just that pprof doesn't account for any of that memory.

The thing I might dig into is if there could be a way to tell pebble that a database is basically 'finalized'. Once the day rolls over from 2022-06-14 to 2022-06-15 I stop writing to the previous db and any memTables that might still be allocated are never going to be used again...

For now I can just close+reopen the older dbs.  Doing that in my test server drops the usage all the way down to 8MB.  Opening them with ReadOnly=true drops it even further.

Sharing a single *Cache between all instances might also help too, I think that would work but might not have been intended :-)

**Comment by JustinAzoff** [comment]
@petermattis hi! yeah, that all tracks with what I figured out last night. I guess the only bug, if you could even call it that, is that there isn't an exposed API to say "Hey, I'm done writing to this db for now, so any memtables that may have been allocated won't be needed moving forward". 

Possible that Flush() should do this, but I'm not sure.  Closing and re-opening the DB works for now.

**Comment by JustinAzoff** [comment]
Just to add a little more details about how much reopening helps, I added a /reopen endpoint to my little test server, and changed the driver script to be

```
for db in {01..20}; do
    for x in {01..20};do 
        curl -s "localhost:6060/?q=${db}" > /dev/null
    done
    curl -s "localhost:6060/reopen?q=${db}" > /dev/null
    echo top20|go tool pprof http://localhost:6060/debug/pprof/heap 2>/dev/null |grep total$
done
```

with the 32MB memtable size and without the /reopen request, this is the memory usage:

```
(pprof) Showing nodes accounting for 152.63MB, 98.69% of 154.65MB total
(pprof) Showing nodes accounting for 366.75MB, 99.32% of 369.27MB total
(pprof) Showing nodes accounting for 473.81MB, 99.47% of 476.34MB total
(pprof) Showing nodes accounting for 546.37MB, 98.88% of 552.57MB total
(pprof) Showing nodes accounting for 792.99MB, 99.37% of 798.02MB total
(pprof) Showing nodes accounting for 725.93MB, 99.09% of 732.61MB total
(pprof) Showing nodes accounting for 812.05MB, 99.00% of 820.28MB total
(pprof) Showing nodes accounting for 943.62MB, 99.14% of 951.83MB total
(pprof) Showing nodes accounting for 1137.10MB, 99.28% of 1145.31MB total
(pprof) Showing nodes accounting for 1050.68MB, 99.24% of 1058.75MB total
(pprof) Showing nodes accounting for 1221.31MB, 99.22% of 1230.91MB total
(pprof) Showing nodes accounting for 1329.31MB, 99.36% of 1337.89MB total
(pprof) Showing nodes accounting for 1543.43MB, 99.45% of 1552.01MB total
(pprof) Showing nodes accounting for 1618.49MB, 99.38% of 1628.58MB total
(pprof) Showing nodes accounting for 1713.15MB, 99.18% of 1727.28MB total
(pprof) Showing nodes accounting for 1939.68MB, 99.51% of 1949.26MB total
(pprof) Showing nodes accounting for 1982.74MB, 99.52% of 1992.35MB total
(pprof) Showing nodes accounting for 2186.31MB, 99.56% of 2195.88MB total
(pprof) Showing nodes accounting for 2224.34MB, 99.55% of 2234.43MB total
(pprof) Showing nodes accounting for 2222.31MB, 99.57% of 2231.90MB total
```

but with the new call to reopen the previous DB after each batch, this is the result:

```
(pprof) Showing nodes accounting for 109.20MB, 98.20% of 111.20MB total
(pprof) Showing nodes accounting for 109.20MB, 99.09% of 110.20MB total
(pprof) Showing nodes accounting for 109.20MB, 99.09% of 110.20MB total
(pprof) Showing nodes accounting for 3212.56kB, 100% of 3212.56kB total
(pprof) Showing nodes accounting for 109.20MB, 98.20% of 111.20MB total
(pprof) Showing nodes accounting for 185.26MB, 99.19% of 186.78MB total
(pprof) Showing nodes accounting for 110.83MB, 98.65% of 112.35MB total
(pprof) Showing nodes accounting for 110.83MB, 98.65% of 112.35MB total
(pprof) Showing nodes accounting for 110.83MB, 98.21% of 112.86MB total
(pprof) Showing nodes accounting for 111.87MB, 98.68% of 113.37MB total
(pprof) Showing nodes accounting for 113.51MB, 98.27% of 115.51MB total
(pprof) Showing nodes accounting for 7627.76kB, 100% of 7627.76kB total
(pprof) Showing nodes accounting for 113.01MB, 98.24% of 115.03MB total
(pprof) Showing nodes accounting for 8278.38kB, 100% of 8278.38kB total
(pprof) Showing nodes accounting for 113.65MB, 98.26% of 115.66MB total
(pprof) Showing nodes accounting for 114.28MB, 98.27% of 116.29MB total
(pprof) Showing nodes accounting for 9451.07kB, 100% of 9451.07kB total
(pprof) Showing nodes accounting for 190.88MB, 99.22% of 192.38MB total
(pprof) Showing nodes accounting for 115.30MB, 98.72% of 116.80MB total
(pprof) Showing nodes accounting for 10485.48kB, 100% of 10485.48kB total
```

**Comment by petermattis** [comment]
> @petermattis hi! yeah, that all tracks with what I figured out last night. I guess the only bug, if you could even call it that, is that there isn't an exposed API to say "Hey, I'm done writing to this db for now, so any memtables that may have been allocated won't be needed moving forward".
>
> Possible that Flush() should do this, but I'm not sure. Closing and re-opening the DB works for now.

I'm mildly surprised that closing and re-opening the DB helps. Closing the DB does not cause the memtable to be flushed to disk. Instead, closing the DB drops the memtable, and re-opening the DB rebuilds the memtable from the WAL. The effect you might be seeing here is that the memtables start small when a DB is first opened, and each new memtable doubles in size up to the configured limit. `DB.Flush` is the mechanism for forcing the memtable to disk, though a new memtable will be allocated so you're not actually saving any memory.

**Comment by JustinAzoff** [comment]
> The effect you might be seeing here is that the memtables start small when a DB is first opened, and each new memtable doubles in size up to the configured limit.

Yeah, that's exactly it.  Closing and reopening the DB drops the memtable size from the upper limit to the initial 256k, and I think zero if it's opened ReadOnly ( no memtable at all? ).

Since I'm writing time partitioned databases like `2022-06-20.db` I know exactly when things rotate over and can easily Close+reOpen the previous day.  Having a FlushMemtable method or something like that would just make it even easier.  The only tricky part with Close+reOpen is ensuring any concurrent access isn't actively trying to use the *DB as it is being reopened.

**Comment by nicktrav** [comment]
Thanks for your report here @JustinAzoff. I'm wondering, given the responses from Peter, are there any specific requests or questions you have outstanding?

The conclusion seems to be "behaves as expected", though we want to make sure we've capturing everything. If you're satisfied, we can close this out.

**Comment by nicktrav** [comment]
> I'm not sure if there are even many users like me that have the potential for a large number of concurrently open dbs

In the Cockroach case, which I'd be confident in assuming makes up the majority of Pebble instances in the wild, the number of concurrently open Pebble DBs is primarily a function of a Cockroach node's "stores". The highest I've seen being something like 8-12, and this was a function of the block devices (one store per mounted device). Given the fixed cost of a Pebble instance, a single store per Cockroach node tends to be the norm. Therefore, for `n > O(10)`, the use case is atypical, though certainly still valid. Just not optimized for.

That said, a `Cache` is shareable across DB instances, and we make use of this for Cockroach ([example](https://github.com/cockroachdb/cockroach/blob/05ca68ab3b44427035d230823210199ec272a3a9/pkg/server/config.go#L524)). The `TableCache` can also be shared ([Cockroach example](https://github.com/cockroachdb/cockroach/blob/05ca68ab3b44427035d230823210199ec272a3a9/pkg/server/config.go#L544)), and can use the same underlying cache used by the DB block caches. This might help some.

> I haven't had a chance to look at how hard it would be to have a db.FlushMemtable() type method that drops any previously allocated memtables.

It sounds like what you're asking for is something like "lazy memtable allocation", whereby calling `Flush` flushes the current memtable, but doesn't immediately allocate the memory for a new one. I'm not sure we have such a need in Cockroach, so it's unlikely we'd pick this up. That said, we'd be more than happy to review any contributions, or guide you through what would need to be changed if you wanted to take it on.

Going to close this for now. Thanks again for your investigation here.
