### ISSUE TITLE
Cloning a snapshot

### ISSUE THREAD

**Issue by asdine** [cockroachdb/pebble#1776]
I am looking for a way to clone a snapshot so that multiple readers can read data
at the same point-in-time.

### Use case

I'm implementing a transaction mechanism with multiple readers / single writer.
Each write transaction may use multiple batches before actually committing the transaction (or rollback)
and the readers must not see the intermediate batches.
Readers use snapshots, which works great if the read tx has been created before the write tx, or before the first Pebble batch
has been committed.
However after that, since there is no way to create a snapshot at a specific seqnum, I was thinking I could keep create a snapshot
right before the write tx begins and clone it every time a read tx happens while the write tx is doing its job.
After the write tx is done, I could close the original snapshot and let the read txs close their clone every time they are done with them.

**Comment by jbowens** [comment]
Hi @asdine,

A single `Snapshot` may be used to create multiple iterators. Can you hold a single `Snapshot` and create new iterators from it as necessary?
