### ISSUE TITLE
panic when reopen a existed db

### ISSUE THREAD

**Issue by stone1100** [cockroachdb/pebble#1777]
close data dir/wal dir when lock data dir fail. https://github.com/cockroachdb/pebble/blob/master/open.go#L207-L213
close data dir in defer(panic: https://github.com/cockroachdb/pebble/blob/master/open.go#L170-L172)

**Comment by nicktrav** [comment]
Hi @stone1100 - thanks for the report. 

I'm not quite following where the panic comes from. Do you have a reproducer? We'll also want the version of Pebble and the OS you're running on.

**Comment by stone1100** [comment]
I think pebble use file lock for protecting reopen an opening db instance, but close data/wal dir duplicated in handle err and defer after file lock failure.

close in handle err:  https://github.com/cockroachdb/pebble/blob/master/open.go#L207-L213
```
	// Lock the database directory.
	fileLock, err := opts.FS.Lock(base.MakeFilepath(opts.FS, dirname, fileTypeLock, 0))
	if err != nil {
                 // can remove close data/wal or set nil after close?
		d.dataDir.Close()
		if d.dataDir != d.walDir {
			d.walDir.Close()
		}
		return nil, err
	}
```
close data/wal dir again in defer(will panic: https://github.com/cockroachdb/pebble/blob/master/open.go#L170-L172)

version: github.com/cockroachdb/pebble v0.0.0-20220616214320-059c072fd94a
reproduce code as below:
```go
func TestPebble_Reopen(t *testing.T) {
	p := t.TempDir()
	db, err := pebble.Open(p, &pebble.Options{})
	assert.NotNil(t, db)
	assert.NoError(t, err)

	// will panic, when re-open db(not close)
	_, _ = pebble.Open(p, &pebble.Options{})
}
```

panic stack as below:
=== RUN   TestPebble_Reopen
--- FAIL: TestPebble_Reopen (0.11s)
panic: close of closed channel [recovered]
	panic: close of closed channel [recovered]
	panic: close of closed channel

goroutine 19 [running]:
testing.tRunner.func1.2({0x46992c0, 0x480a620})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x46992c0, 0x480a620})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/cockroachdb/pebble.Open.func1()
	/Users/stone1100/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220616214320-059c072fd94a/open.go:111 +0x175
panic({0x46992c0, 0x480a620})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).stopTicker(...)
	/Users/stone1100/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220616214320-059c072fd94a/vfs/disk_health.go:95
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).Close(0xc00016d980)
	/Users/stone1100/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220616214320-059c072fd94a/vfs/disk_health.go:108 +0x25
github.com/cockroachdb/pebble.Open.func2()
	/Users/stone1100/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220616214320-059c072fd94a/open.go:171 +0x4b
github.com/cockroachdb/pebble.Open({0xc00016e7d0, 0x50}, 0xc0001c5b80)
	/Users/stone1100/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220616214320-059c072fd94a/open.go:213 +0xe47
github.com/lindb/lindb/pkg/unique.TestPebble_Reopen(0xc0001c6b60)
	/Users/stone1100/go/src/github.com/lindb/lindb/pkg/unique/id_store_test.go:222 +0xbb
testing.tRunner(0xc0001c6b60, 0x47735b0)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f

**Comment by nicktrav** [comment]
Perfect. Thank you for the reproducer!

**Comment by nicktrav** [comment]
Playing around with the example some more, I think the issue is that the `FS` is not set in the options. That explains why I couldn't reproduce this initially - muscle memory for always doing something like 

```go
opts := &Options{
  FS: vfs.DefaultFS // or vfs.NewMem()
}
```

The following works if it is set:

```go
func Test(t *testing.T) {
	dir := t.TempDir()
	opts := &Options{
		//FS: vfs.Default, // will NOT panic if this is set.
	}
	opts.EnsureDefaults()
	db, err := Open(dir, opts)
	assert.NotNil(t, db)
	assert.NoError(t, err)
	defer db.Close()

	_, err = Open(dir, opts)
	require.Error(t, err)
}
```

cc: @jbowens - perhaps we need a bit of UX improvement here? Should `(*Options).EnsureDefaults()` set this to a `vfs.DefaultFS` if not set (as the name would imply)? Or maybe we error out with a more helpful error if it's not set in the options. The principle of lease surprise would lead me to believe the former is preferable.

The following seems to do the trick:

```diff
diff --git a/options.go b/options.go
index d0d23887..64ccd91c 100644
--- a/options.go
+++ b/options.go
@@ -758,6 +758,9 @@ func (o *Options) EnsureDefaults() *Options {
        if o == nil {
                o = &Options{}
        }
+       if o.FS == nil {
+               o.FS = vfs.Default
+       }
        if o.BytesPerSync <= 0 {
                o.BytesPerSync = 512 << 10 // 512 KB
        }
```

There might be something worth digging into with the panic too, though I guess we don't expect two DBs to be opened on the same directory at the same time.

**Comment by stone1100** [comment]
@nicktrav thanks, i set FS, it will not panic.
