### ISSUE TITLE
compaction: allow range deletions in a memtable to trigger a delete-only compaction

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1793]
Currently, delete-only compactions are triggered when the compaction picker notices that there are deletion hints that can be resolved (files fully covered, and in the same snapshot stripe), resulting in deleted files.

The deletion hints are currently calculated asynchronously by a table stats collection job, first for any new files introduced to the LSM that have yet to have stats computed for them, then for any existing files without table stats.

There are at least two current limitations with delete-only compactions.

Range deletes in memtables do not produce deletion hints until the memtable is flushed. A range deletion could be resident in a memtable that deletes a large swath of keys in the DB (or even the entire keyspace!), and the keys in existing sstables could undergo a number of unnecessary compactions before the range delete is flushed, generating the requisite hint. Allowing range delete in a memtable to expediently trigger a delete-only compaction can reduce write-amp.

Delete-only compactions triggered from a hint in a file at level `n` only considers files in levels `m`, where `m > n` (i.e. in levels strictly lower in the LSM). A range del in a file in L0 may cover other files in L0 (as files in L0 can overlap, but will exist in different sublevels), yet this range del's hint will only delete files in L1 or lower. By allowing intra-L0 delete-only compactions, files can be deleted earlier, reducing write-amp.

In most cases, for the most part, solving for the first case would cover the second case. However, to cover the case where a memtable is flushed before its hint is calculated and acted upon, it would be nice to cater for the second case to ensure files in L0 are deleted before moving further down the LSM.

**Comment by tbg** [comment]
>  I was thinking of the case where a raft log truncation lays down a range del

That should be fairly rare, since we wouldn't use rangedels here until the raft log had gotten very large.

Nothing you say immediately rings a bell, sorry to not be of more help! Maybe Erik's memory is better.

**Comment by erikgrinaker** [comment]
Yeah, my initial thought is similar to @tbg here. If the Raft log grew large enough to use range dels, then I suspect most of it would already have moved down to L1 and below. We're normally hoping to truncate the logs while they're still in the memtable.

The other major use would be schema object removals (e.g. tables), although in those cases the data will usually have been dormant for 25 hours anyway, so it's likely already been compacted down.

**Comment by jbowens** [comment]
I think this could potentially help in the case of rebalancing. The range being moved could've received recent writes which are still sitting in L0. If replicas are being rebalanced away from the node because of load, it's also more likely that there's read-amp buildup.

**Comment by nicktrav** [comment]
Note to self: we could probably just quickly prototype something here and see what the impact is before committing.

There is evidence [here](https://cockroachlabs.slack.com/archives/C038JEXC5AT/p1657630075576439) from a recent large table drop that could also help inform this work.
