### ISSUE TITLE
background error: pebble/table: invalid table (bad magic number)

### ISSUE THREAD

**Issue by postables** [cockroachdb/pebble#181]
I'm experimenting with a few different datastores in a project I'm working on with pebble being one of them. Running some "stress tests" on my storage service using pebble I came across this peculiar error:

```
background error: pebble/table: invalid table (bad magic number)
```

Once I got this error, I was unable to store anything else in the datastore. I tried shutting down my service, but it hung trying to shtudown the datastore so I had to `kill -9 <pid>`. I'm avoiding restarting my service with the pebble datastore for now.

My datastore is 18GB in size, and for my stress test I've experimented with a few variety of file sizes:
* randomly generated 2MB files
* randomly generated 1 byte files
* randomly generated 1KB files
* randomly generated 32MB files
* randomly generated 12MB files

[Here](https://gateway.temporal.cloud/ipfs/Qmd4ftddkpCBUBJVr71iBY2vfQ8e2FA6bqqVeM6fZo2KCn) is an output of the directory I have pebble storing files in.

My pebble datastore was opened with the following options:
```
L0CompactionThreshold:     40,
L0SlowdownWritesThreshold: 80,
L0StopWritesThreshold:     120,
```

The project I'm using is versioned with go modules, and this is the version I'm currently using of pebble `v0.0.0-20190708194028-33042a76ec95`

Project was compiled using go version `go1.12.7 linux/amd64`

**Comment by petermattis** [comment]
That's disconcerting. Can you save a copy of the database somewhere that I can download? I'm presuming that it doesn't have any sensitive data. If it does have data you don't want to share, I can help you try and isolate which particular table is corrupted. Note that this error should never happen (I haven't seen it before). The error is coming from `sstable.NewReader`. Specifically, the call to `readFooter` is failing. You can wrap that error with one that prints out `fileNum` so we can determine which sstable is problematic.

**Comment by postables** [comment]
Yea thats quite alright none of the data is private, you can try [this link](https://gateway.temporal.cloud/ipfs/QmdZkV8aECaP2ooiS7S8w4ZonDE7tbnAoAkMhP2HvGkxSj) which should let you explore the various files in the directory pebble is writing too. Alternatively I've tarballed the directory and you can download it [here](https://gateway.temporal.cloud/ipfs/QmU7pjMTC26zwuBgnJL7neXwVYuLKvFM1Ydtmpr3USxUT5) or if that doesn't work [this link](https://dev.api.ipfs.temporal.cloud/api/v0/get?arg=QmU7pjMTC26zwuBgnJL7neXwVYuLKvFM1Ydtmpr3USxUT5) should work but it will be pretty slow to download.

Ok I should be able to make the modifications to `pebble` tonight/tomorrow to print out `fileNum` and can report back with my findings.

**Comment by petermattis** [comment]
Neither of the download links work. The first was not making any progress and the second gives a 403 forbidden. I think I'll wait for you to identify which is the problematic sstable.

**Comment by postables** [comment]
I made the change to wrap the error with `fileNum`, and when restarting my service and attempting to reproduce the error, I was unable to reproduce one. I started the stress test I was running when the error occurred, and will report back if it happens.

**Comment by postables** [comment]
I made the change and was able to trigger the error again
```
2019/07/17 15:33:40 background error: fileNum32090
```

I've attached `032090.sst` in this comment but github required that I gzip it first. If you want an ungzipped version try [this link](https://gateway.temporal.cloud/ipfs/QmUu89Xgt75fT5pPWaBmjWKstHX481A5TrJQcqJt4jtumW)


[032090.sst.tar.gz](https://github.com/petermattis/pebble/files/3402632/032090.sst.tar.gz)

**Comment by petermattis** [comment]
@postables well, that sst is corrupt. It doesn't contain the right magic number in the footer block. I'm going to do a bit more poking around to see if I can determine what happened. Is there any chance you ran out of disk space while doing this testing? If you didn't run out of disk space then that eliminates the most obvious suspects.

**Comment by petermattis** [comment]
I no longer think this has anything to do with running out of disk space.

The manifest indicates that `032090` is 3148804 in size, but on disk the size is 4196466. The sstable magic number is actually located right at bytes 3148796-3148804. Somehow an extra 1047660 bytes were appended to the file. 

@postables what filesystem were you running on? When writing sstables we preallocate space on disk. We try to use `fallocate` for that purpose, but if `fallocate` fails we fallback to using `ftruncate`. I think we don't properly truncate the sstable upon completion when using that code path.

**Comment by petermattis** [comment]
Oops, I was mistaken. We don't preallocate while writing sstables, only the WAL.

**Comment by petermattis** [comment]
I compared the sizes from the directory listing against the sizes in the manifest and exactly one file as a different size: `032090.sst`. So whatever happened is not some sort of systemic bug, but something rare.

**Comment by petermattis** [comment]
I'm baffled as to what happened here. `sstable.Writer` is given ownership of the underlying file. It does a series of writes to the file keeping track of the resulting file size. That computed size is then installed in the manifest, but it ended up being much smaller than the actual sstable size. Where did the garbage at the end of the sstable come from?

@ajkr Do you have any theories as to what could have happened? All I can come up with is that something else in the system is accidentally writing to the wrong file descriptor. @postables do you write to files or file descriptors elsewhere in your system?

**Comment by postables** [comment]
@petermattis 
I double checked and no, the disk that I was using has about 600GB of space remaining.

The filesystem I was running is ext4.

Unless by complete fluke I happened to write to the same files and file descriptors elsewhere in my system that would be a no. Is it possible if the application i was using had a data race in it, would that in rar
e scenarios cause writing to the same file or file descriptor? That is the only possible situation in which I can imagine having written to the same file/file-descriptor.

**Comment by vtolstov** [comment]
Sorry for question, what kernel version?

**Comment by postables** [comment]
```
Linux ___ 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vtolstov** [comment]
do you have problems with other files or only pebble? I know that ext4 have issues with silent data corruption, but i think that this is not you case.

**Comment by postables** [comment]
Only pebble. The server this is running on is extremely beefy and used as the development environment for my companys products and tools, and so far the only issue I have experienced is with pebble, so if there are any general issues from ext4 or something else, then I'm definitely not noticing them.

**Comment by postables** [comment]
@petermattis I just remember something that happened to the datastore about a week ago when I was mucking around with pebble. The service I'm writing was using the pebble datastore to store libp2p peer information. An error occurred during the shutdown process, because the datastore had just shutdown, and a process attempted to write some data. Is there any chance this could've caused an error?

Here is the log:

```
panic: pebble: closed

goroutine 84822 [running]:github.com/petermattis/pebble.(*DB).getInternal(0xc0003aa000, 0xc0018fc900, 0x5a, 0x60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)/home/solidity/go/pkg/mod/github.com/petermattis/pebble@v0.0.0-20190708194028-33042a76ec95/db.go:235 +0x4d4github.com/petermattis/pebble.(*DB).Get(...)/home/solidity/go/pkg/mod/github.com/petermattis/pebble@v0.0.0-20190708194028-33042a76ec95/db.go:230github.com/RTradeLtd/go-ds-pebble.(*Datastore).Get(0xc00008c1d0, 0xc0018fc8a0, 0x5a, 0xc0018fc8a0, 0x5a, 0x2, 0xc001d166e0, 0x4e)/home/solidity/go/pkg/mod/github.com/!r!trade!ltd/go-ds-pebble@v0.0.4/datastore.go:44 +0x88github.com/ipfs/go-datastore/keytransform.(*Datastore).Get(0xc0000d06c0, 0xc001d166e0, 0x4e, 0x104351f, 0x5, 0xc001d166e0, 0x4e, 0xc001d16640)/home/solidity/go/pkg/mod/github.com/ipfs/go-datastore@v0.0.6-0.20190630210907-9f8f47309e90/keytransform/keytransform.go:42 +0x76github.com/libp2p/go-libp2p-peerstore/pstoreds.(*dsKeyBook).PrivKey(0xc00008c220, 0xc00003a3f0, 0x26, 0x0, 0xc0018a67e0)/home/solidity/go/pkg/mod/github.com/libp2p/go-libp2p-peerstore@v0.1.2-0.20190621130618-cfa9bb890c1a/pstoreds/keybook.go:92 +0x182github.com/libp2p/go-libp2p-swarm.(*Swarm).dial(0xc00080ec00, 0x12f0440, 0xc001a25e00, 0xc0028e3740, 0x22, 0x0, 0x0, 0x0)/home/solidity/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.1.1/swarm_dial.go:286 +0x214github.com/libp2p/go-libp2p-swarm.(*Swarm).doDial(0xc00080ec00, 0x12f0440, 0xc001a25e00, 0xc0028e3740, 0x22, 0x0, 0x0, 0x0)/home/solidity/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.1.1/swarm_dial.go:249 +0x1e6github.com/libp2p/go-libp2p-swarm.(*activeDial).start(0xc0015fa960, 0x12f0440, 0xc001a25e00)/home/solidity/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.1.1/dial_sync.go:80 +0x57created by github.com/libp2p/go-libp2p-swarm.(*DialSync).getActiveDial/home/solidity/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.1.1/dial_sync.go:100 +0x1fd
```

**Comment by petermattis** [comment]
> An error occurred during the shutdown process, because the datastore had just shutdown, and a process attempted to write some data. Is there any chance this could've caused an error?

Unlikely. Both read and write operations check that the DB hasn't been closed. This isn't perfectly safe and is meant only to notify an application that it is doing something wrong. The real safety is that a DB can't be opened twice and that is ensured by an OS file lock. 

> Unless by complete fluke I happened to write to the same files and file descriptors elsewhere in my system that would be a no. Is it possible if the application i was using had a data race in it, would that in rare scenarios cause writing to the same file or file descriptor? That is the only possible situation in which I can imagine having written to the same file/file-descriptor.

If you have a race in your application, pretty much anything is possible. Are you writing to a lot of other file descriptors in your application? Is there any pattern in what you're writing to those file descriptors that would be visible upon inspection? I'm wondering if there is any way we can see a signal that this happened.

> Additionally, is there any chance running with sync disabled is causing some kind of data race?

Not that I can see. Disabling sync would cause the WAL to be truncated. What we're seeing is an sstable that has too much data. That is supremely weird.

**Comment by postables** [comment]
> Unlikely. Both read and write operations check that the DB hasn't been closed. This isn't perfectly safe and is meant only to notify an application that it is doing something wrong. The real safety is that a DB can't be opened twice and that is ensured by an OS file lock.

Ah okay that makes sense, thanks for the explanation.

> If you have a race in your application, pretty much anything is possible. Are you writing to a lot of other file descriptors in your application? Is there any pattern in what you're writing to those file descriptors that would be visible upon inspection? I'm wondering if there is any way we can see a signal that this happened.

No the only file descriptors I'm writing to are through pebble. However the pebble datastore is shared by multiple different components of the application. In this case the pebble datastore was being used for:

* Storing IPFS blocks
* Storing LibP2P peer information
* Backing a persistent FIFO queue
* Storing LibP2P DHT records

The keys that get stored for each of these components is wrapped in a [namespace](https://github.com/ipfs/go-datastore/tree/master/namespace). In the case of blocks, all keys are prefixed with `/blocks`. In the case of libp2p peer information it's prefixed with `/peerstore`. In the case of the FIFO queue, it's prefixed with `/queue`. I'm not sure what the LibP2P DHT records use for the namespace.

Could you clarify what you mean by patterns? The only pattern I can think of is each component have a particular prefix to the keys.

> Not that I can see. Disabling sync would cause the WAL to be truncated. What we're seeing is an sstable that has too much data. That is supremely weird.

Damn I was hoping that would be an easy explanation. You are right this is indeed supremely weird.

**Comment by petermattis** [comment]
> Could you clarify what you mean by patterns? The only pattern I can think of is each component have a particular prefix to the keys.

I was asking for data patterns that I could look for in the "garbage" at the end of `032090.sst`. For example, if I saw something in there that looked like an HTTP header and you weren't storing HTTP in the Pebble instance, then we'd have a clue.

> If you have any suggestions on tests I can run, modifications to code I can make like print statements in certain lines, etc... do let me know. Although I'm using pebble as an experiment right now it's absolutely fantastic and something I want to use in production when its ready. I'd be happy to help debug things to get to production all the more quickly!

Another instance of this bug would be very helpful.

**Comment by postables** [comment]
> I was asking for data patterns that I could look for in the "garbage" at the end of 032090.sst. For example, if I saw something in there that looked like an HTTP header and you weren't storing HTTP in the Pebble instance, then we'd have a clue.

Ah okay in that case definitely not. 99% of the data was from `/dev/urandom` `dd`'d into a text file and uploaded. The other 1% is a couple of makefiles, and readmes, but I don't think those would be present in `032090.sst`

> Another instance of this bug would be very helpful.

I still have the datastore that I was using which caused this error, so I can trigger the same error, but I'm not sure if I'll be able to repeat the error on a different datastore. I will keep an eye out for it though and if it happens again I'll add my findings as a comment here.

**Comment by petermattis** [comment]
@postables I'm closing this issues as there is nothing else to debug here. If you see a repeat I'd love to know. There have been a variety of bug fixes in Pebble since you saw this issue, but I can't point to any particular one that would have led to this type of corruption.
