### ISSUE TITLE
db: increase minimum-supported FormatMajorVersion

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1813]
In CockroachDB 23.1, we should increase the minimum-supported (and default) FormatMajorVersion to a version at least as high as `FormatMarkedCompacted`. This will allow us to remove code related to user keys split across neighboring sstables (eg, atomic compaction units). When we make this change, we should put some effort into appropriately documenting the upgrade path for non-CockroachDB users that are still running using earlier format major versions.

**Comment by nicktrav** [comment]
> minimum-supported (and default) FormatMajorVersion

Wonder if we should we be thinking about the "minimum-supported" part some more and scope that out (maybe we support features in line with the CockroachDB support policy?). It would be great to be able to start removing some old code.

Tangentially related, there's chatter over on #1064 about semantic versioning for Pebble. Perhaps we can roll that into it too.

**Comment by RaduBerinde** [comment]
This is now tracked by #3064.
