### ISSUE TITLE
db: range keys sometimes omitted during TBI

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/pebble#1895]
I'm seeing something that indicates a bug with range key defragmentation and block property filters.

In https://github.com/cockroachdb/cockroach/pull/86256, I'm adding a metamorphic test parameter for `TestMVCCHistories` which causes Pebble to use very small blocks, and to flush after every write operation. Try running this a few times:

```
dev test pkg/storage -f 'TestMVCCHistories' --ignore-cache -v --rewrite
```

Quite often (depending on the metamorphic parameters), this will generate changes in `export` and `range_key_iter_incremental` that either truncate range keys (so e.g. `[a-k)` is truncated to `[a-b)`), or fragments disappear completely (e.g. `[b-c)` disappears from a longer chain of connected fragments). This leads me to suspect a bug in Pebble defragmentation, since I don't see any mechanism in CRDB that would truncate range keys like this.

Both of these test cases use `MVCCIncrementalIterator`, using a TBI paired with a normal iterator. However, it must be the normal iterator that's surfacing these truncated range keys -- it's still a bit unclear what's happening.

**Comment by jbowens** [comment]
Are the range keys themselves written at a filtered timestamp? If the range keys are eligible for being filtered out by a RangeKeyFilter block property filter, that can introduce nondeterministic existence of range keys. If the TBI doesn't surface them at all, the normal iterator can skip over them. I don't see how this would cause _truncated_ bounds tho, because the normal iterator should still defragment if it isn't seeked past all fragments. 🤔

**Comment by jbowens** [comment]
I tried running without the `RangeKeyFilters` undress stress and get to around ~70 passes before I hit the goroutine leak [you mentioned](https://github.com/cockroachdb/cockroach/pull/86256#issuecomment-1217124137).

I expect that's a race in database teardown. It looks like they're all table cache shard goroutines. I'll add a wait group to wait for them to exit during teardown and see what happens.

**Comment by erikgrinaker** [comment]
Found the problem, it's in `MVCCIncrementalIterator` -- see https://github.com/cockroachdb/cockroach/issues/86260#issuecomment-1217882094.
