### ISSUE TITLE
metamorphic: test RangeKeyChanged on iterators with block property filters

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#1902]
Currently the metamorphic tests always fake a `RangeKeyChanged()=false` value for iterators configured with a block-property filter. This was done because the `retryableIter` may need to reposition these iterators to skip over filtered key-value pairs, which may change the value of `RangeKeyChanged`.

Instead, should be able to tweak the retryableIter to return true from `RangeKeyChanged` if the original underlying iterator operation _or_ any of the subsequent filtering positioning operations returned `RangeKeyChanged()=true`.

https://github.com/cockroachdb/pebble/blob/358c749ef8fa84f1831b797f15850e25f3c14533/internal/metamorphic/retryable.go#L99-L108

**Comment by bananabrick** [comment]
https://github.com/cockroachdb/pebble/commit/3f835a3d781c175cb52cadbacfbb08b3ed524a7c
