### ISSUE TITLE
metamorphic: replace Delete with DeleteRange to stress DeleteRange

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/pebble#1935]
https://github.com/cockroachdb/pebble/blob/3d9c6101a3a12d5f158dcc0c1d106ac6c5c254b2/internal/metamorphic/meta_test.go#L39-L40

**Comment by RaduBerinde** [comment]
@bananabrick I'm trying to get my bearings in this codebase; would you mind writing out some detail about what needs to be done? I see that there is a `writerDeleteRange` generator.
