### ISSUE TITLE
`Get` and `Iter` on batches treat `Merge` differently

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/pebble#1958]
Consider this test case:

https://github.com/cockroachdb/cockroach/blob/95677eb5f8d006629b16024fb7d87d55344c1470/pkg/storage/batch_test.go#L739-L780

Here, we do a batch `Merge` write `a=bar`, then an engine write `a=foo`, and then read back `a` from the batch using `Get`, yielding the merged `a=foobar`. However, if I replace the `Get` operation with a batch iterator, it only returns `a=bar`. Bug?

PS: I don't think this is an issue in CRDB, since we don't use `Get` for reads in production code, just stumbled across this during some code cleanups.

**Comment by jbowens** [comment]
> However, if I replace the `Get` operation with a batch iterator, it only returns `a=bar`.

When is the batch iterator created? Before or after the `a=foo` engine write?

`Batch.Get` reads through to the current engine state at the time `Batch.Get` is executed. A batch iterator sees the consistent state of the engine at the time the engine was created, so it won't observe any recent engine writes.

It'd be good to clean up these remaining test code usages of `Reader.MVCCGet` and remove it from the interface altogether.

**Comment by erikgrinaker** [comment]
> When is the batch iterator created? Before or after the a=foo engine write?

After. Each read uses a new iterator.

>It'd be good to clean up these remaining test code usages of Reader.MVCCGet and remove it from the interface altogether.

Yep, that's what I was doing when I stumbled across this.

**Comment by erikgrinaker** [comment]
I'll submit a PR with the failing test skipped in a bit.

**Comment by erikgrinaker** [comment]
New test case over in https://github.com/cockroachdb/cockroach/pull/87954.

**Comment by jbowens** [comment]
On a second look, isn't this expected? A `pebbleBatch`'s view of the engine is guaranteed to be consistent for the life of the batch. The first MVCC get will create a `pebbleBatch` iterator, pinning the batch's view of the engine from then on to that instant. Calls to `SetOptions` only refresh the view of the batch itself, not the engine.

**Comment by erikgrinaker** [comment]
Ah yeah, you're right. Forgot that consistent iterators would imply a fixed engine view. This seems to be working as intended then, will remove the test.
