### ISSUE TITLE
db: Get doesn't utilize bloom filters

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#197]
`DB.Get` currently doesn't utilize bloom filters to avoid reading sstables. This is due to `getIter` creating regular iterators and calling `SeekGE`. I'm not sure how I'd want to fix this exactly, but all of the logic for checking bloom filters already exists in `sstable/Reader.get`. That method is only exposed for testing as it doesn't account for merge operations. It also isn't urgent for CockroachDB's use case, as CockroachDB does not create bloom filters on the full key, only on prefixes.

Should `getIter` call `SeekPrefixGE` instead of `SeekGE`?

**Comment by hsanjuan** [comment]
Is this still relevant? My application uses Get before Set() to avoid unnecessary overwrites to existing key-values, but it seems those Gets have larger IO impact than what I would have expected for non-existing keys.

**Comment by Wondertan** [comment]
So was this one closed by #2846 or not?

**Comment by jbowens** [comment]
Yeah, it is, thanks.
