### ISSUE TITLE
db: narrow checkpoints

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/pebble#2045]
See https://github.com/cockroachdb/cockroach/issues/90543. Essentially, we want to only checkpoint parts of the keyspace, to avoid running nodes out of disk (as the initial hardlinks become unreferenced by the original database). The checkpoints should still be inspectable as a normal Pebble database.

**Comment by jbowens** [comment]
I think this should be a minor lift and relatively straightforward. We can include the entire WALs, MANIFESTs, etc, and just exclude sstables that fall wholly outside the key span.

**Comment by RaduBerinde** [comment]
@jbowens won't we need to modify the manifest to remove references to the missing files?

**Comment by jbowens** [comment]
ah, I had been thinking the partial-checkpointed database wouldn't be directly openable by Pebble. The individual files could be inspected through `cockroach debug pebble [manifest|sstable|wal] ...` commands. I suppose we do still need to be able to open the DB to use other higher-level cockroach tooling.

Yeah, the manifest's final version will need to only contain files that are present. I think we'd only need to append a single version edit to the end of the copied manifest marking all skipped files as removed.

@erikgrinaker for instances of replica divergence, were you thinking of only excluding MVCC data and keeping all the local keyspaces for all ranges? So we'd want to checkpoint two key spans: 1) the entire local keyspace 2) the range's MVCC data

**Comment by erikgrinaker** [comment]
I was thinking we'd exclude all keyspans for all other ranges (except perhaps the adjacent ranges on that store). But given that the local keyspans are often small, it shouldn't be a huge problem to keep them all, and the SSTs will likely include lots of other ranges' local keyspans anyway.

Any particular reason you ask?
