### ISSUE TITLE
sstable: avoid mutex acquisition in Writer.EstimatedSize

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2046]
I was a little surprised to see 6% of compaction CPU time being used in `Writer.EstimatedSize`. Most of the time appears to be in `indexBlockBuf.estimatedSize` and much of it in `Lock` and `Unlock` in `sync.Mutex`. It seems like the writer goroutine can calculate and update the estimated size, storing it in an atomic.

<img width="1238" alt="Screen Shot 2022-10-24 at 1 12 20 PM" src="https://user-images.githubusercontent.com/867352/197585764-c8e16045-d576-46a4-938b-9f3ea245331f.png">

**Comment by bananabrick** [comment]
Is parallelism enabled here? That mutex should only get used with parallelism enabled.
