### ISSUE TITLE
db: add tracing events

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2055]
Cockroach uses traces to provide observability into queries. This tracing ends at the Pebble boundary. In cockroachlabs/support#1842, a Cockroach trace recorded a scan that took 200ms but according to the Pebble iterator stats only visited 2 keys and only loaded 14K worth of block bytes. Our current observability was insufficient to determine what happened—was the disk slow while reading?

We can hook into the Cockroach tracing and record a simple trace statement around block loads that need to hit the disk. In this case, this could've confirmed or disproved the disk as the culprit.

**Comment by sumeerbhola** [comment]
I am going to close this out since we have some tracing now. Further improvements can be tracked in other issues.
