### ISSUE TITLE
ingest: check for data overlap doesn't consider range keys

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#2083]
The [`overlapWithIterator` function](https://github.com/cockroachdb/pebble/blob/b53472d0ec8663867ebb480ec64214ecf15e5f86/ingest.go#L379) does not consider range keys when checking for data overlap of the ingested SSTable.

More context in [this](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1667240515381579) (internal) thread.

**Comment by nicktrav** [comment]
Reproducer in #2082.

**Comment by nicktrav** [comment]
Just tacking in an update here. The current thinking is that this is _not a release blocker_ due to the fact that we do not write range keys by default in 22.2.

While we have a reproducer, the original thinking was that the bug wouldn't result in incorrect results. However, the current thinking is that there could be a correctness bug here - a rangekeydel or rangekeyunset ingested into a lower level could be elided before they have the opportunity to drop the the keys they delete. We need to confirm this.

We will need to backport the fixes, once we have them, to 22.2.

**Comment by bananabrick** [comment]
Solved in https://github.com/cockroachdb/pebble/pull/2082
