### ISSUE TITLE
metamorphic: vary bloom bits-per-key

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2127]
The number of bits-per-key used by the bloom filter configuration affects the false positive rate of bloom filter lookups. We've seen several bugs that are dependent on successful bloom-filter file exclusion (eg, #2123/#2118). Currently the metamorphic tests use a fixed 10 bits-per-key when enabled at all. We get some coverage since we vary target-file-size. In the random options, we can vary the bits-per-key to get broader coverage here.

**Comment by itsbilal** [comment]
As part of this same issue, we should also be varying `UseL6Filters` for iterators in the metamorphic test. It could be one of the options randomly generated as part of the `newIterOp`.
