### ISSUE TITLE
In need of stronger sync semantics

### ISSUE THREAD

**Issue by paxostv** [cockroachdb/pebble#2163]
Passing `Sync: true` via `WriteOptions` only guarantees that the data is synced to disk before the write returns, however it doesn't specify when the data becomes accessible. It turns out that the implementation publishes the write to the memtable before waiting for the sync to complete, which means that a concurrent reader may see a key that's written with `Sync: true` before it's synced to disk. This leads to cases where inopportune power failures or other misfortune may cause that data to disappear despite clients having successfully read it.

This was an surprising discovery, as I would have thought that the memtable would be published only after data is synced, however I see why this would considerably slow down non-synced writes in the case there's a mixture of both, since the sequence must be respected.

`Iterator` has an option `OnlyReadGuaranteedDurable` which I presume would provide the desired behavior, but it's unclear to me whether this is a suitable workaround. What is the suggested approach to enforcing these semantics, and/or is pebble a good fit for this use case? An alternative approach is to separate out the WAL and have a `DisableWAL: true` pebble DB, and only write into the latter once the WAL write has been persisted, which is _almost_ what pebble provides so I would hope that there's potential for closing this gap.

**Comment by paxostv** [comment]
Reading the code, the only logical change would be to increase the `visibleSeqNum` only after the sync has been applied (actually doing this would require a bit of work in the code). Right now the sync and publish share the same wait group, so there's no sequencing of them. Is this accurate?

**Comment by sumeerbhola** [comment]
You are correct that Pebble does not wait for sync before publishing the seqnum. The following code comment also outlines this behavior.
https://github.com/cockroachdb/pebble/blob/0fd6d4020f873fcfced13332063d1837c9db4000/commit.go#L164-L172

This was a deliberate choice to improve performance. Our goal was to support CockroachDB's needs, which used the RocksDB "manual WAL flush", before switching to Pebble. It didn't need the stronger semantics as it uses latches, and writes do not release latches until after the write method returns (after the sync is done). Hopefully there is a similar way for you to work around these weaker semantics. It isn't a trivial code change to support the stronger semantics (as I believe you have realized), and this code path is very performance sensitive, so I am a bit wary of supporting two modes of operation.
