### ISSUE TITLE
TestDiskHealthChecking_Filesystem/remove might be flaky

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/pebble#2272]
Test failure: https://github.com/cockroachdb/pebble/actions/runs/3999009992/jobs/6862370894

Relevant logs:

```
--- FAIL: TestDiskHealthChecking_Filesystem (0.42s)
    --- FAIL: TestDiskHealthChecking_Filesystem/remove (0.05s)
        assertion_compare.go:313: 
            	Error Trace:	disk_health_test.go:362
            	Error:      	"0" is not greater than "0"
            	Test:       	TestDiskHealthChecking_Filesystem/remove
            	Messages:   	[]
FAIL
FAIL	github.com/cockroachdb/pebble/vfs	7.194s
ok  	github.com/cockroachdb/pebble/vfs/atomicfs	0.172s
FAIL
make: *** [test] Error 1
Error: Process completed with exit code 2.
```

Triggered on https://github.com/cockroachdb/pebble/pull/2255.

It is possible that I introduced this flake with above PR, but I cannot repro the flakiness. I ran both the whole suite of VFS tests & just the test that failed 100-1000x times & did not repro the flakiness. Tho I did change related code, I also don't have a concrete theory of how my PR would increase the flakiness of this test.

CC @nicktrav as we discussed this during 1:1!

**Comment by nicktrav** [comment]
Looks like we've got this one tracked in #1718. Going to close this one in favor of the one we have open already.

**Comment by joshimhoff** [comment]
Whoops! Thanks. I am clearly new to github search.
