### ISSUE TITLE
vfs: lower the risk of unmonitored FS / File operations

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#2275]
_This was extracted from [this comment](https://github.com/cockroachdb/cockroach/issues/94373#issuecomment-1402752893) on #cockroachdb/cockroach#94373._

The current way in which we "layer" instances of an FS / File is susceptible to situations where FS / File health checks can miss certain operations, depending on where the health check middleware is inserted. Ideally, the health checks are always at the top of the stack / layercake.

Consider tweaks to the `vfs.File` and `vfs.FS` interfaces to eliminate the footgun of un-monitored operations.

Related to cockroachdb/cockroach#94373.

**Comment by jbowens** [comment]
Just some remaining in-flight backports left. Going to close this out.
