### ISSUE TITLE
sstable,objstorage: seed Reader with pre-stored metadata

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2328]
With disaggregated storage, we're introducing a new storage medium with different latency characteristics. I think it's worth looking at the sequential read I/O performed when opening a new table and considering what we can remove through either duplicating the data in the Pebble manifest (and keeping it in-memory in the `FileMetadata`) , or caching on the filesystem for shared objstorage.

Every `sstable.NewReader` call:
1. Reads the sstable footer. The footer is at most 53 bytes, but the amount of logical data once excluding footer version, padding, checksum and magic number is two block handles: one for the metaindex block and one for the index block. These two block handles can be serialized with just 4 varuints or held in-memory with 4x uint64s. 
2. Reads the metaindex block. Open requires reading this block to extract:
  a. the block handle for the value blocks index block (2x uint64)
  b. the properties block handle (2x uint64)
  c. the range deletion block handle, if present (2x uint64)
  d. the range key block handle, if present (2x uint64)
  e. the filter block handle (2x uint64)

These two consecutive reads result in ~112-bytes of data necessary for reading the file. This is small enough to reasonably be embedded within the in-memory fileMetadata, and definitely small enough to store on the local filesystem for all shared files.  Additionally, in practice we almost always load the filter block if it's present, since MVCCGets use `SeekPrefixGE`. IIRC, the filter block is usually ~1% or less of the total size of the database. In disaggregated storage, it seems like it could be worthwhile to cache filter blocks on the filesystem and more aggressively than the more general table cache we're expecting to build.

Table-level block properties might also be worth elevating into either the fileMetadata or a dedicated shared objstorage filesystem cache, since they're consulted on every read for an iterator with a block-property filter. This last point is related to #2002, where we consider elevating the mvcc block properties into the fileMetadata.

**Comment by jbowens** [comment]
Another thought is that opening a table could read the trailing 4kb of the table. This will include the footer and metaindex block. It likely will also include the properties block.

**Comment by sumeerbhola** [comment]
With https://github.com/cockroachdb/pebble/pull/3608 there should be only 2 reads, one when constructing the `Reader` and one when constructing the sstable iterator (for the index blocks and filter block).

@jbowens should we close this issue, and open a different one if we find more improvements are needed?

**Comment by jbowens** [comment]
Sounds good! Closing
