### ISSUE TITLE
db: optional point tombstone deletion size estimates

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2340]
In Cockroach, when we delete a MVCC key with a point tombstone (eg, GC), we always know the size of the live key and value we're deleting. We use these sizes to update MVCC stats.

In Pebble, our point-tombstone compaction heuristics estimate the amount of data dropped by point tombstones by looking at the average logical KV size of either KVs in the same sstable or overlapping sstables in lower levels. In some cases (eg, cockroachlabs/support#2084) this estimate is poor and resulting space amplification can be excessive.

We could extend the `Delete` interface to optionally accept the logical key+value size of the KV pair being deleted and encode it in the value. Pebble could record the sum of these values and the count of these tombstones in new table properties. In compaction heuristics, Pebble could estimate the space reclamation of compacting these point tombstones using these known quantities rather than averages from the own table or lower-levelled tables, significantly improving the estimate.

When a point tombstone causes the elision of another key during a compaction, this size hint could be zeroed, reflecting that it no longer has the expectation of removing lower-level KVs (although it still might, if there were multiple keys with the same user key).

There's still potential for error in compressibility. A user may indicate that a point tombstone deletes a 4KB value, but that value might actually be uniquely compressible and its surrounding data very incompressible (or vice versa).

**Comment by sumeerbhola** [comment]
I really like this idea, since it sidesteps most of the estimation issues.
