### ISSUE TITLE
replay: TestCompactionsQuiesce is flaky under race/asan

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#2355]
Seen [here](https://github.com/cockroachdb/pebble/actions/runs/4249409568/jobs/7389536849).

```console
--- FAIL: TestCompactionsQuiesce (124.35s)
    replay_test.go:515: 
        	Error Trace:	replay_test.go:515
        	            				replay_test.go:519
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 1
        	Test:       	TestCompactionsQuiesce
FAIL
FAIL	github.com/cockroachdb/pebble/replay	126.535s
```

**Comment by nicktrav** [comment]
A slightly different failure mode. This one was from the linux-race CI job ([link](https://github.com/cockroachdb/pebble/actions/runs/4251128566/jobs/7400462929)).

```console
--- FAIL: TestCompactionsQuiesce (183.80s)
    replay_test.go:510: 
        	Error Trace:	replay_test.go:510
        	            				replay_test.go:519
        	Error:      	Condition never satisfied
        	Test:       	TestCompactionsQuiesce
        	Messages:   	(*replay.Runner).Wait didn't terminate
FAIL
```

**Comment by RaduBerinde** [comment]
This test runs in ~2 seconds locally; these race/asan builds are orders of magnitude slower. I think we need to increase the timeout and the [1 second grace period](https://github.com/cockroachdb/pebble/blob/master/replay/replay.go#L423) for quiescing compactions in these builds.

**Comment by nicktrav** [comment]
Another one: https://github.com/cockroachdb/pebble/actions/runs/6884451979/job/18726978449
