### ISSUE TITLE
[Question] What's the flag to represent "after all keys"

### ISSUE THREAD

**Issue by rjl493456442** [cockroachdb/pebble#2359]
In go-ethereum, we want to range-compact the database with specified key range, e.g. [0x00 - 0x10), 
In go-leveldb, nil is used to represent it's after all keys in the database, so originally we use [0xf0, nil)
for the last range.

However it's different in pebble, nil is not the special flag for representing *after all keys*, but means 
empty slice instead(with default compare setting). 

I am wondering how can we specify the range starts from the provided key and includes all following
keys afterwards?

**Comment by jbowens** [comment]
Hi, you're right, there's no special significance to the `nil` key in Pebble.

> I am wondering how can we specify the range starts from the provided key and includes all following
keys afterwards?

We recommend handling this in your key encoding (eg, `Compare` implementation). CockroachDB's key encoding uses `[]byte{0xff, 0xff}` to represent the maximal key and encodes all other keys as keys with a byte prefix that `bytes.Compare`s less than `0xffff`.

**Comment by jbowens** [comment]
Please feel free to reopen if you have another question.
