### ISSUE TITLE
Interpreting Stats and optimizing configuration

### ISSUE THREAD

**Issue by hsanjuan** [cockroachdb/pebble#2375]
I am trying to ingest about 40TB of data into Pebble (on spinning disks). I cannot find a tuning guide of sorts but some pointers here are useful (https://github.com/EighteenZi/rocksdb_wiki/blob/master/RocksDB-Tuning-Guide.md).

The machine is big with has a ridiculous amount of RAM (192GB) but part of it is used as caching layer for ZFS. There is also some additional caching NVME in front of the actual spinning disks.

I have configured Pebble as follows:

```
	var defopts pebble.Options
	cache := pebble.NewCache(10 << 30) // 10 GiB
	defopts = *defopts.EnsureDefaults()
	defopts.MemTableSize = 128 << 20 // 128 MB. Def: 4MB.
	defopts.BytesPerSync = 512 << 20 // 512 MiB
	defopts.Cache = cache
	defopts.DisableWAL = true
	defopts.MaxConcurrentCompactions = func() int {
		return 10
	}
	defopts.MaxOpenFiles = 5000
	defopts.L0CompactionThreshold = 4       // default 4
	defopts.L0StopWritesThreshold = 1000    // default 12
	defopts.LBaseMaxBytes = 512 << 20       // default: 64 MB
	defopts.L0CompactionFileThreshold = 750 // default: 500
	defopts.Levels = make([]pebble.LevelOptions, 7)
	defopts.MemTableStopWritesThreshold = 30
	defopts.Levels[0].TargetFileSize = 4 << 20 // 2MB def: 4M

	for i := 0; i < len(defopts.Levels); i++ {
		l := &defopts.Levels[i]
		l.BlockSize = 8 << 10 // 8 KB : def 4K
		// l.IndexBlockSize = 512 << 10
		l.FilterPolicy = bloom.FilterPolicy(10)
		l.FilterType = pebble.TableFilter
		l.Compression = pebble.NoCompression
		if i > 0 {
			l.TargetFileSize = defopts.Levels[i-1].TargetFileSize * 2
		}
		l.EnsureDefaults()
```

I disabled compression under the impression that it would hurt read latency later in the future, but perhaps it was a bad call.

And here are some stats while writing:

```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
WAL         1     0 B       -     0 B       -       -       -       -   114 G       -       -       -     0.0
  0       250   1.0 G    1.20   114 G     0 B       0     0 B       0   114 G    30 K     0 B       3     1.0
  1        84   533 M    1.20   115 G     0 B       0   8.6 M       3   188 G    26 K   188 G       1     1.6
  2       296   2.5 G    1.02   106 G     0 B       0   9.3 G   1.5 K   233 G    25 K   233 G       1     2.2
  3       706    12 G    1.02   110 G     0 B       0   2.5 G     630   294 G    17 K   303 G       1     2.7
  4      1643    55 G    1.00    96 G     0 B       0   471 M     133   246 G   7.1 K   274 G       1     2.6
  5      4035   200 G    0.76    38 G     0 B       0   113 M      23    95 G   1.4 K    99 G       1     2.5
  6     12159   1.1 T       -     0 B     0 B       0     0 B       0     0 B       0     0 B       1     0.0
total     19173   1.4 T       -   114 G     0 B       0    12 G   2.3 K   1.3 T   106 K   1.1 T       9    11.3
flush       324
compact     32093    24 G   599 M      10          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
ctype     29764       0       0    2329       0       0       0  (default, delete, elision, move, read, rewrite, multi-level)
 memtbl         7   896 M
zmemtbl         1   256 K
 ztbl      5168    92 G
 bcache     2.1 M   8.6 G    0.1%  (score == hit-rate)
 tcache     9.8 K   6.3 M   45.6%  (score == hit-rate)
snaps         0       -       0  (score == earliest seq num)
 titers        29
 filter         -       -    0.0%  (score == utility)
```

Is there something obvious that looks wrong? Write amplification does not look horrible (?) but I see about 30MB/s of data written to the DB translate into 400MB/s of writes to disk (where it maxes out).

I have noticed a 30% perf improvement when increasing `defopts.LBaseMaxBytes ` and `defopts.L0CompactionFileThreshold` from the defaults vs the previous config, but I've also noticed RAM usage grow heavily as a result so not sure if I should increase more. Any insights welcome!

**Comment by nicktrav** [comment]
One quick, initial observation:

>  ztbl      5168    92 G

That implies there are 92G of tables that are no longer in the working set of the LSM, but are being kept around by something (i.e. "zombie tables"). This is usually an issue related to iterator usage - suggest only keeping open an iterator for the shortest time you actually need it, then close it.

**Comment by jbowens** [comment]
Are you importing randomly distributed data or is there some existing sorting? If you do have sorted data, I recommend building sstables using [sstable.Writer](https://pkg.go.dev/github.com/cockroachdb/pebble@v0.0.0-20230301151825-0cd1ceea645a/sstable#Writer) and then [Ingest](https://pkg.go.dev/github.com/cockroachdb/pebble#DB.Ingest)-ing them.

> I disabled compression under the impression that it would hurt read latency later in the future, but perhaps it was a bad call.

Depending on how compressible your data is, I think you should get better performance with compression enabled since it reduces IO. I'm not sure what your workload looks like, but if you have a lot of memory available at read-time too, devoting a large portion to the block cache should help.

**Comment by nicktrav** [comment]
> I think this was perhaps due to an iterator that iterates on all keys at the beginning and it must have been ongoing.

Consider using a `Snapshot` if you want to do this, then take out the iterator on the snapshot. That allows compactions to happen within the various open snapshot stripes, and allows obsolete data to be dropped after a compaction, and for memtables to be flushed. Just remember to call `Close`!

**Comment by jbowens** [comment]
> Perhaps as an optimization, if the read is indeed very long running (scanning entire DB), perhaps you can close and re-open and re-seek the iterator on the snapshot.

nit: Re-opening and re-closing the iterator on the snapshot is a requirement to get any benefit out of the snapshot. The snapshot-backed Iterator will still pin the memtable and sstables for its lifetime. But you can acquire a new Iterator that observes the same state at any time.

**Comment by hsanjuan** [comment]
What does `tcache     9.8 K   6.3 M   45.6%  (score == hit-rate)`  mean? I'm guessing table-cache. Even in a write-only context I have about 50% hit-rate. Does this mean that Pebble is clever enough to realize when a key-value has already being written and skips the write?

**Comment by bananabrick** [comment]
> What does tcache     9.8 K   6.3 M   45.6%  (score == hit-rate) mean? I'm guessing table-cache.

That's right. The table cache doesn't cache keys/values, but an `sstable.Reader`, which is basically a handle used to perform reads on a file.

> Even in a write-only context I have about 50% hit-rate.

In a write only context, new tables are written during either compactions/flushes, and then read during compactions. I believe the first read on the table during compactions will be a cache miss which is why the hit rate is low. Once a table is read during a compaction, I believe that it won't be read again, so a hit rate of around 50% makes sense to me.

If you're performing both reads/writes, I'd expect the table cache hit rate to be higher.

**Comment by nicktrav** [comment]
@hsanjuan - I'm going to close this out for now. If you have specific questions related to tuning, I'd encourage you to ask over on the [CockroachDB Community Slack](https://www.cockroachlabs.com/join-community/). We welcome bug reports / performance issues here on the repo though.
