### ISSUE TITLE
compaction: async deletion of files can result in many goroutines

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#2379]
When using the deletion pacer, we kick off the deletion in a goroutine, [here](https://github.com/cockroachdb/pebble/blob/fdf055ddb6e438a63b81ac2d751da8232b07c893/compaction.go#L3488). This can result in many goroutines being spawned, only to be put to sleep by the pacer, [here](https://github.com/cockroachdb/pebble/blob/fdf055ddb6e438a63b81ac2d751da8232b07c893/pacer.go#L91).

Here's an example summary I saw, which showed 500+ goroutines all sleeping, waiting their turn to delete the files from their respective compactions. This accounted for ~5% of the total goroutine count of this process:

<img width="701" alt="Screenshot 2023-03-03 at 5 20 43 PM" src="https://user-images.githubusercontent.com/804457/222867850-b21c7ec7-2c77-4e44-885b-158dd7b9b5a3.png">

When using a deletion pacer, rather than spawning a goroutine _per compaction_, we could consider having a single goroutine that is responsible for deletion of files. When a compaction completes, it puts the files that need to be deleted in a queue (guarded by some mutex). Then a second goroutine could pull from this queue in order to satisfy the deleting pacing constraints.

Note that when running _without_ a pacer, this problem isn't apparent, as the files are deleted synchronously as part of the compaction.

**Comment by jbowens** [comment]
Was the high goroutine count present with and without encryption-at-rest? cockroachdb/cockroach#98051 has the potential to slow `Remove` FS calls and exacerbate the issue.

**Comment by nicktrav** [comment]
> Was the high goroutine count present with and without encryption-at-rest?

Correct. I saw it in both. The test run using a `master` binary doesn't seem to have this issue. It may take some time to manifest though.

**Comment by bananabrick** [comment]
>When a compaction completes, it puts the files that need to be deleted in a queue (guarded by some mutex). Then a >second goroutine could pull from this queue in order to satisfy the deleting pacing constraints.

We already have this queue, `versionSet.obsoleteTables`.

Currently, compactions will wait for file deletions to complete: https://github.com/cockroachdb/pebble/blob/master/compaction.go#L2534, but we probably don't need that behaviour.

**Comment by jbowens** [comment]
This was resolved in #2641.
