### ISSUE TITLE
make generate is stale

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/pebble#2383]
One problem is https://github.com/cockroachdb/pebble/pull/1752#issuecomment-1448246697

The other problem is that generation of test fixtures is non-deterministic (and in some cases, the generated fixtures cause test failures).

**Comment by RaduBerinde** [comment]
Some notes:

- find-db test database
  * output is not deterministic
  * sometimes an SST is archived, sometimes it isn’t
  * differences can cause subsequent test failures

- should we find a way to make it deterministic?

- shouldn’t CI verify that make generate is a no-op? (at least for generated code files)
  * go-linux CI job runs make test generate  If it ran make generate test it would fail

- for non-deterministic test files, should we stop using go:generate and add a separate make target?

**Comment by jbowens** [comment]
@RaduBerinde I moved this into in progress, but if you're not actively working on it feel free to move it into backlog.
