### ISSUE TITLE
db: nondeterminism in file nums when ingesting as flushable

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#2387]
When ingesting tables as flushables (i.e. when there is overlap between the ingested tables and the memtable), I noticed that there is non-determinism in the generated file numbers of the WAL and the flushed memtable.

The following is a minimal diff that should reproduce the issue. This test just sets up a memtable with two keys, and then attempts to ingest two tables that both overlap with the memtable.

```diff
diff --git a/metrics_test.go b/metrics_test.go
index e10c044d..6e4fd766 100644
--- a/metrics_test.go
+++ b/metrics_test.go
@@ -142,6 +142,12 @@ func TestMetrics(t *testing.T) {
                        b.Commit(nil)
                        return ""

+               case "build":
+                       if err := runBuildCmd(td, d, d.opts.FS); err != nil {
+                               return err.Error()
+                       }
+                       return ""
+
                case "compact":
                        if err := runCompactCmd(td, d); err != nil {
                                return err.Error()
@@ -162,6 +168,12 @@ func TestMetrics(t *testing.T) {
                        d.mu.Unlock()
                        return s

+               case "ingest":
+                       if err := runIngestCmd(td, d, d.opts.FS); err != nil {
+                               return err.Error()
+                       }
+                       return ""
+
                case "iter-close":
                        if len(td.CmdArgs) != 1 {
                                return "iter-close <name>"
diff --git a/testdata/metrics b/testdata/metrics
index 147cdbce..bb11b269 100644
--- a/testdata/metrics
+++ b/testdata/metrics
@@ -296,3 +296,31 @@ block bytes written:
       4          0 B          0 B
       5          0 B          0 B
       6        143 B         41 B
+
+batch
+set d d
+set e e
+----
+
+build ext1.sst
+set d d
+----
+
+build ext2.sst
+set e e
+----
+
+ingest ext1.sst ext2.sst
+----
+
+flush
+----
+0.1:
+  000015:[d#12,SET-d#12,SET]
+  000016:[e#13,SET-e#13,SET]
+0.0:
+  000019:[d#10,SET-e#11,SET]
+6:
+  000008:[a#0,SET-b#0,SET]
+  000013:[c@20#0,SET-c@16#0,SET]
+  000014:[c@15#0,SET-c@14#0,SET]
```

I expect that both ingested tables are added as flushables, and are eventually added to the LSM. I see this, however, there is some non-determinism.

Run the following test a number of times to see differing file nums assigned to the flushed memtable:

```
$ go test -run '^TestMetrics$' -count 10 .
--- FAIL: TestMetrics (0.01s)
    metrics_test.go:135:
        testdata/metrics:316:

        output didn't match expected:
        @@ -1,10 +1,10 @@
         0.1:
           000015:[d#12,SET-d#12,SET]
           000016:[e#13,SET-e#13,SET]
         0.0:
        -  000019:[d#10,SET-e#11,SET]
        +  000020:[d#10,SET-e#11,SET]
         6:
           000008:[a#0,SET-b#0,SET]
           000013:[c@20#0,SET-c@16#0,SET]
           000014:[c@15#0,SET-c@14#0,SET]

FAIL
FAIL    github.com/cockroachdb/pebble   0.248s
FAIL
```

Comparing the outputs of the event logging, I see the following:

```
2023/03/08 14:44:22 [JOB 15] ingesting: sstable created 000015
2023/03/08 14:44:22 [JOB 15] ingesting: sstable created 000016
2023/03/08 14:44:22 [JOB 16] WAL created 000017 (recycled 000006)
2023/03/08 14:44:22 [JOB 17] WAL created 000018
2023/03/08 14:44:22 [JOB 15] ingested as flushable L-1:000015 (825 B), L-1:000016 (825 B)
2023/03/08 14:44:22 [JOB 18] flushing 1 memtable to L0
2023/03/08 14:44:22 [JOB 18] flushing: sstable created 000019
2023/03/08 14:44:22 [JOB 19] WAL created 000020
2023/03/08 14:44:22 [JOB 18] flushed 1 memtable to L0 [000019] (784 B), in 0.0s (0.0s total), output rate 2.9 M/s
2023/03/08 14:44:22 [JOB 20] flushing 1 memtable to L0
2023/03/08 14:44:22 [JOB 20] flushed 1 memtable to L0 [000015 000016] (1.6 K), in 0.0s (0.0s total), output rate 68 M/s
2023/03/08 14:44:22 [JOB 21] flushing 1 memtable to L0
2023/03/08 14:44:22 [JOB 21] flush error: pebble: empty table
```

Versus the following when the test fails:

```
2023/03/08 14:44:53 [JOB 15] ingesting: sstable created 000015
2023/03/08 14:44:53 [JOB 15] ingesting: sstable created 000016
2023/03/08 14:44:53 [JOB 16] WAL created 000017 (recycled 000006)
2023/03/08 14:44:53 [JOB 17] WAL created 000018
2023/03/08 14:44:53 [JOB 15] ingested as flushable L-1:000015 (825 B), L-1:000016 (825 B)
2023/03/08 14:44:53 [JOB 19] flushing 1 memtable to L0
2023/03/08 14:44:53 [JOB 19] flushing: sstable created 000020
2023/03/08 14:44:53 [JOB 18] WAL created 000019
2023/03/08 14:44:53 [JOB 19] flushed 1 memtable to L0 [000020] (784 B), in 0.0s (0.0s total), output rate 2.7 M/s
2023/03/08 14:44:53 [JOB 20] flushing 1 memtable to L0
2023/03/08 14:44:53 [JOB 20] flushed 1 memtable to L0 [000015 000016] (1.6 K), in 0.0s (0.0s total), output rate 69 M/s
2023/03/08 14:44:53 [JOB 21] flushing 1 memtable to L0
2023/03/08 14:44:53 [JOB 21] flush error: pebble: empty table
```

So it looks like there's nondeterminism in the table number assigned to the flushed memtable, and the  WAL for the new memtable.

Is this non-determinism expected? If it is, we should consider ways of eliminating it. If it isn't, this could be a subtle bug.

**Comment by bananabrick** [comment]
Going through the failure case:

```
2023/03/08 14:44:53 [JOB 15] ingesting: sstable created 000015
2023/03/08 14:44:53 [JOB 15] ingesting: sstable created 000016
2023/03/08 14:44:53 [JOB 16] WAL created 000017 (recycled 000006)
2023/03/08 14:44:53 [JOB 17] WAL created 000018
```

These are from the `handleIngestAsFlushable` step. We create a new WAL for the new mutable memtable, and a new wal for the flushable ingest. This is the same for both test runs.

It's a bit confusing because it seems like `d.recycleWAL` allocates its own jobID. Instead, we should pass in the `jobID` from the caller of `d.recycleWAL`.


This is where the difference is:
success:
```
2023/03/08 14:44:22 [JOB 18] flushing 1 memtable to L0
2023/03/08 14:44:22 [JOB 18] flushing: sstable created 000019
2023/03/08 14:44:22 [JOB 19] WAL created 000020
```

failed:
```
2023/03/08 14:44:53 [JOB 19] flushing 1 memtable to L0
2023/03/08 14:44:53 [JOB 19] flushing: sstable created 000020
2023/03/08 14:44:53 [JOB 18] WAL created 000019
```

It looks like the file numbers for the WAL and the sstable are swapped. Note that these jobs have different job ids, so I'm guessing it's a case of two goroutines allocating file numbers in different orders.

Note that when the file numbers for the sstable and the WAL are swapped, the job IDs are also swapped, which supports the theory that this is just two different goroutines executing in different ordered between the two runs.

This might not be a bug. The only thing I'm confused about is why we're arbitrarily rotating the WAL.

**Comment by bananabrick** [comment]
I see what's going on.

Basically, the `flush` command from the test calls `db.Flush` which will force WAL recycling by calling `makeRoomForWrite(nil)` and then it will call `maybeScheduleFlush`. But the `handleIngestAsFlushable` function also calls `maybeScheduleFlush`.

The order of operations in the test are:
ingest -> flush. So, the ingest step will calls `maybeScheduleFlush` and the `flush` step will call `makeRoomForWrite`(which rotates the WAL) and then `maybeScheduleFlush`.

So, we could have the flush happen first, or the WAL rotation happen first.

@nicktrav I think we can make the test pass by `setting d.mu.compact.flushing = true` at the top of the test. This will prevent background flushes from being scheduled. Then we can set `d.mu.compact.flushing = false` before the `flush` command in the test is executed.

**Comment by nicktrav** [comment]
Nice. That does the trick. Thanks!
