### ISSUE TITLE
Need help investigating errors on closing pebble DB

### ISSUE THREAD

**Issue by andrasbeni** [cockroachdb/pebble#2390]
In one of my tests, sometimes I get the following errors when I close the DB:
* `leaked iterators` or
* `leaked memtable reservation`

I was able to reproduce this with versions `v0.0.0-20221104214247-8dc60b62ebbf` and `v0.0.0-20230307175142-1c38c4cb89d4`.
I tied to figure out if there's an `Iterator` that I did not `Close()`, but have not found any. The second error is even more confusing to me.
How can I find what I'm doing wrong?

**Comment by jbowens** [comment]
Both errors are likely caused by leaking an `Iterator`. Unfortunately, we don't have any facilities to help debug this. #1597 would help, but we've never implemented it. I'd recommend instrumenting your code to track all your iterator opens and closes.

**Comment by andrasbeni** [comment]
Thanks
