### ISSUE TITLE
Unusually high CPU/Memory consumption in (*Fragmenter).flush

### ISSUE THREAD

**Issue by Denvormine** [cockroachdb/pebble#2415]
Hi!
We're experiencing quite unusual behavior In CPU/Memory consumption in our service that uses pebble as key-value store.

DB version: v0.0.0-20220729140737-245afda9c39f
DB opts:
```
opts.EventListener = pebble.MakeLoggingEventListener(logging.InitLogger("MAINDB"))
	opts.Merger = CustomMerger
	opts.L0CompactionThreshold = 2
	opts.L0StopWritesThreshold = 1000
	opts.LBaseMaxBytes = 64 << 20 // 64 Mb
	opts.MaxConcurrentCompactions = 3
	opts.MemTableSize = 64 << 20 // 64Mb
	opts.MemTableStopWritesThreshold = 4
	opts.Levels = []pebble.LevelOptions{{
		Compression:    pebble.DefaultCompression,
		TargetFileSize: 16 << 20, // 16 Mb
	}, {
		Compression:    pebble.DefaultCompression,
		TargetFileSize: 32 << 20, // 32 Mb
		FilterPolicy:   bloom.FilterPolicy(10),
	}, {
		Compression:    pebble.DefaultCompression,
		TargetFileSize: 64 << 20, // 64 Mb
		FilterPolicy:   bloom.FilterPolicy(10),
	}, {
		Compression:    pebble.DefaultCompression,
		TargetFileSize: 128 << 20, // 128 Mb
		FilterPolicy:   bloom.FilterPolicy(10),
	}, {
		Compression:    pebble.DefaultCompression,
		TargetFileSize: 256 << 20, // 256 Mb
		FilterPolicy:   bloom.FilterPolicy(10),
	}, {
		Compression:    pebble.DefaultCompression,
		TargetFileSize: 512 << 20, // 512 Mb
		FilterPolicy:   bloom.FilterPolicy(10),
	}, {
		Compression:    pebble.DefaultCompression,
		TargetFileSize: 1024 << 20, // 1 Gb
	}}
	opts.EnsureDefaults()
```

General Info about service: we can upload files to it, service will store file info, meta, and other information in pebble and store the file content on the HDD. We also can get information and content about files. File Key consists of namespace (string), UNIX timestamp, sequence number. We have goroutine that once per 1 second (not more then 1 at the time) starts scrub work that iterates over file keys and deletes them if UNIX timestamp is old enough. If file's timestamp is not old enough, then we jump to the next namespace (we have around 800 namespaces).

All write operations are logged and logs are stored in pebble. After receiving confirmation about successful replication of a file from the same service on the other node, those logs are deleted (quite a short lifespan).

Some info about load on the machine where this problem appears:
Around 1500 files are stored per day (about 100k in db).
Around 100 requests per day from users to get a file per.
Almost no deletions by scrub (around 50 files last month).

After service's start it has been working as expected for several weeks. Then day by day consumption of CPU/memory resources started to grow. Some time passed and there was a flush, after which consumption went back to normal, but quite a big chunk of memory wasn't released. Then 24 hours later Memory usage per operation started to grow rapidly, CPU was fine for 2-3 days. The service crashed (out of memory) and restarted 6 days after last flush. After restart CPU/memory levels were looking good, but the same pattern appears and it probably will crash after a week or so.
It appears that the more time passed since the last flush the more CPU/memory consumption will grow per operation.

Here's an image of CPU and memory consumption over a month of work.
![FullPicture](https://user-images.githubusercontent.com/50184325/227215035-c0e3e8d1-2a89-412b-94bc-7ae7c81f28c2.png)

What's interesting it the amount of memory allocations that can happen in a span of a minutes (8GB to 16GB):
![ZoomIn](https://user-images.githubusercontent.com/50184325/227215453-3fbd9537-0517-4ecf-b310-0b8da04167c8.png)

Metrics before db.Close (I can see nothing bad happening):
```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         2    35 M       -    34 M       -       -       -       -    35 M       -       -       -     1.0
      0         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      4         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      5         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      6         2    33 M       -   5.8 M     0 B       0     0 B       0    33 M       2    34 M       1     5.7
  total         2    33 M       -    35 M     0 B       0     0 B       0    68 M       2    34 M       1     2.0
  flush         0
compact         1     0 B   5.8 M       0          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype         1       0       0       0       0       0       0  (default, delete, elision, move, read, rewrite, multi-level)
 memtbl         2    64 M
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache         0     0 B    0.2%  (score == hit-rate)
 tcache         2   1.3 K  100.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers         0
 filter         -       -    0.0%  (score == utility)
```

I tried to analyze heap and it seems that getting file info (3 Gets to pebble) causes all the high consumption problems. Interesting thing is that there's 2 hot places where we're getting a lot of data: scrub (check-n-delete file) and StoreFileAt operation (part of storing file from request) and they appear differently on different heap snapshots. Sometimes it's 99% from scrub, the other times it's 99% from StoreFileAt, (Just 1 time a catched a moment where they were both on the top of heap). Here are some examples (only links because images are quite long):

https://user-images.githubusercontent.com/50184325/227242291-5c38ca9f-3c50-4649-a908-6eb396641684.png
https://user-images.githubusercontent.com/50184325/227242310-fe8bc3e5-b871-4ad7-9d0a-7f035c4e2d5c.png
https://user-images.githubusercontent.com/50184325/227242335-4a2d13c8-6d5a-4ad2-9278-12ac8a001d21.png
https://user-images.githubusercontent.com/50184325/227242363-d02cd5b3-9e6d-41af-b573-fa78add5bc54.png
https://user-images.githubusercontent.com/50184325/227242447-2a46fd81-46d9-4092-9d0c-8c4adce5ce58.png

Here're examples of heap (alloc_space) and cpu usage for 30 seconds:

https://user-images.githubusercontent.com/50184325/227243119-4c7c5c21-57a8-476d-88cd-2eb0fb9a9fcc.png
https://user-images.githubusercontent.com/50184325/227243158-6e5e2c93-05ca-424b-a02e-be88df723012.png

I ran a test with 2 services for 2 days with 200 uploads per second, but there was no problem (1GB memory peak, 200MB after uploads ended). 35 million files are uploaded in a span of a 2 days. Then I started uploading files with 1rps and memory usage started to grow, after a few days it went from 200mb to 600-800mb. The same pattern, but not such severe, appears here as well:

https://user-images.githubusercontent.com/50184325/227242813-9b040e9d-0a80-4ecd-81f0-f20514fb5cd6.png

It seems like with more load there're less problems with memory.

Can you please tell me where should I look or what can be the cause of such (*Fragmenter).flush heap memory allocations? I checked every corner and I didn't find any place where there can be unclosed snapshot/iterator. We had this problem before (it's fixed), but there were metrics with 5k (more or less) open snapshots and several zombie memtabls and tables before db.Close.

**Comment by jbowens** [comment]
Some questions:
1. Are you frequently writing range tombstones (eg, `DeleteRange`) or range keys (`RangeKeySet`)?
2. By "flush" are you referring to a Pebble-initiated memtable flush, or are you referring to an application-level mechanism that commits a `pebble.Batch` that's been accumulating data?
3. When you use `Batch.Get`, are you sure you're closing the `io.Closer` returned from `Get`?

**Comment by Denvormine** [comment]
1. Only DeleteRange. We have a sequence log, starting from stored initSeqNum (0 at the first start) to lastSeqNum. And each time we get a confirmation, we delete range (about 3-4 actual not deleted before entries). BUT it performed via db.DeleteRange(initSeqNum, lastSeqNum) every time. This might be the problem in case when there can be multiple tombstones placed for the same key. But is it?
2. Pebble-initiated memtable flush. (It happend only once, service usually crashes before able to do flush)
3. I checked the same places multiple times and found nothing wrong. I'll try to check them some more time. The only thing that I can say for sure that we don't close Batch that is used in scrub iteration operation (it will be fixed in the next release, but yet to be deployed).

One interesting thing: I copied and opened that database from prod and flush+compaction started, memory usage skyrocketed to 9GB, stayed the same until applying some load, then it went down to 2GB and then to 200MB.

**Comment by nicktrav** [comment]
I see the version of Pebble you're running is quite old (July of 2022). Is it possible for you to retry with a more recent version?

**Comment by Denvormine** [comment]
I'll try to bump pebble version as well as closing batch and changing DeleteRange. But is this problem happening only because of tombstones?

**Comment by jbowens** [comment]
> This might be the problem in case when there can be multiple tombstones placed for the same key. But is it?

Yeah, this is the problem.

Range tombstones can overlap each other arbitrarily. This makes seeking among range tombstones at read time difficult, so Pebble 'fragments' the tombstones at overlap points when writing them to sstables. 

Consider writing three `DeleteRange`s  in succession: `[a,b)`, `[a,c)` and `[a,d)`. Each range tombstone is given its own monotonically increasing sequence number, used internally to determine its ordering in history: `[a,b)#1`, `[a,c)#2` and `[a,d)#3` (where `#n` denotes the sequence number). When writing them to sstables, Pebble will "fragment" these tombstones into _six_ fragments: `[a,b)#1`, `[a,b)#2`, `[a,b)#3`, `[b,c)#2`, `[b,c)#3`, `[c,d)#3`. Normally during a flush or compaction, only the most recent fragment for a particular keyspan survives unless a snapshot is open and requires that we preserve history farther back.

A memtable is append-only. If a new `DeleteRange` is written to the memtable, the subsequent read will fragment all the range tombstones in the memtable. If you're repeatedly overlapping previously written range tombstones, this fragmentation becomes quadratic.

I have a few suggestions:
1. If you write non-overlapping range tombstones, `DeleteRange(previousLastSeqNum, lastSeqNum)`, you'll avoid the quadratic explosion in range tombstone fragments in the memtable.
2. There's a setting [`Options.Experimental.FlushDelayDeleteRange`](https://github.com/cockroachdb/pebble/blob/e917c847dc4bb1dbf3f094d41aa3eb95526a00f3/options.go#L652-L656) that  forces a flush _N_ duration after a `DeleteRange` is committed, if one doesn't occur before then. Flushing the memtable early allows Pebble to drop unnecessary range tombstone fragments before they're allowed to accumulate.
3. You may find that a smaller `MemTableSize` is better for a queue-like workload. Since memtables are append-only, a large `MemTableSize` allows a large prefix of uncompacted garbage to accumulate. This garbage can slow scans which need to skip over the uncompacted garbage to get to the first live key.
4. `DeleteRange` is intended for large, infrequent deletes. In some places in CockroachDB, we use a heuristic that individually `Delete`s keys unless there's at least 64 consecutive keys. If some of the above approaches to this problem aren't workable for some reason, you may find better performance by iterating and individually deleting keys.

**Comment by Denvormine** [comment]
Yep, Thank you very much for answering! I'll make some changes to the code and keep you updated.

**Comment by jbowens** [comment]
@Denvormine I'm closing this out, but please feel free to re-open if your issue is unresolved.
