### ISSUE TITLE
compile error, cannot use v (type *io_prometheus_client.MetricFamily) as type protoreflect.ProtoMessage

### ISSUE THREAD

**Issue by ericjing83** [cockroachdb/pebble#2452]
dear sir,

I try to compile the hello world demo, but failed :
Could you help me to fix below error msg? Thanks~

# github.com/prometheus/common/expfmt
..\github.com\prometheus\common\expfmt\decode.go:89:34: cannot use v (type *io_prometheus_client.MetricFamily) as type protoreflect.ProtoMessage in argument to pbutil.ReadDelimited:
 *io_prometheus_client.MetricFamily does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
..\github.com\prometheus\common\expfmt\encode.go:120:36: cannot use v (type *io_prometheus_client.MetricFamily) as type protoreflect.ProtoMessage in argument to pbutil.WriteDelimited:
 *io_prometheus_client.MetricFamily does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
# github.com/cockroachdb/pebble/vfs

<quote>
func main() {
 var err error
 o := &pebble.Options{}
 db, err := pebble.Open("./demo", o)
 if err != nil {
  fmt.Println(err)
  return
 }
 key := []byte("hello")
 err = db.Set(key,[]byte("world"), nil)
 if err != nil {
  fmt.Println(err)
  return
 }
 res,closer, err := db.Get(key)
 if err != nil {
  fmt.Println(err)
  return
 }
 fmt.Println("res=",string(res))
 err = closer.Close()
 if err != nil {
  fmt.Println(err)
  return
 }
 fmt.Println("closer success")
}
<unquote>

**Comment by nicktrav** [comment]
With a fresh directory, and mod file, your demo works just fine. For example:

```bash
rm -rf test
mkdir test
pushd test
go mod init test
cat <<-HERE > main.go
package main

import (
	"fmt"

	"github.com/cockroachdb/pebble"
)

func main() {
	var err error
	o := &pebble.Options{}
	db, err := pebble.Open("./demo", o)
	if err != nil {
		fmt.Println(err)
		return
	}
	key := []byte("hello")
	err = db.Set(key, []byte("world"), nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	res, closer, err := db.Get(key)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println("res=", string(res))
	err = closer.Close()
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println("closer success")
}
HERE
go get ./...
go run main.go
popd
```

Returns:

```
res= world
closer success
```

This is most likely an issue with dependencies.

Pebble has a dependency on `github.com/prometheus/client_model`, which declares `io_prometheus_client.MetricFamily`, and that seems incompatible with the version of `github.com/prometheus/common` that you're using.

I would suggest looking at your dependencies first. Could you try `go get ./...`.

**Comment by ericjing83** [comment]
thanks for your advice.
The Github is not very stable in China mainland, I install all the dependencies one by one manually. I'm a little bit overwhelmed.
Could you tell me how to download the historic version of github.com/prometheus/common?

**Comment by ericjing83** [comment]
Dear, 
Could you provide a link for me to download your version of github.com/prometheus/client_model and github.com/prometheus/common?

**Comment by ericjing83** [comment]
FYI, this is the result of go get:
PS D:\usr\local\gopath\src\testProject> go get ./...
# github.com/prometheus/common/expfmt
..\github.com\prometheus\common\expfmt\decode.go:89:39: cannot use v (variable of type *io_prometheus_client.MetricFamily) as type protoreflect.ProtoMessage in argument to pbutil.ReadDelimited:
        *io_prometheus_client.MetricFamily does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
..\github.com\prometheus\common\expfmt\encode.go:120:40: cannot use v (variable of type *io_prometheus_client.MetricFamily) as type protoreflect.ProtoMessage in argument to pbutil.WriteDelimited:
        *io_prometheus_client.MetricFamily does not implement protoreflect.ProtoMessage (missing ProtoReflect method)

**Comment by ericjing83** [comment]
I found that, there is a "Deprecation note" for github.com/prometheus/client_model, the last update was in 2022. May be this is the reason why it's incompatible with "common".

**Comment by ericjing83** [comment]
Dear nicktrav,
Could you help me?

**Comment by ericjing83** [comment]
Finally, it's fixed.

To share with you how I fix it. I open the go file where function "pbutil.WriteDelimited" and "pbutil.ReadDelimited" is defined, then I change the import from "google.golang.org/protobuf/proto" to "github.com/golang/protobuf/proto". Then,everything is ok.
So, it means the "github.com/prometheus/common" is calling the legacy version of protobuf instead of the one from google.

FYI:
Golang version: 1.19.8
Pebble version: the latest one
version of google.golang.org/protobuf/proto: the latest one

**Comment by nicktrav** [comment]
Glad you were able to work this out!
