### ISSUE TITLE
Atomic counter

### ISSUE THREAD

**Issue by cristaloleg** [cockroachdb/pebble#2469]
Hi, thanks for creating Pebble.

I got a case when I need something similar to Postgres `Serial` type. In other words, I need an auto-increment value that is unique and monotonically increasing (to use as an int64 ID for another system), scrolling through the API I haven't found anything similar.

Is there a way to get an auto-increment value or how to do this in Pebble? and if not is there a chance that it will be added?

Thanks!

**Comment by jbowens** [comment]
I recommend implementing this _above_ Pebble, using your own synchronization: for example, use an in-memory `atomic.Uint64` type and its `Add` method to increment to assign committing batches an ID to use.

**Comment by cristaloleg** [comment]
Well, yeah, can be done like that. Thanks.
