### ISSUE TITLE
search key with prefix + '*'

### ISSUE THREAD

**Issue by ericjing83** [cockroachdb/pebble#2470]
Hi,

I'm wondering, is it possible to get value from *db.get(prefix + '*'), while '*' means any number of byte slice?
I found that one of the solution is to use iter, define an iter with prefix(lower bound / upper bound), but it means a for loop is needed to scan the key/value pair in current db, how is the performance in this respect? May be this is not a good way to do keywords searching.
Is there any walk around to achieve this? Thanks.

**Comment by ericjing83** [comment]
I think the iter.next() with prefix will scan the key/value one by one, instead of doing a more efficient search based on b+tree. I'm i right?

**Comment by jbowens** [comment]
Please see [this example](https://pkg.go.dev/github.com/cockroachdb/pebble#example-Iterator-PrefixIteration) for prefix iteration.

> I think the iter.next() with prefix will scan the key/value one by one, instead of doing a more efficient search based on b+tree. I'm i right?

`iter.next` uses a heap to advance the next key/value pair. Pebble implements a [log-structured merge tree](https://en.wikipedia.org/wiki/Log-structured_merge-tree), which does not use a b+tree in its on-disk format.
