### ISSUE TITLE
sstable: remove unused Properties

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/pebble#2471]
The memory footprint of the `Properties` struct has been growing. It also includes a `LoadedMap` which is only used in `String()` (so doesn't seem essential). The memory footprint effects how many files we can cache since it is a field in `Reader`. There seem to be some fields we never use: ColumnFamily*, ExternalFormatVersion, FixedKeyLen, IndexKeyIsUserKey, IndexValueIsDeltaEncoded, OldestKeyTime, and could just ignore when parsing, and not bother writing them (for newer sstable versions).

There has also been some discussions on the effect on the sstable size (an sstable with a single DEL on a tiny key is 800+ bytes), so we may get some savings there too.

@jbowens

**Comment by nicktrav** [comment]
This might be a good candidate for our "LTS readiness" workstream in 23.2.

**Comment by jbowens** [comment]
Today unrecognized sstable properties are stashed in the `UserProperties` table. Maybe we should add a new option that allows configuring an allowlist of user-defined properties load into `UserProperties`. Then we can remove the fields from the `Properties` struct and update parsing logic to ignore and fields that are not in the struct and don't appear in the allowlist.

**Comment by jbowens** [comment]
Aggregating heap profiles from all 5 runs of the ycsb/F in a pebble nightly ycsb benchmark, properties-related allocations are prominent.

2nd highest:
```
      flat  flat%   sum%        cum   cum%
      ...
  37947316  3.18% 72.53%   37947316  3.18%  github.com/cockroachdb/pebble/sstable.(*Properties).saveUvarint (inline)
```

4th highest:
```
  14395206  1.21% 75.62%   38706085  3.24%  github.com/cockroachdb/pebble/sstable.(*Properties).load
```

7th highest:
```
  11992380  1.00% 78.94%   11992380  1.00%  github.com/cockroachdb/pebble/sstable.(*Properties).saveString (inline)
```

**Comment by sumeerbhola** [comment]
> Today unrecognized sstable properties are stashed in the UserProperties table. Maybe we should add a new option that allows configuring an allowlist of user-defined properties load into UserProperties.

@jbowens The user-properties include block property collector names, which are user configurable. Instead of putting the burden on the user of Pebble, we should just create an internal deny list of things we are removing. Thoughts?

**Comment by jbowens** [comment]
I was thinking that we could avoid loading user-defined properties that are no longer used (eg, filters used by previous Cockroach table property filterers), but those should be very few. We do have the list of `Options.BlockPropertyCollectors` which we could automatically add to the allowlist.

I think a deny list is reasonable too.
