### ISSUE TITLE
Building cockroachDB from the source code

### ISSUE THREAD

**Issue by mariamalikorg** [cockroachdb/pebble#2472]
cockroach DB v22.2.28

go version go1.20.2 linux/amd64

I am trying to build the cockroachDB from the source code: https://github.com/cockroachdb/cockroach/tree/v22.2.8

make build and install complains:

cockroach/pkg/ui/workspaces/db-console/src/js/node_modules/protobufjs/src/namespace.js:307:25)
make: *** [Makefile:1360: pkg/ui/workspaces/db-console/src/js/protos.js] Error 1
make: *** Deleting file 'pkg/ui/workspaces/db-console/src/js/protos.js'
make: *** Waiting for unfinished jobs....
make: *** [Makefile:1354: pkg/ui/workspaces/db-console/ccl/src/js/protos.js] Error 1
make: *** Deleting file 'pkg/ui/workspaces/db-console/ccl/src/js/protos.js'

Any guidance on how to resolve this issue? Thank you

**Comment by jbowens** [comment]
Hi, this is the Pebble repository. If you need help with the Cockroach repository, please check out the [Cockroach wiki](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/overview?homepageId=56197319) or join the [Cockroach community slack](https://www.cockroachlabs.com/join-community/).
