### ISSUE TITLE
Building CockroachDB from source code - zstd and gcc version update

### ISSUE THREAD

**Issue by mariamalikorg** [cockroachdb/pebble#2510]
The goal is to update the zstd version that cockroachDB is using. Original zstd:v1.5.2 and in order to update to zstd:v1.5.5, we changed the DEPS.bzl to address this. 
Error generated as 
**"/tmp/rules_go_work-3919116952/cgo/github.com/DataDog/zstd/_x16.o: In function `HUF_decompress4X1_usingDTable_internal':
huf_decompress.c:(.text+0xaab6): undefined reference to `HUF_decompress4X1_usingDTable_internal_fast_asm_loop'
/tmp/rules_go_work-3919116952/cgo/github.com/DataDog/zstd/_x16.o: In function `HUF_decompress4X2_usingDTable_internal':
huf_decompress.c:(.text+0x191a9): undefined reference to `HUF_decompress4X2_usingDTable_internal_fast_asm_loop'
/home/ubuntu/.cache/bazel/_bazel_ubuntu/d700a5dbbcbcbf15a675b682db67c070/external/toolchain_cross_x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/6.5.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: /tmp/rules_go_work-3919116952/cgo/github.com/DataDog/zstd/_cgo_.o: hidden symbol `HUF_decompress4X2_usingDTable_internal_fast_asm_loop' isn't defined
/home/ubuntu/.cache/bazel/_bazel_ubuntu/d700a5dbbcbcbf15a675b682db67c070/external/toolchain_cross_x86_64-unknown-linux-gnu/bin/../lib/gcc/x86_64-unknown-linux-gnu/6.5.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: final link failed: Bad value
collect2: error: ld returned 1 exit status
compilepkg: error running subcommand external/toolchain_cross_x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-gcc: exit status 1
Target //pkg/cmd/cockroach:cockroach failed to build
Use --verbose_failures to see the command lines of failed build steps.
"**
I think this could be resolved by updating the GCC version. cockroachDBv22.2.8 from the source code using bazel has linked gcc v6.5.0. I think I have to update the repository.bzl file under build/toolchain

Is it the right direction and can you please help me understand how to address this issue? 
Thank you

**Comment by nicktrav** [comment]
This isn't related to Pebble.

As a starting point, please check out our [Getting and building CockroachDB from source page](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181338446/Getting+and+building+CockroachDB+from+source) or join the [Cockroach community slack](https://www.cockroachlabs.com/join-community/). If neither of those work, please open an issue on the [_Cockroach_ repo](https://github.com/cockroachdb/cockroach/issues/new/choose).
