### ISSUE TITLE
objstorage: read ahead is broken

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/pebble#2531]
The `readaheadState` in the vfs read handle is not being initialized properly, resulting in no "automatic" read-ahead functionality (read-ahead for compactions still works).

**Comment by nicktrav** [comment]
@jbowens @sumeerbhola - I recall we had a perf issue ~recently and we suspected readahead. Could this be related?

Or is this only due to recent changes to VFS related to objstorage refactorings, etc.

**Comment by jbowens** [comment]
If we're talking about the same issue, it was on 22.2 and we ended up suspecting that it was an issue of the OS page cache being trashed instead of loss of readahead.
