### ISSUE TITLE
investigate why metamorphic test failure wasn't posted to github

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/pebble#2576]
See failure here: https://github.com/cockroachdb/pebble/issues/2562

**Comment by itsbilal** [comment]
Dev-inf is looking at this. The underlying reason is that timeouts with stress don't produce an output xml file that state the failure, so the CI script finds nothing report-worthy.

**Comment by rickystewart** [comment]
I'm closing this in favor of cockroachdb/cockroach#104900.
