### ISSUE TITLE
metamorphic: prevent leaking of batch allocations

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/pebble#2579]
See: https://github.com/cockroachdb/pebble/blob/master/metamorphic/generator.go#L443. We call `g.batchClose` when we commit a batch, but we don't add a `closeOp` for the batch. Because of this, while the batch is removed from the `generator`, we never call `batch.Close` on it. If we don't call `batch.Close` on a batch, we don't call `batch.release` on it, and if `batch.release` isn't called, we don't add the batch back to the sync.Pool.

This is a minor issue since the only consequence is that we're allocating more batches than necessary in the metamorphic test.

**Comment by jbowens** [comment]
Fixing this will also improve our test coverage for resetting batches. Bugs can accidentally leak batch data across uses if not properly cleared.
