### ISSUE TITLE
stable versions

### ISSUE THREAD

**Issue by newhook** [cockroachdb/pebble#2587]
Hey folks, we've started to use pebble as a replacement for the original go leveldb package. One issue is knowing what represents a stable release since there are no tagged versions. I see from earlier issues that using the crl-release-* branches was the recommendation. Is that still the case? Did you consider instead having tagged semver releases?

**Comment by nicktrav** [comment]
This is something we're going to take on for the Cockroach 23.2 release cycle (Fall '23). Stay tuned!

See also #1064.

**Comment by martinarisk** [comment]
I would like stable tag too

**Comment by RaduBerinde** [comment]
I just tagged a `v1.0.0` release with the version that is part of CockroachDB 23.1.12.

I plan to tag a `v1.1.0` release within the next months or so with the version that is part of CockroachDB 23.2.0 or .1.

Next version will be `v2.0.0` and will correspond to CockroachDB 24.1. This version will no longer support older formats (including RocksDB and LevelDB).
