### ISSUE TITLE
How to change the Blocksize in Cockroach using pebble

### ISSUE THREAD

**Issue by mariamalikorg** [cockroachdb/pebble#2588]
I will start the CockroachDB server node with the specified configuration. After examining the source code, it appears that the block size is set to a default value of 4k. My question is, how can I modify the block size value? 

I am changing the value of Blocksize as follows
command: ./cockroach start-single-node --insecure --cache=.25 --max-sql-memory=.25 --store="cockroach-data,pebble=[Level \"6\"] compression=ZSTD  [BlockSize \"16384\"]" --enterprise-encryption=path=cockroach-data,key=aes-256.key,old-key=plain --advertise-addr=x.x.x.x --background

Can you help confirm if it's the right way? Thank you

**Comment by jbowens** [comment]
> After examining the source code, it appears that the block size is set to a default value of 4k

In CockroachDB, the block size defaults to 32 KiB: https://github.com/cockroachdb/cockroach/blob/76c337ae9d684206de00f9f655d4cea007e30794/pkg/storage/pebble.go#L616-L626

> I am changing the value of Blocksize as follows
> ```
> command: ./cockroach start-single-node --insecure --cache=.25 --max-sql-memory=.25 --store="cockroach-data,pebble=[Level "6"] compression=ZSTD [BlockSize "16384"]" --enterprise-encryption=path=cockroach-data,key=aes-256.key,old-key=plain --advertise-addr=x.x.x.x --background
```
I think you want something more like:
```
./cockroach start-single-node --insecure --cache=.25 --max-sql-memory=.25 --store='cockroach-data,pebble=[Level "6"] compression=ZSTD block_size=16384' --enterprise-encryption=path=cockroach-data,key=aes-256.key,old-key=plain --advertise-addr=x.x.x.x --background
```
Note that the above should only change the block size for L6. You can check the OPTIONS file in the store directory to check the options actually used by Pebble.
