### ISSUE TITLE
ingest: Add invariant-gated checks for accurate use of virtual sstable bounds

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#2593]
When #2538 merges, we will be synthesizing file bounds for virtual sstables that got keys masked through an Excise. And when #2582 merges, we'll be doing the same for sstables split by virtualizations We should add invariants.Enabled-gated checks to ensure that iterators created on top of virtual sstables do not return excised/masked keys, and that every key returned is within {Smallest,Largest}{PointKey,RangeKey}. We should also confirm if the bounds were calculated correctly to begin with.

After #2616 is complete, this issue only refers to verifying the tight calculation of sstable bounds, i.e. that there is a user key at each of the Smallest, Largest bounds. This check can happen in `fileManifest.ValidateVirtual`, however it would require creating iterators and is hence best to be invariants-gated as well.

**Comment by RahulAggarwal1016** [comment]
Fixed with https://github.com/cockroachdb/pebble/pull/2698
