### ISSUE TITLE
tool: enhance `{db,sstable} check` commands

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#264]
`{db,sstable} check` should check for misordered keys. `db check` should also open each sstable and run `sstable check` as the DB-level iteration can skip over sstables due to the presence of range tombstones.

**Comment by sumeerbhola** [comment]
Is the remaining work on this a duplicate of #366 which is already fixed?

**Comment by petermattis** [comment]
> Is the remaining work on this a duplicate of #366 which is already fixed?

Does `DB.CheckLevels` verify the keys in each sstable are in sorted order? I'm not sure if it should, but if it doesn't we should document the difference between `db check` and `sstable check *.sst` and that both are useful to run.

**Comment by petermattis** [comment]
Another interesting gap in the `check` functionality is that it doesn't perform MERGE record processing. We recently encountered a bug in CockroachDB in which corrupted data in a MERGE record could be reproduced by a simple scan of the keys. That is `db scan` would reveal the corruption, while the existing `db check` did not. Perhaps `db check` should also perform a `db scan` but omit printing the keys/values. That will slow it down a lot for large databases, though.

**Comment by rohansuri** [comment]
@petermattis I'll start work on this.

Some questions:
1) `sstable check` [currently](https://github.com/cockroachdb/pebble/blob/master/tool/sstable.go#L170) only verifies point key order. Should we add verification of range delete keys too? (in both `db, sstable check`).

2) Could you give an example/link the issue of the corruption with regard to MERGE records?

3) I see that `db scan` performs MERGE record processing in [`Iterator.mergeNext`](https://github.com/cockroachdb/pebble/blob/master/iterator.go#L221). However it'll do that only if the latest occurrences of a given user key are MERGE records.
  For example,
    ```
    a.MERGE.4:a4
    a.SET.3:a3
    a.MERGE.2:a2
    a.SET.1:a1
    ```
    `a@4` and `a@3` will be processed and value "a3a4" will be produced. However, `Iterator` will [skip](https://github.com/cockroachdb/pebble/blob/master/iterator.go#L114) over all other versions (2, 1) of `a` until it gets a new user key. Hence MERGE record at seqNum=2 will never be processed.
  Do we want the same behaviour in `db check` or do we want to process all MERGE records, even the ones that are succeeded by non-MERGE records?

As for the implementation I think we can do the existing checks and newer checks in a single pass without needing to invoke `db scan` or `sstable check` individually. Let me attempt that.

**Comment by petermattis** [comment]
> sstable check currently only verifies point key order. Should we add verification of range delete keys too? (in both db, sstable check).

Changed range delete keys is slightly involved as RocksDB doesn't guarantee any ordering on the range delete keys stored on disk. See [`sstable.Reader.transformRangeDelV1`](https://github.com/cockroachdb/pebble/blob/master/sstable/reader.go#L1189) for the code which handles this. It would be nice to check for `rangeDelV2` format range delete blocks, but I'm fine if this is a TODO for the future.

> Could you give an example/link the issue of the corruption with regard to MERGE records?

https://github.com/cockroachdb/cockroach/issues/43541#issuecomment-579038518. Essentially, it looks like there was a bit flip in the data that prevented the merge operator from succeeding. The interesting part from the `db check` tools perspective is that the user specified merge operator may do additional checking of data that seems reasonable to Pebble.

> Do we want the same behaviour in db check or do we want to process all MERGE records, even the ones that are succeeded by non-MERGE records?

It would be desirable to check all merge records if possible because it could help identify corruption that was seen in the past but no longer visible in the current state. You'd want to do something where a contiguous range of merge records are passed to the merge operator. 

> As for the implementation I think we can do the existing checks and newer checks in a single pass without needing to invoke db scan or sstable check individually. Let me attempt that.

Thumbs up to that approach. Definitely nice to not have to scan over all of the data twice.

**Comment by petermattis** [comment]
#544 fixed the remaining TODOs here.
