### ISSUE TITLE
db: disable delete pacing during open

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/pebble#2667]
Currently we delete any obsolete files during Open and wait for that cleanup to continue. We should disable delete pacing, at this point as there is no foreground traffic to disrupt; we are just blocking startup.

**Comment by jbowens** [comment]
Nice find

**Comment by RaduBerinde** [comment]
Ah, I think I'm wrong.. I forgot we pace in a separate goroutine and don't wait for it, so the paced deletions would happen asynchronously and won't block Open. Closing.
