### ISSUE TITLE
db: nil pointer with ExperimentalFormatVirtualSSTables

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2690]
When running the metamorphic tests allowing format major versions to ratchet up to `ExperimentalFormatVirtualSSTables`, I've observed nil pointers in the levelIter.

**Comment by bananabrick** [comment]
I believe we're allowing format major versions to ratchet up to `ExperimentalFormatVirtualSSTables` in the metamorphic test now, and there were no failures in the nightly stress test from yesterday. Going to close this out.
