### ISSUE TITLE
TestCompactionPickerScores flakes occasionally

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/pebble#2703]
TestCompactionPickerScores flakes occasionally, with below error:

```
--- FAIL: TestCompactionPickerScores (0.02s)
    datadriven.go:143: 
        testdata/compaction_picker_scores:142:
         000005
        output didn't match expected:
        @@ -1,6 +1,2 @@
        -num-entries: 5
        -num-deletions: 5
        -num-range-key-sets: 0
        -point-deletions-bytes-estimate: 164586
        -range-deletions-bytes-estimate: 0
        +(not found)
```

Above flaked on https://github.com/cockroachdb/pebble/pull/2694. It's unlikely that the cause was changes made in the PR, since the changes in the PR were in the metamorphic testing suite.

https://github.com/cockroachdb/pebble/actions/runs/5424471226/jobs/9863874389?pr=2694

@jbowens tried to repro:

```
21942 runs so far, 0 failures, over 10m55s
```

**Comment by joshimhoff** [comment]
[logs_5776.zip](https://github.com/cockroachdb/pebble/files/11919153/logs_5776.zip)

**Comment by msbutler** [comment]
just saw this here https://github.com/cockroachdb/pebble/actions/runs/5425467296/jobs/9866246987?pr=2702
