### ISSUE TITLE
metamorphic: don't skip DB restarts in case shared storage is enabled

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/pebble#2717]
https://github.com/cockroachdb/pebble/pull/2694 added metamorphic testing of shared storage + the secondary cache. The test sometimes failed like this:

```
--- FAIL: TestMeta (12.59s)
    --- FAIL: TestMeta/execution (0.00s)
        --- FAIL: TestMeta/execution/random-008 (0.52s)
            meta.go:208: 
                ===== SEED =====
                1688998824586968860
                ===== ERR =====
                exit status 1
                ===== OUT =====
                Seed: 0
                dbRestartOp: open _meta/230710-142024.5874202807356/random-008/data/000059.sst: file does not exist
```

So that PR was adjusted to NOT do DB restarts in case shared storage is enabled.

We should fix whatever bug is causing the above test failure & then enable DB restarts (in case shared storage is enabled).

**Comment by itsbilal** [comment]
Took a quick look, this is because the flushable ingest code is not written with the provider in mind, and tries to resolve pathnames to SSTs referenced in the WAL as local SSTs.
