### ISSUE TITLE
sstable ingestion can lead to duplicate keys

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#272]
`sstable/Writer.Add` allows adding multiple keys to the same sstable with the same user-key and different seqnums. This functionality is required by compactions in order to store multiple versions of a user-key. However, if such an sstable is ingested it is given a global seqnum and all of those multiple versions of the key now look like duplicates. Not good. At the very least, this will likely run afoul of key ordering invariants when this table is compacted.

One possibility is to hide `sstable/Writer.Add` from external usage, and only expose `sstable/Writer.{Set,Merge,Delete,DeleteRange}` which do not allow specifying a seqnum.

**Comment by petermattis** [comment]
Pebble is missing a check during ingestion which RocksDB has: when ingesting a file we generate the `FileMetadata` by opening the sstable and seeking to the first and last keys. If either key contains a non-zero seqnum the ingestion errors out.

**Comment by sumeerbhola** [comment]
iiuc, the sstable iterator code will ignore these sequence numbers because we know it is an ingested file (SmallestSeqNum == LargestSeqNum in FileMetadata) so we will set the GlobalSeqNum override in the Reader. Is that correct? If so, this is just an extra defensive measure?

**Comment by petermattis** [comment]
The sstable.Iterator code will return duplicate internal keys, though. Consider what happens if we have an sstable with the keys `a#2` and `a#1`. We ingest this sstable and it gets a global sequence number of `10`. Now sstable.Iterator will return the keys `a#10` and `a#10` which will likely cause problems elsewhere in the system.
