### ISSUE TITLE
old files were not deleted when compaction completed

### ISSUE THREAD

**Issue by jimmyyan** [cockroachdb/pebble#2735]
when i dumped the manifest file, i found so many old files were deleted when compaction,but there were still remain on the disk,
who can tellme why this happened, is there any parameters should i set?

**Comment by jbowens** [comment]
Are you closing iterators appropriately? An open iterator reading from a particular LSM version will prevent all sstables that existed at that version from being deleted.

**Comment by jimmyyan** [comment]
THx，that's a clue for me to check the problem
