### ISSUE TITLE
Make batchMaxRetainedSize configurable

### ISSUE THREAD

**Issue by lahsivjar** [cockroachdb/pebble#2780]
I have a use case with pebble where the `pebble.Batch` size would usually be greater than `1 MB`. The current logic in pebble would GC the data held by the `pebble.Batch` if the data exceeds `1MB` ([ref](https://github.com/cockroachdb/pebble/blob/9c487492d79eae251864a428450306a7c0e3c602/batch.go#L1331-L1337)).

I was hoping that we can make the `batchMaxRetainedSize` configurable, what do others think about this? (If it sounds like a feasible idea I can create a PR).

**Comment by jbowens** [comment]
Hi @lahsivjar, yeah, I think it's feasible, at least for instances where `d.NewBatch` is used.

**Comment by lahsivjar** [comment]
👋 folks (@RaduBerinde @jbowens ), curious about the release schedule for this. I see that the latest releases are cut from a 1.1 branch so don't have this commit (or other commits), is there any plan for v2 release or is it possible to get this in the 1.x release?

**Comment by lahsivjar** [comment]
> I will need to add an upgrade command to v1 and you would need to use it to upgrade any old stores. Does that work?

That would be great and it does work for our use-cases 🙏

**Comment by RaduBerinde** [comment]
@lahsivjar I tagged a v2.0.0 release. Please check out the updated README around fomat versions and upgrading existing stores: https://github.com/cockroachdb/pebble/blob/8d697d1a30f28c4f1ccdf1ee508f7c02d1f7f181/README.md
