### ISSUE TITLE
metamorphic: Add support for EventuallyFileOnlySnapshots in metamorphic tests

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#2781]
A new type of snapshots, `EventuallyFileOnlySnapshots` were implemented in #2775. `EventuallyFileOnlySnapshots` retain the same guarantees as snapshots over the key-spans passed into them at creation time.

As part of this issue, we need to update Pebble metamorphic tests to add testing for EventuallyFileOnlySnapshots (EFOS). One way to do this is to have a test option that swaps the implementations of all snapshots with `EventuallyFileOnlySnapshot([]KeyRange{KeyMin-KeyMax})`. Another change would be to add support for creating / reading from EFOS as a toplevel object, and adding the relevant operations to open/close EFOS. The only challenge with this last part will be to ensure that iterators opened on an EFOS are scoped to just the keyranges passed in at creation time.

**Comment by jbowens** [comment]
> One way to do this is to have a test option that swaps the implementations of all snapshots with EventuallyFileOnlySnapshot([]KeyRange{KeyMin-KeyMax}).

It would be tricky, but for some sequences of operations performed against a snapshot, we could also compute a set of narrow keyspans that bound the keys observable by the snapshot. This won't always be possible but there are many ways in which the observable set of keys gets constrained:
* Iterator bounds
* -WithLimit positioning operations have consistent behavior up to the limit.
* SeekPrefixGEs are constrained to the prefix
* Seek operations are bounded by the seek key.
We could preprocess the operations to determine the bounds on the snapshots access and create EventuallyFileOnlySnapshots with the precomputed bounds.
