### ISSUE TITLE
Cockroach Pebble ZSTD compression mode

### ISSUE THREAD

**Issue by mariamalikorg** [cockroachdb/pebble#2830]
Can you please comment on the compression mode for ZSTD that ZSTD is utilizing in CockroachDB pebble? Is it operating in dictionary mode or LDM mode? I've noticed the GitHub repository [github.com/valyala/gozstd](https://github.com/DataDog/zstd that calls for the cgo implementation of ZSTD.

Thank you

**Comment by jbowens** [comment]
Hi, I'm not sure. We use DataDog/zstd in all real builds of Cockroach, using v1.4.5.
