### ISSUE TITLE
Windows CI out-of-memory

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2849]
```
2023-08-25T17:19:00.6769113Z runtime: VirtualAlloc of 2147483648 bytes failed with errno=1455
2023-08-25T17:19:00.6769214Z fatal error: out of memory
```
https://github.com/cockroachdb/pebble/actions/runs/5978602527/job/16221019736?pr=2845

**Comment by RaduBerinde** [comment]
On my linux system, running all tests shows 8GB max resident. The GH Actions runner has 7GB of RAM.

The failure is under `TestGetBytes` which is a very simple test which allocates a 2GB slice.

https://github.com/cockroachdb/pebble/blob/dac60ce1cd2ec1c28e6e071dee66ae625ab7d089/sstable/unsafe_test.go#L22
