### ISSUE TITLE
Use the CLI/cmd with a merge operator

### ISSUE THREAD

**Issue by anacrolix** [cockroachdb/pebble#2851]
How do I use cmd/pebble with a dir that I use a custom merge operator when interacting with the dir programmatically?

Jira issue: PEBBLE-86

**Comment by RaduBerinde** [comment]
In `cockroach`, we use the `pebble/tool` package and implement our own cmd:

https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/debug.go#L1412
