### ISSUE TITLE
Loading v23.2.0-alpha.00000000-4069-g0310d119569CC on disaggregated storage demo cluster has led to a crash loop

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/pebble#2894]
Rollout of `v23.2.0-alpha.00000000-4069-g0310d119569` on the CC disaggregated storage demo cluster has led to a crash loop.

```
ERROR: server startup failed: failed to start server: failed to create engines: pebble: could not open remote object catalog: pebble: error when loading remote object catalog file "REMOTE-OBJ-CATALOG-000035": version edit adds existing object 1503319
SQLSTATE: XX000
HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
Failed running "start"
```

Note that before I ran the rollout I replaced a node that was down for many days due to an unrelated infra issue with a new one. But that worked fine, and all nodes were healthy, until I updated the nodes to a new version. The new node updated first without any issues. The second node to update hit this crash loop. There are unavailable ranges, since the new node hadn’t finished rebalancing yet, but I don’t think think that is particularly interesting, as the new node plus the second node in a crash loop. 

Due to above, if we want to fix the existing cluster, we need to load a fix. If we clear the crashing node, we would lose data, since we only have two copies of it, due to the first node replacement being done right before the second node crashed.

**Comment by RaduBerinde** [comment]
The initial code around the catalog accidentally, when it rotates the catalog file, appends the last update to the already up-to-date state. This was fine (a no-op) but fails some debug assertions in newer builds. I will move the assertions to `invariants` for now.
