### ISSUE TITLE
metamorphic: increase number of key versions to exercise restart code in nextPrefixV3

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/pebble#2921]
The code in https://github.com/cockroachdb/pebble/blob/f509cd48c70c622238091f02b9e04be5cf108797/sstable/block.go#L1262-L1319 is not exercised in the metamorphic test.

For example, see the coverage in https://storage.googleapis.com/crl-codecover-public/pebble/2023-09-20%2008:16Z%20f509cd48%20-%20meta%20test%20only/pebble/sstable/block.go.gcov.html

**Comment by jbowens** [comment]
This is a bit tricky to exercise. Even if very strongly prefer generating keys that are versions of existing of prefixes, it's relatively unlikely that we'll get a large enough swath of SETs of keys with the same prefix in the same SST. We exercise DELs and DeleteRanges so frequently that we tend to produce relatively small databases. I'm going to play with changing the operation weights in some runs and see if that combined with increasing the number of versions we write does the trick.
