### ISSUE TITLE
arenaskl: forget to check negative index, may lead to panic.

### ISSUE THREAD

**Issue by al8n** [cockroachdb/pebble#2923]
Hi, I am confused about these two lines.
```go
n := int32(nd.keySize) - 8
cmp := s.cmp(ndKey[:n], key.UserKey)
```
What if `nd.KeySize` is less than `8` (The size of the trailer)? Then, the `ndKey[:n]` will panic. Although I think when encoding the `InternalKey`, a trailer will always be encoded, `n` cannot be negative in this case. But what I need clarification is the following lines of code. Based on the above assumption, the `else` branch will never be executed. Please correct me if I am wrong.

```go
if n >= 0 {
        ndTrailer = binary.LittleEndian.Uint64(ndKey[n:])
} else {
        ndTrailer = uint64(base.InternalKeyKindInvalid)
}
```

Here is the source code of the full function:

```go
func (s *Skiplist) keyIsAfterNode(nd *node, key base.InternalKey) bool {
	ndKey := s.arena.buf[nd.keyOffset : nd.keyOffset+nd.keySize]
	n := int32(nd.keySize) - 8
	cmp := s.cmp(ndKey[:n], key.UserKey)
	if cmp < 0 {
		return true
	}
	if cmp > 0 {
		return false
	}
	// User-key equality.
	var ndTrailer uint64
	if n >= 0 {
		ndTrailer = binary.LittleEndian.Uint64(ndKey[n:])
	} else {
		ndTrailer = uint64(base.InternalKeyKindInvalid)
	}
	if key.Trailer == ndTrailer {
		// Internal key equality.
		return false
	}
	return key.Trailer < ndTrailer
}
```

**Comment by jbowens** [comment]
Yeah, that's correct. I believe that else branch was purely defensive in the case of in-memory corruption. On the current `master` branch, this code is adapted and the Trailer is no longer encoded at `keyOffset`, and is instead embedded directly on the `arenaskl.node`.

**Comment by al8n** [comment]
> Yeah, that's correct. I believe that else branch was purely defensive in the case of in-memory corruption. On the current `master` branch, this code is adapted and the Trailer is no longer encoded at `keyOffset`, and is instead embedded directly on the `arenaskl.node`.

Thank you! 

I looked through the code in master, and found that the `nodeAlignment` is not change, still `4`. But now, the `node` struct has a uint64, should the `nodeAlignment` be changed to `8`?

**Comment by jbowens** [comment]
The nodes need to be aligned at 4-byte offsets because we use 32-bit atomics. The existence of a uint64 does not change that.

Closing this out because I don’t think anything here is actionable.
