### ISSUE TITLE
TypeField or Method Missing y.lockedFiles.Swap undefined (type sync.Map has no field or method Swap)

### ISSUE THREAD

**Issue by Akhilesh53** [cockroachdb/pebble#2954]
I am getting this error while initializing pebble. What is the solution to this?

**Comment by jbowens** [comment]
You’ll need to upgrade to Go 1.20 or later.

**Comment by Akhilesh53** [comment]
Thanks. @jbowens This worked. But while inserting the directory in the below code, it is giving this error.

Code
```
func main() {
	db, err := pebble.Open("./db", &pebble.Options{FS: vfs.NewMem()})
	if err != nil {
		log.Fatal(err)
	}
	key := []byte("hello")
	if err := db.Set(key, []byte("world"), pebble.Sync); err != nil {
		log.Fatal(err)
	}
	value, closer, err := db.Get(key)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s %s\n", key, value)
	if err := closer.Close(); err != nil {
		log.Fatal(err)
	}
	if err := db.Close(); err != nil {
		log.Fatal(err)
	}
}
```

Error:

<img width="694" alt="image" src="https://github.com/cockroachdb/pebble/assets/64018679/504c26bb-fc11-4670-8e23-2670886c8081">

**Comment by jbowens** [comment]
The in-memory FS you're creating does not contain a directory "db". You need to create it first.

```
fs := vfs.NewMem()
if err := fs.MkdirAll("db", os.ModePerm); err != nil {
    log.Fatal(err)
}
db, err := pebble.Open("db", &pebble.Options{FS: fs})
```

Or just use the root directory so you don't need to create it.
```
	db, err := pebble.Open("", &pebble.Options{FS: vfs.NewMem()})
```

**Comment by Akhilesh53** [comment]
If I use the root directory, what is its location? In case I have to remove the previous files due to any reason. That would be helpful. @jbowens
