### ISSUE TITLE
"error in roaringArray.readFrom: did not find expected serialCookie in header"

### ISSUE THREAD

**Issue by Akhilesh53** [cockroachdb/pebble#2959]
Error is coming at line no 104. 

<img width="871" alt="image" src="https://github.com/RoaringBitmap/roaring/assets/64018679/b7ca3db9-8b09-4ac6-b876-aba0a7d5dcc9">

This is the func definition which is returning []byte from cockroach/pebble db. 

<img width="642" alt="image" src="https://github.com/RoaringBitmap/roaring/assets/64018679/ae1eec5c-a479-4f9e-99eb-b3eb5c294dcf">

The same error is occurring here too. 

<img width="1003" alt="Screenshot 2023-09-30 at 12 04 21 PM" src="https://github.com/RoaringBitmap/roaring/assets/64018679/123ad737-099c-4d19-837c-8f19ee62bc14">

Sending the values in the channel from here (see the below pic) :

<img width="870" alt="image" src="https://github.com/RoaringBitmap/roaring/assets/64018679/f29f8494-6905-465a-9b43-7e822f2be013">

This error occurs frequently, But the same did not happen while using Badger.
Please help me out. 
Please keep the comments section open so that I can ask any other doubts.

**Comment by jbowens** [comment]
This is not an error originating from Pebble, and we cannot help you debug your application.

**Comment by Akhilesh53** [comment]
Agreed. But we are fetching the data from Pebble only. The []byte coming in response, when we are trying to write it in a bitmap, is not finding the cookie header. I just want to understand if there is anything I am missing out on while setting and getting the values?
