### ISSUE TITLE
corruption error during scanReadTableStats does not contain the SST number

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/pebble#2976]
In scanReadTableStats, if `loadTableStats` hits an error, if it's a corruption error it will lead to a panic but there will be no information about which SST it is about. We should `Wrap` the error with more information.

**Comment by RaduBerinde** [comment]
See https://github.com/cockroachdb/pebble/pull/2633 for a similar fix (but I believe for a different code path).

**Comment by jbowens** [comment]
@RaduBerinde — this is still relevant and the relevant code path has not been fixed yet, right?

**Comment by RaduBerinde** [comment]
No, sorry, I was wrong, this should be covered by #2633 and its backports.
