### ISSUE TITLE
Particular use case, mainly read over remote machine, how to use with ssh 

### ISSUE THREAD

**Issue by fxfactorial** [cockroachdb/pebble#3047]
I'm using code which itself uses pebble. My use case is mainly read only at the moment, and a usecase came up to use a pebble db remotely. 

That is, what I'd love is some way to have pebble when given the dir string to `func Open(dirname string, opts *Options) (db *DB, _ error) {` for if dirname starts with `ssh` it should do ssh reads or provide some way for me to give that ability. 

Like how in emacs tramp mode, I can operate on files remotely if I start the path with `ssh:///home/linux_machine/blahblah/`

**Comment by jbowens** [comment]
Sorry, it's unlikely we'll ever support something of this nature because we have no use for it within CockroachDB.
