### ISSUE TITLE
internal/keyspan: refactor Truncate to not use filteringIter

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#3048]
Currently, `keyspan.Truncate` creates a `filteringIter` with a filter function. We uncovered a bug around certain uses of seeks in `filteringIter` in #3046 that forced us to add a check around Seek calls in the filteringIter, at the cost of one additional key comparison. If we refactored keyspan.Truncate to not use `filteringIter`, we could make that key comparison specific to just the `Truncate` case, and not other uses of `filteringIter` that don't mutate spans.

**Comment by RaduBerinde** [comment]
Fixed by #3282.
