### ISSUE TITLE
perf: add support for min_sync_wal_interval

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#309]
CockroachDB has its own WAL syncing loop which is parameterized with a `min_sync_wal_interval` setting which controls a minimum delay to insert in between WAL syncs. WAL syncs are the dominant source of IOPS on a CockroachDB node, and IOPS are expensive on AWS EBS and GCP Persistent disks. Recent experiments have shown that setting a small but non-zero `min_sync_wal_interval` can significantly reduce IOPS while having almost no effect on latency and throughput. 

In Pebble, the sync loop is called `record.LogWriter.flushLoop`. Inserting a minimum delay between loops should be trivial. The loop in CockroachDB is https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/rocksdb.go#L694-L744. See the parts involved with `minWALSyncInterval`.

**Comment by sumeerbhola** [comment]
some questions:
Are you suggesting that pebble not support an external SyncWAL() method and internally use such a parameter (that will delay when the write to pebble returns)?
Also I don't quite understand how SyncWAL() is working in the rocksdb context -- are we issuing writes that are returning before the WAL is synced? We then need to externally track which writes returned before the start of the SyncWAL() to know which have actually committed?

**Comment by petermattis** [comment]
> Are you suggesting that pebble not support an external SyncWAL() method and internally use such a parameter (that will delay when the write to pebble returns)?

Correct.

> Also I don't quite understand how SyncWAL() is working in the rocksdb context -- are we issuing writes that are returning before the WAL is synced? We then need to externally track which writes returned before the start of the SyncWAL() to know which have actually committed?

The RocksDB commit returns before the WAL has been synced, but we then block return of the CockroachDB-level commit of the batch until the sync occurs.

**Comment by sumeerbhola** [comment]
I am not quite understanding the details of the batch group stuff in rocksdb.go, hence the question.
So are we not in a situation where the interface of rocksdb.go is used in the following manner?
loop {
   write(batch);
}
wait for sync for all batches;

since in the above a higher write latency by changing the implementation of write(batch) to also do a sync would add the min sync latency to each write().

**Comment by petermattis** [comment]
> since in the above a higher write latency by changing the implementation of write(batch) to also do a sync would add the min sync latency to each write()

Hmm, I'm not understanding this question. Might be easier to talk through this in person.

**Comment by sumeerbhola** [comment]
(post conversation with @petermattis )
The caller of pebble will still be doing async writes, so there is no latency issue.
