### ISSUE TITLE
Is there any way to limit the compaction rate in pebbledb

### ISSUE THREAD

**Issue by fynnss** [cockroachdb/pebble#3105]
In our scenario, there is a substantial volume of write operations occurring within a short timeframe, followed by a period of no write activity but with ongoing read operations.

If background compaction is triggered, it introduces contention for both bandwidth and disk I/O, consequently impacting the behaviors of write and read operations. Therefore, we aspire to impose limitations on the speed/IO of background compaction, ensuring it executes slowly to prevent interference with foreground activities.

**Comment by jbowens** [comment]
The only knob for limiting compactions is the max compaction concurrency `Options.MaxCompactionConcurrency`. There are some related issues for addressing related concerns about compactions' impact on foreground traffic (and the inverse problem of fully utilizing the hardware for compactions when foreground traffic is light): #1329, #687, #766

One other knob that may be relevant is file deletion pacing. Once files are removed from the LSM by compactions and no longer in use, they're queued for deletion. By default there is no pacing of these deletions. File deletions can cause significant filesystem IO, so there's a mechanism to pace them. It's enabled when [`Options.TargetByteDeletionRate`](https://github.com/cockroachdb/pebble/blob/4cbc644681f22c02750590d98d626f63c88f18b8/options.go#L916-L928) is nonzero. The rate should be set to a rate that files can be deleted without considering pacing. If file deletions are queueing at a higher rate, pacing will delete at the rate they're queued but smoothed.

**Comment by Fynnss** [comment]
Hi, @jbowens, thank you for your reply.

After reviewing these issues, I noticed that there is currently no effective way to limit the rate of compaction. However, I found the parameter you mentioned, [Options.TargetByteDeletionRate](https://github.com/cockroachdb/pebble/blob/4cbc644681f22c02750590d98d626f63c88f18b8/options.go#L916-L928), interesting as it can result in a significant amount of IO. What value do you recommend for configuring this option?

Additionally, there is another option called ReadCompactionRate. It affects the frequency of compaction. If the value size increases and the read delay becomes higher, should this parameter also be increased to avoid frequent compactions?
