### ISSUE TITLE
replace uses of runtime.fastrand with math/rand/v2 once we require go 1.22

### ISSUE THREAD

**Issue by mvdan** [cockroachdb/pebble#3138]
https://github.com/cockroachdb/pebble/blob/dbeb05897e38d3bc81bda459ce5da01b370660a6/internal/fastrand/fastrand.go#L11

There's a public replacement in math/rand/v2 starting in the upcoming Go 1.22, and Go 1.24 will remove `runtime.fastrand`. See https://go-review.googlesource.com/c/go/+/548235.

You might want to wait until Go 1.22 or even 1.23 is out to do this; this issue is mainly a heads up and a reminder :)

Jira issue: PEBBLE-124

**Comment by RaduBerinde** [comment]
Fixed in #4016 and #4018
