### ISSUE TITLE
db:  manifest dump level info

### ISSUE THREAD

**Issue by leowkong** [cockroachdb/pebble#3165]
the opts parmeter which passed to the funciotn ` func Open(dirname string, opts *Options)`  has setted the opts.Levels values as nil , so I expect the level should only exists level0 . But when I run the  "pebble db dump manifest" , I got the dump file which contains L0-L6 files info.  So the default level num of pebble is 7? 
![image](https://github.com/cockroachdb/pebble/assets/101857651/ca39060d-186f-4c62-a726-531a4bd39e07)

**Comment by jbowens** [comment]
> So the default level num of pebble is 7?

Yes, Pebble always uses 7 levels, and the number of levels is unconfigurable. If you provide less than 7 levels in the `Options.Levels` slice, the last provided `LevelOptions` is used for all subsequent levels.

```
	// Per-level options. Options for at least one level must be specified. The
	// options for the last level are used for all subsequent levels.
	Levels []LevelOptions
```
