### ISSUE TITLE
SharedStorage design docs or examples

### ISSUE THREAD

**Issue by tylerwilliams** [cockroachdb/pebble#3177]
Hi, we currently use pebble on large NAS ssd-like drives. Have been watching the development of the SharedStorage feature with interest, but I'm having trouble getting a big picture description of how it's used and the tradeoffs involved outside of just reading the code.

Is there anything you can share here about this new addition, it's purpose, production readiness, performance, etc?

Thanks! (pebble rocks btw)

**Comment by RaduBerinde** [comment]
Hi,

Thanks for the interest. This feature is currently in development and is not ready to use. The goal is to be able to store SSTs on systems like S3, either permanently or temporarily. This can allow faster restores from backup, or faster rebalancing of ranges between cockroach nodes.

**Comment by jlewi** [comment]
There are a couple older issues regarding plans for an S3 backend (#640, #805). Does SharedStorage mean supporting object storage is now in the works?

I have the following use case. I'd like to be able to run a KV store API server that scales from 0 to 1. If Pebble can use an object store as a backend then this becomes very easy to implement.

**Comment by RaduBerinde** [comment]
We have the experimental ability to read and write sstables to S3, but the latencies are too high in practice to use directly and the per-IO pricing might also make it unfeasible. Unfortunately, for now, we don't have anything here that can be used in production.

**Comment by aep** [comment]
is this still the case? the remote storage code is still there.
This feels like it might be for backups?
versus having to download the whole pebble db before it can be used.

**Comment by RaduBerinde** [comment]
The code will be used for a new feature to restore backups by attaching the SSTs directly, then doing the downloads in the background. This is performed via `IngestExternalFiles`. The DB needs to be configured with a `remote.Locator -> remote.Store` mapping via `Options.Experimental.RemoteStorage`.

Experimentally it's also possible to tell Pebble to create objects on remote storage using `CreateOnShared` and `CreateOnSharedLocator`. But this is not that well tested.

If you want to try these features, I recommend using a more recent Pebble; the `crl-release-25.1` branch is the most recent that is stable.
