### ISSUE TITLE
db:  create a new pebble databse inside a existed pebble db

### ISSUE THREAD

**Issue by leowkong** [cockroachdb/pebble#3238]
I noticed that there is a LOCK file under the pebble db data directory . For my application needs, I need to create a new pebble db under an already created pebble db. This newly created db will not be accessed by the previous db, and the data is completely independent, is this supported and safe by pebble?

**Comment by jbowens** [comment]
What do you mean by “under”? In a subdirectory? Within a subdirectory will be ok.

**Comment by flywukong** [comment]
> What do you mean by “under”? In a subdirectory? Within a subdirectory will be ok.

yes,   In a subdirectory

**Comment by leowkong** [comment]
@jbowens  yes,  new db is in a subdirectory
