### ISSUE TITLE
ingest: `IngestAndExcise` should use `flushableIngest` for ingests

### ISSUE THREAD

**Issue by aadityasondhi** [cockroachdb/pebble#3335]
This came up in an [internal thread](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1708457620647379).

When we use `IngestAndExcise` as default and have an overlap with the memtable, we have to wait for the memtable to flush since we don't use flushable ingest. This is because for the general `IngestAndExcise` use case, the sstables are from another LSM and do not have a RANGEDEL.

A possible solution sketch (from the discussion):
> Option to pass to IngestAndExcise promising that the exciseSpan is also repeated explicitly via RANGEDELs in the sstables. Then we could layer these on top as flushable ingests, and when it came time to actually flush this flushable ingest, we would do the excise, and get the lower read amp.

**Comment by itsbilal** [comment]
Note that this issue is about the interim solution of throwing in rangedels with the sstables, and having an option for that. The better solution where we expose rangedels with iterators on the flushable ingests is #2676.
