### ISSUE TITLE
Graceful handling of full disk?

### ISSUE THREAD

**Issue by eest** [cockroachdb/pebble#3427]
I am trying out pebble as key/value store for a project which is a long-running system. At one point the disk was full and I found my process had crashed with the following log message:
```
pebble: fatal commit error: write /var/lib/dtm/pebble/000518.log: no space left on device
```

From what I can tell this message is a result of this code:
https://github.com/cockroachdb/pebble/blob/9d0109cfee7a3615e63e13802447d68d37fa65ac/db.go#L843-L847

And it looks like this will call `os.Exit(1)`:
https://github.com/cockroachdb/pebble/blob/9d0109cfee7a3615e63e13802447d68d37fa65ac/internal/base/logger.go#L42-L46

I understand that the database session may be broken at that point, but would it make sense to replace the call to `os.Exit(1)` with something less final so you get the possibility of doing error handling, like trying to open the database again at a later time or so?

**Comment by itsbilal** [comment]
In CockroachDB's usage of pebble, the crash-as-quickly-as-possible behaviour is desirable as disk exhaustion warrants manual intervention regardless. We use ballast files to give the operator an option to temporarily remedy disk-full scenarios and get a small amount of disk headroom to aid in recovery: https://www.cockroachlabs.com/docs/v23.2/cluster-setup-troubleshooting#automatic-ballast-files
