### ISSUE TITLE
db: reverse iteration

### ISSUE THREAD

**Issue by leowkong** [cockroachdb/pebble#3435]
Is reverse iteration supported? how to can I get a iterator  which give me the last key/value pair whose key is less than or equal of  the given key ?

is the follow code using right way? 
```
	iter, _ := db.NewIter(&pebble.IterOptions{})
	iter.SeekLT(key)
        return iter.Key()
```

**Comment by jbowens** [comment]
Hi, yes, reverse iteration is supported.

The code you provided will seek to the last key _strictly less_ than `key`. If you want to seek to the last key less than _or equal_, you'll need to use `SeekGE` and `Prev` if necessary. For example,

```
if !iter.SeekGE(key) || Compare(iter.Key(), key) > 0 {
    iter.Prev()
}
```
