### ISSUE TITLE
Deleted upstream dependency; bump github.com/cockroachdb/errors

### ISSUE THREAD

**Issue by karalabe** [cockroachdb/pebble#3659]
Hey there,

We've received a report that our builds are failing https://github.com/ethereum/go-ethereum/issues/29984, and it seems it's a dependency issue originating from Pebble, which in turn originates from `github.com/cockroachdb/errors` v1.11.1 (fixed in https://github.com/cockroachdb/errors/pull/137).

It *appears* that an upstream repo (`sentry-go -> iris`)... just... deleted it's published git version tag. /facepalm

Any chance of bumping the `github.com/cockroachdb/errors` package in mainline pebble to the one that has the fixed dependency, and then tagging a v1.1.1 patch release do we could also pick up the fix?

Thanks

**Comment by karalabe** [comment]
I'm assuming builds are still ok-ish for most systems because Go uses GOPROXY by default which caches the packages at Google, so those get served out of bounds and not pulled form GitHub, but I'd wager disabling the Go proxy will error.

**Comment by nicktrav** [comment]
Thanks for pointing this out, @karalabe. Fix is up in #3660.

**Comment by karalabe** [comment]
Thank you!

**Comment by nicktrav** [comment]
We ran into some issues up in Cockroach and needed to revert. We wont yank the existing tag, so you should still be fine with that version, but we'll want to figure this out by the time we next tag.

Going to re-open to track figuring this out.

**Comment by RaduBerinde** [comment]
I created a `pebble-release-1.1` branch at the `v1.1.1` tag onto which we can cherry-pick commits if/when we need to make a new 1.1.2 release.

I don't think we want to update these deps in CRDB 23.2/24.1 just for the sake of it.

**Comment by nicktrav** [comment]
> I don't think we want to update these deps in CRDB 23.2/24.1 just for the sake of it.

Sounds good. Feel free to close if there's nothing left to do here.
