### ISSUE TITLE
db: clarify and fix intended WAL reading and record.Reader behaviour

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/pebble#376]
- `record.Reader` contains a `recover()` method that (other than test code) is only called when `record.Reader.recovering` is already true, but `recover()` is the only one setting it to true, so unclear if `recover()` will ever be called.

- The purpose of `recover()` is to skip to the next block when we encounter a corrupt chunk. We need to clarify when this is desirable.
   -  @petermattis mentioned that for the WAL such skipping may not be desirable and just stopping at the first corruption is preferable. We need to confirm this is the desired behavior. `replayWAL()` currently stops at the first error and eats up the "expected" errors. We may be able to do better error classification and at least log something when we have probably lost data.
   - the MANIFESTS is also read using `record.Reader`. Any error there is a failure to open the db.
 
- Possible WAL error handling when finding an invalid chunk:
   - if we are in a partial block and there are not enough bytes left for the chunk header, ignore the error. It is WAL recycling or we crashed and some trailing data was lost.
   - if we are in a partial block and the next chunk is corrupt, ignore the error for the same reason.
   - if we are in a full block and the next chunk is corrupt, skip to next block.
      - if the first chunk in the next block is valid
         - from latest logNum: definitely corruption. Log it.
         - from older logNum: ignore since could possibly be because of reuse.
      - if the first chunk in the next block is invalid: we only reuse clean WALs since WALs from previous crashes are flushed in open() so this is a corruption.
     - if there is no next block: ignore since could be WAL recycling.

**Comment by petermattis** [comment]
The `recover()` and `recovering` stuff is hold over from the go-leveldb code which looked to be supporting something other than "point-in-time" WAL replay. It can probably be removed.
