### ISSUE TITLE
Manifest file not closed

### ISSUE THREAD

**Issue by lni** [cockroachdb/pebble#379]
It seems that the manifest file is not closed after db.Close(). This can be reproduced using the code below on windows - windows doesn't allow you to delete the folder when it contains an opened file. 

```
package main

import (
  "os"
  "runtime"

  "github.com/cockroachdb/pebble"
)

func main() {
  if runtime.GOOS != "windows" {
    panic("please run on windows")
  }
  dir := "test-data"
  db, err := pebble.Open(dir, &pebble.Options{})
  if err != nil {
    panic(err)
  }
  db.Close()
  if err := os.RemoveAll(dir); err != nil {
    // expected to reach here on windows for pebble v0.0.0-20191101210655-58fbf96a8f51
    panic(err)
  }
}
```
I got the following error message from the last panic()

```
panic: remove test-data\MANIFEST-000001: The process cannot access the file because it is being used by another process.
```

**Comment by petermattis** [comment]
@lni Thanks for the bug report. This was not Windows specific. We were failing to close the MANIFEST in `DB.Close()` and leaking the file descriptor.
