### ISSUE TITLE
Backup 

### ISSUE THREAD

**Issue by 0x366** [cockroachdb/pebble#3835]
Hello guys, im writing intensively data to pebble, that is also sensitive. 

I want to back it up from time to time - put into archive, encode and put into cloud. So I can restore pebble from backup in case of any accidents. 

What are the best way of copying data, to not corrupt anything, while the app is writing to it ? 

Jira issue: PEBBLE-236

**Comment by jbowens** [comment]
Hi @0x366, check out these options: https://github.com/cockroachdb/pebble/issues/2993#issuecomment-1757807774
