### ISSUE TITLE
wal: reader batch corruption

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#3865]
While stitching together physical WAL segments, the WAL reader reads each record's contents into a temporary buffer. There's a bug where an error encountered mid-copy of a record (eg, because the record was large enough to be
split across multiple chunks), the buffer was not reset before attempting to read the next file's record. This corruption could prevent replay of the WAL.

- [x] fix wal.Reader
- [ ] add randomized test of WAL failover and recovery

Jira issue: PEBBLE-244

**Comment by dshjoshi** [comment]
What sequence of user actions led to this issue being uncovered?

**Comment by dshjoshi** [comment]
@jbowens Have we already added " add randomized test of WAL failover and recovery"?

**Comment by jbowens** [comment]
Yes
