### ISSUE TITLE
make `compactionIter.key` always point to an immutable buffer

### ISSUE THREAD

**Issue by ajkr** [cockroachdb/pebble#402]
Currently it points to an immutable buffer after calling `saveKey()`, which must be done before `compactionIter.Next()` returns. There's an intermediate state during `Next()` where it points to `iterKey`'s buffer, which is mutable. I think it'd be clearer/less error-prone to only point `key` at the most recent saved buffer and use `iterKey` directly when needed.

**Comment by rohansuri** [comment]
Hi @ajkr, this seems like a good first issue. Would you accept a PR?

Also I noticed that in the `compactionIter.singleDeleteNext()` we're not setting `compactionIter.value` to iterValue (empty for singleDelete keys) which has the benign effect of emitting the previous entry's value.

test case:
```
define
a.SET.3:a
b.SINGLEDEL.2:
b.DEL.1:
----

iter
first
next
next
----
a#3,1:a
b#2,0:
.
```

result:
```
expected:
a#3,1:a
b#2,0:
.
        
found:
a#3,1:a
b#2,0:a
.
```

I'd be happy to fix this as well as part of the same PR.

**Comment by ajkr** [comment]
Hi @rohansuri, agreed, this would be a good first issue, and we'd be glad to accept a PR. Yes I think it makes sense to clear `compactionIter.value` in the case you mentioned so that we don't emit tombstones with values.
