### ISSUE TITLE
Multiple mergers

### ISSUE THREAD

**Issue by vkhobor** [cockroachdb/pebble#4122]
Hi! Is it supported to use multiple merger-s in pebbledb?

Basically I need one to concatenate strings (which is the default implementation), and one that increments a counter.

I've read this comment in the code. Based on this it seems only one merger is allowed per database.
```
type Merger struct {
        Merge Merge

        // Name is the name of the merger.
        //
        // Pebble stores the merger name on disk, and opening a database with a
        // different merger from the one it was created with will result in an error.
        Name string
```

Then if this is true, would it be a workable solution if I implement both increment and concatenation in a single merger?
I could use like a tag in the byte[] value to discriminate between the types `Int: 6` and `String: hhh`

Jira issue: PEBBLE-291

**Comment by jbowens** [comment]
> Then if this is true, would it be a workable solution if I implement both increment and concatenation in a single merger?
I could use like a tag in the byte[] value to discriminate between the types Int: 6 and String: hhh

Yeah, this is the recommended way to do this. You can either distinguish with a tag in the value, like you described, or based on the key.
