### ISSUE TITLE
1 million insertions takes forever

### ISSUE THREAD

**Issue by guycipher** [cockroachdb/pebble#4127]
Writing 1 million key value pairs takes over an hour (I had to cancel it).  Are there any options that have to be configured?
```
	db, err := pebble.Open("demo", &pebble.Options{})
	if err != nil {
		log.Fatal(err)
	}
	
	defer db.Close()

	// Write 1 million key/value pairs to the database.
	t := time.Now()
	for i := 0; i < 1000000; i++ {
		key := []byte("key-" + string(i))
		value := []byte("value-" + string(i))
		if err := db.Set(key, value, pebble.Sync); err != nil {
			log.Fatal(err)
		}
	}
	log.Println("Put time: ", time.Since(t))

	// Get key 988888
	t = time.Now()
	value, closer, err := db.Get([]byte("key-988888"))
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Get time: ", time.Since(t))

	if err := closer.Close(); err != nil {
		log.Fatal(err)
	}
	log.Println(value)
```

Specs:
![Screenshot from 2024-10-31 19-40-59](https://github.com/user-attachments/assets/05466557-26f0-4152-a360-0055745a0177)

For default configurations I'd expect to write 1 million sequential keys without problem.  

Do kindly let me know, thank you!

Jira issue: PEBBLE-292

**Comment by jbowens** [comment]
> ```
> 		if err := db.Set(key, value, pebble.Sync); err != nil {
> 			log.Fatal(err)
> 		}
> ```

By calling `DB.Set` with `pebble.Sync` one-by-one per KV serially, you're waiting for each individual key-value pair to be individually written to the WAL and durably synced before proceeding to the next one. It's expected that this should be a crawl.

The simplest improvement you can make is to use a batch (`db.NewBatch`) and commit, say 10,000 KVs at a time.

The fastest method of loading data into a DB would be to use the [`DB.Ingest`](https://pkg.go.dev/github.com/cockroachdb/pebble#DB.Ingest) API to ingest pre-constructed sstables.

**Comment by guycipher** [comment]
Very good, thank you.
