### ISSUE TITLE
At Rest Data Encryption?

### ISSUE THREAD

**Issue by bonedaddy** [cockroachdb/pebble#420]
The latest [release](https://github.com/dgraph-io/badger/releases/tag/v2.0.0) to badger includes at-rest data encryption with automatic key rotation. Such functionality in `pebble` would be awesome

**Comment by petermattis** [comment]
@bonedaddy There are no plans to add encryption-at-rest directly into Pebble. The [`vfs.FS`](https://github.com/cockroachdb/pebble/blob/master/vfs/vfs.go#L38) interface does allow a user of Pebble to encrypt data at rest transparently to the rest of Pebble, though I realize this leaves a lot of heavy lifting to the application.
