### ISSUE TITLE
db: randomized error testing

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#438]
Per a comment at https://github.com/cockroachdb/pebble/pull/434#pullrequestreview-333685674:

> I wonder if we need a randomized way of testing all the untested error paths -- it generally seems painful to construct such tests by hand. For instance, this path could be triggered by deleting an sstable from under the DB to trigger an error in tableCacheShard.findNode(). Some other error may involve corrupting sstables.

The challenge I see is what correctness condition to look for. Injecting a random error should lead to either a background error, or a foreground error returned via a `DB` or `Iterator` operation. When such an error occurs, we can try to cleanly shutdown the `DB` and verify that no assertions fire (i.e. no leaked iterators).

**Comment by ajkr** [comment]
Is this intended to be part of the metamorphic test?

Deleting an sstable seems tricky. Maybe it's in table cache and all its blocks are in block cache - in that case is an error expected?

I think injecting errors continuously and not requiring an outcome for any particular error could work. We could inject at the filesystem level, and when this mode is enabled the test permits user operations to either return an error or return correct results. If it's a write error we can shut down the DB and verify cleanup, then start it up again and continue. If it's a read error we can close the iterator and verify cleanup.

**Comment by petermattis** [comment]
> Is this intended to be part of the metamorphic test?

I haven't thought that far ahead. Seems possible that this could be a variant of the metamorphic test. We wouldn't be able to do any comparison between test runs, which makes it not really metamorphic, but it would be nice to reuse the random operation generation.

> Deleting an sstable seems tricky. Maybe it's in table cache and all its blocks are in block cache - in that case is an error expected?

Yeah, I don't think you can expect any particular errors to be generated.

> I think injecting errors continuously and not requiring an outcome for any particular error could work. We could inject at the filesystem level, and when this mode is enabled the test permits user operations to either return an error or return correct results. If it's a write error we can shut down the DB and verify cleanup, then start it up again and continue. If it's a read error we can close the iterator and verify cleanup.

This is what I was imagining as well. The hope is that we'd eventually trigger all of the error code paths, and that `DB.Close` would catch stuff like not properly closing iterators in those code paths.

**Comment by ajkr** [comment]
> I haven't thought that far ahead. Seems possible that this could be a variant of the metamorphic test. We wouldn't be able to do any comparison between test runs, which makes it not really metamorphic, but it would be nice to reuse the random operation generation.

How about after an error happens and a clean restart or iterator re-creation follows, then we retry the same operation that triggered the error initially? I think it should still see the same results as runs that didn't see an error on that operation, so then we could compare across test runs.

**Comment by petermattis** [comment]
> How about after an error happens and a clean restart or iterator re-creation follows, then we retry the same operation that triggered the error initially? I think it should still see the same results as runs that didn't see an error on that operation, so then we could compare across test runs.

Hmm, that's a good point. I guess this does make sense to fold into the metamorphic test framework.

**Comment by ajkr** [comment]
> How about after an error happens and a clean restart or iterator re-creation follows, then we retry the same operation that triggered the error initially?

It didn't quite work because there are some errors that happen every time for a given input. For example, `"pebble: SeekPrefixGE supplied with key outside of lower bound"` happens when the seek target has a smaller prefix than the lower bound. For input like that, retrying on error leads to an infinite loop.

This particular error is not that problematic. I think it is similarly good to mark the iterator as not valid without setting an error in that case. But the principle question remains of whether the metamorphic test should generate operations that are expected to trigger an error. If so, it becomes difficult to test correctness under fault injection, as we don't know which errors are worth retrying and which aren't.

BTW, another case of this is `pebble.ErrNotFound`. That one is easy to hardcode as never worth retrying.

**Comment by petermattis** [comment]
> This particular error is not that problematic. I think it is similarly good to mark the iterator as not valid without setting an error in that case. But the principle question remains of whether the metamorphic test should generate operations that are expected to trigger an error. 

Having the metamorphic test only generate error free operations seems challenging. And it has been useful to verify that various configurations produce the same errors for a set of operations.

> If so, it becomes difficult to test correctness under fault injection, as we don't know which errors are worth retrying and which aren't.

I was imagining that you'd only retry "injected" errors. That is, if you inject a synthetic IO error, and this error is propagated up to a user visible error, you could retry the operation. How to detect your synthetic IO error? The go1.13 [`errors`](https://golang.org/pkg/errors/) package provides the ability to find the root error. We'd have to be disciplined about wrapping errors correctly. Or you can do something with the error string. That's less clean, but perhaps an easier place to start.

**Comment by petermattis** [comment]
@jbowens Do you think there is anything left to be done here, or can this issue be closed?

**Comment by jbowens** [comment]
I think it can be closed.
