### ISSUE TITLE
db: investigate mergingIter.seek{GE,LT} tombstone handling

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#458]
`mergingIter.seek{GE,LT}` call `rangedel.Seek{GE,LT}` respectively to seek the range-del-iter on each level. But unlike other calls to `rangedel.Seek{GE,LT}` the returned tombstone is not cached in the level. This seems suspicious and possibly buggy. In particular, it seems to allow violation of the invariant that the tombstones in levels `[0,heap[0].index]` are at or past the key at `heap[0].key`.

Stumbled across this while debugging another problem. I don't have a test scenario which fails due to this yet.

**Comment by sumeerbhola** [comment]
It does look error-prone. Perhaps it is working because the call to `initMinHeap/initMaxHeap` at the end of those functions calls `initMinRangeDelIters/initMaxRangeDelIters` and initializes `mergingIterLevel.tombstone` for all levels.

**Comment by petermattis** [comment]
> Perhaps it is working because the call to initMinHeap/initMaxHeap at the end of those functions calls initMinRangeDelIters/initMaxRangeDelIters and initializes mergingIterLevel.tombstone for all levels.

Ah, good point. That is undoubtedly the reason this isn't a bug. Still seems like it should be fixed. Or, at least, commented.
