### ISSUE TITLE
perf: maybe throttle concurrent compactions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#47]
Similar to #46, Pebble only allows a single compaction to occur at any time. RocksDB allows multiple concurrent compactions. The benefit of allowing multiple concurrent compactions is a bit unclear, as on the surface allowing a concurrent compaction would seem to simply divide write bandwidth across the concurrent compactions. The exception to this is the benefit in allowing L0 compactions due to the need to quickly move L0 sstables to lower levels in order to avoid write throttling due to too many L0 sstables. This points to an alternative to concurrent compactions: allow compactions to be preempted (or paused), preferentially performing work on higher priority compactions (or flushes).

Cc @ajkr

**Comment by ajkr** [comment]
Yeah it can slow down each individual compaction. It always bothered me that users have to configure both flush/compaction parallelism and background work rate limiter. The amount of concurrency should depend on the rate limit. For example if we want to limit background work to 750 MB/s and we know Snappy can compress at 250 MB/s, we should have three background threads. Anything above that just slows down each individual worker, like you said.

With slower compression like ZSTD, the compression speed is usually much lower, more like 50-100MB/s. I guess that's why MyRocks ended up with ~12 background threads.

**Comment by ajkr** [comment]
Concurrent compactions helps as long as the bottleneck is CPU, in which case parallelizing the work can increase the throughput. After reaching the point where the background rate limit is saturated, then I agree adding more parallelism is pointless and just slows down individual compactions. Ideally we can derive the amount of parallelism necessary for a given rate limit.

For preemption, I don't know. One of the goals of partitioned level compaction is to make individual compactions small enough that the LSM state doesn't change too much while that compaction is running. If it changes so much that we need to urgently switch to flush or L0->L1 to avoid write stalls, perhaps the compactions could be made smaller.

**Comment by petermattis** [comment]
> For preemption, I don't know. One of the goals of partitioned level compaction is to make individual compactions small enough that the LSM state doesn't change too much while that compaction is running. If it changes so much that we need to urgently switch to flush or L0->L1 to avoid write stalls, perhaps the compactions could be made smaller.

Small compactions make a lot of sense, yet we've previously debugged issues with super-large compactions that were created due to range deletion tombstones overlapping a significant portion of the key space.

**Comment by petermattis** [comment]
While looking at the RocksDB mechanisms for [pacing user-writes](https://github.com/petermattis/pebble/issues/7#issuecomment-496019473) I noticed a mechanism for adjusting the compaction concurrency. The [`WriteController::GetCompactionPressureToken`](https://github.com/facebook/rocksdb/blob/master/db/write_controller.h#L49) method is called when the system is approach a write stall condition. This is done by [`ColumnFamilyData::RecalculateWriteStallConditions`](https://github.com/facebook/rocksdb/blob/master/db/column_family.cc#L723-L882). The compaction pressure token causes `WriteController::NeedSpeedupCompaction` to return `true` (that method also returns `true` if user-writes are stopped or throttled). `NeedSpeedupCompaction` controls whether [`DBImpl::GetBGJobLimits`](https://github.com/facebook/rocksdb/blob/master/db/db_impl_compaction_flush.cc#L1892-L1921) returns a value for `max_compactions` greater than 1. If `NeedSpeedupCompaction()` returns `false`, background compactions are throttled by only allowing 1 at a time.

The effect of all of these mechanisms is to only allow concurrent compactions if compactions are falling behind user writes.

**Comment by ajkr** [comment]
> The effect of all of these mechanisms is to only allow concurrent compactions if compactions are falling behind user writes.

That was originally introduced to handle the case where RocksDB is running in multiple processes on the same host (like multiple MyRocks instances) and there's no inter-process coordination for rate limiting. This way, each instance compacts at a low rate unless it really needs a high rate. Although, nothing prevents all the instances from needing a high rate simultaneously..

It's also a bit confusing to me to have rate limiting both on compaction parallelism and compaction writes. My dream is to limit compaction write rate only, and then calculate the minimum number of compaction threads necessary to utilize that rate.
