### ISSUE TITLE
internal/metamorphic: add "crash" testing simulation

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#471]
We can extend the metamorphic test to provide robust simulation of crash testing. A crash would be simulated by introducing a new `vfs.FS` implementation which buffers written data until a sync is performed. Additionally, the `vfs.FS` implementation buffers file creation until the parent directory is synced (i.e. files are created with a temporary name, and only renamed to the actual name once the parent directory is synced). The effect of this new `bufferedFS` implementation would be that closing a DB would lose all unsynced data and unsynced metadata operations.

The metamorphic test would be extended with a new "restart" operation. A "restart" operation will have the effect of orphaning all open snapshots, iterators, and batches, so the random op generator would know not to utilize those objects after the "restart" barrier. Running a "restart" operation would have a configurable effect: either it would actually close and re-open the DB, or it would be a no-op. 

Note that the metamorphic test currently specifies `pebble.NoSync` for all operations. We'd need to make this controllable. If we're comparing a no-op restart with an actual restart, we'd want to always specify `pebble.Sync`. But we can also compare actual restart behavior under different Pebble configs and then randomize whether operations were synced or not.

Cc @sumeerbhola as we were chatting about this early today. Does the above description make sense? I see a nice benefit in building this crash testing into the metamorphic test as it ensures that we as much coverage of the Pebble operation surface area as the metamorphic test is providing.

**Comment by sumeerbhola** [comment]
This is mostly consistent with what I was thinking about (with some additions like turning off the ssblock cache so all sstable reads go to the FS; setting Options.BytesPerSync to a very high value so there are no accidental syncs to save us).

The part that I am not certain about is how to deal with correctness for the WAL and the manifest files, specifically preventing later syncs for covering up for missed earlier syncs. For example, `LogWriter.Close()` does a sync, and it will be closed if we call `DB.Close()`. `versionSet.close()` does not currently sync the `versionSet.manifestFile` but someone could change that and cover up for missed syncs. It seems that "orphaning" the `DB` (and disabling background syncs based on `BytesPerSync`), i.e., not `Close()` it, as part of "restart" could prevent such additional syncs. We would need to close the `fileLock` so that we could open another `DB`. Thoughts?

**Comment by ajkr** [comment]
> The part that I am not certain about is how to deal with correctness for the WAL and the manifest files, specifically preventing later syncs for covering up for missed earlier syncs. For example, LogWriter.Close() does a sync, and it will be closed if we call DB.Close(). versionSet.close() does not currently sync the versionSet.manifestFile but someone could change that and cover up for missed syncs. It seems that "orphaning" the DB (and disabling background syncs based on BytesPerSync), i.e., not Close() it, as part of "restart" could prevent such additional syncs. We would need to close the fileLock so that we could open another DB. Thoughts?

Good point. We encountered this before and it led to finding an fsyncgate style bug, which was fun. The way I did it was by corrupting data corresponding to a failed sync since we have it in process memory: https://github.com/cockroachdb/cockroach/pull/36989/files#diff-b18a2ce89985319f6a9d16872b2f5d53R91-R96.

**Comment by ajkr** [comment]
Oh, I see you are asking about successful syncs covering up missing syncs, not successful syncs covering up failed syncs. It is a slightly different problem, then. If the DB is killed, i.e., things are properly not `Close()`d, I think there is not much to worry about. `BytesPerSync` might cover up missing sync occasionally but if run many times it should not hide forever. But your way sounds fine if you want to be extra safe or if you're planning to look for missing syncs with clean shutdown.

**Comment by petermattis** [comment]
> This is mostly consistent with what I was thinking about (with some additions like turning off the ssblock cache so all sstable reads go to the FS; setting Options.BytesPerSync to a very high value so there are no accidental syncs to save us).

Good point about disabling `Options.BytesPerSync`, though @ajkr also has a point that it won't hide all problems, and it is a useful config diff for the metamorphic test to explore.

Do we have to disable the block cache? That too is a config that the metamorphic test explores.

> The part that I am not certain about is how to deal with correctness for the WAL and the manifest files, specifically preventing later syncs for covering up for missed earlier syncs. 

I'm not sure if anything additional needs to be done here. Certainly a later sync can cover up an earlier one, but the power of the randomized testing is that a later sync won't always cover up a missing earlier one.

It is possible that we're not currently missing any syncs. Something we'll want to do when developing this test is to disable each of the current syncs and verify that the test catches their absence. This could even be a test of the test itself.

> It seems that "orphaning" the DB (and disabling background syncs based on BytesPerSync), i.e., not Close() it, as part of "restart" could prevent such additional syncs. 

Yeah, we probably want some sort of "unclean" `Close()` operation. I think this could be done in the `bufferedFS` itself. When we want to stop the database, we could disable all write operations through to the underlying FS. Then `Close()` could do all the syncing it wants but it wouldn't have any effect.

**Comment by petermattis** [comment]
Is there anything left to do here now that #486 is merged?

**Comment by sumeerbhola** [comment]
It is done -- all the work for this was in #472 and #486 (and the Pebble fixes in #500, #504, #505 to make the test pass)
