### ISSUE TITLE
SST files not deleted after manual compaction

### ISSUE THREAD

**Issue by lni** [cockroachdb/pebble#477]
I tried to use manual compaction to compact the entire DB after placing a range delete record to delete everything from the DB. I expect all SST files to be deleted after the manual compaction, but got the following error. 

```
remove rdb_test_dir_safe_to_delete\000011.sst: The process cannot access the file because it is being used by another process.
```

The above error is returned by d.opts.Cleaner.Clean in DB.deleteObsoleteFile. The named SST file is left in the DB folder after compaction & DB close.  Any chance the SST file is not closed by certain other part of pebble?  

This can only be reproduced on Windows as Windows doesn't allow you to delete opened files. 

Given similar file descriptor leak has recently happened twice, maybe add something to the vfs layer to count & check opened files at the end of each test?

**Comment by petermattis** [comment]
@lni Thanks for the report!

> Any chance the SST file is not closed by certain other part of pebble?

Certainly possible. We do run all of the pebble unit tests on Windows as part of CI. I would expect one of the tests to fail if there is an obvious problem with not closing an sstable. We've fixed previous bugs before. Can you provide a specific scenario which causes a problem?

> Given similar file descriptor leak has recently happened twice, maybe add something to the vfs layer to count & check opened files at the end of each test?

That's an interesting idea. Probably straightforward to add to `memFS`.

**Comment by lni** [comment]
@petermattis thanks for looking into this. Below is a test that can reproduce the reported issue on Windows. It fails intermittently - I got a few failures for my last 10 runs. 

```
package leaktest

import (
  "encoding/binary"
  "os"
  "path/filepath"
  "strings"
  "testing"

  "github.com/cockroachdb/pebble"
)

const (
  testDataDir        = "test-junk-data"
  maxIndex    uint64 = 1024 * 128
  junk               = "a piece of junk data"
)

func TestPebbleFDLeak(t *testing.T) {
  os.RemoveAll(testDataDir)
  fk := make([]byte, 8)
  binary.BigEndian.PutUint64(fk, 0)
  lk := make([]byte, 8)
  binary.BigEndian.PutUint64(lk, maxIndex)
  func() {
    opts := &pebble.Options{}
    pdb, err := pebble.Open(testDataDir, opts)
    if err != nil {
      t.Fatalf("%v", err)
    }
    defer pdb.Close()
    wo := &pebble.WriteOptions{Sync: true}
    wb := pdb.NewBatch()
    defer wb.Close()
    key := make([]byte, 8)
    for i := uint64(0); i < maxIndex; i++ {
      binary.BigEndian.PutUint64(key, i)
      wb.Set(key, []byte(junk), wo)
    }
    if err := pdb.Apply(wb, wo); err != nil {
      t.Fatalf("%v", err)
    }
    rdwb := pdb.NewBatch()
    defer rdwb.Close()
    rdwb.DeleteRange(fk, lk, wo)
    if err := pdb.Apply(rdwb, wo); err != nil {
      t.Fatalf("%v", err)
    }
    if err := pdb.Compact(fk, lk); err != nil {
      t.Fatalf("%v", err)
    }
  }()
  onFile := func(path string, info os.FileInfo, err error) error {
    if err == nil && !info.IsDir() {
      if strings.HasSuffix(info.Name(), ".sst") {
        t.Fatalf("SST file found: %s", path)
        return nil
      }
    }
    return nil
  }
  filepath.Walk(testDataDir, onFile)
}
```
