### ISSUE TITLE
perf: compaction / user iterator readahead

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#50]
RocksDB has separate knobs for controlling readahead for compaction and user iterators. RocksDB recommends a value of 2MB for [`compaction_readahead_size`](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L755) when running on spinning disk. This knob defaults to off. Similarly [`ReadOptions.readahead_size`](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L1101) controls readahead for user iterators. A similar recommendation of 2MB is made for improving forward iteration performance on spinning disk. It isn't clear if either knob is useful when using buffered IO.

Related to readahead is the OS caching behavior. RocksDB specifies `fadvise(..., POSIX_FADV_DONTNEED)` when writing sstables to avoid having the data for those tables retained in the OS block cache.

Cc @ajkr. Do you know how useful these knobs and fadvice-dont-need are in practice?

**Comment by ajkr** [comment]
I found `POSIX_FADV_DONTNEED` only used when compressed block cache is enabled. That prevents compressed data from being unnecessarily duplicated in page cache. This is the logic I'm referring to: https://github.com/facebook/rocksdb/blob/bb474e9a02abfe9c97b193a27c846de9fbdb4389/table/block_based_table_builder.cc#L776.

Hard to guess about readahead. I didn't look how file descriptors are used, but if we're not using `FADV_RANDOM` perhaps the page cache's builtin readahead will suffice.

**Comment by petermattis** [comment]
I missed the part about `POSIX_FADV_DONTNEED` only be used in conjunction with the compressed block cache. Sounds like investigating this functionality and readahead is low priority.

**Comment by itsbilal** [comment]
#726 implemented dynamic readahead in the sstable reader, and #817 made a change to rely on page cache readahead after a certain threshold as that was observed to deliver better performance. This issue is mostly resolved; though compactions aren't special cased right now. I filed #854 to track the compaction special case.
