### ISSUE TITLE
cmd/pebble: add many more benchmarks

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#51]
The RocksDB [`db_bench`](https://github.com/facebook/rocksdb/blob/master/tools/db_bench_tool.cc) tool contains a variety of benchmarks:

```
Available benchmarks:
      	fillseq       -- write N values in sequential key order in async mode
      	fillseqdeterministic       -- write N values in the specified key order and keep the shape of the LSM tree
      	fillrandom    -- write N values in random key order in async mode
      	filluniquerandomdeterministic       -- write N values in a random key order and keep the shape of the LSM tree
      	overwrite     -- overwrite N values in random key order in async mode
      	fillsync      -- write N/100 values in random key order in sync mode
      	fill100K      -- write N/1000 100K values in random order in async mode
      	deleteseq     -- delete N keys in sequential order
      	deleterandom  -- delete N keys in random order
      	readseq       -- read N times sequentially
      	readtocache   -- 1 thread reading database sequentially
      	readreverse   -- read N times in reverse order
      	readrandom    -- read N times in random order
      	readmissing   -- read N missing keys in random order
      	readwhilewriting      -- 1 writer, N threads doing random reads
      	readwhilemerging      -- 1 merger, N threads doing random reads
      	readwhilescanning     -- 1 thread doing full table scan, N threads doing random reads
      	readrandomwriterandom -- N threads doing random-read, random-write
      	updaterandom  -- N threads doing read-modify-write for random keys
      	xorupdaterandom  -- N threads doing read-XOR-write for random keys
      	appendrandom  -- N threads doing read-modify-write with growing values
      	mergerandom   -- same as updaterandom/appendrandom using merge operator. Must be used with merge_operator
      	readrandommergerandom -- perform N random read-or-merge operations. Must be used with merge_operator
      	newiterator   -- repeated iterator creation
      	seekrandom    -- N random seeks, call Next seek_nexts times per seek
      	seekrandomwhilewriting -- seekrandom and 1 thread doing overwrite
      	seekrandomwhilemerging -- seekrandom and 1 thread doing merge
      	crc32c        -- repeated crc32c of 4K of data
      	xxhash        -- repeated xxHash of 4K of data
      	acquireload   -- load N*1000 times
      	fillseekseq   -- write N values in sequential key, then read them by seeking to each key
      	randomtransaction     -- execute N random transactions and verify correctness
      	randomreplacekeys     -- randomly replaces N keys by deleting the old version and putting the new version
      	timeseries            -- 1 writer generates time series data and multiple readers doing random reads on id
```

The number of options is intimidating, yet there are undoubtedly good ideas that should be incorporated into Pebble benchmarking.

Additionally, we need infrastructure for verifying that real-world performance does not regress. This is complicated as we need to watch for dips in performance, not just compare a few numbers at the end of a run.

**Comment by ajkr** [comment]
The benchmarks we have now with `pebble ycsb` are pretty good. One thing I'm trying to figure out is what numbers to look at particularly for workloads involving writes.  Here's my high level proposal.

The first step will be find the "peak sustainable throughput". That metric could be found by an unbounded search on the rate limit argument to `pebble ycsb`. A workload would be deemed sustainable if, on a prefilled large DB, it can run until pending compaction bytes converges without hitting any stall/stop limits. If pending compaction bytes keeps increasing meaningfully beyond some period of time, or stall/stop limits are ever reached, we can declare the throughput is too high.

The next step is to establish the latency/throughput curve. We can run workloads at a few different throughputs between 0 and the peak sustainable throughput. We can record read/write p50/p99 latencies and graph the results. Here's an example graph I'd like to make, taken from the YCSB paper.

![image](https://user-images.githubusercontent.com/4780362/62335988-15256b00-b483-11e9-92e6-a2f3a4176bfa.png)

Then the third step is automation allowing us to run an A/B test on different Pebble binaries or on Pebble vs. RocksDB. Maybe also a way to quantify improvement/regression (this is easy for peak sustainable throughput, but not so easy for the latency/throughput curve).

**Comment by ajkr** [comment]
> The next step is to establish the latency/throughput curve. We can run workloads at a few different throughputs between 0 and the peak sustainable throughput. We can record read/write p50/p99 latencies and graph the results. Here's an example graph I'd like to make, taken from the YCSB paper.

It might be reasonable for this step to have a warm-up phase until cache is populated and pending compaction bytes has stabilized. I guess the latency profile will stabilize afterwards.
