### ISSUE TITLE
internal/cache: untangle mutual recursion in `runHand{Hot,Cold,Test}`

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#526]
The code to advance the clock hands has a nasty bit of mutual recursion. I don't think this is fundamental to the Clock-PRO algorithm.

```
shard.evict       -> shard.runHandCold
shard.runHandCold -> shard.runHandTest
shard.runHandCold -> shard.runHandHot
shard.runHandHot  -> shard.runHandTest
shard.runHandTest -> shard.runHandCold
```

It is easy to remove the `runHandHot -> runHandTest` recursion. The other recursion is quite a bit more difficult to figure out. It might be worthwhile to revisit this implementation from scratch. Note that the `TestCache` test verifies that the eviction behavior precisely matches expectations for the algorithm which will help catch breakage.

**Comment by petermattis** [comment]
I should note that I've actually seen this mutual recursion produces stacks with dozens and dozens of frames. I don't think this is a high priority to fix, but I think it should be fixed.

**Comment by chanyoung** [comment]
Hi, I'm interested in this issue and I've also seen a lot of stack frames being produced by the mutual recursion.

While I trying to untangle the recursive calls, I've seen that the clock hands passing each other. This is a little weird to me, because the parts where recursion occurs are seen as to prevent the hands go past others; handHot push handTest, handTest push handCold, and so on.

Anyway, I agree that this problem is not deeply related to the fundamental of Clock-PRO. In particular, I don't think this would lead visible difference in performance. However, as the clock hands start crossing each other, the algorithm becomes difficult to predict and the concept of reuse distance becomes obscure.

So, if you don't mind, can I try to untangle the mutual recursion and make clock hands not to cross each other?

**Comment by petermattis** [comment]
@chanyoung Go for it. This isn't a high priority, but a contribution would be appreciated. I'm mildly worried that untangling will produce a slightly different set of evictions. Note that this implementation was adapted from another go implementation which was adapted from a [python implementation](https://bitbucket.org/SamiLehtinen/pyclockpro). It is possible that the implementation here differs from the one described in the paper. The whole point being that more love can be given to this area, though some care needs to be taken as there are not good high-level tests that changes here do not cause bugs. The low-level golden data test in `TestCache` feels too tied to the implementation specifics.

**Comment by chanyoung** [comment]
Thanks for the information. Before making a PR, I will test it in TPCC and YCSB and share the results.

**Comment by chanyoung** [comment]
Oops, I'm sorry for the spamming.. I didn't notice it.

I tested untangled version with unit test(TestCache), YCSB, cockroach tpcc workload.
Performance degradations are not observed during tests, and seems untangled version produces almost same footprint.

1. TestCache
Expect cache miss but got hit: 62
Expect cache hit but got miss: 42

2. YCSB (each tests are conducted 5 times, yaxis = block cache hit rate, xaxis = number of ycsb operations, every 1,000 ycsb operations the cache hit ratio is logged.)
2.1. --workload A -d 0m --num-ops=10_000_000 --values 64 --cache 134217728 -c 50 --keys=zipf --initial-keys 0 --prepopulated-keys 100_000_000
![128_a](https://user-images.githubusercontent.com/6683987/96095828-1e74e900-0f0a-11eb-8f6a-5e66c54c460f.png)
![128_a_zoom](https://user-images.githubusercontent.com/6683987/96095873-2cc30500-0f0a-11eb-9a4a-9ec8c64b0b45.png)

2.2. --workload B -d 0m --num-ops=10_000_000 --values 64 --cache 134217728 -c 50 --keys=zipf --initial-keys 0 --prepopulated-keys 100_000_000
![128_b](https://user-images.githubusercontent.com/6683987/96096177-84fa0700-0f0a-11eb-90f7-ea1509493ce5.png)

2.3. --workload C -d 0m --num-ops=10_000_000 --values 64 --cache 134217728 -c 50 --keys=zipf --initial-keys 0 --prepopulated-keys 100_000_000
![128_c](https://user-images.githubusercontent.com/6683987/96096660-0a7db700-0f0b-11eb-901f-176850c1783b.png)
![128_c_zoom](https://user-images.githubusercontent.com/6683987/96096679-0d78a780-0f0b-11eb-8537-e0bb86c8e799.png)

2.4. --workload D -d 0m --num-ops=10_000_000 --values 64 --cache 134217728 -c 50 --keys=uniform --initial-keys 0 --prepopulated-keys 100_000_000
![128_d](https://user-images.githubusercontent.com/6683987/96096734-1e291d80-0f0b-11eb-9ec5-c6406fbd627e.png)

2.5. --workload E -d 0m --num-ops=10_000_000 --values 64 --cache 134217728 -c 50 --keys=zipf --initial-keys 0 --prepopulated-keys 100_000_000
![128_e](https://user-images.githubusercontent.com/6683987/96096798-2ed99380-0f0b-11eb-87da-4d03cb8551d2.png)

2.6. --workload A -d 0m --num-ops=10_000_000 --values 64 --cache 1073741824 -c 50 --keys=zipf --initial-keys 0 --prepopulated-keys 100_000_000
![1024_a](https://user-images.githubusercontent.com/6683987/96097020-6fd1a800-0f0b-11eb-9431-1d0be88c9819.png)
![1024_a_zoom](https://user-images.githubusercontent.com/6683987/96097039-752ef280-0f0b-11eb-8430-c62188785efb.png)

2.7. --workload B -d 0m --num-ops=10_000_000 --values 64 --cache 1073741824 -c 50 --keys=zipf --initial-keys 0 --prepopulated-keys 100_000_000
![1024_b](https://user-images.githubusercontent.com/6683987/96097084-82e47800-0f0b-11eb-9a6a-9ba40e73c4a0.png)
![1024_b_zoom](https://user-images.githubusercontent.com/6683987/96097097-8677ff00-0f0b-11eb-99dc-7428a305d6b2.png)

2.8. --workload C -d 0m --num-ops=10_000_000 --values 64 --cache 1073741824 -c 50 --keys=zipf --initial-keys 0 --prepopulated-keys 100_000_000
![1024_c](https://user-images.githubusercontent.com/6683987/96097135-94c61b00-0f0b-11eb-9a0e-91764c7ca78b.png)
![1024_c_zoom](https://user-images.githubusercontent.com/6683987/96097160-9a236580-0f0b-11eb-877f-3055b4fa2f07.png)

2.9. --workload D -d 0m --num-ops=10_000_000 --values 64 --cache 1073741824 -c 50 --keys=uniform --initial-keys 0 --prepopulated-keys 100_000_000
![1024_d](https://user-images.githubusercontent.com/6683987/96097259-b45d4380-0f0b-11eb-970b-cb8f4cc8c241.png)
![1024_d_zoom](https://user-images.githubusercontent.com/6683987/96097270-b7f0ca80-0f0b-11eb-8554-34a1427e52a0.png)

2.10. --workload E -d 0m --num-ops=10_000_000 --values 64 --cache 1073741824 -c 50 --keys=zipf --initial-keys 0 --prepopulated-keys 100_000_000
![1024_e](https://user-images.githubusercontent.com/6683987/96097437-e5d60f00-0f0b-11eb-9e4f-267a27029638.png)
![1024_e_zoom](https://user-images.githubusercontent.com/6683987/96097442-e79fd280-0f0b-11eb-9ee1-4d261389fc3d.png)

3. TPCC
I tested several times with a local three nodes(warehouses = 200, duration=5 hours) with various cache size but I couldn't find any notable changes. Results were almost same.
