### ISSUE TITLE
db: L6 files ... have overlapping ranges

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#528]
The metamorphic test discovered a new instance of the `files ... have overlapping ranges` assertion:

```
// INFO: [JOB 159] ingesting: sstable created 003747
// INFO: [JOB 158] compacted L5 [003686] (938 B) + L6 [003730 003502] (1.6 K) -> L6 [003744] (840 B), in 0.0s, output rate 6.8 M/s
// INFO: [JOB 158] MANIFEST deleted 003745
// INFO: [JOB 160] compacting L5 [003739] (951 B) + L6 [003596 003554] (1.7 K)
// INFO: [JOB 159] MANIFEST created 003748
// INFO: [JOB 160] compacting: sstable created 003749
// INFO: [JOB 159] MANIFEST deleted 003746
// INFO: [JOB 159] ingested L6:003747 (843 B)
db.Ingest(batch24) // <nil> #2193
// INFO: [JOB 160] compaction to L6 error: pebble: internal error: L6 files 003747 and 003749 have overlapping ranges: vmquh#805,SET-vmquh#805,SET vs rgjrgluwhj#0,SET-zhui#0,MERGE
```

Looks like concurrent compaction and ingestion were occurring. The ingestion finished first and when the compaction went to complete the assertion triggered. Here is the full history from the test run: [history.txt](https://github.com/cockroachdb/pebble/files/4183744/history.txt)

@rohansuri #511 seems to be to blame. If I revert that PR I'm no longer able to reproduce a failure. Hopefully you can see from the attached history.txt what the problem is. If not, I can upload some more info and give you instructions on how to run the meta test in a loop to reproduce. Let me know if you're not able to look at this soon as we may have to temporarily revert #511. Or perhaps @sumeerbhola sees what the error in the new logic is.

**Comment by rohansuri** [comment]
@sumeerbhola did raise a question regarding concurrent compaction and ingestion (last comment [here](https://github.com/cockroachdb/pebble/pull/511#pullrequestreview-350239742)):
> We are continuing without updating targetLevel since we can't ingest here but it is ok to ingest at a lower level since we know there is no overlap in the data. But we can't do the same when looking at the compaction bounds below because we can't look at the data that those compactions will produce.

To which I replied:
> Correct me if I'm wrong but since compaction will always produce keys from ssts in startLevel or outputLevel, both levels having their data overlap already tested and found to be not overlapping (else we'd have returned early), there's no need to check for data overlap with the newly compacted ssts on this level.

Looks like this reasoning doesn't stand true. Will investigate it today and get back here.

**Comment by petermattis** [comment]
I took another this morning and I need to adjust my statement: #511 revealed a previously existing bug. I believe the problem is that `DB.maybeScheduleCompaction` which calls `compactionPIcker.pick{Auto,Manual}` can race with `DB.ingestApply`. The specific problem here is that `pickAuto` is making decisions about what files to include in a compaction, but it doesn't have a mutually exclusive lock with `DB.ingestApply` because `DB.mu` is released by `versionSet.logAndApply`. The solution is for `maybeScheduleCompaction` to grab `versionSet.logLock`.

```diff
diff --git a/compaction.go b/compaction.go
index 3b9a5cee..c5d64894 100644
--- a/compaction.go
+++ b/compaction.go
@@ -967,6 +967,10 @@ func (d *DB) maybeScheduleCompaction() {
                }
                return
        }
+
+       d.mu.versions.logLock()
+       defer d.mu.versions.logUnlock()
+
        for len(d.mu.compact.manual) > 0 && d.mu.compact.compactingCount < d.opts.MaxConcurrentCompactions {
                manual := d.mu.compact.manual[0]
                c, retryLater := d.mu.versions.picker.pickManual(d.opts, manual, &d.bytesCompacted, d.getInProgressCompactionInfoLocked(nil))
```

**Comment by petermattis** [comment]
(I'll send a PR with the above shortly).

**Comment by rohansuri** [comment]
Really interesting. So this is not impacting the ingestion decision because `DB.mu` is held that prevents `DB.mu.compact.inProgress` from changing. But when we install a new version that adds the newly ingested file (releasing `DB.mu`), concurrently `DB.maybeScheduleCompaction` *still uses the old version/picker*, not seeing the new file and hence not setting up its inputs correctly. Later, when compaction wants to install a new version, it conflicts due to overlap with the current version installed by ingestion. Nice catch!

**Comment by petermattis** [comment]
@rohansuri Yep, that is a nice restatement of the problem.

**Comment by hueypark** [comment]
I am very suspicious of `versionSet.close`(https://github.com/cockroachdb/pebble/blob/2aca904b138a7dc4feba5f0ce1399021f09beda3/version_set.go#L261). We should have called `vs.manifest.Close ()` first.
However, I can't reproduce the phenomenon. This can occur only when `Compaction` is followed by `Close`, but that parts are properly protected by `db.mu` and `d.mu.compact.cond`.
@petermattis  Do you have any other opinions?

**Comment by petermattis** [comment]
@hueypark I'm assuming the comment above was added here by accident at the the nearly identical comment on #560 is the one you intended.

**Comment by hueypark** [comment]
@petermattis You're right. Thank you for telling me.
