### ISSUE TITLE
key corruption when reading pebble SSTs in rocksdb due to a 0 global sequence number

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#532]
Pebble's `sstable.Writer` currently sets the external format version to 2 on every SST written, whether it's written in a compaction, flush, or for ingestion. When rocksdb reads these SSTables, it treats them as ingested SSTs with a global sequence number (0 by default). This results in reads returning wrong data when RocksDB is restarted on a Pebble-written store directory.

As part of fixing this issue, the version needs to be unset when SSTs are written as part of a compaction or flush, and any other incompatibilities around global sequence numbers between rocksdb and pebble should be investigated.

**Comment by itsbilal** [comment]
I'm already looking into this, but since it was going slower than expected, I filed an issue to track it and to make it easier to ask questions / loop others in.

**Comment by petermattis** [comment]
Looking forward to what you discover here. Let me know if you need any suggestions for debugging techniques or where to look.

**Comment by itsbilal** [comment]
So my sequence of events was slightly off, which changed it from a WAL replay issue to an SST reading issue due to RocksDB interpreting a 0 sequence number on every key. Updating the issue to reflect it all.

**Comment by petermattis** [comment]
Making sure we're on the same page regarding the corruption the `external_file_sst.version` property thing was exhibiting with RocksDB.

Dumping the keys at the DB level shows:

```
~ ./cockroach debug rocksdb dump --db=bad-store/ --key_hex | grep 79656B767971776F726D
0x79656B767971776F726D00002C00000000007609 ==>
```

But looking at the sstable level shows:

```
./cockroach debug sst_dump --command=scan --file=bad-store/000119.sst --output_hex | grep 79656B767971776F726D
'79656B767971776F726D00' seq:0, type:0 =>
'79656B767971776F726D00000000000000007609' seq:0, type:1 =>
```

Where did that `2C` in the timestamp portion of the key come from?

None of the other sstables contain that key. And the log files which contain it have keys which look like the ones from `sst_dump`:

```
~ pebble wal dump bad-sto
re/*.log --key=%x | grep -i 79656B767971776F726D
    SET(79656b767971776f726d00,<40>)
    SET(79656b767971776f726d00000000000000007609,<0>)
    DEL(79656b767971776f726d00)
```

**Comment by petermattis** [comment]
Taking another look at this today to understand where the corruption is happening in RocksDB. Looks like it is happening at a low-level. Here is RocksDB's `BlockBasedTableIterator` code instrumented to output the keys:

```
~ ./cockroach debug rocksdb dump --db=bad-store/ --key_hex | grep 79656B767971776F726D
BlockBasedTableIterator::Next: 79656B767971776F726D00002C080000000000
BlockBasedTableIterator::Next: 79656B767971776F726D00002C00000000007609012C080000000000
0x79656B767971776F726D00002C00000000007609 ==>
```

Compare that two dump the keys in the sstable (again using RocksDB):

```
~ ./cockroach debug sst_dump --command=scan --file=bad-store/000119.sst --output_hex | grep 79656B767971776F726D
BlockBasedTableIterator::Next: 79656B767971776F726D000000000000000000
'79656B767971776F726D00' seq:0, type:0 =>
BlockBasedTableIterator::Next: 79656B767971776F726D000000000000000076090100000000000000
'79656B767971776F726D00000000000000007609' seq:0, type:1 =>
```

Need to move the instrumentation down into `DataBlockIter`.

**Comment by petermattis** [comment]
Making progress. When the `rocksdb.external_sst_file.version` property is set to 2, RocksDB will attempt to use the value of `rocksdb.external_sst_file.global_seqno` as the global seqnum for the sstable. This is done in https://github.com/cockroachdb/rocksdb/blob/crl-release-6.2.1/table/block_based_table_reader.cc#L685-L756. That function does not just blindly use the value of  the `rocksdb.external_sst_file.global_seqno`. It tries to detect the global seqno property not being set to a reasonable value, and then to do something reasonable. For the Pebble generated sstables, the global seqno property was being set to 0. That causes the following code in `GetGlobalSequenceNumber` to execute:

```
    if (global_seqno == 0) {
      global_seqno = largest_seqno;
    }
```

Where does `largest_seqno` come from? It is `FileMetadata.LargestSeqnum`:

```
~ pebble manifest dump bad-store/MANIFEST-000121 | grep 000119
  added:         L0 000119:1926<#2034-#2092>[bxsvlrsoglkig\x00#2092,DEL-yekvyqworm\x00\x00\x00\x00\x00\x00\x00\x00v\x09#2034,SET]
```

So `LargestSeqnum` is `2092` which is `0x82c`. When stored in little endian format, that appears as `0x2c08`. I can see this value being used to update the seqnum on the internal keys. Still to figure out is how the `0x2c` is leaking into the user key sometimes.

**Comment by petermattis** [comment]
I think I understand how `2c` is leaking into the user portion of the key. The sstable contains the two internal keys:

```
79656B767971776F726D000000080000000000
79656B767971776F726D0000000000000000760901F2070000000000
```

The last 8 bytes of the key correspond go the internal key trailer, composed of the sequence number and record type. Decoded, the above look like:

```
79656b767971776f726d00#2048,DEL
79656b767971776f726d00000000000000007609#2034,SET
```

With the global seqnum set to `82c`, the first key is actually returned as:

```
79656B767971776F726D00002C080000000000
```

or

```
79656B767971776F726D00#2092,DEL
```

The problem is when we go to decode the next key. The block uses prefix compression. For the second key, the prefix compression says that 13 bytes of the prefix are shared with the previous key. That happens to correspond to exactly `79656B767971776F726D00002C`. The key decoding then tacks on the unshared suffix bytes to arrive at `79656B767971776F726D00002C0000000000760901F2070000000000`. 

The root of the problem here is that RocksDB is stuffing the global seqnum into the key that is used for decoding the next key. That simply isn't kosher. The reason this normally isn't a problem is because RocksDB is expecting sstables which use global sequence numbers to have each record encoded with a zero seqnum:

```
      // If we are reading a file with a global sequence number we should
      // expect that all encoded sequence numbers are zeros and any value
      // type is kTypeValue, kTypeMerge, kTypeDeletion, or kTypeRangeDeletion.
      assert(GetInternalKeySeqno(key_.GetInternalKey()) == 0);
```

Note that Pebble's approach to passing around internal keys in decoded form (`InternalKey`) avoids the fragility here. I bet if I turn on assertions, the above assertion will fire.

```
~ ./cockroach debug rocksdb dump --db=bad-store/ --key_hex | egrep '79656B767971776F726D'
Assertion failed: (GetInternalKeySeqno(key_.GetInternalKey()) == 0), function ParseNextDataKey, file /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/table/block.cc, line 540.
```

With that, I believe the mystery is solved.
