### ISSUE TITLE
get stuck in the middle of manual compaction

### ISSUE THREAD

**Issue by lni** [cockroachdb/pebble#556]
Hi @petermattis 

I just noticed another issue, will really appreciate if you can help to have a quick look. 

When running my tests using pebble backed by a memfs vfs, my manual compaction request didn't return. It turns out to be waiting for the flushed chan to be closed here: 

https://github.com/cockroachdb/pebble/blob/master/db.go#L936

The workload is very small, a few megabytes maximum and everything is in memory. So it is really "compaction is a bit slow" problem, it seems the manual compaction got stuck there forever.

Apologize that I don't have any test case that can re-produce the reported issue, any chance you can have a quick look to see is there anything possible that can cause this? Many thanks!

**Comment by petermattis** [comment]
> I just noticed another issue, will really appreciate if you can help to have a quick look.

Thanks for the report. I'm not sure what can be done without more info. Reproduction would be best. A goroutine dump when this happens would be useful. Even better than a goroutine dump would be a core dump.

**Comment by petermattis** [comment]
Actually, I think I see what the problem is. At the very least, I found a problem, hopefully the same one you're encountering. Can you try out #557?

**Comment by lni** [comment]
@petermattis thanks for the quick response & fix. 

I will try #557 and let you know the result. It will take some time as the reported issue only got triggered after many runs of my monkey test.

**Comment by petermattis** [comment]
@lni I closed this optimistically. Definitely ping this issue if the bug you're seeing is not fixed.
