### ISSUE TITLE
Pebble re-assigns last sequence number in manifest while rocksdb increments it

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#565]
Pebble's assignment of sequence numbers as well as behaviour of the `LastSeqNum` field in the manifest does not exactly match rocksdb's. The very first sequence number assigned to an operation in Pebble after a restart where the previous engine was rocksdb, and where the last operation was an ingestion with a global sequence number (and there were no WALs left over to replay), ends up matching that ingestion's global sequence number.

After a flush, this trips a check in `version.CheckOrdering`which checks that the global sequence number of an ingested SST does not match the start sequence number of another SST.

When the same sequence of operations happens, but with rocksdb running both before and after the restart, we see that the first entry in the WAL written after the restart has a sequence number one greater than that of the ingestion before the restart.

To reproduce: Take this metamorphic test check file,
[check_file_ingest_issue.meta.txt](https://github.com/cockroachdb/pebble/files/4314277/check_file_ingest_issue.meta.txt), and run it in cockroach with this command:

```
make test PKG=./pkg/storage/metamorphic/ TESTS="TestRocksPebbleCheck/rocksdb,pebble" TESTFLAGS="-v --keep --check <path-to-file>"
```

And watch that, at the ingestion following `iterator_close(iter101)`, Pebble is stuck in an infinite loop as it tries to flush its memtable while these messages are repeated in stdout indefinitely (with increasing SST numbers):

```
I200309 21:04:01.556872 23616 vendor/github.com/cockroachdb/pebble/compaction.go:898  background error: pebble: internal error: L0 flushed file 020821 has an ingested file coincident with smallest seqnum: 2745-2774
I200309 21:04:01.556903 23617 vendor/github.com/cockroachdb/pebble/compaction.go:946  [JOB 20673] flushing to L0
I200309 21:04:01.557099 23617 vendor/github.com/cockroachdb/pebble/compaction.go:1289  [JOB 20673] flushing: sstable created 020822
I200309 21:04:01.566342 23617 vendor/github.com/cockroachdb/pebble/compaction.go:996  [JOB 20673] flushed to L0 [020822] (1.8 K)
I200309 21:04:01.566835 23617 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 20673] sstable deleted 020822
I200309 21:04:01.566848 23617 vendor/github.com/cockroachdb/pebble/compaction.go:898  background error: pebble: internal error: L0 flushed file 020822 has an ingested file coincident with smallest seqnum: 2745-2774
I200309 21:04:01.566886 23622 vendor/github.com/cockroachdb/pebble/compaction.go:946  [JOB 20674] flushing to L0
I200309 21:04:01.567025 23622 vendor/github.com/cockroachdb/pebble/compaction.go:1289  [JOB 20674] flushing: sstable created 020823
I200309 21:04:01.576285 23622 vendor/github.com/cockroachdb/pebble/compaction.go:996  [JOB 20674] flushed to L0 [020823] (1.8 K)
I200309 21:04:01.576938 23622 vendor/github.com/cockroachdb/pebble/compaction.go:1858  [JOB 20674] sstable deleted 020823
I200309 21:04:01.576963 23622 vendor/github.com/cockroachdb/pebble/compaction.go:898  background error: pebble: internal error: L0 flushed file 020823 has an ingested file coincident with smallest seqnum: 2745-2774
```

Observed with MVCC metamorphic tests in cockroach.

**Comment by petermattis** [comment]
Nice find! Have you tracked down where in RocksDB it is bumping the sequence number found in the MANIFEST by one? Just curious to see the code and where I missed that.

**Comment by itsbilal** [comment]
@petermattis RocksDB seems to treat "current sequence" and "last sequence" differently, with "current sequence" being set to one ahead of "last sequence" at write time.

See https://github.com/cockroachdb/rocksdb/blob/crl-release-6.2.1/db/db_impl_write.cc#L436 and line 458

`logSeqNo` in pebble currently is more similar to `current_sequence`, but we can change it to be like `last_sequence` and increment it by 1 more in the commit pipeline. Or we could just set `logSeqNo` to the manifest value plus 1 at open() time,  and do the inverse at write time.

**Comment by petermattis** [comment]
> See https://github.com/cockroachdb/rocksdb/blob/crl-release-6.2.1/db/db_impl_write.cc#L436 and line 458

Unfortunately, that is not the code path that we use as we don't enable pipelined writes (I think). Looking around, I think the code path we do use (`!two_write_queues`, `!pipelined`) has the same behavior, though. Can you double-check?

**Comment by itsbilal** [comment]
Ah, my bad, didn't realize we didn't use that code path. In that case it's lines 282 and 298 in the same file `db/db_impl_write.cc`:

https://github.com/cockroachdb/rocksdb/blob/9cee3b54aae29d14fdab520edf4475e408dade98/db/db_impl_write.cc#L282

Everything else I said is still correct.

**Comment by petermattis** [comment]
> Ah, my bad, didn't realize we didn't use that code path.

That file has numerous code paths. I've been tripped up by reading the wrong code there myself. Thanks for the double-check. I believe lines 282 and 298 are the relevant lines as well.
