### ISSUE TITLE
Re: SeekPrefixGE and Comparer

### ISSUE THREAD

**Issue by maarek** [cockroachdb/pebble#569]
https://github.com/cockroachdb/pebble/blob/d2ecbc248decea8d177e2d2777d8ef458267eddc/iterator.go#L63

Should `findNextEntry()` split on the key.UserKey as in the code above or on the prefix in order to match the prefix to the Key? 

I am trying to use SplitPrefixGE and maybe I am not understanding the purpose of Split in regards to a prefix match. If my prefix were 2 bytes in length and my compariter.Split is equal to the length of the key (e.g. 10), then I would not match a Key entry if the 2 byte prefix != 10 byte. The iterator would not be valid and a valid key could be skipped.

**Comment by petermattis** [comment]
I'm not sure I quite follow your problem explanation. Can you provide code to demonstrate? `SeekPrefixGE` is a bit of an odd duck. It is really useful for only one purpose: allowing the use of bloom filters during iteration under constrained circumstances. I would generally advise using `SeekGE` unless you have reason to believe the performance difference will be impactful. That said, it is also possible there is a bug here, or at least a need for better documentation.

**Comment by maarek** [comment]
Thanks!

I was under the assumption that the use of `SeekGE` was going to seek and iterate from a full key match and all keys GE to the match.  Then `SeekPrefixGE` would handle a partial key match and only iterate across all keys that matched the prefix. I didn't realize that SeekGE would handle a partial key match as well. So I changed it up to SeekGE(prefix) and just test validity and prefix match on the iteration. This works well. I'm still a bit fuzzy on the use case for `SeekPrefixGE` but I will try to read up more on the use case of bloom filters and how this works for that case.

**Comment by petermattis** [comment]
> I'm still a bit fuzzy on the use case for SeekPrefixGE but I will try to read up more on the use case of bloom filters and how this works for that case.

The documentation around `SeekPrefixGE` leaves something to be desired. For example, "and shares a common prefix with the given key" leaves a bit open to interpretation. I think adding an example will help. I'll leave this issue open until that is done.

**Comment by petermattis** [comment]
@maarek Let me know if the improved docs in #570 make the use of `SeekPrefixGE` any clearer.

**Comment by maarek** [comment]
@petermattis Yeah I think I am understanding it a little more. Maybe you can tell me if I'm right in my assumption that SeekGE would be best for my use case. 

My key structure is `<prefix>:<someid>:<num>` or `<prefix>:<anotherid>:<someid>`. An example might be `s:123:0`, `s:123:1`, etc. and `c:abc:123`, `c:cbd:123`, etc.

My prefix denotes a specific collection of data. The first id, being a secondary grouping and so on. Is this similar to `key@timestamp` where key `a` is different than key `aa`. In my case prefix are different `s:` vs `c:` but an id under that prefix is defined by all bytes in the id. 

So in the first case, maybe I am provided `s:123` and I want to iterate all `num` under `s:123`, but not `s:456`. This is where I had envisioned ScanPrefixGE coming in. But I can see that I can scan `s:123` and in the loop, drop out when I've passed the `s:123` prefix range.

On the second hand, I have another subset of queries that need to work across the `c:` prefix subset. Typically this one scans from `c:456` and continues on until canceled, ignoring `s:` prefix but the secondary index `456` doesn't matter, as long as we got to `c:456` on the initial seek and then forward from there. 

I don't see a bloom filter being necessary here but where I was thinking `SeekPrefixGE` would be to limit the subset of elements on the seek by a partial prefix match. If I iterate over the prefix `s:` then I want to see all elements under `s:`. If I iterate `s:123` then I only get `s:123` if I want `c:` then the same holds. But maybe this is for the SeekGE( ) and Iterator logic to figure out and not the DB to optimize in some way. 

Sorry, if this is long winded. I am eager to dig into the inner workings of the operator and still understand more of the "filtering" use case as well. See how I can figure out more optimal ways of querying subsets of data. 👍

**Comment by petermattis** [comment]
`SeekPrefixGE` is not a good fit for your use case. Rather, you should take a look at `IterOptions.UpperBound`. If you want to scan the `c:` prefix, you create an iterator with `IterOptions.UpperBound = "d:"` (or technically, you do use `c;`). Something like:

```
  iter := db.NewIter(&pebble.IterOptions{UpperBound: "c;"})
  for valid := iter.SeekGE("c:"); valid; valid = iter.Next() {
    // iter.Key() is guaranteed to start with the prefix "c:"
  }
```

The DB is able to use the `UpperBound` to optimize which sstables are searched.
