### ISSUE TITLE
perf: use raw block device for db

### ISSUE THREAD

**Issue by vtolstov** [cockroachdb/pebble#58]
Thanks for this great project, i known that ceph uses in their bluestore rocksdb, does it possible to use raw block device for pebble?
In case of using raw block device we don't need to know how to tune filesystem, and use kv directly...

**Comment by petermattis** [comment]
@vtolstov Do you have a pointer to what Ceph does? Raw block devices are a bit tricky to deal with. Direct IO on regular files is normally a better option.

**Comment by vtolstov** [comment]
As i see ceph uses blobdb from rocksdb. So all data stored in one blob, that can lie on filesystem or in raw block device. In case of raw block device i think that it provide benefits like - not need to do fsck that can delete files or have corrupted filesystem on unclean shutdown. Faster writes, because you don't need to update fs metadata.
So working with raw block dev in case of kv will be good, also this block can lie on fs too.

**Comment by petermattis** [comment]
@vtolstov RocksDB does not support using raw block devices as far as I'm aware. Can you point me towards the code or functionality you're thinking of?

**Comment by vtolstov** [comment]
i'm ask in ceph mailing list about usage raw block device for rocksdb kv

**Comment by petermattis** [comment]
@ajkr Do you know of any support in RocksDB for raw block devices? My guess is that this is a reference to direct IO support.

**Comment by petermattis** [comment]
@vtolstov is likely referring to [this](http://docs.ceph.com/docs/master/rados/configuration/storage-devices/):

> Direct management of storage devices. BlueStore consumes raw block devices or partitions. This avoids any intervening layers of abstraction (such as local file systems like XFS) that may limit performance or add complexity.

**Comment by petermattis** [comment]
And here is the [source code](https://github.com/ceph/ceph/tree/master/src/os/bluestore) for bluestore. They are definitely implementing their own filesystem on top of a raw block device. Claimed perf benefits:

> 4KB random write IOPS performance increases by 18%, average latency decreases by 15%, and 99.99% tail latency decreases by up to 80%. 4KB random read performance is better at higher queue depths with BlueStore.

This is a really large undertaking, though. Definitely not something that we'd tackle for Pebble any time soon.

**Comment by petermattis** [comment]
Here is a [slide deck](https://www.snia.org/sites/default/files/SDC/2017/presentations/General_Session/Weil_Sage%20_Red_Hat_Goodbye_XFS_Building_a_new_faster_storage_backend_for_Ceph.pdf) on bluestore.

**Comment by vtolstov** [comment]
thank you very much! please don't close this issue for feature reference

**Comment by mqudsi** [comment]
It would be very nice to have this work so that any fs-related issues pertaining to journaling, performance, block size, etc. could all be skipped.

**Comment by vtolstov** [comment]
@petermattis do you have any time to start something that can helps to get bluestore analog ?

**Comment by petermattis** [comment]
@vtolstov We have no concrete plans to work on this.
