### ISSUE TITLE
An invalid file `CURRENT.000015.dbtmp` exists in the directory and cannot be garbage collected.

### ISSUE THREAD

**Issue by iswade** [cockroachdb/pebble#596]
```
-rw-r--r--  1 wade  staff   8.0M  3 29 22:36 000291.sst
-rw-r--r--  1 wade  staff    70M  3 29 22:36 000292.log
-rw-r--r--  1 wade  staff    47M  3 29 22:36 000293.sst
-rw-r--r--  1 wade  staff    16B  3 29 22:35 CURRENT
-rw-r--r--  1 wade  staff    16B  3 29 22:13 CURRENT.000015.dbtmp
-rw-r--r--  1 wade  staff     0B  3 29 22:35 LOCK
-rw-r--r--  1 wade  staff    14K  3 29 22:36 MANIFEST-000023
-rw-r--r--  1 wade  staff   700B  3 29 22:35 OPTIONS-000024
```

**Comment by petermattis** [comment]
@iswade Thanks for the bug report. Can I bother you for some more details? What did you do to get the system into this state? Have you only been using Pebble? Is the extra file harmful? (I don't think it should be, just curious if something is going on that I'm not thinking of).

**Comment by iswade** [comment]
I have only tested this Pebble on Mac OS. Haven't tested Rocksdb.
May be caused by randomly killing the process.
The extra file is currently looking harmless, I can restart the program  and everything is ok.

**Comment by petermattis** [comment]
@jbowens Can you take a look at this? I think what is happening is that if you kill the process in the middle of `setCurrentFile`, the temporary `CURRENT.<filenum>.dbtmp` file can be left around and will not be cleaned up in `Open`. I think the loop in `Open` over the files in the DB directory needs to look for files with this pattern and delete them.

**Comment by iswade** [comment]
Thanks for handling this problem.
