### ISSUE TITLE
perf: pipeline decompression and compression during compaction

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#599]
When looking at CPU profiles, block decompression during reads, and compressing writes, show up significantly. On the read side, it would be nice for that decompression to take place asynchronously via some sort of read-ahead mechanism. On the write side, it would be nice for the compression to take place asynchronously and not block further compaction work. There is a [PR in RocksDB](https://github.com/facebook/rocksdb/pull/6262) that adds a pipeline for the compression side. We should investigate doing something similar.

**Comment by nicktrav** [comment]
The compression piece of this has now been implemented. I've created #1722 for tracking work on the decompression.
