### ISSUE TITLE
Merge Operator Result Recycling

### ISSUE THREAD

**Issue by 256dpi** [cockroachdb/pebble#617]
Thanks for the wonderful library! I'm already using it in two projects and up until now there have been no issues! 👍

I'm intensively using the merge operator with values that need to be decoded and encoded again. While I'm able to pool the used slices for all operations within the operator I'm currently not able to recycle the returned slice. Since the merge is done on every read of a key, at lot of slices are lost.

One solution to the problem would be to allow the operator to return a callback that is closed once the value is not used anymore:

```go
Finish() ([]byte, func(), error) 
Finish() ([]byte, io.Closer, error)  // alternative, similar to other pebble APIs
```

Another option would be to add a `Release` method to the interface that would be called once the result is not used anymore:

```go
type ValueMerger interface {
	MergeNewer(value []byte) error
	MergeOlder(value []byte) error
	Finish() ([]byte, error)

	// Release is closed once the value returned by Finish is not used anymore.
	Release([]byte)
}
```

Let me know what you think, I'm also happy to provide a PR if this would be accepted.

**Comment by petermattis** [comment]
> Thanks for the wonderful library! I'm already using it in two projects and up until now there have been no issues! 

Glad to hear it is working well. Are these public projects? Can you share links? This is mostly just curiosity on my part.

> I'm intensively using the merge operator with values that need to be decoded and encoded again. While I'm able to pool the used slices for all operations within the operator I'm currently not able to recycle the returned slice. Since the merge is done on every read of a key, at lot of slices are lost.

Are the returned slices all similar lengths? Are you iterating over many of them using an `Iterator`, or using `Get` to retrieve records? I ask because another possibility is to change the signature of `Finish()` to take in a slice to use as a buffer. If you're iterating over many records this could cut down the allocations by an order of magnitude or two.

Of the other possibilities you suggest, I prefer the `Finish() ([]byte, io.Closer, error)` approach due to its similarity with the `Get` API.

> Let me know what you think, I'm also happy to provide a PR if this would be accepted.

A PR would be appreciated. Let's figure out the API here first, though.

**Comment by 256dpi** [comment]
> Glad to hear it is working well. Are these public projects? Can you share links? This is mostly just curiosity on my part.

My first project with pebble was https://github.com/256dpi/quasar that is now used in production to manage the incoming message queue for https://shiftr.io. Originally, I just wanted to try out pebble, but it performed so well that I decided to just go ahead with it. The service has run with it now for 9 months without any issue at all processing about 600 writes/sec

My new project, which is using a lot of merge operations, is a framework to build custom app-specific databases. In a nutshell, the idea is to move the code that usually drives the transaction in the app layer to the database and expose it as native db commands to the client. It's quite fresh and not open source yet, I hope to share it soon. If you want to know more I'm happy to continue the discussion offline. :)

> Are the returned slices all similar lengths? Are you iterating over many of them using an Iterator, or using Get to retrieve records? I ask because another possibility is to change the signature of Finish() to take in a slice to use as a buffer. If you're iterating over many records this could cut down the allocations by an order of magnitude or two.

Currently the merges all originate from uniform `Get` calls, but I have features planned that will read the same values from an iterator in the future. Also the values handled by the operator might in the future be of varying sizes.

I have the feeling `Finish([]byte) ([]byte, error)` is hard to optimize as pebble does not know how big the slice should be. The former gives the application the power to decide what's best in the situation. Also it allows the application to not recycle a slice, if for example the length does not match the used buffer pool class. Perhaps there are other internal optimizations this unlocks that I do no see that make it worthwhile.

> Of the other possibilities you suggest, I prefer the Finish() ([]byte, io.Closer, error) approach due to its similarity with the Get API.

I also like the parity with other pebble methods. However, does it make sense to allow the application to return an error? Also, in order to satisfy `io.Closer` you need a pointer to an object. The easiest would be to implement the `Close() error` on the merger itself and just return the merger. As this might be the easiest approach, why not make it the default?

In my application I'm already obtaining the `ValueMerger` objects from a pool and releasing them back when `Finish` is called. In my case the cleanest would be to have the additional `Close` method that could be used to release the merger and also return the slice. Actually, If the merger is already pooled it could just provide the backing array for the slice and reuse it.

Summarizing the last bits, it would look like that:

```go
var mergerPool = sync.Pool{
	New: func() interface{} {
		return &merger{}
	},
}

var pebbleMerger = &pebble.Merger{
	Name: "merger",
	Merge: func(key, value []byte) (pebble.ValueMerger, error) {
		return mergerPool.Get().(*merger), nil
	},
}

type merger struct {
	result [1024]byte
}

func (m *merger) MergeNewer(value []byte) error { /* ... */ }
func (m *merger) MergeOlder(value []byte) error { /* ... */ }

func (m *merger) Finish() ([]byte, error) {
	// write some data to buffer
	buf := m.result[:]
	return buf, nil
}

func (m *merger) Close() error {
	mergerPool.Put(m)
	return nil
}

// alternative Finish
func (m *merger) Finish() ([]byte, io.Closer, error) {
	// write some data to buffer
	buf := m.result[:]
	return buf, m, nil
}
```

**Comment by petermattis** [comment]
> I also like the parity with other pebble methods. However, does it make sense to allow the application to return an error? Also, in order to satisfy io.Closer you need a pointer to an object. The easiest would be to implement the Close() error on the merger itself and just return the merger. As this might be the easiest approach, why not make it the default?

This sounds good to me. I think this approach is ready for implementation.

**Comment by 256dpi** [comment]
While working at the PR, I identified some opportunities to clarify others things and potentially further improve the interface:

1. Currently the direction of a merge is never changed. If the direction is passed to the merger upon construction e.g. `type Merge func(key, value []byte, reverse bool) (ValueMerger, error)` we could reduce the interface to just one `Merge(value []byte) error` method. Unless, there might be a future scenario where a direction change is needed it, it would make this aspect much more simpler. (No need to needlessly reverse the arrays)

2. Is it correct that upon calling `Finish()` a full sequence of merge values has peen passed to the operator? Or is there a situation currently, or in the future, where the operator would only operate on a part of a merge value sequence? In the former case it would be nice to document the guarantee, in the later I would suggest to indicate the situation e.g. `Finish(partial bool) ([]byte, io.Closer, error)`.

Some context: In my application I use operators to mutate base values. Depending on the nature of the operator, the operands may itself not be mergeable. In that situation and If the operands do not start with a base value, I'm stacking the merge operands in the background and compute the final value once the stack has been returned during iteration. If `Finish(false)` would be called, I could retrieve the zero value of the first operator and compute the full value already in the operator. This would make iteration more efficient and also allow better compaction.

**Comment by petermattis** [comment]
> Currently the direction of a merge is never changed. If the direction is passed to the merger upon construction e.g. type Merge func(key, value []byte, reverse bool) (ValueMerger, error) we could reduce the interface to just one Merge(value []byte) error method. Unless, there might be a future scenario where a direction change is needed it, it would make this aspect much more simpler. (No need to needlessly reverse the arrays)

I can't imagine a scenario where a direction change would occur. That said, I'm not sure if the proposed change is significantly better than the current API. And any change we make here would affect existing users (e.g. CockroachDB).

> Is it correct that upon calling Finish() a full sequence of merge values has peen passed to the operator? Or is there a situation currently, or in the future, where the operator would only operate on a part of a merge value sequence? In the former case it would be nice to document the guarantee, in the later I would suggest to indicate the situation e.g. Finish(partial bool) ([]byte, io.Closer, error).

No, this isn't correct. See `compactionIter` which can merge a partial set of values because compaction iteration will only see the merge records in the compaction inputs. During compaction we rarely have the full set of merge operands, but we can detect when the oldest merge operand is encountered. That sounds slightly different than "partial", but I think it is what you're looking for. Any suggestions for a better term than "partial"?

**Comment by 256dpi** [comment]
> I can't imagine a scenario where a direction change would occur. That said, I'm not sure if the proposed change is significantly better than the current API. And any change we make here would affect existing users (e.g. CockroachDB).

The change would make an optimization clearer: I use the same approach as in cockroach's `MVCCValueMerger` which is to reverse the slice if necessary before doing a merge or obtaining the result. Since most of the time (compaction, forward iteration) `MergeOlder` is called, the slice is probably reversed in most calls to `Finish()` as it requires forward ordering. If the direction would be static the slice could just be iterated in reverse at the end if necessary. The proposed API would suggest that approach. However, the performance benefit is probably negligible. If documented properly, the same improvement could be achieved with the current API, the contract ist just a little weaker.

> No, this isn't correct. See compactionIter which can merge a partial set of values because compaction iteration will only see the merge records in the compaction inputs. During compaction we rarely have the full set of merge operands, but we can detect when the oldest merge operand is encountered. That sounds slightly different than "partial", but I think it is what you're looking for. Any suggestions for a better term than "partial"?

I see, makes sense! The only alternative I could think of is "complete" which of course would be true if all operands are present. However "partial" still sounds best to me as it encodes that an operator usually sees the full set, but just sometimes a partial one during compaction. It would properly suggest which path should be more optimized.

**Comment by petermattis** [comment]
> I see, makes sense! The only alternative I could think of is "complete" which of course would be true if all operands are present. However "partial" still sounds best to me as it encodes that an operator usually sees the full set, but just sometimes a partial one during compaction. It would properly suggest which path should be more optimized.

`complete` is accurate either as `compactionIter` often won't have all of the merge operands for a particular key. How about the term `base`? I think this matches the actual behavior which is that the merge has included the base merge operand. This would be set to true when `compactionIter` knows there will be no more older merge operands, though there might be newer ones which were not part of the compaction.

**Comment by 256dpi** [comment]
In general `base` sounds good to me, all tough I personally would favor `includesBase` to make it even more clearer. Shall I look into a PR?
