### ISSUE TITLE
Check for SSTable size consistency between manifest and disk

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#651]
RocksDB regularly does a consistency check to see if the on-disk size of an SSTable matches the size recorded in the manifest. It would be worthwhile to see why RocksDB does this check, and to replicate it in Pebble.

https://github.com/cockroachdb/rocksdb/blob/e494e15a0b08c13fafd5710f279f348d47d476de/db/db_impl.cc#L2956

**Comment by petermattis** [comment]
Looks like this check is done once at startup: https://github.com/facebook/rocksdb/commit/e67241f0b92e2b922cbf58fcfea98926c7c440ce

In addition to checking the sstable size, this also checks that the sstable exists. Seems reasonable to add as a sanity check to Pebble.
