### ISSUE TITLE
db: add DB.GetTableProperties

### ISSUE THREAD

**Issue by 3pointer** [cockroachdb/pebble#665]
Hi, I got a question when try to use pebble.

I want to seek all approximate size(100M) keys without iterate the whole data.
so I need a rangeTableProperty, record offset of key after it was add into table every time.
but I didn't find the way to retrieve all tableProperties with given `*pebble.DB`.

I want to know is there a way to get customer tableProperty of all tables at same time? just like [rocksdb](https://github.com/facebook/rocksdb/blob/ab13d43e1dcf35458f7a025f3b95bf69df371c7b/db/db_impl/db_impl.cc#L2897) 

Thank you.

**Comment by petermattis** [comment]
@3pointer Can you elaborate on what you're trying to do? Adding a table property that is the record offset of every key is super expensive. Perhaps I'm not understanding what your table property is capturing. I don't understand the sentence about wanting to seek all the keys without iterating the whole data.

**Comment by 3pointer** [comment]
Sure, I'm trying to record some keys and size offset in tableProperty. not every key, if default size is 10MB, then I'll record the key every 10MB, the code looks like

```
type RangeSize struct {
	key []byte
	size int
}
type RangePropertiesCollector struct {
	lastKey pebble.InternalKey

	curSize int
	lastSize int

	offsets []RangeSize
}

func (c *RangePropertiesCollector) Add(key pebble.InternalKey, value []byte) error {
	size := key.Size() + len(value)

	c.curSize += size

	// lastKey not exists or curSize - lastSize > 10MB
	if len(c.lastKey.UserKey) == 0 || ((c.curSize - c.lastSize) > (10<<20)) {
		c.lastSize = c.curSize
		c.offsets = append(c.offsets, RangeSize{key: key.UserKey, size: c.curSize})
	}
	c.lastKey = key
	return nil
}

func (c *RangePropertiesCollector) Finish(userProps map[string]string) error {
	// encode c.offsets to string
	// userProps["test.key-range"] = ...
	return nil
}
```

so, if I can retrieve `test.key-range` of all tables, I will know all record key and its size and offset. then I can choose some record key with approximate size(100M) without iterator.

**Comment by petermattis** [comment]
> so, if I can retrieve test.key-range of all tables, I will know all record key and its size and offset. then I can choose some record key with approximate size(100M) without iterator.

I'm still not clear on what you're trying to do here. I don't understand what it means to "choose some record key with approximate size(100M)". Are you trying to read a random key with some probability? Perhaps it would help my understanding if you shared how you expect to use this property data.

The property data you're collecting is actually quite similar to the data stored in an sstable index block. The index block data isn't available for public consumption, though. Just pointing that out to make sure my understanding is correct.

**Comment by 3pointer** [comment]
> I'm still not clear on what you're trying to do here. I don't understand what it means to "choose some record key with approximate size(100M)". Are you trying to read a random key with some probability?

Sorry for that I was not elaborate clearly, what I want actually is divided total sorted kv pairs into ranges with appropriate size.

let assume the size of total kv pairs start from `a` to `z` is 1GB, then the ranges after divided by 100MB maybe looks like 

`Range{LowerBound: a, UpperBound:c}`,`Range{LowerBound: c, UpperBound:e}...`

so that I can iterator ranges concurrently.

> Perhaps it would help my understanding if you shared how you expect to use this property data.

after collect all property, if there is a way to get all tables property

```
allProperties := getAllTablesProperty(db)
for _, p := range allProperties {
        rangeSizes := decodeToRangeSizes(p, "test.key-range")
        preSize := 0
        for _, r := range rangeSizes {
                    
                 // r.Size - preSize means the real size between keys
                 // put r.Key, r.Size - preSize into sorted map.

                 preSize = r.Size
        }
} 
```

if I'm correct, then I will get some keys and its size between last key in sorted map. 

Thanks for help again.

**Comment by petermattis** [comment]
Ok, this all makes sense. I'm good with adding a function like `DB.GetTableProperties(start, end)` (i.e. similar to RocksDB's `GetPropertiesOfTablesInRange`). Note that this is going to be somewhat expensive as it will read the properties from disk if the table is not in the table cache. We have no immediate needs for this, so if you'd like to see this added soon, please send a PR.

An alternative to the table property approach is to use `DB.SSTables()` which will provide you the start and end key for each sstable and its size. You don't get control over where these keys are set, and the granularity is at the level of an sstable, but `DB.SSTables()` is super quick (all of the sstable metadata is guaranteed to be in memory) and you'd still be able to iterate over ranges concurrently.

**Comment by 3pointer** [comment]
Thanks for the answer. 

> An alternative to the table property approach is to use `DB.SSTables()` which will provide you the start and end key for each sstable and its size.

`DB.SSTables()` seems good.  I print all table info in my scenario, the size of each table is around 10M. I wonder is there a way to control the size of each table at beginning?

**Comment by petermattis** [comment]
> I wonder is there a way to control the size of each table at beginning?

You don't get perfect control over the table size as there are multiple factors affecting it. The `LevelOptions.TargetSize` option does provide some control.
