### ISSUE TITLE
internal/manual: delete empty assembly file

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/pebble#680]
This file breaks the cockroachdb tests: https://github.com/cockroachdb/cockroach/issues/49154

Empty assembly files are not needed since Go 1.12. If they are used for compatibility with older versions of go, they need to contain the magic directives from https://github.com/cockroachdb/cockroach/pull/37939/files to avoid changing the security properties of the final binary.

**Comment by petermattis** [comment]
Care to send a PR?

Also, why did this only suddenly break things? Or has this been broken for a while?

**Comment by petermattis** [comment]
Oh, we only recently added this empty `.s` file. Got it. I'll remove.
