### ISSUE TITLE
db: provide more specific errors for exceeding max batch and memtable size

### ISSUE THREAD

**Issue by nnsgmsone** [cockroachdb/pebble#702]
I encountered such an error while running, my batch size is very large, there are several G. Is there a limit to the size of the batch?
![2020-05-21 14-35-56 的屏幕截图](https://user-images.githubusercontent.com/31609524/82530736-8ba96b80-9b70-11ea-90a8-bf0a307fe61f.png)
Below is my packaging code. . Is there a problem with my usage?
![2020-05-21 14-37-57 的屏幕截图](https://user-images.githubusercontent.com/31609524/82530818-b72c5600-9b70-11ea-9b14-e77d58771c10.png)
![2020-05-21 14-38-06 的屏幕截图](https://user-images.githubusercontent.com/31609524/82530822-ba274680-9b70-11ea-9d07-95a1c0309ec6.png)

**Comment by nnsgmsone** [comment]
After I increased the size limit of the batch, the problem seemed to be no longer encountered. Is it because of this? I think an option should be added, if the size limit of the batch is exceeded, then set and delete should report errors.

**Comment by nnsgmsone** [comment]
![2020-05-21 15-09-13 的屏幕截图](https://user-images.githubusercontent.com/31609524/82533047-2015cd00-9b75-11ea-83f8-10b3555108b6.png)

**Comment by petermattis** [comment]
@nnsgmsone Batches have a size limit of 4GB. I'm not sure of all the places that arises. I see at least `flushableBatchEntry.offset`, `DeferredBatchOp.offset`, and `internal/batchskl.node.offset`, which are all 32-bit values. Changing this is unlikely to occur, though we should make the failure mode more obvious. Out of curiosity, why do you need such a large batch? Do you really need to atomically commit multiple GBs? Could you use `DB.Ingest` instead? I suspect `DB.Ingest` would be much faster and you could avoid ever keeping multiple GBs in memory at once.

> After I increased the size limit of the batch, the problem seemed to be no longer encountered.

How did you "increase the size limit of the batch"? As I mentioned above, there are a lot of 32-bit values that you'd have to change.

**Comment by nnsgmsone** [comment]
I set the memtablesize with the following method:
![2020-05-21 20-35-03 的屏幕截图](https://user-images.githubusercontent.com/31609524/82559841-df34ad00-9ba2-11ea-8baa-7e9769dc9bbe.png)
@petermattis

**Comment by petermattis** [comment]
`MemTableSize` is not the same as batch size. All of my previous comments stand. Batches cannot be larger than 4 GB.

**Comment by petermattis** [comment]
Additionally, the memtable cannot be larger than 4 GB as `internal/arenaskl.node.keyOffset` is a 32-bit value. Using such a large memtable is likely to have bad performance characteristics anyways. Again, we should make the failure mode when a user tries to do this clearer.

**Comment by nnsgmsone** [comment]
Thank you, in order to speed up the insert. . . Did some bad handling. .

**Comment by petermattis** [comment]
If you benchmark, you'll find that increasing batch size or memtable size reaches a limit where further increases do not speed up inserts. For fastest ingestion of data, use `DB.Ingest`.

**Comment by nnsgmsone** [comment]
Thanks, I tried
