### ISSUE TITLE
perf: scalability with large sstable counts

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#718]
Performing some testing on a DB with a very large sstable count (600k+ sstables) shows a few areas where O(num-sstable) work starts becoming a problem. For reference, here is a snapshot of the LSM:

```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1   3.5 M       -    17 G       -       -       -       -    17 G       -       -       -     1.0
      0         0     0 B    0.00    17 G    19 G   1.3 K     0 B       0   2.2 G   1.3 K     0 B       0     0.1
      1        16    62 M    0.97    18 G     0 B       0     0 B       0    73 G    20 K    74 G       1     4.0
      2       167   671 M    1.00   3.6 G     0 B       0    17 G   4.4 K    14 G   3.6 K    14 G       1     3.8
      3      1776   6.9 G    1.00   966 M     0 B       0    19 G   4.9 K   3.7 G     564   3.9 G       1     3.9
      4      4168    13 G    0.18   2.9 G    46 M       3    10 G   2.6 K   3.9 G   1.7 K   4.0 G       1     1.4
      5     51292   755 G    1.00   4.3 M   1.2 T    83 K    29 M       6   4.7 M      12   4.7 M       1     1.1
      6    548912   7.7 T       -   462 G   7.3 T   580 K    62 M       6   938 G    31 K   949 G       1     2.0
  total    606331   8.5 T       -   8.5 T   8.5 T   664 K    46 G    12 K   9.5 T    59 K   1.0 T       6     1.1
  flush      1322
compact     45626     0 B          (size == estimated-debt)
 memtbl         1    64 M
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache     672 K   7.5 G   72.6%  (score == hit-rate)
 tcache     121 K    66 M   99.8%  (score == hit-rate)
 titers         0
 filter         -       -   90.4%  (score == utility)
```

Committing a new version creates a new `readState` via `DB.updateReadStateLocked`. If the old `readState` is no longer referenced we call `Version.UnrefLocked` which calls `Version.unrefFiles`. Looping over all of the sstables in the version to decrement their reference counts takes a non-trivial amount of time.

```
    334            .          .           func (v *Version) unrefFiles() []base.FileNum { 
    335            .          .           	var obsolete []base.FileNum 
    336            .          .           	for _, files := range v.Files { 
    337         20ms       20ms           		for i := range files { 
    338            .          .           			f := files[i] 
    339        3.89s      3.89s           			if atomic.AddInt32(&f.refs, -1) == 0 { 
    340         10ms       10ms           				obsolete = append(obsolete, f.FileNum) 
    341            .          .           			} 
    342            .          .           		} 
    343            .          .           	} 
    344            .          .           	return obsolete 
    345            .          .           } 
```

When a new version is installed, we recompute the size of each level from scratch. This also shows up on CPU profiles. Given that we know the previous versions level sizes and the files that were added, we could perform this computation incrementally.

```
    471            .          .           	for i := range vs.metrics.Levels { 
    472            .          .           		l := &vs.metrics.Levels[i] 
    473            .          .           		l.NumFiles = int64(len(newVersion.Files[i])) 
    474            .      640ms           		l.Size = uint64(totalSize(newVersion.Files[i])) 
    475            .          .           		l.Sublevels = 0 
    476            .          .           		if l.NumFiles > 0 { 
    477            .          .           			l.Sublevels = 1 
    478            .          .           		} 
    479            .          .           	} 
```

Applying the version edit to build a new version also does O(num-sstable) operations. For unchanged levels, we still have to increment the reference counts:

```
    506            .          .           			// We still have to bump the ref count for all files. 
    507        670ms      670ms           			for i := range files { 
    508            .          .           				atomic.AddInt32(&files[i].refs, 1) 
    509            .          .           			} 
    510            .          .           			continue 
```

For changed levels, we see the cost of building up the new `[]*FileMetadata` slice:

```
    593            .          .           			// Add the preceding files from currFiles. 
    594         40ms       40ms           			for k := 0; k < j; k++ { 
    595            .          .           				cf := currFiles[k] 
    596        880ms      950ms           				if deletedMap[cf.FileNum] { 
    597            .          .           					addZombie(cf.FileNum, cf.Size) 
    598            .          .           					continue 
    599            .          .           				} 
    600         10ms       30ms           				removeZombie(cf.FileNum) 
    601         30ms       30ms           				atomic.AddInt32(&cf.refs, 1) 
    602        390ms      410ms           				v.Files[level] = append(v.Files[level], cf) 
    603            .          .           			} 
...
    626            .          .           		// Add any remaining files in currFiles that are after all the added files. 
    627         20ms       20ms           		for i := range currFiles { 
    628         20ms       20ms           			f := currFiles[i] 
    629        490ms      550ms           			if deletedMap[f.FileNum] { 
    630            .          .           				addZombie(f.FileNum, f.Size) 
    631            .          .           				continue 
    632            .          .           			} 
    633         10ms       10ms           			removeZombie(f.FileNum) 
    634            .          .           			atomic.AddInt32(&f.refs, 1) 
    635        240ms      270ms           			v.Files[level] = append(v.Files[level], f) 
    636            .          .           		} 
```

**Comment by petermattis** [comment]
I suspect at some point we'll need to replace using `[]*FileMetadata` to represent the metadata for a level with Something Else. The O(n) operations are painful when n is close to 1 million. A copy-on-write btree, such as the one used for [interval btrees](https://github.com/cockroachdb/cockroach/blob/master/pkg/util/interval/generic/internal/interval_btree_tmpl.go) in CRDB is one possibility. The btree naturally maintains the `*FileMetadata` in sorted order. Updating the level then becomes an O(logn) operation, rather than the current O(n) operation. Making this change would be quite involved as we pass around sub-slices of `[]*FileMetadata` in a lot of places to represent a contiguous range of sstables in a level. Any replacement for `[]*FileMetadata` would have to pass around some sort of `LevelSlice` composed of a start and end point (e.g. a start and end iterator). 

The btree approach could also alleviate the pain of decrementing the reference counts for all sstables when a `Version` is unreferenced. We could change the `FileMetadata` reference count semantics so that a `FileMetadata` is referenced when it is added to a btree node and decremented when it is removed or when the btree node is deleted. Cloning a btree node would have to increment the reference counts of the `*FileMetadata` on that node, but that is a lot less reference counting that currently takes place when a `Version` is created and when it is unreferenced.

Cc @nvanbenschoten in case you have opinions on this data structure problem.

**Comment by nvanbenschoten** [comment]
What are the concurrency requirements here? The copy-on-write btree trades O(1) time snapshots for O(log n) space mutations. However, there's a [fast-path](https://github.com/cockroachdb/cockroach/blob/9708a82d64bc4802b31baf2e5199281112c4fc1e/pkg/util/interval/generic/internal/interval_btree_tmpl.go#L156-L159) to avoid this if a node in the tree has already been copied since the last clone. So without any clones, the copy-on-write abstraction cost reduces down to just that of atomic operations during tree transformations, which may or may not be negligible for your use case.

Also, do you need to be able to query over intervals? If not, you might want to strip out the interval augmentation.

> We could change the FileMetadata reference count semantics so that a FileMetadata is referenced when it is added to a btree node and decremented when it is removed or when the btree node is deleted.

Using the tree's internal reference counting and exposing a callback for items when their nodes are removed is a neat idea. It shouldn't be too hard to do.

**Comment by petermattis** [comment]
> What are the concurrency requirements here? The copy-on-write btree trades O(1) time snapshots for O(log n) space mutations. However, there's a fast-path to avoid this if a node in the tree has already been copied since the last clone. So without any clones, the copy-on-write abstraction cost reduces down to just that of atomic operations during tree transformations, which may or may not be negligible for your use case.

A `Version` is immutable once created. So write once, then read frequently. The reads need to happen concurrently. Right now, the creation of a `Version` requires O(n) operations (where n is the number of sstables). For levels which haven't changed, we're sharing the slice, but we have to bump the reference counts on the `*FileMetadata`. For levels that have changed, we allocate a new slice. The more I think about it, the more this seems like a great fit for a copy-on-write btree.

> Also, do you need to be able to query over intervals? If not, you might want to strip out the interval augmentation.

No, there is no need to query over intervals. The `*FileMetadata` are guaranteed to cover non-overlapping ranges. Would be fun to copy this code back into Pebble again. I wonder how many times we can ping-pong it back and forth?

**Comment by jbowens** [comment]
I think this is good to close out. There's still a remaining _O_(# sstables) bottleneck in CockroachDB's routine to calculate available capacity, but that's outside of Pebble.

**Comment by jbowens** [comment]
I spoke too soon...

This devolves into O(# sstables) for flushes of sstables with broad key distributions. 
```
func (c *compaction) setupInuseKeyRanges() {
	level := c.outputLevel.level + 1
	if c.outputLevel.level == 0 {
		// Level 0 can contain overlapping sstables so we need to check it for
		// overlaps.
		level = 0
	}

	// Gather up the raw list of key ranges from overlapping tables in lower
	// levels.
	var input []userKeyRange
	for ; level < numLevels; level++ {
		overlaps := c.version.Overlaps(level, c.cmp, c.smallest.UserKey, c.largest.UserKey)
		iter := overlaps.Iter()
		for m := iter.First(); m != nil; m = iter.Next() {
			input = append(input, userKeyRange{m.Smallest.UserKey, m.Largest.UserKey})
		}
	}

	if len(input) == 0 {
		// Nothing more to do.
		return
	}

	// Sort the raw list of key ranges by start key.
	sort.Slice(input, func(i, j int) bool {
		return c.cmp(input[i].start, input[j].start) < 0
	})

	// Take the first input as the first output. This key range is guaranteed to
	// have the smallest start key (or share the smallest start key) with another
	// range. Loop over the remaining input key ranges and either add a new
	// output, or merge with the last output.
	c.inuseKeyRanges = input[:1]
	for _, v := range input[1:] {
		last := &c.inuseKeyRanges[len(c.inuseKeyRanges)-1]
		switch {
		case c.cmp(last.end, v.start) < 0:
			c.inuseKeyRanges = append(c.inuseKeyRanges, v)
		case c.cmp(last.end, v.end) < 0:
			last.end = v.end
		}
	}
}
```

**Comment by petermattis** [comment]
Nice find. Feels like `setupInuseKeyRanges` could be made more intelligent for L0 using the L0-sublevels information.

**Comment by jbowens** [comment]
As far as I know, the in-use key ranges are only used for eliding tombstones that we know don't cover keys because they don't overlap any lower sstables. If there are many<sup>1</sup> overlapping sstables within the compaction key range, we could use the start boundary of the first table and the end boundary of the last table within each level. This would just about disable the eliding optimization for these compactions, but the in-use range is probably already very dense if there are many sstables.

Calculating how many files overlap a range within a level could be done with a `manifest.Annotator` like the [`orderStatistic`](https://github.com/cockroachdb/pebble/blob/39fe91db49c0b9a57980850aa75c715777a49f8a/internal/manifest/btree_test.go#L519) annotator we use in the B-Tree tests, which would allow us to efficiently query the length of a `manifest.LevelSlice`. Or we could use the fact that the B-Tree is balanced and a B-Tree node has min and max item counts to calculate a lower or upper bound on the number of files within a `manifest.LevelSlice`.

<sup>1</sup> – I'm not sure how to choose how many is many, and it would probably end up being an arbitrary choice.

---

Another option is to continue to exactly calculate the covered bounds but use the in-use ranges from higher levels to repeatedly seek within the lower level's files. The broader higher-level sstable bounds should let us seek over most of the lower-level sstables. I'm thinking of trying this first, although I'm a little worried that all the seeking might be slow down stores with lower sstable counts.
