### ISSUE TITLE
internal/manifest: error when picking base compaction...should not be compacting

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#739]
I experimented with enabling `L0SublevelCompactions` in the `pebble bench ycsb` benchmark. Running `--workload=A`, I saw a lot of errors of the form: `error when picking base compaction: file 5603 chosen as seed file for compaction should not be compacting`. Is this concerning?

**Comment by itsbilal** [comment]
@petermattis Do you mind elaborating the ycsb workload and pebble options you ran this with, where you saw these errors show up very regularly?

**Comment by petermattis** [comment]
I believe it was something like `pebble bench ycsb /mnt/data1/bench --engine=pebble --wipe --workload=A --concurrency=256 --values=1024 --initial-keys=10000000 --cache=$[4 * 1024 * 1024 * 1024] --duration=10m`.
