### ISSUE TITLE
tool: Encode sublevels more efficiently in LSM visualization

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#764]
Currently, in the JS LSM visualization tool, we encode a map of L0 files to their sublevel at each version edit in a manifest. This is way too inefficient as the number of files and number of version edits grows; it's not uncommon to see the tool outputting 500MB+ html files, which take forever to parse in a browser.

Using a more efficient JSON encoding (such as only representing file additions/deletions by sublevel) will greatly help in reducing this overhead.

**Comment by petermattis** [comment]
From a Slack comment:

> Right now a version edit has Added and Deleted files per Level. That could be extended to sublevels by using a negative level number to indicate a sublevel. The challenge then is computing that info.
