### ISSUE TITLE
internal/metamorphic: test failure "files have overlapping ranges"

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#770]
In c577a10 I added both the new `delete_range_flush_delay` option and the `l0_sublevel_compactions` option to the OPTIONS file. I ran `make stressmeta` and it produced this failure. I'm not sure yet if it's a product of  `delete_range_flush_delay` or `l0_sublevel_compactions`.

```
TestMeta/random-004: meta_test.go:200:
        ===== ERR =====
        exit status 1
        ===== OUT =====
        pebble: internal error: L6 files 000742 and 001624 have overlapping ranges: [zyebvfvdxx#0,SET-zyebvfvdxx#0,SET] vs [zyebvfvdxx#0,SET-zyebvfvdxx#0,SET]
```

```
go test -v -run 'TestMeta' -run-dir ./200623-171311.897/random-004
```

[200623-171311.897.zip](https://github.com/cockroachdb/pebble/files/4822736/200623-171311.897.zip)

**Comment by petermattis** [comment]
This is almost certainly due to `l0_sublevel_compactions` as we're not setting `delete_range_flush_delay` in `pebble/metamorphic/options.go` yet.

**Comment by jbowens** [comment]
Might be related: The PR to bump pebble to a SHA that includes c577a10 in cockroach hit a pkg/storage/metamorphic failure:

```
------- Stdout: -------
=== RUN   TestRocksPebbleEquivalence/seed=5577006791947779410/pebble_var_opts
check file = /tmp/TestRocksPebbleEquivalence_seed=5577006791947779410846279354/output.meta
output file = /tmp/TestRocksPebbleEquivalence_seed=5577006791947779410_pebble_var_opts739497359/output.meta
store path = /tmp/TestRocksPebbleEquivalence_seed=5577006791947779410_pebble_var_opts832664482/store
panic: file deleted 14 before it was inserted
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=2035445&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

**Comment by petermattis** [comment]
@itsbilal Just saw the `file deleted X before it was inserted` error on the Pebble metamorphic test: https://travis-ci.org/github/cockroachdb/pebble/jobs/701772739. The full history is there in case it is necessary for reproduction.
