### ISSUE TITLE
internal/metamorphic: enhance by printing a prng seed on failure

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#785]
When the metamorphic tests fail in CI, it prints the history diff, options and operations for debugging. It seems like we might be able to make it easier to debug and reproduce by printing the prng seed from which the operations and random options were deterministically generated. If we add a `--seed` flag, we could reproduce a CI failure on the same SHA easily.

**Comment by petermattis** [comment]
I think this should work, especially if you are testing on the same SHA. If we make extensions to the metamorphic test the same seed could produce different values, but on a given SHA I think the generation is deterministic.
