### ISSUE TITLE
db: panic on DB.Flush

### ISSUE THREAD

**Issue by reusee** [cockroachdb/pebble#786]
I saw the following panic.
No reproduce yet.

pebble version: v0.0.0-20200629192910-ba0024f2d091
os: macOS 10.15.5
go version: 1.14

```
panic: rename /Users/reus/Library/Mobile Documents/com~apple~CloudDocs/ling-store/pebble/values/033589.log /Users/reus/Library/Mobile Documents/com~apple~CloudDocs/ling-store/pebble/values/033591.log: no such file or directory
```
```
goroutine 1 [running]:
github.com/cockroachdb/pebble.(*DB).makeRoomForWrite(0xc000314a80, 0x0, 0xc0000002b8, 0x0)
	/Users/reus/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200629192910-ba0024f2d091/db.go:1370 +0x1093
github.com/cockroachdb/pebble.(*DB).AsyncFlush(0xc000314a80, 0x0, 0x0, 0x0)
	/Users/reus/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200629192910-ba0024f2d091/db.go:1033 +0x112
github.com/cockroachdb/pebble.(*DB).Flush(...)
	/Users/reus/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200629192910-ba0024f2d091/db.go:1008
```

**Comment by petermattis** [comment]
@reusee This will be hard to debug without a reproduction. Are you sure that nothing else on the system could have removed the `.log` file from underneath Pebble? Can you share the contents of your `OPTIONS-*` file?

**Comment by reusee** [comment]
@petermattis I'm sure no other process was deleting those files. They were empty since I was not doing any update operation, just calling Flush periodically. 

contents of OPTION file:
```
[Version]
  pebble_version=0.1

[Options]
  bytes_per_sync=524288
  cache_size=33554432
  cleaner=delete
  comparer=leveldb.BytewiseComparator
  delete_range_flush_delay=0s
  disable_wal=false
  flush_split_bytes=0
  l0_compaction_concurrency=10
  l0_compaction_threshold=4
  l0_stop_writes_threshold=12
  l0_sublevel_compactions=false
  lbase_max_bytes=67108864
  max_concurrent_compactions=1
  max_manifest_file_size=134217728
  max_open_files=1000
  mem_table_size=4194304
  mem_table_stop_writes_threshold=2
  min_compaction_rate=4194304
  min_flush_rate=1048576
  merger=pebble.concatenate
  table_property_collectors=[]
  wal_dir=

[Level "0"]
  block_restart_interval=16
  block_size=4096
  compression=Snappy
  filter_policy=none
  filter_type=table
  index_block_size=4096
  target_file_size=2097152

```

**Comment by petermattis** [comment]
> @petermattis I'm sure no other process was deleting those files. They were empty since I was not doing any update operation, just calling Flush periodically.

Can you share your code? Even if you can't reproduce, that can be helpful for understanding what you were doing.

**Comment by reusee** [comment]
@petermattis I'm afraid not but I can confirm that only the Flush code path was covered. I suspect that the root cause was the iCloud Drive. Maybe the cloud syncing mechanism caused the files to be unavailable just when Flush called. I'm not sure. I've never seen this issue on linux machines. Maybe it's not pebble but the file system's problem.

**Comment by petermattis** [comment]
I'm definitely suspicious of iCloud Drive. I've never run Pebble on that filesystem. It could very well be doing something funky. Is using iCloud Drive a requirement? I'm going to try and stress the use of Flush and see if I can shake anything loose.

**Comment by reusee** [comment]
@petermattis I'm developing a file backup tool and using Pebble to index meta-datas. Putting Pebble files under iCloud Drive gives free syncing support. Maybe it's not a good idea since syncing from the cloud may make the data dir inconsistent with what Pebble process is expecting.

**Comment by reusee** [comment]
I found that iCloud Drive will actually delete some local files that have been uploaded to the cloud.
It was not Pebble's issue so I'm closing this.

**Comment by petermattis** [comment]
> I found that iCloud Drive will actually delete some local files that have been uploaded to the cloud.
It was not Pebble's issue so I'm closing this.

Wow! Fascinating. Thanks for the follow-up.
