### ISSUE TITLE
internal/cache: has non-zero reference count

### ISSUE THREAD

**Issue by nnsgmsone** [cockroachdb/pebble#790]
I run multiple instances of pebble on the same machine, and then I got the following error:
```
pebble: cache() hash non-zero reference count: 2
```

Below is my code to call pebble:
```
pebble.Open(name, &pebble.Options{
        FS:          nil,
        MemTableSize: 0,
        ReadOnly:     false,
        DisableWAL:   true,
})
```

**Comment by petermattis** [comment]
@nnsgmsone Thanks for the report. Did you by chance copy that error message by hand? The message you provided does not actually exist in the Pebble code, but a very similar one does: `pebble: cache (%p) has non-zero reference count: %`. This error indicates a problem with the reference counting of the `Cache` structure. Given the code you provided, is it possible that you forgot to call `DB.Close`?

**Comment by nnsgmsone** [comment]
@petermattis Yes, my copy is missing %p. In my example, I opened 10 instances, and then closed each one in succession (but during this period, a new instance was opened, and the new instance may have this error).I think the cache of each instance should not be shared. what caused the error。

**Comment by petermattis** [comment]
> @petermattis Yes, my copy is missing %p. In my example, I opened 10 instances, and then closed each one in succession (but during this period, a new instance was opened, and the new instance may have this error).I think the cache of each instance should not be shared. what caused the error。

Your error message also has the term `hash`, rather than `has`. Was that a copying error on your part?

It is fine to share a cache between DB instances. It is fine for each DB instance to have its own cache. Both approaches work. Even when each DB instance has its own cache, there will be multiple references added to the cache for the various components. For example, each open sstable maintains a reference to the cache. You need to properly close the DB and any opened Iterators for this to be able to work properly. The error is indicating that you missed a close somewhere. There are two objects (the DB, an `sstable.Iterator`, a `tableCache` shard) that are holding references to the cache.

I'm pretty sure this is a bug in your code. If you can provide code to reproduce I'm happy to take a look and verify that is the case.

**Comment by nnsgmsone** [comment]
@petermattis yes, is a copying error on my part. I submitted an example that can reproduce the error。[pebbletest](https://github.com/nnsgmsone/pebbletest)。The key point of my doubt is why different pebble will affect each other, my original usage is that each pebble will not be closed (because I need to reuse)。In the project, as long as the close is removed, it will cause an error. The specific code is in test/main.go:
```
func test(rs routines.Routines) {
    ts := make([]*unit, 10)
    qs := make([]queue.Queue, 0, 10)
    for i := 0; i < 10; i++ {
        q := queue.New(fmt.Sprintf("%v.q", atomic.AddUint32(&cnt, 1)), 100, []string{"a", "b"})
        ts[i] = &unit{q, make(chan task.TaskResult, 1)}
        rs.AddTask(ts[i])
    }
    for _, t := range ts {
        r := <-t.ch
        if err := r.Error(); err != nil {
            for _, q := range qs {
                q.Destroy()
            }
            log.Fatal(err)
        }
        qs = append(qs, r.Result().(queue.Queue))
    }
    for _, q := range qs {
        for {
            mp, err := q.Pop()
            if err != nil {
                break
            }
            if mp == nil {
                break
            }
        }
        // q.Destroy() // crash after remove
    }
}                    
```

**Comment by petermattis** [comment]
> The key point of my doubt is why different pebble will affect each other, my original usage is that each pebble will not be closed (because I need to reuse)。

I suspect you're misunderstanding the error. The different Pebble instances are not interacting with each other. You're failing to close one or more instances and then those instances are getting garbage collected by the Go runtime. When that happens, in race builds a finalizer on the cache object gets invoked and that finalizer says "hey, you're doing something wrong here as my reference count wasn't properly decremented before I was garbage collected".

> In the project, as long as the close is removed, it will cause an error. The specific code is in test/main.go:

Yep, this is expected. You need to keep around a global reference to the `pebble.DB` or you need to close it.

**Comment by nnsgmsone** [comment]
@petermattis  think you.
