### ISSUE TITLE
db: provide option to flush WAL in DB.Checkpoint

### ISSUE THREAD

**Issue by absolute8511** [cockroachdb/pebble#795]
I just write a simple test case to check whether the checkpoint has the same data as below:

```
func TestCheckpointData(t *testing.T) {

// some init, xxxx

eng, err := pebble.Open(dataDir, opts)

wb := eng.NewBatch()
wb.Set(key, value, writeOpts)
eng.Apply(wb, writeOpts)

eng.Checkpoint(ckPath)

eng2, err := pebble.Open(ckPath, opts)

v1, closer1, err := eng.Get(key)
v2, closer2, err := eng2.Get(key)

assert.Equal(t, v1, v2)        // failed
assert.Equal(t, v2, value)  // failed

}

```

**Comment by petermattis** [comment]
@absolute8511 Can you fill in the `some init` portion of this test? I believe the test would fail if `writeOpts` does not specifying `Sync = true`. That's expected. There could also be something else going wrong.

**Comment by absolute8511** [comment]
I am using the `sync=false`. As it is documented, I thought the `Sync = true` should only affect the OS buffer cache (just fsync syscall)?  I think even the `Sync=false`, the checkpoint file content should be readable.

**Comment by jbowens** [comment]
@absolute8511 As far as I know, writing with `Sync = false` doesn't guarantee that the write will be flushed to the OS buffer cache. The WAL has it's own buffering and won't flush until either a full 32kb block is buffered or a write with `Sync = true` is committed.

I can see how this could be surprising. It seems reasonable that `Checkpoint` could force a flush of the WAL before taking the checkpoint.

**Comment by petermattis** [comment]
Flushing in `Checkpoint` would make the operation quite a bit more impactful on the rest of the DB. Perhaps this behavior should be more clearly documented. Also, I wonder what RocksDB's behavior is. I don't recall RocksDB doing a flush in Checkpoint, but that could just be my faulty memory.

**Comment by petermattis** [comment]
RocksDB provides a parameter that controls whether flushing will be performed:

```
  // log_size_for_flush: if the total log file size is equal or larger than
  // this value, then a flush is triggered for all the column families. The
  // default value is 0, which means flush is always triggered. If you move
  // away from the default, the checkpoint may not contain up-to-date data
  // if WAL writing is not always enabled.
  // Flush will always trigger if it is 2PC.
  virtual Status CreateCheckpoint(const std::string& checkpoint_dir,
                                  uint64_t log_size_for_flush = 0);
```

We actually have a `TODO` in the code to implement this parameter:

```
	// TODO(peter): RocksDB provides the option to flush if the WAL size is too
	// large, or roll the manifest if the MANIFEST size is too large. Should we
	// do this too?
```

**Comment by jbowens** [comment]
> Flushing in `Checkpoint` would make the operation quite a bit more impactful on the rest of the DB. Perhaps this behavior should be more clearly documented. Also, I wonder what RocksDB's behavior is. I don't recall RocksDB doing a flush in Checkpoint, but that could just be my faulty memory.

Sorry, I spoke imprecisely here. I meant flushing/syncing the WAL's `LogWriter`, not flushing the memtable to a sstable. I think for our `LogWriter` flushing / syncing are done together, which is the source of confusion. If I understand correctly, @absolute8511 expected that applying the batch with `Sync = false` would write it to the WAL's OS file, just not fsync to guarantee it persists. If it had been written to the OS file, the batch would still be copied when `Checkpoint` copies the WAL's OS file. Instead, Pebble's `LogWriter` will buffer the write in a `block` until it's full or the first call to `SyncRecord`.

**Comment by petermattis** [comment]
> Sorry, I spoke imprecisely here. I meant flushing/syncing the WAL's LogWriter, not flushing the memtable to a sstable. 

Ah, that's a good idea. We can synchronously write an empty `DB.LogData()`, though perhaps it is better to add an explicit `FlushWAL` command.

**Comment by absolute8511** [comment]
Yeah, just flush wal should be enough. Rocksdb's checkpoint always have the up-to-date data if WAL writing used (not using the sync)

**Comment by petermattis** [comment]
> Rocksdb's checkpoint always have the up-to-date data if WAL writing used (not using the sync)

Is that true when the RocksDB `manual_wal_flush` option is specified? I think RocksDB accidentally gets that behavior due to the `log_size_for_flush` parameter which defaults to flushing the memtable. But if you specify `manual_wal_flush=true` and `log_size_for_flush = std::numeric_limits<uint64_t>::max` I think RocksDB can create a checkpoint which doesn't have a recent write.

**Comment by nnsgmsone** [comment]
@petermattis I think there will be abnormal situations, such as a batch'a', wal as follows:

1.  'a' start
2. 'a' update
3.  'a' update

If you commit, The normal process is:
1. write a new log to wal('a' commit)
2. flush data


Because there is no sync,  it may be that the data of wal has not been written, but the data corresponding to batch'a' has been placed.  If the pebble log is not an undo log, then the situation of wal is as follows:

1.  a start
2. a update
3. a  update

If pebble's processing strategy at this time is to find that there is no commit, and then write a new log 4: 'a' cancel.. Then turning off sync may cause confusion.I don't know how pebble is recovered from wal, if it is what I thought, then turning off sync may cause a lot of confusion, and the behavior of the database may be very strange.

**Comment by nnsgmsone** [comment]
Whether directly adding a checkpoint interface can ensure the consistency of pebble after turning off sync, I feel that it needs careful analysis.

**Comment by nnsgmsone** [comment]
Personal point of view, using injest in a batch import scenario may be a better choice than turning off sync.

**Comment by petermattis** [comment]
@nnsgmsone I'm not sure I follow the example scenario you laid out, but I will confirm that if you disable sync then you've lost any data durability guarantees. If you care about the durability and consistency of data on disk, then you need to sync on commit.

**Comment by nnsgmsone** [comment]
@petermattis  yes, he should have turned off sync in order to improve the speed of batch writing. I think there is a problem with his usage, because turning off sync will cause data exceptions. So I suggest that he use inject to import data in bulk. . Just a suggestion

**Comment by nnsgmsone** [comment]
After all, this is a very dangerous practice (unless the engine guarantees it)

**Comment by absolute8511** [comment]
What I need is just avoid `fsync` on WriteOptions just like the rocksdb comment as below.

https://github.com/facebook/rocksdb/blob/a693341604fd585619136a2e81e7a2d0fcdaee44/include/rocksdb/options.h#L1378

**Comment by nnsgmsone** [comment]
@absolute8511 you can use flush before checkpoint, like:
```
 eng, _ := pebble.Open("test.db", &pebble.Options{
        ReadOnly:   false,
        DisableWAL: true,
    })
    wb := eng.NewBatch()
    wb.Set([]byte("a"), []byte("b"), &pebble.WriteOptions{false})
    eng.Apply(wb, &pebble.WriteOptions{false})
    
    eng.Flush()                                                                                                                                                                                             

    eng.Checkpoint("check.db")

    eng2, _ := pebble.Open("check.db", &pebble.Options{
        ReadOnly:   false,
        DisableWAL: true,
    })

    v1, _, _ := eng.Get([]byte("a"))
    v2, _, _ := eng2.Get([]byte("a"))

    {
        fmt.Printf("%v\n", bytes.Compare(v1, v2))
        fmt.Printf("%v\n", bytes.Compare(v2, []byte("b")))
    }   

```
However, because pebble uses hard link instead of copy, the checkpoint can not be used as a snapshot. . .

**Comment by absolute8511** [comment]
> @absolute8511 you can use flush before checkpoint, like:
> 
> ```
>  eng, _ := pebble.Open("test.db", &pebble.Options{
>         ReadOnly:   false,
>         DisableWAL: true,
>     })
>     wb := eng.NewBatch()
>     wb.Set([]byte("a"), []byte("b"), &pebble.WriteOptions{false})
>     eng.Apply(wb, &pebble.WriteOptions{false})
>     
>     eng.Flush()                                                                                                                                                                                             
> 
>     eng.Checkpoint("check.db")
> 
>     eng2, _ := pebble.Open("check.db", &pebble.Options{
>         ReadOnly:   false,
>         DisableWAL: true,
>     })
> 
>     v1, _, _ := eng.Get([]byte("a"))
>     v2, _, _ := eng2.Get([]byte("a"))
> 
>     {
>         fmt.Printf("%v\n", bytes.Compare(v1, v2))
>         fmt.Printf("%v\n", bytes.Compare(v2, []byte("b")))
>     }   
> ```
> 
> However, because pebble uses hard link instead of copy, the checkpoint can not be used as a snapshot. . .The modification of the source data will cause the modification of the snapshot, which may be different from your expectations.And your usage is very dangerous, it may lead to abnormal data. . .

So the pebble's checkpoint is not the same as rocksdb?  If the checkpoint does not work as the expected, then what the checkpoint should be used for?

In the rocksdb's implementation, only immutable files use the hard link, all mutable files (such as wal) will be copied.

**Comment by nnsgmsone** [comment]
@absolute8511 I don’t know the specific pebble logic, but it should look the same because WAL, CURRENT and MANIFEST are not hard links. However, because you turned off sync, wal is empty, which may cause the checkpoint to not work as expected. I think you can consult petermattis. In addition, I think that your approach to speeding up write performance by turning off sync may be a bit rude, and may cause some unexpected consequences.

**Comment by absolute8511** [comment]
@nnsgmsone  `Sync=false` will not cause the empty WAL, I think maybe you mixed up the `sync` and the `disable WAL` configuration which is separated in the WriteOptions.

**Comment by nnsgmsone** [comment]
@absolute8511 That is indeed my test code closed wal。However, I found that the checkpoint replication wal is incomplete, 

I did a test，I first run the following code:
```
func main() {
    eng, _ := pebble.Open("test.db", &pebble.Options{
        ReadOnly: false,
        //  DisableWAL: false,
    })
    wb := eng.NewBatch()
    wb.Set([]byte("a"), []byte("b"), &pebble.WriteOptions{false})
    eng.Apply(wb, &pebble.WriteOptions{false})

    eng.Flush()

    eng.Checkpoint("check.db")
}
```

![2020-07-07 15-32-45 的屏幕截图](https://user-images.githubusercontent.com/31609524/86738546-bfc8e500-c067-11ea-960e-890e8fbbb45d.png)

I next run the following code:
```
func main() {
    eng, _ := pebble.Open("test.db", &pebble.Options{
        ReadOnly: false,
        //  DisableWAL: false,
    })
    wb := eng.NewBatch()
    wb.Set([]byte("a"), []byte("c"), &pebble.WriteOptions{false})
    eng.Apply(wb, &pebble.WriteOptions{false})

    eng.Flush()

    //  eng.Checkpoint("check.db")                                                                                                                                                                          

    eng2, _ := pebble.Open("check.db", &pebble.Options{
        ReadOnly: false,
        //  DisableWAL: true,
    })

    v1, _, _ := eng.Get([]byte("a"))
    v2, _, _ := eng2.Get([]byte("a"))

    {
        fmt.Printf("%s, %s\n", string(v1), string(v1))
    }
    {
        fmt.Printf("%v\n", bytes.Compare(v1, v2))
        fmt.Printf("%v\n", bytes.Compare(v2, []byte("b")))
    }
}
```
Then I got the following result:
![2020-07-07 15-41-18 的屏幕截图](https://user-images.githubusercontent.com/31609524/86739246-52698400-c068-11ea-8928-74ba44eaec3c.png)
Whether it is test.db or check.db, the value of a is c, I think this may be different from your expectations

**Comment by nnsgmsone** [comment]
yes, i close the wal。Then you should be able to work with db.Flush(). But turning off sync personally feels really . . . You can use injest to increase write performance.

**Comment by petermattis** [comment]
> So the pebble's checkpoint is not the same as rocksdb? If the checkpoint does not work as expected, then what the checkpoint should be used for?

Pebble's checkpoint is the same as RocksDB's with the exception that the WAL is not flushed. That could be fixed, and is exactly what this issue is discussing. In all other ways, a Pebble checkpoint should be identical to a RocksDB checkpoint. If you find a difference, that is a bug.

> In the rocksdb's implementation, only immutable files use the hard link, all mutable files (such as wal) will be copied. So the checkpoint will not be affected by the modification of the source data.

This is the same in Pebble. Immutable sstables use hard links. The WAL and MANIFEST are copied.

> And for WriteOptions with sync=false, I think the main usage is to speed up write (since OS crash is rarely then process crash), not only for the checkpoint.

Yes, `sync=false` speeds up writes, but you need to be very very (!) careful how you use it. CRDB uses it for certain operations that do not require durability because they are already durable due to other mechanisms.
