### ISSUE TITLE
Any plans to implement backend for S3 ?

### ISSUE THREAD

**Issue by yingfeng** [cockroachdb/pebble#805]
This idea comes from a fork of rocksdb---[rocksdb-cloud](https://github.com/rockset/rocksdb-cloud), which exposes key value interfaces to applications while the data is stored in remote object storage such as S3, and local disk is a kind of cache to guarantee the performance.  Such a store could have a much lower cost than native key value stores running on local disk for cloud native engines. Corresponding adjustment might contain: 

- A persistent read block cache which could cache data to local disk(could be SSD or NVMe), similar with the persistent tiered read cache within RocksDB
- A mechanism of recording global WAL for recovery
- A mechanism to upload some sstable files to remote S3

Although pebble is used for OLTP database as CockroachDB, the adjusted engine could have a much lower cost if CRDB is deployed within cloud.

**Comment by petermattis** [comment]
Hi @yingfeng. There are no plans to add an S3 backend. While it has been considered and explored, adding such a backend is a significant bit of work and would require an even more significant amount of testing.
