### ISSUE TITLE
Reset a batch after it is applied into the DB

### ISSUE THREAD

**Issue by lni** [cockroachdb/pebble#806]
I am trying to see is it possible to reuse a batch after it is successfully applied into the DB. The doc of the Batch.Reset() method mentions that -  
 
```
Used in cases where Batch is only being used to build a batch, and where the end result is a Repr() call, 
not a Commit call or a Close call.
```

A Commit call is just a call to db.Apply(), so according to the doc, Reset() is not suppose to be called when the batch is applied into the DB? 

I had a look at the code, after Batch.Repr() is called in DB.commitWrite(), the content of the returned []byte is copied in LogWriter.emitFragment(). Not sure why Batch.Reset() is not ok after a successful call to DB.Apply(batch).

Did I miss anything? Thanks!

**Comment by petermattis** [comment]
@lni I think the docs are out of date and unclear. You can call `Batch.Reset()` after a call to `Batch.Commit` or `Batch.Apply`. I believe the intention behind the comments is that this is generally not needed. Batch allocation is pooled so doing `b := DB.NewBatch(); ... ; b.Commit(); b.Close()` is memory efficient.

**Comment by jbowens** [comment]
> You can call Batch.Reset() after a call to Batch.Commit or Batch.Apply. I believe the intention behind the comments is that this is generally not needed. Batch allocation is pooled so doing b := DB.NewBatch(); ... ; b.Commit(); b.Close() is memory efficient.

@petermattis Since batch allocation is pooled, isn't it _not_ ok to call `Reset` after `Commit` or `Apply`, because the batch might already have been reacquired from the pool by another goroutine?

**Comment by petermattis** [comment]
> @petermattis Since batch allocation is pooled, isn't it not ok to call Reset after Commit or Apply, because the batch might already have been reacquired from the pool by another goroutine?

We only release the Batch into the pool in `Batch.Close()`.
