### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by jjzcru** [cockroachdb/pebble#828]
I would like to try out the library but I wasn't able to find a getting started guide.

I read the README and I enter the docs an only explains the benefits of pebble and the design ideas but nothing like a code example snippet.

**Comment by petermattis** [comment]
@jjzcru Are you aware of `go doc`? For example, https://godoc.org/github.com/cockroachdb/pebble#DB. I'm sure the docs could be better structured and include better examples, but they do exist. PRs for improvements are welcome.
