### ISSUE TITLE
db: elision-only L6 compactions

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#838]
There are a couple circumstances through which a tombstone may be written to a L6 file. An open snapshot can prevent a tombstone's elision during an ordinary compaction, and a move compaction can move a file containing tombstones into L6.

When (if any) blocking snapshots are closed, these tombstones and any covered keys within the same sstable may be elided. Today, this doesn't happen until the compaction of an overlapping file in the above level. These sstables unnecessarily consume disk space, and their point tombstones can introduce latency to range iteration. It's also surprising to have a database with zero keys, zero snapshots and a non-zero number of sstables (cockroachdb/cockroach#51786).

A relevant TODO: https://github.com/cockroachdb/pebble/blob/master/compaction_picker.go#L957-L959

**Comment by jbowens** [comment]
I spiked out an implementation of this in 6f6321b7ef20c75b663ccdb0b4367f4da46d376f. During compaction picking, if no other compactions are found, the picker does a linear scan of L6. It looks for files that have deletions (as populated from properties by the table stats collector) and whose largest sequence number is less than the smallest snapshot. If it finds one, it constructs a L6 -> L6 compaction of the file's atomic compaction unit.

It would be nice to avoid the scan of L6 file metadata. I wonder about the copy-on-write btree and annotating nodes with arbitrary bookkeeping information so we can get fast queries of:
* count of files within a LevelSlice
* sum of files within a LevelSlice
* lookups of files with tombstones with sequence numbers less than _x_ within a LevelSlice

**Comment by petermattis** [comment]
> I wonder about the copy-on-write btree and annotating nodes with arbitrary bookkeeping information

This sounds interesting. Another example of bookkeeping information we currently scan for are sstables that are marked for compaction.

**Comment by jbowens** [comment]
RocksDB does a few notable things here.

- RocksDB has a notion of a 'bottommost' file, which is a file that does not overlap with any older files. It uses this during compaction when determining whether to elide tombstones, just like our in-use key ranges. However, RocksDB [builds a slice of _all_ the bottommost files across all levels](https://github.com/facebook/rocksdb/blob/b0279d386956de7901f000e4a8fd090a38ee358e/db/version_set.cc#L2873-L2896) with every new version.
- Every time new compaction scores are calculated, RocksDB [iterates through all these bottommost files](https://github.com/facebook/rocksdb/blob/master/db/version_set.cc#L2906-L2925) to find ones older than the oldest snapshot number and containing 2 or more deletions. There's a comment as to why 2+ deletions is the threshold, but it doesn't mean anything to me.
- When a snapshot is released, RocksDB updates the oldest snapshot number and [rescans the list of bottomost files](https://github.com/facebook/rocksdb/blob/69a6d0b411de13a27271ef8cf90121ad2bce1c3a/db/db_impl/db_impl.cc#L2939-L2984), using a global threshold to avoid scanning the entire list of bottommost files if it's unneeded.
- If the snapshot released was the only open snapshot, RocksDB [uses the current visible seq num](https://github.com/facebook/rocksdb/blob/69a6d0b411de13a27271ef8cf90121ad2bce1c3a/db/db_impl/db_impl.cc#L2945-L2949) to populate bottommost files, which I guess is defensiveness against concurrent compactions and snapshot creation?

**Comment by jbowens** [comment]
I think annotating copy-on-write btree nodes with information to serve a similar purpose as RocksDB's `bottommost_files_mark_threshold_` makes sense. In the interim, we could scan the entire list of L6 files every time a snapshot is released, or maintain a threshold similar to `bottommost_files_mark_threshold_` somewhere... maybe on the compaction picker?

**Comment by sumeerbhola** [comment]
> There's a comment as to why 2+ deletions is the threshold, but it doesn't mean anything to me.

I assume you meant this comment:
```
     // largest_seqno might be nonzero due to containing the final key in an
      // earlier compaction, whose seqnum we didn't zero out. Multiple deletions
      // ensures the file really contains deleted or overwritten keys.
```
The first sentence is unclear to me. I wonder whether the multiple deletions is referring to a single deletion case where the DEL key is in this sstable and the SET (to be deleted) is in the next sstable. Though it shouldn't matter if we are constructing an atomic compaction unit.

**Comment by petermattis** [comment]
> However, RocksDB builds a slice of all the bottommost files across all levels with every new version.

Ouch. Expensive.

> If the snapshot released was the only open snapshot, RocksDB uses the current visible seq num to populate bottommost files, which I guess is defensiveness against concurrent compactions and snapshot creation?

Yeah. If there are no snapshots, the earliest possible snapshot that could be created concurrently is the current visible sequence number.

> > There's a comment as to why 2+ deletions is the threshold, but it doesn't mean anything to me.
>
> The first sentence is unclear to me. I wonder whether the multiple deletions is referring to a single deletion case where the DEL key is in this sstable and the SET (to be deleted) is in the next sstable. Though it shouldn't matter if we are constructing an atomic compaction unit.

That comment is confusing to me too. I'm not terribly thrilled with the RocksDB logic. Rewriting an L6 sstable in order to recover the space from a handful of tombstones doesn't seem worthwhile. Seems like we should only do this if the amount of space to recover is some reasonable fraction of the sstable size. I think we can make some estimate of that fraction from the info in the sstable properties.

**Comment by jbowens** [comment]
Elision-only compactions were added in a2588dc33968e7c4e05271f0e4d9b07a9aa4fa24, so I'll close this out.

#847 tracks improvements to elision-only compactions such as using a sstable property of # obsolete keys or potentially splitting obsolete data into a separate sstable.
