### ISSUE TITLE
db: problematic point-in-time handling of WAL checksum failures

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#864]
From https://github.com/cockroachdb/pebble/issues/566#issuecomment-673898177 and https://github.com/facebook/rocksdb/pull/7252#issuecomment-673766236, RocksDB mishandles point-in-time recovery of a WAL replay when a checksum error occurs. The problematic scenario is two WAL files and a checksum error that occurs in the first WAL. During replay, the checksum error will cause processing of the first WAL file to terminate, but RocksDB will merrily process the next WAL.

It looks like Pebble has this same behavior. The issue in Pebble is that errors due to WAL recycling are jumbled together with checksum errors. It would be straightforward to mark checksum errors separately, but I'm not sure this is sufficient. When replaying a recycled WAL it is possible for a record at the tail of the WAL to have what appears to be a valid header, but an invalid checksum. This can occur if the data in the body of the record just happens to align with the position of the header and has matching data. For recyclable WALs a record has the following format:

```
+----------+-----------+-----------+----------------+--- ... ---+
| CRC (4B) | Size (2B) | Type (1B) | Log number (4B)| Payload   |
+----------+-----------+-----------+----------------+--- ... ---+
```

In order for the header to be considered valid, `Type` has to be one of `recyclable{Full,First,Middle,Last}ChunkType`, `Log number` has to match the number of the WAL being read, and there must be `Size` bytes remaining in the current chunk. Only then is the `CRC` field compared to `CRC(Payload)`. A valid header (modulo the CRC) is unlikely in random data, but not impossible. Stopping WAL replay at the checksum failure could thus erroneously not replay the tail of the WAL. But if we don't stop WAL replay at the checksum failure we may violate the point-in-time recovery semantics.

@itsbilal I think you're familiar with the WAL handling. Can you double-check the above and see if I'm missing anything that actually makes our WAL replay correct with regards to both point-in-time recovery semantics and replaying all valid WAL entries?

I'm not sure what can be done here or the urgency of fixing. One thought is to add another field to the record header which is a CRC of the header itself. I think that would allow us to distinguish random data which looks like a valid record header (but would fail the header checksum) from a real record header that has had its payload corrupted.

**Comment by petermattis** [comment]
I had another (better?) idea on how to fix this problem. Notice that there is only a problem if there are 2 WAL files and the corruption is in the first. If there is only a single WAL file, or if the corruption is in the last WAL file, it doesn't matter whether an invalid entry is due to corruption or that we reached the end of the log as there is no other WAL file to replay. In the 2 WAL case, if the corruption occurs in the first log, we could distinguish between corruption and end of the log if we knew how long the log file was when we switched to the new WAL. Currently we don't store that info anywhere, but we could. Two possibilities present themselves: 

1. We could truncate a WAL to its actual size when we switch to a new WAL. This approach has the upside of being backward compatible with RocksDB. It has the downside that if manual flushes or flushes due to ingestion are occurring, we may be frequently truncating the WAL to a smaller size and thus losing the benefits of WAL recycling (which is a win when writing to the WAL does not change its size).
2. We could store the size of the WAL in some auxiliary storage. While the `MANIFEST` sounds like the natural place to store this info it is actually problematic because we don't currently perform a `MANIFEST` write when rotating the WAL. Instead, we could create a marker file that sits alongside the WAL and either contains the WAL size or encodes the WAL size in the filename. For example, for a WAL named `000001.log` we could create a file named `000001.log.capped` and the file would contain the size of the valid contents in the associated WAL. If the `.capped` file isn't present we would fall back to the previous behavior of using the file size. This approach also maintains some measure of compatibility with RocksDB as RocksDB would simply ignore the `.capped` files.

Cc @ajkr in case RocksDB wants to mirror whatever solution we decide on for Pebble.

@sumeerbhola I'd appreciate your thoughts on this as well.

**Comment by jbowens** [comment]
Taking a step back on the advantages of log recycling, I don't have a clear understanding of where exactly the latency of writing to a fresh WAL file comes from.
```
			// Try to use a recycled log file. Recycling log files is an important
			// performance optimization as it is faster to sync a file that has
			// already been written, than one which is being written for the first
			// time. This is due to the need to sync file metadata when a file is
			// being written for the first time. Note this is true even if file
			// preallocation is performed (e.g. fallocate).
```

This is just blind speculation and probably pretty dependent on the filesystem, but I could see log recycling helping in a few ways:

1. data blocks are already allocated and don't need to be reallocated for a new file
2. new file's metadata doesn't need to be synced
3. existing file's pages already in the OS page cache and don't need to be allocated/read/etc.

It seems like both of these options would pay a new cost in writing file metadata? In the first option, we would need to write and sync the first WAL's metadata to record the truncated size. The second option, we need to create and sync a new file's metadata and data. Would these new metadata writes negate some of the benefit of log recycling?

**Comment by jbowens** [comment]
To make sure I understand the problem we're solving: We can't differentiate between a checksum failure from a corrupted record and a checksum failure from a previous WAL's garbage at the tail of the file?

When rotating a WAL w/ log recycling, could we write a special EOF record that signifies the point at which we rotated the log? I think it might also be backwards compatible with RocksDB. If this special record occupies a new record type enum value, RocksDB would stop reading the WAL at the record that's not well-formed (from the old format's perspective), avoiding a checksum failure.

**Comment by petermattis** [comment]
> This is just blind speculation and probably pretty dependent on the filesystem, but I could see log recycling helping in a few ways:

WAL recycling has a measurable performance impact when running on `ext3` and `ext4`. I think I also measured an impact on `xfs`. You're correct that the benefit is filesystem dependent. The underlying issue on `ext{3,4}` is that those systems using dynamically sized extents for the file storage. While you can use a system call to preallocate those intents, and use the `ftruncate` system call to adjust the file's size, the data stored in the intents is not zeroed until it is written. This is accomplished by the `ext{3,4}` having an internal "size" field that represents the true written size of the file. If you read past the size the file system automatically returns zero. Updating that internal "size" field requires a write of the file's inode. So if you're appending to a newly created a preallocated file, every sync requires syncing the data block as well as the inode which is at least 2 write operations. We can actually see these two writes using a block tracing tool like `blktrace` or `perf`. 

> To make sure I understand the problem we're solving: We can't differentiate between a checksum failure from a corrupted record and a checksum failure from a previous WAL's garbage at the tail of the file?

Correct.

> When rotating a WAL w/ log recycling, could we write a special EOF record that signifies the point at which we rotated the log? I think it might also be backwards compatible with RocksDB. If this special record occupies a new record type enum value, RocksDB would stop reading the WAL at the record that's not well-formed (from the old format's perspective), avoiding a checksum failure.

This is another good alternative. I don't think RocksDB would treat the invalid record differently from a checksum failure, but we could certainly encourage them to adopt the same handling of this new enum.

Another extension of this is that we could always write the trailer whenever we write a log record. That is, when we write a record fragment of length N at offset X, we also one of these "EOF" records at X+N. When we write the next record, we overwrite the previous "EOF" record.

Anyways, this approach seems compelling because it avoids having a new very tiny file associated with each WAL. The backwards compatibility story thus seems better.

**Comment by jbowens** [comment]
It looks like RocksDB is tracking the WAL within the `MANIFEST` as a means of handling problems like this. The size of the WAL appears in the `MANIFEST`, so the database knows how far to expect the recycled log to be valid. It also has the advantage of having a clearer upgrade path. If the WAL is known in the `MANIFEST`, it should be valid up to its size. Otherwise, all bets are off.

https://github.com/facebook/rocksdb/pull/7236

cockroachdb/cockroach#54729 is an example of the ambiguity during an upgrade causing problems. We need some way of determining whether the replayed WALs were written using a version of Pebble that writes clean WAL tails. One idea is to add a special option that doesn't get exposed externally via the `Options` struct but gets written to the `OPTIONS` file. On `Open`, Pebble could consult the previous `OPTIONS` file and if the special option is enabled, it interprets WALs strictly. Otherwise, it interprets them forgivingly and writes its own `OPTIONS` file with the special option enabled.

**Comment by petermattis** [comment]
Gah, upgrade paths. You think you've thought this through, but something often slips by.

> cockroachdb/cockroach#54729 is an example of the ambiguity during an upgrade causing problems. We need some way of determining whether the replayed WALs were written using a version of Pebble that writes clean WAL tails. One idea is to add a special option that doesn't get exposed externally via the Options struct but gets written to the OPTIONS file. On Open, Pebble could consult the previous OPTIONS file and if the special option is enabled, it interprets WALs strictly. Otherwise, it interprets them forgivingly and writes its own OPTIONS file with the special option enabled.
>
> @petermattis — wdyt?

That sounds good to me.
