### ISSUE TITLE
vfs: Add option to turn off sync-on-close in syncingFile

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#873]
Currently, `vfs.syncingFile` always syncs un-synced data when `Close()`'d. This is often unnecessary for files, such as those created by the temp engine, where we would still need the background-syncing-of-written-data to smoothen out disk latencies that `syncingFile` provides us, but we don't really need the `Close`-time durability guarantee.

This would help speed up disk writes in cases where the close-time sync currently dominates. See https://github.com/cockroachdb/cockroach/issues/53712#issuecomment-685939152 for an example of where this happens.

**Comment by petermattis** [comment]
Another possibility is to add an option which disables the full "Sync" at close and replaces it with a `sync_file_range` call. That call is non-blocking and would ensure we're not allowing significant dirty data to accumulate but doesn't have the latency hit of a blocking sync call. This approach would be mildly safer making it preferable if the performance is good.
