### ISSUE TITLE
db: suspicious assignments in db.go:1257 and db.go:1264

### ISSUE THREAD

**Issue by cristaloleg** [cockroachdb/pebble#900]
Assignment in https://github.com/cockroachdb/pebble/blob/master/db.go#L1257 and 
https://github.com/cockroachdb/pebble/blob/master/db.go#L1264 don't make much sense, 'cause function will return results shortly.

It's not a bug but looks suspicious, probably you (I mean someone from Pebble authors) know more about that. If you're fine - I can make a tiny PR.

PS: cannot make a link to the code on the latest commit, so commit is `08b545a1f5403e31a76b48f46a780c8d59432f57`

**Comment by petermattis** [comment]
Likely detritus from a refactoring, or possibly just erroneous when first written. Not a bug, but fine to remove. Care to send a PR?

**Comment by cristaloleg** [comment]
Done in #901
