### ISSUE TITLE
iterators api

### ISSUE THREAD

**Issue by benitogf** [cockroachdb/pebble#907]
How do we use iterators to get keys with a prefix?

```
client, err := pebble.Open("example", &pebble.Options{})
iter := client.NewIter(&pebble.IterOptions{})
iter.SeekPrefixGE([]byte("prefixkey"))
for iter.Next() {
    log.Println(string(iter.Key())
}
err = iter.Close()
```

doing this will get: `pebble: split must be provided for SeekPrefixGE`

**Comment by petermattis** [comment]
@benitogf The `SeekPrefixGE` API seems to be a source of confusion. I'll look at improving the docs. The short answer is don't use it. Rather, use `SeekGE` and specify an `UpperBound`:

```
// Notice the `\0` suffix.
iter := client.NewIter(&pebble.IterOptions{UpperBound: []byte("prefixkey\0")})
defer iter.Close()
for key, value := iter.SeekGE([]byte("prefixkey")); key != nil; key, value = iter.Next() {
  log.Println(string(iter.Key())
}
```

**Comment by petermattis** [comment]
@jbowens Can you see about enhancing the doc comment for `Iterator.SeekPrefixGE` suggesting the above pattern is likely what they actually want?

**Comment by benitogf** [comment]
thanks @petermattis will look into it, some questions:

- using `iter.First()` or `iter.Last()` after a seek eg `iter.SeekGE([]byte("prefixkey"))` will reset the position? if so how can we get the iterator on last or first of a prefix?
- whats the default sorting order of the iterators? is there a way to specify a different sort criteria? eg. with a key that contains a timestamp?

**Comment by petermattis** [comment]
> using iter.First() or iter.Last() after a seek eg iter.SeekGE([]byte("prefixkey")) will reset the position? if so how can we get the iterator on last or first of a prefix?

You can use `LowerBound` and `UpperBound` to constrain to a prefix of keys:

```
iter := client.NewIter(&pebble.IterOptions{LowerBound: []byte("prefixkey"), UpperBound: []byte("prefixkey\0")})
for key, value := iter.First(); key != nil; key, value = iter.Next() {
}
```

Using `{Lower,Upper}Bound` in this way is desirable as it enables optimizations to avoid iterating outside of the bounds.

> whats the default sorting order of the iterators? is there a way to specify a different sort criteria? eg. with a key that contains a timestamp?

This documentation covers this: https://godoc.org/github.com/cockroachdb/pebble#DB. If the documentation isn't clear I'd prefer to improve it rather than answering in this issue. More scalable that way. Helps the next person to come along with a similar question.

**Comment by benitogf** [comment]
Thanks again @petermattis very useful information here
https://godoc.org/github.com/cockroachdb/pebble/internal/base#InternalIterator
https://godoc.org/github.com/cockroachdb/pebble/internal/base#pkg-variables

**Comment by benitogf** [comment]
Sorry but I couldn't make the example provided work as expected, specifying an upper bound with a nul character suffix doesn't iterate over keys with the prefix, however without the upperBound option it seems to work:
 
```
prefixKey := "prefix"
iter := db.client.NewIter(&pebble.IterOptions{
	LowerBound: []byte(prefixKey),
	// UpperBound: []byte(prefixKey + "\x00"),
})
iter.First()
for iter.Valid() {
       log.Println(string(iter.Key()))
       iter.Next()
}
```

**Comment by petermattis** [comment]
Oops. I wrote my previous response too quickly and confused `next(key)` with `upper-bound(key)`. Something like the following is needed:

```
func keyUpperBound(b []byte) []byte {
	end := make([]byte, len(b))
	copy(end, b)
	for i := len(end) - 1; i >= 0; i-- {
		end[i] = end[i] + 1
		if end[i] != 0 {
			return end[:i+1]
		}
	}
	return nil // no upper-bound
}
...
prefixKey := []byte{"prefix"}
iter := client.NewIter(&pebble.IterOptions{
	LowerBound: prefix, 
	UpperBound: keyUpperBound(prefix),
})
for key, value := iter.First(); key != nil; key, value = iter.Next() {
}
```

In the example, this will set lower-bound to "prefix" and upper-bound to "prefiy". Note that this while this works for `bytes.Compare`, it doesn't work for general comparators which is why there are no convenience facilities for this in Pebble itself.

**Comment by ivanjaros** [comment]
does setting the upper bound provide any performance gain compared to simply doing bytes.HasPrefix() on the iter.Key() and breaking out of the loop manually?

**Comment by petermattis** [comment]
> does setting the upper bound provide any performance gain compared to simply doing bytes.HasPrefix() on the iter.Key() and breaking out of the loop manually?

Yes. If you set the upper bound that upper bound is propagated to the leaf internal iterators and some of those iterators can elide the upper bound check. For example, if you set the upper bound to `z` and one of the sstables contains keys in the range [`a`, `q`] then the sstable iterator can elide the upper bound check for that sstable.
