### ISSUE TITLE
Allow retrieving the options from a running database?

### ISSUE THREAD

**Issue by karalabe** [cockroachdb/pebble#914]
When creating a new database via `pebble.Open`, we need o specify an input option, which will get extended with a whole lot of different defaults to form the final option set. This updated option set however is only stored internally (clone of the parameter), so there's no real way to inspect what pebble actually set. I'm guessing this might be an omission, because the `Option` type has a `String` function, which formats all the settings elegantly, except it's useless from my perspective because I can't get access to the actual option set the database is running with in the first place.

**Comment by jbowens** [comment]
Pebble writes the full set of options to disk in an `OPTIONS-xxxxxx` file in the data directory. Does that meet your needs, or do you need to programmatically access the final options set? The `pebble.Open` method extends the options using `(*Options).EnsureDefaults()`. If you want to know the fully-specified options used programmatically, you could call it yourself before calling `pebbl.eOpen`:

```
opts := &pebble.Options{ /* ... */ }
opts.EnsureDefaults()
fmt.Println(opts.String())
db, err := pebble.Open("", opts)
```

**Comment by karalabe** [comment]
Ooooh, if it writes it out that's super. I just want to double check that it runs with what I think it runs.

**Comment by karalabe** [comment]
Just checked it, almost perfect. If I don't specify a Level (or only 1), it only writes out that, but not the rest out of 7 (if I thought correctly that it has 7 like leveldb). In that case there's a slight information loss because it's not clear what the options for subsequent layers are (see https://github.com/cockroachdb/pebble/issues/913)
