### ISSUE TITLE
TableFormat chokes on LevelDB

### ISSUE THREAD

**Issue by karalabe** [cockroachdb/pebble#915]
The docs of TableFormat states:

```
	// TableFormat specifies the format version for writing sstables. The default
	// is TableFormatRocksDBv2 which creates RocksDB compatible sstables. Use
	// TableFormatLevelDB to create LevelDB compatible sstable which can be used
	// by a wider range of tools and libraries.
	TableFormat TableFormat
```

However if I set it to `TableFormatLevelDB`, pebble will reject it as an unsupported format. I guess it's a WIP? Just wanted to highlight it.

**Comment by petermattis** [comment]
Not really a WIP. I think that comment should be updated. The intention was to allow `sstable.Writer` to create LevelDB compatible sstables. I can't recall why `pebble.Options.TableFormat` was added, but it should either be removed, or the error clarified to indicate that LevelDB format sstables won't be supported for writing by `pebble.DB`.
