### ISSUE TITLE
perf: heuristics to reduce impact of point tombstones on read latency

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#918]
High densities of point tombstones slow down iteration, wasting IO on loading keys that are discarded and cpu time skipping over them.

In RocksDB, sstables that contain majority deletion entries are prioritized for compaction through inflating these tables' compensated sizes. ~In Pebble, we never adjust compaction priorities to compact point tombstones.~ (_Update: In #1018 we adjusted compaction heuristics in way similar to RocksDB to increase the priority of compacting these point tombstones._)  We should investigate if any CockroachDB workloads accumulate high densities of point tombstones and those densities affect the workload in practice. If there is an impact, we might try triggering compactions of files based on the frequency with which an iterator skips over point tombstones in the file.

Related to #29, which also triggers compactions from reads but aimed at reducing read amplification.

Jira issue: PEBBLE-214

**Comment by jbowens** [comment]
I updated the issue description to capture the fact that since #1018, Pebble does incorporate point tombstones into compaction heuristics by incorporating them into 'compensated size.'

It's still possible that read-triggered compactions of point tombstones would be beneficial, especially for point tombstones in a part of the keyspace where the average value size is small (resulting in less contribution to compensated size). The internal iterator stats added in #1538 can help us evaluate if the existing heuristics are enough.

**Comment by sumeerbhola** [comment]
This could have helped in https://github.com/cockroachlabs/support/issues/2107#issuecomment-1452660323

**Comment by jbowens** [comment]
This would've helped in cockroachlabs/support#1830.

**Comment by jbowens** [comment]
I think this came up in another issue, but a more generalized approach could use CPU attribution to determine which sstables to compact. Seems tricky but possible?

**Comment by sumeerbhola** [comment]
I think this is also coming up with rangedels that we are just skipping over in https://github.com/cockroachlabs/support/issues/2203#issuecomment-1498078068

**Comment by andrewbaptist** [comment]
Can we add "IO attribution" to ranges? This would be similar to CPU attribution in the sense that it would use lower-level calls to determine how much each individual range is reading/writing per request and the KV layer could store and expose that information both at the range and node level. 

The general idea as we are attempting to keep systems balanced is that having more information can help us make better decisions. 

I think the way to do this best is to pass a "IOStats" object into all the mvcc operations that update it on the operation.

**Comment by nicktrav** [comment]
> Can we add "IO attribution" to ranges? 

Certainly. We have cockroachdb/cockroach#98377 already for this, which is planned for the 23.2 cycle. 

> I think the way to do this best is to pass a "IOStats" object into all the mvcc operations that update it on the operation.

Shall we copy those suggestions over on cockroachdb/cockroach#98377 too. Perhaps we can make that issue more generalized?

**Comment by andrewbaptist** [comment]
That is a slightly different ask. What I mean specifically is that if call to `MVCCGet` would track how much IO it did (tracked in bytes read/written) this could either be 1 or 2 stats. So for instance the `MVCCGetResult` would add a new field `IOStats` that has this information. I would expect this to be somewhat correlated with CPU but if systems are "IO starved" we may want to make rebalancing decisions based on "IO heavy ranges" rather than "CPU heavy". 

If we implement #98377 we should also add the IOStats related to compaction load. 

Initially this information would just show up in the "hot ranges" page, but this is another way a range can be hot. We have seen cases where compaction doesn't happen on clusters since they are primarily write only, but the few ranges that do have updates end up with very expensive IO operations to complete. Also since compaction is a "replica level" decision, not a "range level", different stores have very different IO profiles for the same range. Having this visibility could be very useful.

**Comment by sumeerbhola** [comment]
What already have `InternalIteratorStats.{BlockBytes,BlockBytesInCache}` which are reported to KV (and are in traces too). One just needs to aggregate this per range. The storage package does not know about ranges, so I don't think the aggregation should happen there.

**Comment by jbowens** [comment]
Uncompacted point tombstones have several effects:

* Increased CPU — During iteration we must skip over the tombstones and the keys they delete.
* Increased I/O — Tombstones dilute blocks, making a single block load incur more I/O per useful KVs. This impacts scans that load more than one block, or if dense enough, can impact gets by forcing more than 1 data block load per level.

The effect on I/O is visible in the telemetry cluster over the past month. Two stores have an outsized accumulation of point tombstones, and the sum of uncached block loads mirrors the graph of tombstones:

<img width="828" alt="Screenshot 2023-05-26 at 11 39 43 AM" src="https://github.com/cockroachdb/pebble/assets/867352/0db7db18-6804-482c-b27b-7e8fe7896a65">
<img width="832" alt="Screenshot 2023-05-26 at 11 39 50 AM" src="https://github.com/cockroachdb/pebble/assets/867352/de37fa60-b897-45fd-bf0f-f95de8c708a8">

Interestingly, the graph of total block loads (cached + uncached) does _not_ show any noticeable trend. I'm not sure why, other than maybe it's a consequence of where in the keyspace these point tombstones are and the corresponding workload.

The I/O effects should be reduced by our space-amplification metrics, especially with improved accuracy from recent improvements like (#2340). These heuristics strive to keep the space amplification of point tombstones down to 10% of the overall LSM size. However, tombstones might not be evenly distributed across the keyspace. The present situation on the Telemetry cluster suggests this. So 10% amplification concentrated in one region of the keyspace may still increase tail latencies intolerably.

So in general, I think our goal here is to reduce the _densities_ of tombstones, and in particular in areas of the keyspace that _are read_. The I/O effects are more pronounced on the sstable containing the deleted keys, rather than the tombstones, since they may encode values as well. As a result, I think this would be tricky to incorporate into a heuristic. Like read-triggered compactions we could try to reduce densities of tombstones only when they're _observed_ by an iterator. But point tombstones are most disruptive to latencies when they're read, but not frequently enough to keep the blocks within the cache (like apparently is the case in the Telemetry cluster).

I'm thinking we should instead focus on reducing tombstone densities, irrespective of iteration. Still thinking

**Comment by jbowens** [comment]
I've seen repeatedly that new nodes seeded with replication snapshots or new clusters seeded with an IMPORT are susceptible to accumulating a large quantity of point tombstones because their LSMs are _too_ well shaped. We won't pursue any compactions from L5 to L6 because L5 is way too small. We won't elide any point tombstones until we begin to trigger L5->L6 compactions. Ignore the gap in data, but these graphs are illustrative: 

<img width="828" alt="Screenshot 2023-06-12 at 6 32 39 PM" src="https://github.com/cockroachdb/pebble/assets/867352/22063114-6b74-4371-b1ab-09889ecb84e0">
<img width="830" alt="Screenshot 2023-06-12 at 6 32 52 PM" src="https://github.com/cockroachdb/pebble/assets/867352/d37e84c4-6595-48f4-b595-f2f4ec34d108">

Another consideration (from [this slack thread](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1687260811626429)) is that tombstones can reduce block cache locality for reads, even if the tombstones are outside the scope of reads. With expiration-based leases we have _N_ hot keys that are repeatedly read and written. Sandwiched between these _N_ hot keys, we have the raft log that's continually accumulating entries and then truncating them with point tombstones. I believe there are typically very few _live_ keys between these _N_ hot keys. But accumulation of point tombstones within the raft log can push these _N_ hot keys into _N_ separate ssblocks, trashing the block cache with blocks that are only useful for reading these single keys. This can happen while never reading the raft log and never surfacing the point tombstones to the `pebble.Iterator`.

**Comment by jbowens** [comment]
This could have helped in cockroachlabs/support#2628.

**Comment by nicktrav** [comment]
Linking cockroachlabs/support#2640, relevant to prioritizing compactions of the liveness range.
