### ISSUE TITLE
Atomic field alignment in 32bit machine

### ISSUE THREAD

**Issue by rjl493456442** [cockroachdb/pebble#930]
According to Golang's [issue](https://golang.org/pkg/sync/atomic/#pkg-note-BUG),  **On 32 bit platforms, only 64-bit aligned fields can be atomic**. 

However, the atomic fields are not aligned properly in the codebase. For example, the [`log.size`](https://github.com/cockroachdb/pebble/blob/master/db.go#L252) is not aligned, also the `logSeqNum` and `visibleSeqNum` in versionSet are not aligned.

I already submit a [PR](https://github.com/cockroachdb/pebble/pull/929) to fix a few of them. But regarding the atomic fields in `db.mu`, maybe it will be best fixed by the maintainers with your code style.

**Comment by petermattis** [comment]
Happy to accept PRs for this, but we're unlikely to fix ourselves as we don't use 32-bit platforms.

Is there a way to hook up testing to automatically discover these problems? If you fix all of the existing ones, what is to stop the code from rotting?

**Comment by rjl493456442** [comment]
Ah, sure I can help with fixing the remaining issues. Setup 32bits testing environment on Travis will help(I guess).

**Comment by rjl493456442** [comment]
Fixed by #929
