### ISSUE TITLE
background error: could not open table: no such file or directory

### ISSUE THREAD

**Issue by karalabe** [cockroachdb/pebble#931]
While trying to reproduce the 20% blowup, one of my test runs started choking with:

```
background error: pebble: could not open table 019002: open /datadrive/shootout/611493701/019002.sst: no such file or directory
```

The above was looping, printing over and over and over multiple times per second (didn't measure, don't have sub-second logs).

**Comment by petermattis** [comment]
@karalabe That's a worrisome error, but we won't be able to investigate without more information. Can you share what your workload is doing? Can you share the rest of the logs? Can you share the `MANIFEST` file (assuming you haven't restarted)?

**Comment by karalabe** [comment]
Unfortunately I can't repro it, I was just writing a script that throws random stuff into the db and deletes random stuff, trying to repro my other 20% issue. I've ran the thing quite a few times but managed to trigger this issue only once.

Just for the record I was running this https://gist.github.com/karalabe/75e7919a7d67d4d65afb94d74ca04188, just with the item count set to 10000000.

Wrt the data files, unfortunately my script has a defer os.Remove so I don't have anything left.
