### ISSUE TITLE
compactionPicker: try to pick another file if atomic unit has file already compacting

### ISSUE THREAD

**Issue by aadityasondhi** [cockroachdb/pebble#936]
This is a follow-up from https://github.com/cockroachdb/pebble/pull/927.

Currently, if `expandToAtomicUnit` finds an atomic compaction unit to have a file that is already compacting based on `FileMetadata.Compacting`, the entire compaction is skipped. 

A more efficient way to do this would be to try to pick another file instead of skipping the compaction. This can be done in `compactionPickerByScore.pickFile`. We would want to pick the file with the next lowest ratio, and try a compaction on it.

**Comment by nicktrav** [comment]
@jbowens - is this still relevant in a post- split user keys world?
