### ISSUE TITLE
Update on an indexed batch causes batch iterator to see same key twice when switching directions

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/pebble#943]
We see this in a modified metamorphic test
```
iter64 = batch61.NewIter("", "") // <nil> #11982
...
iter64.SetBounds("dsqz", "ewcjnfotphz") // <nil> #12191
iter64.SeekGE("vkqxbbggc") // [false] <nil> #12195
iter64.Prev() // [false] <nil> #12206
iter64.Last() // [true,"eebkemwwnk","jal"] <nil> #12217
batch61.Set("ebflokolqf", "rn") // <nil> #12219
iter64.Next() // [true,"eebkemwwnk","jal"] <nil> #12220
```

The `Next` should not have returned the same key-value pair as the preceding call to `Last`.
`iter64.Last` ends up with an empty heap when it steps to `iterPosPrev` in `Iterator`. The call to `iter64.Next` is at `iterPosPrev` and `i.iterKey` is nil, https://github.com/cockroachdb/pebble/blob/master/iterator.go#L447-L455 so it does a `SeekGE` on the `mergingIter`. This exposes the ""ebflokolqf" that was just set in the batch, since it is after the seek position. Since the iterator was at `iterPosPrev` it then does a call to `nextUserKey` https://github.com/cockroachdb/pebble/blob/master/iterator.go#L458 which steps from "ebflokolqf" to "eebkemwwnk", which is the result returned above.

A Pebble with a different options setting is lucky in that `iter64.Last` ends up on a key k such that
"ebflokolqf" < k < "eebkemwwnk"
This happens to be an InternalKeyKindDelete since the last byte is 0 (I'm speculating that different compactions caused this delete to be pushed down to the lowest level in the first case, so it vanished). `i.iterKey` is at k, so we call `i.nextUserKey` https://github.com/cockroachdb/pebble/blob/master/iterator.go#L456 instead of `mergingIter.SeekGE`. This prevents "ebflokolqf" from becoming visible since the iterator is already greater than that key.

This is reproducible by running https://github.com/sumeerbhola/pebble/tree/meta_failure_master (the commit mentions the seed to use).

In general, consider keys k1, k2, k3 that are lexicographically ordered. The `Last` call, in stepping to `iterPosPrev` is positioned at k1. The user thinks the iterator is at k3 since that is what was returned by `Last`. If k2 gets inserted, the code will step twice (thinking k2 is what was returned to the user), and return k3 again. The above example is a special case where this happens when k1 is nil.

I think the fix here is whenever `Iterator` positions itself at `iterPosPrev` or `iterPosNext` it needs to remember the key that it actually returned so it can use that as a constraint when changing direction.

It is possible that this is not sufficient to cover the cases when the direction is not changed. Say the iterator returned k3, and is at `iterPosPrev` k1. Then k2 is inserted, and then Prev is called. The user expectation is that the `Prev` should return k2.

**Comment by petermattis** [comment]
Fascinating. I don't think we have a requirement anywhere in CRDB that a batch iterator sees mutations that were added after the iterator was created. And I'm not seeing that behavior guaranteed in the docs. It is slightly inconsistent that batch iterators have different behavior with regards to mutations than other iterators. Perhaps we should change `batchIter` to take a snapshot of the batch and not return records newer than that snapshot. I'm not exactly sure how I'd implement this. Probably just some `skipForward` and `skipBackward` loops before returning from any of the positioning calls. The snapshot itself would just be a seqnum (recall the batch seqnum's are a position in the batch combined with `InternalKeySeqNumBatch`). Thoughts?

**Comment by sumeerbhola** [comment]
> The snapshot itself would just be a seqnum (recall the batch seqnum's are a position in the batch combined with InternalKeySeqNumBatch). Thoughts?

That seems doable. But I want to make sure I understand the CRDB semantics: we create an `indexedBatch` when executing a CRDB `BatchRequest`, which can contain a combination of Get/Put/... commands. These will sequentially be processed using `evaluateCommand` which will create an iterator for the command, and there is no iterator reuse here unlike a read-only batch which uses `pebbleReadOnly`. Since the iterator is created after the previous commands it will see those writes. For a read-write command `Command.EvalRW` there is no need to read its own write since there are single key puts/cputs. The `DistinctSpans` field and and the `Distinct()` batch path is used as an optimization to avoid constructing an `indexedBatch` (so not relevant to this issue) when we know that none of the commands in a batch have overlapping spans.

So we don't really exercise a path where an iterator is created on a batch, then something is set on the batch, and the iterator continues to be used.

Is that all correct?

**Comment by petermattis** [comment]
> So we don't really exercise a path where an iterator is created on a batch, then something is set on the batch, and the iterator continues to be used.
> 
> Is that all correct?

That is my understanding, but your walking through this has me second guessing whether it is true. We should definitely do some checking. Perhaps with some code instrumentation.

**Comment by sumeerbhola** [comment]
> I don't think we have a requirement anywhere in CRDB that a batch iterator sees mutations that were added after the iterator was created.

I think we were mistaken in this understanding.
- `TestMVCCPutAfterBatchIterCreate` which was added by @bilal in https://github.com/cockroachdb/cockroach/commit/96c51c3413e589c0180912677190ba829f42f515#diff-11e6517b0ef05cb160a2a14174c0a9719c30b71d74c74bd8bca67de3b37d12ba: according to it if we seek an existing batch iterator, it can see keys that were added after the creation of the iterator. It uses this in `NextKey` -- my understanding is that this is just because the metamorphic test can do next/nextkey on an iterator without seeking, and not a real requirement to support this in `NextKey`.
- Looking again at `pebbleBatch`, it does reuse iterators when `DistinctSpans` is false, so the reused iterators (which will be seeked when reusing) need to see the mutations added to the batch by preceding commands, after the iterator was created.

The positive thing is that the reused iterator will be seeked before iteration, so the current code seems correct (though some of the MVCC tests are expecting stricter semantics than are needed).
