### ISSUE TITLE
data race on iterator

### ISSUE THREAD

**Issue by benitogf** [cockroachdb/pebble#953]
```
WARNING: DATA RACE
Write at 0x00c000449080 by goroutine 13:
  github.com/cockroachdb/pebble.(*DB).newIterInternal()
      /home/travis/gopath/src/github.com/cockroachdb/pebble/db.go:701 +0x243
  github.com/cockroachdb/pebble.(*DB).NewIter()
      /home/travis/gopath/src/github.com/cockroachdb/pebble/db.go:820 +0x216
```

```
Previous read at 0x00c000449080 by goroutine 7:
  github.com/cockroachdb/pebble.(*Iterator).Error()
      /home/travis/gopath/src/github.com/cockroachdb/pebble/iterator.go:522 +0x4a
```

Full logs: https://travis-ci.com/github/benitogf/katamari/builds/187573774

**Comment by petermattis** [comment]
@benitogf Thanks for the report. Without further details, my best guess is that you're not adhering to the `Iterator` API. Pebble `Iterators` are pool allocated. They are put back into the pool in `Iterator.Close`. If you use the `Iterator` in any fashion after the `Close` you'll encounter a race like this. If you can reproduce this problem, one way to verify this is to change the code in `Iterator.Close()` to comment out the block of code at the end which calls `iterAllocPool.Put`. If this causes the race to disappear, you'll just need to track down where you are using the iterator after calling `Close()`. From the report, it looks like you're calling `Iterator.Error()` after call `Close()`

**Comment by benitogf** [comment]
Thanks @petermattis realized that `Close()` will also return the accumulated errors, so just removing  `Iterator.Error()` worked
