### ISSUE TITLE
Are repeated deletes and reads leading to silent intermittent data corruption?

### ISSUE THREAD

**Issue by austincollinpena** [cockroachdb/pebble#960]
This is a very odd problem, I'm sure, but I'd appreciate some help on it. I know a claim about data corruption isn't one to make lightly, so I'll do my best to explain the situation.

I'm currently trying to a build a simple LRU cache for Pebble and in my test, I repeatedly write to a new key, and then read another key. In the end, I verify that the key is preserved while the table size was kept within my limit.

[Here is a link to the repo](https://github.com/austincollinpena/pebble-lru).

As I try to access the key here:

```go
newVal, err := lru.Get([]byte("a"), Pdb)
			if !bytes.Equal(newVal, []byte("2")) {
				t.Fail()
			}
```

In my fresh repository, everything works great at first, but after running the test multiple times I start to get this value: []byte(238) instead of []byte("2")

```
2
2
�
�
�
�
2
2
2
```

Env: Windows 10 pro.

Other notes:
- Turning off sync seems to increase the rate at which these errors occur
- Seems that single delete may have increased the error rate, but I'm not sure

To reproduce, Run the test in the provided repo around ten or twelve times and the issue should pop up.

**Comment by petermattis** [comment]
Pretty sure your error is here:

```
func (c *Cache) Get(key []byte, db *pebble.DB) (value []byte, err error) {
	val, closer, err := db.Get(key)
	if err != nil {
		return nil, err
	}
	if err := closer.Close(); err != nil {
		return nil, err
	}
	if val == nil {
		return nil, nilError
	}
	c.lock.Lock()
	c.moveItemToFront(key)
	c.lock.Unlock()
	return val, nil
}
```

The problem is you're using the returned value after the closer has been closed. The docs for `DB.Get` say:

```
// Get gets the value for the given key. It returns ErrNotFound if the DB does
// not contain the key.
//
// The caller should not modify the contents of the returned slice, but it is
// safe to modify the contents of the argument after Get returns. The returned
// slice will remain valid until the returned Closer is closed. On success, the
// caller MUST call closer.Close() or a memory leak will occur.
```
