### ISSUE TITLE
Q: Performance

### ISSUE THREAD

**Issue by ivanjaros** [cockroachdb/pebble#964]
In the past, i was using bolt and badger as kvdb. Bolt for simple things or things sutied for large data storage and badger if i needed more performance and qps. Last time i tested them both, badger gave me about 12k transactions per second and bolt about 250(no batching), because bolt has blocking transactions.

I am presently in a need of something fast that is alternative to badger because badger no longer works on windows, at least not properly. So i am wondering where pebble stands performance-wise? I never worked with level/rocks db before so i have no reference points.

**Comment by petermattis** [comment]
@ivanjaros I don't have any concrete numbers to offer you. Pebble should have as good or better write performance to badger for small to medium size keys and values. I recall Badger having better performance for large keys and values due to the way it stores them outside of the LSM tree.

**Comment by ivanjaros** [comment]
ok, try and see i guess :)
