### ISSUE TITLE
compaction: O(num-sstables) check for forced compactions

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#970]
This one slipped me eye. It doesn't show up in `BenchmarkManySSTablesNewVersion`'s numbers because all the sstables in that benchmark are ingested into L6.

```
	// Check for forced compactions. These are lower priority than score-based
	// compactions. Note that this loop only runs if we haven't already found a
	// score-based compaction.
	//
	// TODO(peter): MarkedForCompaction is almost never set, making this
	// extremely wasteful in the common case. Could we maintain a
	// MarkedForCompaction map from fileNum to level?
	for level := 0; level < numLevels-1; level++ {
		iter := p.vers.Levels[level].Iter()
		for f := iter.First(); f != nil; f = iter.Next() {
			if !f.MarkedForCompaction {
				continue
			}
			var info *candidateLevelInfo
			for i := range scores {
				if scores[i].level == level {
					info = &scores[i]
					break
				}
			}
			if info == nil {
				panic(fmt.Sprintf("could not find candidate level info for level %d", level))
			}
			info.file = iter.Take()
			pc := pickAutoHelper(env, p.opts, p.vers, *info, p.baseLevel)
			// Fail-safe to protect against compacting the same sstable concurrently.
			if pc != nil && !inputRangeAlreadyCompacting(env, pc) {
				pc.score = info.score
				return pc
			}
		}
	}
```

As far as I can tell, we never set `MarkedForCompaction` on Pebble anymore, so files can only be marked for compaction by RocksDB before restarting with Pebble. Do we think `MarkedForCompaction` is still useful outside on-disk compatibility with RocksDB?

If Pebble will never set files as marked for compaction, we could use an annotator to surface an arbitrary file marked for compaction within each B-Tree. If Pebble is never marking files for compaction, is it even beneficial to honor the `MarkedForCompaction` flag?

It seems like we could just ignore the `MarkedForCompaction` flag and rely on Pebble's own hueristics.

**Comment by petermattis** [comment]
> Do we think MarkedForCompaction is still useful outside on-disk compatibility with RocksDB?

We don't have the ability to set this via Pebble anymore, right? I think it would be ok to stop respecting this flag in the compaction heuristics.
