### ISSUE TITLE
compaction: sstable age triggered compactions

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#972]
RocksDB has an option for triggering compactions of sstables created older than a TTL, ensuring that every file is eventually compacted. (eg, [`GetExpiredTtlFilesCount`](https://github.com/facebook/rocksdb/blob/1b224324b58b925efbd6e765dd345b4650d57fb1/db/version_set.cc#L2492-L2512)) CockroachDB has never used this option.

We've [observed](https://cockroachlabs.slack.com/archives/C3T5LG9R8/p1603729564078200) a CockroachDB 20.1 cluster running RocksDB with a `system.jobs` table with large (~25 GB) on-disk size estimate, despite containing very little live data. It seems likely that this data is occupied by the obsolete keys shadowed by point tombstones. RocksDB's minoverlapping-ratio heuristic weights point tombstones to prioritize their compaction which presumably helps in the situation, but not enough (maybe because these jobs values are much larger relative to the average value size in the database). Pebble's does not weight point tombstones because earlier work showed most point tombstones within the LSM in a tpcc workload had already dropped the keys they shadowed. It might be worth double checking that result now because compaction heuristics have changed quite a bit since then.

An alternative to weighting point tombstones into the ratio heuristic is a compaction trigger similar to RocksDB's TTL, so that we're assured we'll always eventually reclaim disk space. A `manifest.Annotator` could track the oldest sstable in each level and `pickAuto` could schedule a compaction if its age exceeds a configured threshold. If we backported to earlier releases, we could perform this check in the same `pickAuto` loop that checks for files marked for compaction.

**Comment by jbowens** [comment]
It's also worth noting that the jobs page was timing out on the observed cluster, probably from iterating over ~25 GB data and many point tombstones. #918 would help here too.

**Comment by jbowens** [comment]
For implementing a time-triggered compaction, we'll want to create an annotator that that computes the oldest `*FileMetadata` in a level. The [`elisionOnlyAnnotator`](https://github.com/cockroachdb/pebble/blob/master/compaction_picker.go#L1050-L1108) is a good example to copy. We can compare the files by [`FileMetadata.CreationTime`](https://github.com/cockroachdb/pebble/blob/0c19db5b5cc1133d295f1f44ad0de5cb457b8d29/internal/manifest/version.go#L76). Like the `elisionOnlyAnnotator`, we'll want to skip any files already `Compacting`.

We can use the annotator from a `pickAgeTriggeredCompaction` function, which should also look pretty similar to the elision-only compaction equivalent [`pickElisionOnlyCompaction`](https://github.com/cockroachdb/pebble/blob/0c19db5b5cc1133d295f1f44ad0de5cb457b8d29/compaction_picker.go#L1112-L1141), except we'll want to find the oldest across all levels 1 to `numLevels-1`. We'll want to compact this oldest sstable only if its older than some threshold configured through an `Options`.

**Comment by jbowens** [comment]
I just noticed that the `MANIFEST` from cockroachlabs/support#638 does not have creation times. I'm a little confused by that .

We might be able to use the minimum sequence number as a proxy for file age, except that zeroed sequence numbers can distort that and it makes it harder to set a time threshold.

**Comment by jbowens** [comment]
On second thought, do we want to compact the oldest sstable or the non-L6 sstable containing the oldest key? In cockroachlabs/support#638, we are seeing compactions from L4->L5 adding more point tombstones to L5, but no compactions from L5->L6 in this section of the keyspace. This means that none of the files we want to compact are particularly old, but they contain old point tombstones.

It seems like this particular issue would be best solved with some kind of point tombstone compensation.

**Comment by jbowens** [comment]
For cockroachlabs/support#638 the SREs switched the cluster over to Pebble (CRDB 20.1) and the size of the jobs table dropped 90% in about 24 hours. Pebble in CRDB 20.1 used a compaction heuristic that compacted the file containing the smallest sequence number (analogous to RocksDB's `kOldestSmallestSeqFirst` heuristic). That suggests we maybe _don't_ need point-tombstone compensation and instead could stave off this type of issue with an "oldest key"-triggered compaction.

I think to implement this, we would add a new `oldest_key_flush_timestamp` sstable property. A flush would set this property to the the current timestamp. A compaction would set this property to the minimum timestamp of all the compaction inputs' timestamps.

Then we'd add a new annotator [as described above](https://github.com/cockroachdb/pebble/issues/972#issuecomment-717539611), with the annotation value storing the `*FileMetadata` of the file with the smallest `oldest_key_flush_timestamp` property within the level. After checking for automatic compactions, the compaction picker would query the `oldest_key_flush_timestamp` annotator for each level and schedule a compaction if its `oldest_key_flush_timestamp` value is older than a threshold.

There are a couple potential hiccups:
* The `oldest_key_flush_timestamp` property, as described above, has weird semantics. Since a compaction can produce multiple files, not all the files produced by the compaction necessarily contain keys that were flushed at `oldest_key_flush_timestamp`. I'd guess that this fuzziness doesn't matter that much in practice. If we wanted to make it a little more accurate, we could set a compaction output's property to the minimum of compaction inputs that overlap with the output table's key range.
* The `oldest_key_flush_timestamp` property would be unset for existing tables. When we first query the `oldest_key_flush_timestamp` annotator for these files and see that the value is unset, we could substitute the current timestamp. This would ensure that we don't overeagerly compact the entire database when the compaction picker is introduced, while also allowing us to eventually compact these tables (if the process stays up sufficiently long).
* Properties aren't generally available via the `*FileMetadata`. I think we'd need to extend the table stats collector to load the `oldest_key_flush_timestamp` property and set a new field on the `*FileMetadata`.

**Comment by petermattis** [comment]
> I think to implement this, we would add a new oldest_key_flush_timestamp sstable property. A flush would set this property to the the current timestamp. A compaction would set this property to the minimum timestamp of all the compaction inputs' timestamps.

There is already an `sstable.OldestKeyTime` property which we aren't setting. We do set `FileMetadata.CreationTime`. Could we use that field to power age triggered compactions. I believe that is what RocksDB uses for the TTL compactions.

**Comment by jbowens** [comment]
> We do set FileMetadata.CreationTime. Could we use that field to power age triggered compactions.

In cockroachlabs/support#638, we observed higher level sstables being compacted _into_ the problematic point tombstone files, rewriting them. This continually resets the `CreationTime`. We could reverse the compaction picking and pick the output-level table by age. I don't think this is what RocksDB is doing though.

I'm not sure what we'd do if the oldest table has nothing above it. There may still be other old files containing space that could be reclaimed.
