### ISSUE TITLE
any plan for rocksdb ColumnFamily visualization support?

### ISSUE THREAD

**Issue by skyzh** [cockroachdb/pebble#982]
We find the LSM tree visualization tool very useful, and added rocksdb ColumnFamily support for this tool at https://github.com/skyzh/pebble . However, this change may break how pebble works internally, as the patched version will not panic if ColumnFamily is found in rocksdb manifest.

So I would like to know, if there's any plan for adding rocksdb ColumnFamily visualization support. From my perspective, there are multiple ways to do this, and I would like to help:

* separating LSM visualization tool from pebble
* add ColumnFamily-related parsing in pebble, but only make this functionality available when using LSM visualization tool.

**Comment by petermattis** [comment]
> So I would like to know, if there's any plan for adding rocksdb ColumnFamily visualization support. 

There are no current plans. The visualization tool is primarily targeted at Pebble. That it works at all with RocksDB is nice, but not something that is actively supported.

> separating LSM visualization tool from pebble

This is certainly a viable option if you want to support it. 

> add ColumnFamily-related parsing in pebble, but only make this functionality available when using LSM visualization tool.

If we were to add any column family parsing to Pebble, I'd want it to be of the nature that prevents accidental usage of DBs with column families.
